### ISSUE TITLE
bug: SIG link update needed for ti-srebot

### ISSUE THREAD

**Issue by Yiyiyimu** [chaos-mesh/chaos-mesh#1002]
Thanks for your review. The bot only counts LGTMs from Reviewers and higher roles, but you're still welcome to leave your comments. See the corresponding SIG page for more information. Related SIG: [chaos-mesh]()([slack](https://slack.tidb.io/invite?team=tidb-community&channel=sig-chaos-mesh&ref=github)).

_Originally posted by @ti-srebot in https://github.com/chaos-mesh/chaos-mesh/pull/999#issuecomment-701142931_

**Comment by zhouqiang-cl** [comment]
@AndreMouche PTAL

**Comment by zhouqiang-cl** [comment]
We will remove this 😝

**Comment by Yiyiyimu** [comment]
Thank you @zhouqiang-cl ! 

Another problem is that the ti-srebot would jump out every time I make a reply for the code review. I think maybe it could filter out if there is `LGTM` and then decide whether to jump out. Or is it that I missed some registration so it tries to inform me? I'm a bit confused 😕

**Comment by zhouqiang-cl** [comment]
> Thank you @zhouqiang-cl !
> 
> Another problem is that the ti-srebot would jump out every time I make a reply for the code review. I think maybe it could filter out if there is `LGTM` and then decide whether to jump out. Or is it that I missed some registration so it tries to inform me? I'm a bit confused 😕

No，you did not miss anything，It is a bug of bot 😯，I think it will be fixed after the nation day。I am sorry for the confuse

**Comment by Yiyiyimu** [comment]
> No，you did not miss anything，It is a bug of bot 😯，I think it will be fixed after the National Day。I am sorry for confusing you

That would be great! Thx!
