### ISSUE TITLE
bug: There lacks a } in install.sh

### ISSUE THREAD

**Issue by 1964405262** [chaos-mesh/chaos-mesh#1003]
## Bug Report

**What version of Kubernetes are you using?**
v1.18.6

**What did you do?**
I installed chaos-mesh by running install.sh

**What did you see instead?**
install.sh:行1584: 语法错误: 未预期的文件结尾

After checking install.sh , I found there lacks a } on line 597

**Comment by WangXiangUSTC** [comment]
What is the version of Chaos Mesh are you use?

**Comment by Thearas** [comment]
The master branch.

**Comment by zhouqiang-cl** [comment]
introduce by https://github.com/chaos-mesh/chaos-mesh/pull/955/files#diff-3fbb47e318cd8802bd325e7da9aaabe8L589

**Comment by WangXiangUSTC** [comment]
thanks, fixed in https://github.com/chaos-mesh/chaos-mesh/pull/1006

**Comment by zhouqiang-cl** [comment]
Fixed, but has a cache, maybe take some time to work

**Comment by zhouqiang-cl** [comment]
@1964405262 @Thearas guys，you can try v1.0.0 first

**Comment by zhouqiang-cl** [comment]
Seems the cache has been flushed, so it is worked now, Closing this issue, feel free to reopen it if it still can not work
