### ISSUE TITLE
pod chaos-controller-manager and chaos-dashboard CrashLoopBackOff

### ISSUE THREAD

**Issue by Shaofa** [chaos-mesh/chaos-mesh#1058]
## Bug Report

**What version of Kubernetes are you using?**
```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:14:22Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.8-aliyunedge.1", GitCommit:"9837faf", GitTreeState:"", BuildDate:"2020-03-09T11:28:59Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
```

**What did you do?**

install chaos-mesh with helm: https://chaos-mesh.org/docs/installation/installation#install-by-helm

**What did you expect to see?**
all pods keep running

**What did you see instead?**
chaos-controller-manager and chaos-dashboard CrashLoopBackOff
```
$ kubectl -n chaos-testing logs -p pod/chaos-controller-manager-5d6f5c89d9-dmxk8
Controller manager Version: version.Info{GitVersion:"v1.0.0", GitCommit:"07a0d50107aeb2c1b7e96ebb57573865f6c1ea80", BuildDate:"2020-09-25T10:21:17Z", GoVersion:"go1.14.6", Compiler:"gc", Platform:"linux/amd64"}
2020-10-15T08:43:04.041Z	INFO	setup	Chaos controller manager is running in cluster scoped mode.
2020-10-15T08:43:34.044Z	ERROR	controller-runtime.manager	Failed to get API Group-Resources	{"error": "Get \"https://172.20.0.1:443/api?timeout=32s\": dial tcp 172.20.0.1:443: i/o timeout"}
github.com/go-logr/zapr.(*zapLogger).Error
	/root/go/pkg/mod/github.com/go-logr/zapr@v0.1.0/zapr.go:128
sigs.k8s.io/controller-runtime/pkg/manager.New
	/root/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/manager/manager.go:238
main.main
	/src/cmd/controller-manager/main.go:99
runtime.main
	/usr/local/go/src/runtime/proc.go:203
2020-10-15T08:43:34.044Z	ERROR	setup	unable to start manager	{"error": "Get \"https://172.20.0.1:443/api?timeout=32s\": dial tcp 172.20.0.1:443: i/o timeout"}
github.com/go-logr/zapr.(*zapLogger).Error
	/root/go/pkg/mod/github.com/go-logr/zapr@v0.1.0/zapr.go:128
main.main
	/src/cmd/controller-manager/main.go:101
runtime.main
	/usr/local/go/src/runtime/proc.go:203
```

**Comment by cwen0** [comment]
@Shaofa Can you check if all`kube-proxy` pods are healthy? From the log provided by you, the `controller-manager` pod didn't access to `kube-proxy` pod.

**Comment by Shaofa** [comment]
> @Shaofa Can you check if all`kube-proxy` pods are healthy? From the log provided by you, the `controller-manager` pod didn't access to `kube-proxy` pod.

there're too many nodes in my cluster, how can i install it on one node

**Comment by cwen0** [comment]
@Shaofa Do you mean that you want to restrict the controller-manager to a specific node? If you want to do it, you can refer to this https://kubernetes.io/docs/tasks/configure-pod-container/assign-pods-nodes/, set a specific label for the node, and add `nodeSelector` for the controller-manager pod.

**Comment by idiot40** [comment]
I also encountered the same problem, how did you solve it?

**Comment by S972776051** [comment]
你好请问如何解决的

**Comment by STRRL** [comment]
> 你好请问如何解决的

This issue is closed by "stale", which means there had been a long time for no update on this issue.

And CrashLoopBackOff is soo general and there is NO common way to fix all these issues about CrashLoopBackOff.

If you are facing the issue of Chaos Mesh not working, with CrashLoopBackOff occurred on the Pod, please open a new issue, with more detail like Kubernetes environment, human operations and Pod Logs.
