### ISSUE TITLE
Get Started links from README has been broken

### ISSUE THREAD

**Issue by Colstuwjx** [chaos-mesh/chaos-mesh#1067]
## Bug Report

**What version of Kubernetes are you using?**

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-16T00:04:31Z", GoVersion:"go1.14.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-30T20:19:45Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

**What did you do?**

Click the links from README.md:

```
- [Get Started on kind](https://chaos-mesh.org/docs/installation/get_started_on_kind)
- [Get Started on minikube](https://chaos-mesh.org/docs/installation/get_started_on_minikube)
```

**What did you expect to see?**
Show me the pages.

**What did you see instead?**
Page Not found.

BTW, these two links should be:

```
https://chaos-mesh.org/docs/get_started/get_started_on_kind
https://chaos-mesh.org/docs/get_started/get_started_on_minikube
```

rather than:

```
https://chaos-mesh.org/docs/installation/get_started_on_kind
https://chaos-mesh.org/docs/installation/get_started_on_minikube
```

I think this issue should be a good-first-issue for our new-coming contributors.

**Comment by cwen0** [comment]
@Colstuwjx Thanks for your report! Can you help us to fix it?

**Comment by Colstuwjx** [comment]
Yes, I have been submitted PR #1073 , and I think the root cause should be that we didn't show the latest content in our website, so our users see out-of-date content, and may misunderstand.

I suggest that we mark #885 as more higher priority, and change to always show the latest content in our website, just like [k/website](https://github.com/kubernetes/website) did.
