### ISSUE TITLE
Multi-DC chaos question

### ISSUE THREAD

**Issue by Colstuwjx** [chaos-mesh/chaos-mesh#1070]
## Question

I've seen our document about [multi-dc](https://chaos-mesh.org/docs/use_cases/multi_data_centers) or [three-dc](https://github.com/chaos-mesh/apps/tree/master/three-centers) chaos experiment, but they all assumes that the chaos happens on one k8s cluster, which is not applicable to the real world.

The fact is, we may setup one cluster on each dc, and how we make chaos in such environment? How to define the target pods which may deployed on the another kubernetes cluster, e.g. add network delays on deployment A in dc-a for visiting deployment B on dc-b.

Thanks.

**Comment by cwen0** [comment]
@Colstuwjx You can try to set [ExternalTargets](https://github.com/chaos-mesh/chaos-mesh/blob/master/api/v1alpha1/networkchaos_types.go#L164) for your NetworkChaos.
