### ISSUE TITLE
Make pkg doesn't reference controller gloabl variables (e.g. common.ControllerCfg )

### ISSUE THREAD

**Issue by Colstuwjx** [chaos-mesh/chaos-mesh#1072]
## Feature Request

**Is your feature request related to a problem? Please describe:**

It's not a good idea to reference controller(a.k.a business code) variables from pkg(a.k.a common libraries), it may introduces cycle imports, and I did find one, the common.ControllerCfg, it has been used by [pkg/utils/selector.go](https://github.com/chaos-mesh/chaos-mesh/blob/212da2d5095666bde793a9b4d636abfc38496f0f/pkg/utils/selector.go#L88) and [pkg/router/reconciler.go](https://github.com/chaos-mesh/chaos-mesh/blob/cf9e1ca11670df27b2b8995b0f4942cf96142330/pkg/router/reconciler.go#L46).

**Describe the feature you'd like:**

Remove  controller references from pkg, since `pkg` should be a common library without business code.

**Describe alternatives you've considered:**

None.

**Teachability, Documentation, Adoption, Migration Strategy:**

We need to refactor all related codes and testcases, it would introduce break changes since we need to tweak the function arguments, but I think we should do this, and setup the rules for avoiding do such reference anymore.

**Comment by Colstuwjx** [comment]
BTW, there is a [twophase reference](https://github.com/chaos-mesh/chaos-mesh/blob/cf9e1ca11670df27b2b8995b0f4942cf96142330/pkg/router/reconciler.go#L87) which is also a potential cycle import point.

**Comment by YangKeao** [comment]
Yes. I have faced a lot of cycle import problems while developing #940 :sob: 

I felt that the lack of `namespace` is the source of cycle import, because we have to split things into package (which cannot cycle import) in go but cannot split them into `namespace` (which is safe to cycle import).

I don't know whether creating such a lot small packages is a good practice, as it will really bring a lot of trouble :facepalm: .

**Comment by Colstuwjx** [comment]
TBH, I'm not clear understand with your so-called `namespace`, if it means package namespace, I suggest we setup some code regulations for it. From now, we add packages under the `pkg` folder as needed, and of course, it may introduce cycle import risks.

There are some suggestions, in my opinion:

1. common libraries could put into `utils` or sth like `lib`, make it as a purge lib;
2. common logic encapsulate, like pkg/router, put them into an sub-directory, e.g. core/router;
3. api related code, put them into sth like `api`, on root directory or under `pkg`

If we could push these three steps further, I think the cycle import and confusion about the pkg codes would be reduced.
Thanks.

**Comment by STRRL** [comment]
Unfortunately, go does NOT support cycle dependency. 

If A imports B and B imports A, then A and B is actually one thing. We could make an interface `I` to describe it.
From another vision, DI/IoC containers could tolerance these bad smells on program's logic. But not for cycle imports, go will throw errors during compling.

As @Colstuwjx says, only well-designed structure could resolve this.
