### ISSUE TITLE
Time compare bug in twoPhase test

### ISSUE THREAD

**Issue by mikechengwei** [chaos-mesh/chaos-mesh#1079]
## Bug Report

**What did you do?**
When i run /run-e2e-test ,the following error occurred
![image](https://user-images.githubusercontent.com/13257127/96447795-0ae8bb80-1245-11eb-8eab-417231ce5b25.png)

Source code:
![image](https://user-images.githubusercontent.com/13257127/96447998-569b6500-1245-11eb-93c4-d70afb1c0924.png)

I think `exp` time and `NextStart` time aren't use same base time, they use `time.Now()` get current time . So there are some gaps in seconds.

**Comment by WangXiangUSTC** [comment]
fixed in #1080
