### ISSUE TITLE
Can anyone explain the meaning of this field in networkchaos, **Correlation**, what's that stand for?

### ISSUE THREAD

**Issue by qhh0205** [chaos-mesh/chaos-mesh#1082]
## Question
Can anyone explain the meaning of this field in networkchaos, **Correlation**, what's that stand for?
https://github.com/chaos-mesh/chaos-mesh/blob/1e6f743e59ae36082ced861e677646a536b7cf5c/api/v1alpha1/networkchaos_types.go#L239
- Read the documentation:
  - [Chaos Mesh Readme](https://github.com/chaos-mesh/chaos-mesh)
  - [Chaos Mesh Doc](https://chaos-mesh.org/docs)

**Comment by cwen0** [comment]
@qhh0205 Hi, `correlation` defines the affinity to the last packet. For example, if we have a correlation of 100, it means the following packets will become in with the previous latency, making it a smooth latency pattern, which means the jitter you set will be ineffective. If it’s 0, it will become totally random and chaotic in the pattern. 

![image](https://user-images.githubusercontent.com/22956341/96535361-3b236f00-12c4-11eb-8a0a-08dc1e717c3f.png)

Normally we set a correlation value of 50-80

**Comment by qhh0205** [comment]
@cwen0 It seems that correlation field and jitter field  have the same function? They both has the same effect.

**Comment by cwen0** [comment]
@qhh0205 I think `correlation` and `jitter` work together, `jitter` controls the range of fluctuations, and then the `correlation` controls the probability. These two fields are inherited from the TC command. https://man7.org/linux/man-pages/man8/tc-netem.8.html

**Comment by YangKeao** [comment]
@qhh0205 Here is a description in detail:

For `delay`, this calculation model is quite simple: `((rnd % (2 * sigma)) + mu) - sigma` where the `sigma` is `jitter` and the `mu` is `latency`.

The `rnd` is a standard `u32` random number correlated with last number. 

```c
value = prandom_u32();
corr_plus_one = corr + 1;
rnd = (value * ((1ull<<32) - corr_plus_one) + last_rnd * corr_plus_one) >> 32;
```

For `loss`, the calculation model is much more complicated, [here](http://netgroup.uniroma2.it/twiki/bin/view.cgi/Main/NetemCLG) is a detailed discussion about the current model. You can read the source code in kernel `/net/sched/sch_netem.c`

**Comment by qhh0205** [comment]
ok, thanks！
