### ISSUE TITLE
Changes to chaos are not reflected / documentation is not clear?

### ISSUE THREAD

**Issue by bznein** [chaos-mesh/chaos-mesh#1096]
## Bug Report

**What version of Kubernetes are you using?**
```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T21:51:49Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-30T20:19:45Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```
**What did you do?**
Followed the tutorial under https://chaos-mesh.org/docs/development_guides/develop_a_new_chaos to develop a simple `helloworld` chaos. Managed to run it and see `Hello World` in the logs.
 Then uninstalled chaos-mesh, modified`/controllers/helloworldchaos/endpoint.go`'s `Apply` function to print a different log message, ran `make`, `make docker-push` and re-followed the steps from https://chaos-mesh.org/docs/development_guides/develop_a_new_chaos#make-the-docker-image onward.
  
**What did you expect to see?**
`chaos-controller-manager` should have shown the new log message.
**What did you see instead?**
It keeps showing `Hello World!` as if the changes made are not applied in any way.

**Comment by zhouqiang-cl** [comment]
@cwen0 PTAL

**Comment by cwen0** [comment]
@bznein Can you check if the chaos mesh image used is the latest version that you build just now?

**Comment by YangKeao** [comment]
I think the problem is caused by the `IfNotPresent` in `helm/chaos-mesh/values.yaml`. You could modify it to `Always` and so that kubernetes will always download the newest version from the `localhost` registry.

**Comment by YangKeao** [comment]
@cwen0 How should we avoid any modification on `values.yaml` during the development? Do you think `Always` is a good idea here? 

To be honest, as a single node minikube user, I only need to run `eval $(minikube docker-env)` and then `make DOCKER_REGISTRY="" image`, so I haven't faced this problem :smile:  .

**Comment by bznein** [comment]
@YangKeao yes! thank you! That was exactly the problem! 

I would close the issue but I see you tagged your teammate, so I'll leave it open for your discussion but feel free to close whenever you want :)

**Comment by cwen0** [comment]
@YangKeao Maybe we can omit `imagePullPolicy`. If we did not set it, `the default pull policy is IfNotPresent. In addition, omit the imagePullPolicy and use :latest as the tag for the image to use,  the image will be pull force.

**Comment by cwen0** [comment]
> @cwen0 How should we avoid any modification on `values.yaml` during the development? Do you think `Always` is a good idea here? I don't think modifying it for development and modifying it back before commit is a good practice 😠 .
> 
> To be honest, as a single node minikube user, I only need to run `eval $(minikube docker-env)` and then `make DOCKER_REGISTRY="" image`, so I haven't faced this problem 😄 .

I don't think `Always` is a good idea. Because when the user had pulled the image to their node, and then they can't access the docker registry. Some pods will fail to be restart because of the `Errpullimage`.

**Comment by YangKeao** [comment]
@cwen0 I mean in `master` branch. I agree with you that omit the policy is great, which will be `Always` for `:latest` and will be `IfNotPresent` for other tags :laughing:
