### ISSUE TITLE
Chaos Dashboard crashes if a custom defined chaos is deployed

### ISSUE THREAD

**Issue by bznein** [chaos-mesh/chaos-mesh#1098]
## Bug Report

**What version of Kubernetes are you using?**
```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T21:51:49Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-30T20:19:45Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

**What did you do?**
Followed the guide at https://chaos-mesh.org/docs/development_guides/develop_a_new_chaos but changed the `make` command to `UI=1 make` and the  `helm install` part to add `--set dashboard.create=true`

Enable port-forward and opened `localhost:2333`

**What did you expect to see?**
The chaos dashboard correctly running

**What did you see instead?**
The dashboard starts but does not load anything, and the `chaos-dashboard` pods fails with the following error:

```
2020-10-23T16:36:39.068Z	ERROR	collector.HelloWorldChaos	failed to archive experiment	{"error": "unsupported chaos type HelloWorldChaos"}
github.com/go-logr/zapr.(*zapLogger).Error
	/root/go/pkg/mod/github.com/go-logr/zapr@v0.1.0/zapr.go:128
github.com/chaos-mesh/chaos-mesh/pkg/collector.(*ChaosCollector).Reconcile
	/src/pkg/collector/collector.go:79
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/root/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:256
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/root/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:232
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker
	/root/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:211
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1
	/root/go/pkg/mod/k8s.io/apimachinery@v0.17.1-beta.0/pkg/util/wait/wait.go:152
k8s.io/apimachinery/pkg/util/wait.JitterUntil
	/root/go/pkg/mod/k8s.io/apimachinery@v0.17.1-beta.0/pkg/util/wait/wait.go:153
k8s.io/apimachinery/pkg/util/wait.Until
	/root/go/pkg/mod/k8s.io/apimachinery@v0.17.1-beta.0/pkg/util/wait/wait.go:88
2020-10-23T16:36:39.084Z	DEBUG	controller-runtime.controller	Successfully Reconciled	{"controller": "helloworldchaos", "request": "chaos-testing/hello-world"}
```

Deleting the experiment (`kubectl delete helloworldchaos.chaos-mesh.org hello-world`) fixes the issue.

**Comment by YangKeao** [comment]
Yes. There is still a lot of work to do before a custom defined chaos can be operated/viewed on dashboard (and there is no document about it 😿  ). 

But at least it shouldn't crash 💢 . @fewdan Can you help to fix the crash ? ( if it's not too much trouble. )

**Comment by bznein** [comment]
Thanks for the quick reply! I might help and submit a PR to avoid the
crash, if you want.
We might discuss what would be the best behaviour

**Comment by yeya24** [comment]
The log is expected and I don't see a crash. ZapLogger prints out the whole stack when there is an error. 

As @YangKeao said, the document is not complete about how to use new chaos in the dashboard.

**Comment by bznein** [comment]
@yeya24 I'll come back with more details in the next days, bit I can tell you for now that the chaos dashboard pod goes into error state and the dashboard is not usable.

**Comment by yeya24** [comment]
Thanks. More details and logs would be better. There might be some other error that happens at the same time and cause the real crash.

**Comment by bznein** [comment]
Of course, as I tried to reproduce it today, everything worked like a charm :)

Will close the issue and open a new one if things go wrong again, thanks!
