### ISSUE TITLE
chaos daemon run with privileged = false

### ISSUE THREAD

**Issue by WangXiangUSTC** [chaos-mesh/chaos-mesh#1101]
## Feature Request

**Is your feature request related to a problem? Please describe:**

now we will run chaos daemon with `privileged=true`, all capabilities will be added when privileged is true. Some users think we should limit the authority.

**Describe the feature you'd like:**

set `privileged=false`, and add some capabilities we really need.

**Comment by YangKeao** [comment]
`privileged=true` will not only grant all capabilities to the container, but it also maps all `/dev` folder into the container. As described in [issue](https://github.com/kubernetes/kubernetes/issues/5607), kubernetes doesn't provide a way to map only one device into the container without running container in privileged mode.

However, map `/dev/fuse` into the container is required by IOChaos.
