### ISSUE TITLE
Download existing / running experiments YML

### ISSUE THREAD

**Issue by torblerone** [chaos-mesh/chaos-mesh#1115]
## Feature Request

**Is your feature request related to a problem? Please describe:**
I have difficulty explaining to my colleagues how Chaos Experiments are structured as YML in Chaos Mesh. Since you can import experiments directly as YML when creating them on the dashboard, we would like to create our own examples. These should be able to be derived from running and functioning experiments according to our requirements. At the moment this is not yet possible.

**Describe the feature you'd like:**
I would like to be able to download/export the YML of the experiment in the detailed view of a running experiment in the dashboard.
I want to be able to manage this in my own SCM and share it with other teams as a basic script so that the teams have it easier to integrate chaos engineering into their daily work and to use the dashboard.

**Describe alternatives you've considered:**
none

**Teachability, Documentation, Adoption, Migration Strategy:**
On the "Update" button in the dashboard, you could add an export / download button, with which you can download the YML of an experiment. Similarly, this is e.g. possible in the Kubernetes dashboard in the detailed view of deployments. There you can view, edit and also download the YML live.

**Comment by fewdan** [comment]
Thank you for your suggestion, we will consider it.
