### ISSUE TITLE
Dashboard timeline show events

### ISSUE THREAD

**Issue by torblerone** [chaos-mesh/chaos-mesh#1116]
## Feature Request

**Is your feature request related to a problem? Please describe:**
I am having trouble seeing the individual events in the timeline of an experiment. I have to click through each event and find out the affected pods etc. by hand.

**Describe the feature you'd like:**
I would like a feature to be able to see not only the duration of an experiment but also the individual events in the timeline. There I would like to see which pods were affected, whether the event was successful, etc. etc.

**Comment by fewdan** [comment]
Thank you for your suggestion, we will consider it.

**Comment by g1eny0ung** [comment]
> I am having trouble seeing the individual events in the timeline of an experiment. I have to click through each event and find out the affected pods etc. by hand.

@torblerone If I understand correctly, the single experiment detail page contains a timeline that tracked its own events.
