### ISSUE TITLE
Network experiments can't run in public cloud cluster

### ISSUE THREAD

**Issue by lcwus2** [chaos-mesh/chaos-mesh#1120]
## Bug Report

**What version of Kubernetes are you using?**

v1.17.4

**What did you do?**

I want to run network experiment, but it reported `admission webhook "vpodnetworkchaos.kb.io" denied the request: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 10.23.1.206:31767: connect: connection refused"`

I see the same problem in FAQs, but my chaos-mesh was deployed in public cloud environment, I can't find where to change it.
![image](https://user-images.githubusercontent.com/30100640/97653037-cd80fb00-1a9a-11eb-856c-b6055c90c800.png)

**What did you expect to see?**

**What did you see instead?**

**Comment by cwen0** [comment]
@lcwus2 If you installed chaos mesh by `install.sh`, you can use `install.sh  --host-network` to upgrade it. If you used helm to install chaos mesh, you can set `hostNetwork` in `values.yaml` and run `helm upgrade chaos-mesh chaos-mesh/chaos-mesh --namespace=chaos-testing -f values.yaml` to upgrade chaos mesh.

**Comment by cwen0** [comment]
@lcwus2 Have you fix this issue?

**Comment by lcwus2** [comment]
curl -sSL https://mirrors.chaos-mesh.org/v1.0.1/install.sh --host-network | bash
curl: option --host-network: is unknown
curl: try 'curl --help' or 'curl --manual' for more information

**Comment by cwen0** [comment]
@lcwus2 `curl -sSL https://mirrors.chaos-mesh.org/v1.0.1/install.sh | bash -s -- --host-network`

**Comment by lcwus2** [comment]
thanks, it works @cwen0
