### ISSUE TITLE
Go get chaos-mesh  report `k8s.io/kube-aggregator@v0.0.0` 404 not found

### ISSUE THREAD

**Issue by zhouqiang-cl** [chaos-mesh/chaos-mesh#1121]
`go get` this project report `k8s.io/kube-aggregator@v0.0.0` report 404, how to solve it?

from: https://github.com/chaos-mesh/chaos-mesh/commit/0d206dfd19fff72fa1183d6b2b06ef26528c8d19#commitcomment-43748783

----
请教一个问题哈，我的项目想引用这个项目，go get这个项目的时候提示k8s.io/kube-aggregator@v0.0.0 这个依赖404呢，请问要怎么解决呢

**Comment by LM-LM** [comment]
不好意思 我没有懂




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "chaos-mesh/chaos-mesh"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月31日(星期六) 下午2:48
收件人:&nbsp;"chaos-mesh/chaos-mesh"<chaos-mesh@noreply.github.com&gt;;
抄送:&nbsp;"夜空中最亮的星"<2876757716@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [chaos-mesh/chaos-mesh] Go get chaos-mesh  report `k8s.io/kube-aggregator@v0.0.0` 404 not found (#1121)





 
/cc @LM-LM

**Comment by fewdan** [comment]
@LM-LM 
I haven't reproduced it, maybe you can refer to this [method](https://blog.csdn.net/weixin_44102363/article/details/103374538) ?

**Comment by zhouqiang-cl** [comment]
> 不好意思 我没有懂
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "chaos-mesh/chaos-mesh" <notifications@github.com&gt;; 发送时间:&nbsp;2020年10月31日(星期六) 下午2:48 收件人:&nbsp;"chaos-mesh/chaos-mesh"<chaos-mesh@noreply.github.com&gt;; 抄送:&nbsp;"夜空中最亮的星"<2876757716@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;; 主题:&nbsp;Re: [chaos-mesh/chaos-mesh] Go get chaos-mesh report `k8s.io/kube-aggregator@v0.0.0` 404 not found (#1121) /cc @LM-LM — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

I just create an issue to record the original question, then it can be more easily be found by others.

**Comment by adamzhoul** [comment]
` go get github.com/chaos-mesh/chaos-mesh

go: downloading github.com/chaos-mesh/chaos-mesh v1.0.1
go: github.com/chaos-mesh/chaos-mesh upgrade => v1.0.1
go get: github.com/chaos-mesh/chaos-mesh@v1.0.1 requires
	k8s.io/kube-aggregator@v0.0.0: reading https://goproxy.cn/k8s.io/kube-aggregator/@v/v0.0.0.mod: 404 Not Found
	server response: not found: k8s.io/kube-aggregator@v0.0.0: invalid version: unknown revision v0.0.0`

same probelm

**Comment by YangKeao** [comment]
It seems to be an issue from `goproxy.cn`. You can file an issue on [goproxy/goproxy.cn](https://github.com/goproxy/goproxy.cn/issues)

BTW, `go get github.com/chaos-mesh/chaos-mesh` is not suggested. If you want to build `chaos-mesh`, `make image` is the best way.

**Comment by adamzhoul** [comment]
> I don't think it's a problem of `chaos-mesh`. You can file an issue on [goproxy/goproxy.cn](https://github.com/goproxy/goproxy.cn/issues)
> 
> BTW, `go get github.com/chaos-mesh/chaos-mesh` is not suggested. If you want to build `chaos-mesh`, `make image` is the best way.

got it, thanks

**Comment by cwen0** [comment]
@zhouqiang-cl @adamzhoul closing as a fixed issue but please feel free to reopen if needed. Thanks!
