### ISSUE TITLE
kind install failed

### ISSUE THREAD

**Issue by phantooom** [chaos-mesh/chaos-mesh#1145]
## Bug Report

**What version of Kubernetes are you using?**
1.19.2 

**What did you do?**

curl -sSL https://mirrors.chaos-mesh.org/v1.0.1/install.sh | bash -s -- --local kind

**What did you expect to see?**
install successed

**What did you see instead?**

```
Install kubectl client
kubectl Version 1.19.2 has been installed
Install Kind tool
Kind Version 0.9.0 has been installed
Install local Kubernetes kind
Kind cluster kind has been installed
main: line 367: /root/kind/kind/config: No such file or directory
```

**Comment by cwen0** [comment]
@phantooom Can you check if your `kind` tool works normally?

**Comment by liangyuanpeng** [comment]
It seems that `kind` was not installed successfully

**Comment by cwen0** [comment]
@liangyuanpeng You can reinstall `kind` tool separately or just remove `kind` directly, and then rerun `install.sh`.

**Comment by liangyuanpeng** [comment]
@cwen0  Thanks for your reply, Actually , it's not my problem. :)  @phantooom  Have any update?

**Comment by WangXiangUSTC** [comment]
@phantooom I close this issue now, you can reopen it again if meet any other problems
