### ISSUE TITLE
chaos-dashboard: could not re-submit after failed to submit a chaos experiment

### ISSUE THREAD

**Issue by STRRL** [chaos-mesh/chaos-mesh#1153]
## Bug Report
After user failed to submit a chaos experiment, user could click previous steps to reconfiguration chaos, but could not re-submit anymore (SUBMIT button is gray). 

**What did you do?**

- create a new chaos experiment, operating on step 1 and step 2 as usual.
- At step 3, choose NetworkChaos; Set action as Delay, set Latency as an invalid value (this will cause a failure while submit).
- click NEXT -> FINISH -> SUBMIT
- Then I received a notice about error occurred, this is under expectation.
- Then I click step 3, reconfigure latency. 
- click NEXT -> FINISH

**What did you expect to see?**
I could click SUBMIT button.

**What did you see instead?**
 SUBMIT button is gray, I can not use it.

**Comment by szeitlin** [comment]
I am having this problem, I think. The same setup - network and latency. The button isn't grayed out, but it seems like the submit button isn't doing anything?
