### ISSUE TITLE
e2e test should support run partial testcase

### ISSUE THREAD

**Issue by Colstuwjx** [chaos-mesh/chaos-mesh#1154]
## Feature Request

**Is your feature request related to a problem? Please describe:**

From the experience of k/k repo, e2e test has always been an unstable part, especially while some PRs make some of the test cases broken. In order to make such thing don't block the other PRs' CI, we should support running specific e2e test case, rather than all test cases. On the other hand, running all the CI cases is a time-wasting job.

**Describe the feature you'd like:**

From now, chaos-mesh CI only support `/run-e2e-tests`, and we should consider introducing sth like `/run-e2e-tests <specific test case>`, e.g. `/run-e2e-tests Network`.

**Describe alternatives you've considered:**

No.

**Teachability, Documentation, Adoption, Migration Strategy:**

Need well document about how to run these cases specifically.

**Comment by STRRL** [comment]
Thanks for your suggestion. We are working on making us e2e test easier.

You could run e2e tests on your own machine, like: 

```shell
./hack/e2e.sh -- --ginkgo.focus='PodKill'
```

This script only needs docker. It will build all necessary images before e2e test execution.

**Comment by Colstuwjx** [comment]
Yes, but we still need to support such instruction with our CI robot, from now, if we want to run e2e test within a PR, the only thing we could do is that type `/run-e2e-tests` without any arguments, and each run may cost more than 20 minutes!

In a word, I hope we could support sth like `/run-e2e-tests Network` or `/run-e2e-tests PodKill` for our CI robot, to run specific test case.
