### ISSUE TITLE
How to install chaos-mesh by helm through rancher2.X

### ISSUE THREAD

**Issue by ct1104** [chaos-mesh/chaos-mesh#1183]
## Question

when i add the Catalog with infomation below  : 
usl : https://github.com/chaos-mesh/chaos-mesh.git
branch: master

than I lanched the chaos-mesh instance  and got the message below:

`Wait helm template rendering notes failed. Error: rendered manifests contain a resource that already exists. Unable to continue with install: could not get information about the resource: mutatingwebhookconfigurations.admissionregistration.k8s.io "chaos-mesh-mutation" is forbidden: User "u-sxdek4jpsk" cannot get resource "mutatingwebhookconfigurations" in API group "admissionregistration.k8s.io" at the cluster scope : exit status 1`

**Comment by STRRL** [comment]
Hi @ct1104 , you need "cluster admin" to install chaos-mesh. Your current user `u-sxdek4jpsk` sounds not holds so much authority.

**Comment by STRRL** [comment]
Hi @ct1104 , do you resolve the issue? If you have any questions, please let us know! 😁
