### ISSUE TITLE
Can't deploy chaos-mesh using Kubernetes go client

### ISSUE THREAD

**Issue by jujoramos** [chaos-mesh/chaos-mesh#1184]
## Bug Report

**What did you do?**
Tried to import `"github.com/chaos-mesh/chaos-mesh/api/v1alpha1"` within my go test file in order to deploy `chaos-mesh` and run some experiments using the Kubernetes go client.
```
import (
	"github.com/chaos-mesh/chaos-mesh/api/v1alpha1"
)

go vet ./...
```

**What did you expect to see?**
Package imported and ready to use.

**What did you see instead?**
```
go: finding module for package github.com/chaos-mesh/chaos-mesh/api/v1alpha1
go: found github.com/chaos-mesh/chaos-mesh/api/v1alpha1 in github.com/chaos-mesh/chaos-mesh v1.0.2
go: github.com/chaos-mesh/chaos-mesh@v1.0.2 requires
	k8s.io/kube-aggregator@v0.0.0: reading k8s.io/kube-aggregator/go.mod at revision v0.0.0: unknown revision v0.0.0
```

**Comment by yliucode** [comment]
@jujoramos  How did you solve this problem?

**Comment by jujoramos** [comment]
@yliucode: I've tried using the `helm` go client but had some conflicts regarding the project dependencies, so ended up using pure helm instead.
