### ISSUE TITLE
Hamza Hedfi

### ISSUE THREAD

**Issue by Hedfi-Hamza** [chaos-mesh/chaos-mesh#1194]
## Feature Request

**Is your feature request related to a problem? Please describe:**

**Describe the feature you'd like:**

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by zhouqiang-cl** [comment]
Hi, @Hedfi-Hamza Could you tell us why did you create this issue?
I did not get the point
