### ISSUE TITLE
Generated OpenApi (openapi/v2) docs are incomplete

### ISSUE THREAD

**Issue by manusa** [chaos-mesh/chaos-mesh#1220]
## Bug Report

**What version of Kubernetes are you using?**
1.18.2, 1.19.1...

**What did you do?**
Parse generated OpenApi definitions generated by Kubernetes from the applied provided CRDs.
```shell script
$ VERSION="1.0.2" && kubectl apply -f https://mirrors.chaos-mesh.org/v$VERSION/crd.yaml
$ kubectl get --raw /openapi/v2 | jq '.definitions."org.chaos-mesh.v1alpha1.PodChaos"'
```

**What did you expect to see?**
A complete object definition including all [properties](https://github.com/chaos-mesh/chaos-mesh/blob/244be9194c3f6404f8a55ffe806992e66d64b518/config/crd/bases/chaos-mesh.org_podchaos.yaml#L36) and descriptions (CRD validation has them but generated OpenApi JSON doesn't).

**What did you see instead?**
```json
{
  "type": "object",
  "x-kubernetes-group-version-kind": [
    {
      "group": "chaos-mesh.org",
      "kind": "PodChaos",
      "version": "v1alpha1"
    }
  ]
}
```
(Same for every other Custom Resource)

**Relates to:**
- https://github.com/manusa/yakc/issues/23
- https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#specifying-a-structural-schema

**Comment by WangXiangUSTC** [comment]
Does this mean that our CRD file format is not standard? And if yes, do you have some tools to format it?

**Comment by manusa** [comment]
Hi, I'm really not an expert on this area, so I'm very unsure if your format is OK or not (I'd say it is, else K8s would complain).

However, the end result (if you check my reproducing steps), is that OpenApi spec is incomplete (I've seen the same for CRDs in other projects e.g. [KUDO](https://kudo.dev/)).

The end result for your project is that neither my [client](https://github.com/manusa/yakc) nor any client generated with https://github.com/kubernetes-client/gen will have complete types (for this second part I'm just guessing, take it with a pinch of salt), which it's a pity.

I tried to alter your CRDs to include flags such as `x-kubernetes-preserve-unknown-fields: true`, but it didn't help.

**Comment by YangKeao** [comment]
@WangXiangUSTC A simpler way to reproduce this problem is to `kubectl explain PodChaos`. I will try to find the problem,

**Comment by manusa** [comment]
Java model types generated with the OpenAPI generated from the CRDs in the current master branch snapshot look complete. 

https://github.com/manusa/yakc/pull/32/files

I'll release my part once a final Chaos-Mesh release is ready. Thank you!
