### ISSUE TITLE
How cloud ChaosMesh dynamically injected into the target Pod,  if the pod is not recreate / restart?

### ISSUE THREAD

**Issue by gotoworld** [chaos-mesh/chaos-mesh#1222]
## Question

Before asking a question, make sure you have:

As I know, Sidecar dynamically injected into the target Pod by **admission-webhooks**, Only when **a Pod is been recreated / restarted**.

if i above is right,  i am confused with follow questions.

1. How cloud ChaosMesh dynamically injected into the target Pod,  if the pod is not recreate / restart?

2. Which kinds of chaosmesh experiments is used CRD sidecar injection? Which case is only use Chaos-daemon to injected the fault (eg: iochaos/networkchaos ?) ?

3. May you privode some more document about the chaosmesh archetecture or principle ?

Thanks a lot!

**Comment by gotoworld** [comment]
For example, When running  the timechaos experiment,  using `kubectl get pod xxxx-selected-4-timechaos-pod -o yaml`.  we never encouter the sidecar containers describe in yaml.

![image](https://user-images.githubusercontent.com/8605471/100305869-fd111d80-2fdc-11eb-9434-db79102b4609.png)

**Comment by STRRL** [comment]
Hi @gotoworld , which version of chaos-mesh do you ues?

AFAIK, the latest release of chaos-mesh does NOT use sidecar for injecting chaos anymore.

**Comment by gotoworld** [comment]
@STRRL    v1.0.1,  

if the latest version NOT use sidecar for injection,  are all the chaosmesh expirement use Chaos-daemon?

if the answer is yes, then the following archetecture is wrong? 
![image](https://user-images.githubusercontent.com/8605471/100307159-1c5d7a00-2fe0-11eb-97f0-462e92f51bab.png)

**Comment by YangKeao** [comment]
@gotoworld Yes. In the previous version (less than 1.0), Chaos Mesh will inject a sidecar container for IOChaos. After 1.0, no sidecar will be injected at all.

Remind that sidecar could only make it possible to share the network namespace with the target pod (and inject into mount namespace through mount propagation), it's not strengthful enough to inject other errors. Chaos Mesh injects other containers by finding PID according to the container id, and enter the target namespace (which can be found in `/proc/$pid/ns`) and group (which can be found in `/proc/$pid/cgroup`)

**Comment by STRRL** [comment]
> if the answer is yes, then the following archetecture is wrong?

This architecture picture is indeed outdated. Could you tell us where do you find it? I think we could update it.

**Comment by YangKeao** [comment]
As for TimeChaos, it's another story. We inject time chaos by ptrace the target process and modify the vDSO part of memory in the target process. I have shared the implementation of it in the community meeting and here is the video [link](https://www.youtube.com/watch?v=Er9_XriY4k8).

**Comment by gotoworld** [comment]
> > if the answer is yes, then the following archetecture is wrong?
> 
> This architecture picture is indeed outdated. Could you tell us where do you find it? I think we could update it.

@STRRL  https://cloud.tencent.com/developer/news/566351

**Comment by gotoworld** [comment]
> @gotoworld Yes. In the previous version (less than 1.0), Chaos Mesh will inject a sidecar container for IOChaos. After 1.0, no sidecar will be injected at all.
> 
> Remind that sidecar could only make it possible to share the network namespace with the target pod (and inject into mount namespace through mount propagation), it's not strengthful enough to inject other errors. Chaos Mesh injects other containers by finding PID according to the container id, and enter the target namespace (which can be found in `/proc/$pid/ns`) and group (which can be found in `/proc/$pid/cgroup`)

---
Got it, very helpful, thanks a lot!

**Comment by gotoworld** [comment]
> As for TimeChaos, it's another story. We inject time chaos by ptrace the target process and modify the vDSO part of memory in the target process. I have shared the implementation of it in the community meeting and here is the video [link](https://www.youtube.com/watch?v=Er9_XriY4k8).

Yes,  for TimeChaos, i have got the article: https://int64.me/2020/%e5%9c%a8%e5%ae%b9%e5%99%a8%e4%b8%ad%e8%ae%a9%e6%97%b6%e9%97%b4%e8%87%aa%e7%94%b1%e6%91%87%e6%91%86.html

Thank you @YangKeao

**Comment by gotoworld** [comment]
> > > if the answer is yes, then the following archetecture is wrong?
> > 
> > 
> > This architecture picture is indeed outdated. Could you tell us where do you find it? I think we could update it.
> 
> @STRRL
> 
> https://dzone.com/articles/chaos-mesh-a-chaos-engineering-solution-for-system
> https://cloud.tencent.com/developer/news/566351
> https://www.infoq.cn/article/fysibtiumuoz2rsdaabf
> https://www.kubernetes.org.cn/7443.html

@STRRL  May u pls send me the latest architecture picture, if there is. thanks

**Comment by STRRL** [comment]
> @STRRL May u pls send me the latest architecture picture, if there is. thanks

You could watch this: https://chaos-mesh.org/docs/overview/architecture

The architecture is quite simple, because powerful chaos-daemon could resolve all these chaos.

**Comment by gotoworld** [comment]
> > @STRRL May u pls send me the latest architecture picture, if there is. thanks
> 
> You could watch this: https://chaos-mesh.org/docs/overview/architecture
> 
> The architecture is quite simple, because powerful chaos-daemon could resolve all these chaos.

I have seen this architecture diagram before, it is very simple, shielding the implementation details, in fact, we are very concerned about its specific implementation details.
