### ISSUE TITLE
chaos-dashboard: weird behavior with creating chaos experiments while press "cmd + P"

### ISSUE THREAD

**Issue by STRRL** [chaos-mesh/chaos-mesh#1234]
## Bug Report

**What version of Kubernetes are you using?**

kuberenetes v1.19.4 with minikube v1.15.1 on macos 11.0.1

image: pingcap/chaos-dashboard:latest 1460b531073a
```
chaos-dashboard --version
Chaos Dashboard Version: version.Info{GitVersion:"v0.9.0-168+ffbded20bafe03", GitCommit:"ffbded20bafe039d8678df8da4885e7502dd5471", BuildDate:"2020-11-30T12:20:44Z", GoVersion:"go1.14.6", Compiler:"gc", Platform:"linux/amd64"}
``` 
**What did you do?**

While creating new chaos experiments, I press "cmd + P"(it's an accident, I do not know why I press it 🤪).
Then the "search modal" pop-up, like this:
![image](https://user-images.githubusercontent.com/20221408/100703999-aaba6d00-33df-11eb-8250-14da4f18f30a.png)

Then I close it.

**What did you expect to see?**

**What did you see instead?**

After I close the "search", every time I press only the "command", the search modal will show up. And I can not use "command + A"(select all)  or "command + R"(refresh)  anymore.

IT'S SO WEIRD!

**Comment by STRRL** [comment]
"command + P" could stable reproduce this issue on my machine.

Sometimes I didn't press "command + P", the same issue also occurs. 😰

**Comment by g1eny0ung** [comment]
`Command + P` is a shortcut to trigger the searching. Seems that I forgot to clear the key binding after close the searching modal. 🤣 I will resolve this problem ASAP.
