### ISSUE TITLE
Remove reduntant e2e test for `pause`

### ISSUE THREAD

**Issue by Yiyiyimu** [chaos-mesh/chaos-mesh#1245]
Currently each chaos has the e2e test for testing its function when pause and unpause. So it's testing two parts: 1. its function 2. if pause working. But since 
1. each chaos already have its own e2e test for function (like `Schedule` for some of them)
2. pause is generally working on different chaos

I think we could only test pause on a single type of chaos, which might save us some time for running e2e test.

**Comment by STRRL** [comment]
No, I don't think it should be removed.

E2e test is a kind of black-box test, when you design e2e test cases, you should drop all the sense about implementation. 
We could not remove these test cases although these use the same codes and the same logic.

**Comment by Yiyiyimu** [comment]
Hi @STRRL thank you for the explanation and I do think they are reasonable.

The reason I raised this issue is when I'm implementing `pause for certain duration` (#1016), I add e2e test to make sure they're working. Running it for one chaos would take 5-6 minutes. The test duration could get optimized but no less than 2 minutes I think.

If I follow the same design pattern for pause e2e test, I need to add the same test to each chaos and it would take tens of minutes to finish them, which would kind of waste time I think. I'm also implementing another timeline-related feature `at`, and it would further prolong the e2e test.

So yes it would be nice to leave the implementation away to better replicate users scenarios. But removing duplicate test would be no harm to the coverage of e2e test but save us quite a lot of time, especially when we have more general features to test.

**Comment by STRRL** [comment]
> But removing duplicate test would be no harm to the coverage of e2e test but save us quite a lot of time, especially when we have more general features to test.

Actually, code coverage is NOT the goal of the test. It's just a metric about the relationship of your "main code" and your "test case code". It could present the logic is correct but the precondition is that the test case is "useful", "real"/"reasonable".

I think reduce our black-box test cases is dangerous, for example:

- the schedule feature for IoChaos passed e2e tests
- "schedule for IoChaos" and "schedule for AnotherChaos" are both implemented by the same codes (as you already knows the implementation)

so 

- "schedule for AnotherChaos" should also work well! 🤪 (really?)

Balck-box test is the way to check these situations. So do not think it's redundant. : P

About speeding up e2e tests, honestly, I do not have any other idea. 🙈

In `./hack/e2e.sh` it uses `--nodes=6` which means it will startup 6 routines for testing. It takes 20-30 minutes on our CI env, and about 10-15 minutes for `git fetch` and `docker build`. So the rest 10 - 20 minutes is for e2e test-cases, I think it still acceptable.🙈

**Comment by Yiyiyimu** [comment]
The example is not somewhat accurate, it should be
- the schedule feature for IoChaos and AnotherChaos passed e2e tests
- the pause + schedule for IoChaos passed e2e tests
- "pause for IoChaos" and "pause for AnotherChaos" are both implemented by the same codes

so 

- pause + schedule for AnotherChaos should also work well...

Ah yeas I still could not guarantee that.. Plus I shouldn't do the "premature optimization" since it has not happened yet🙈

Again thanks a lot for the explanation!!🍻 I'll close this issue
