### ISSUE TITLE
Discussion: Internal Design for Chaos Mesh Workflow

### ISSUE THREAD

**Issue by STRRL** [chaos-mesh/chaos-mesh#1247]
Renderer markdown: [link](https://github.com/STRRL/chaos-mesh/blob/workflow/workflow/docs/design.md)

If you have any suggestions, feel free to comment.

**Comment by YangKeao** [comment]
How will a node move forward from `Holding` to `Running` and to `Succeed`? Why a `NetworkChaos` could execute multiple times in your example (A NetworkChaos Node: Init -> Running -> Holding -> Running -> Succeed)?

**Comment by STRRL** [comment]
I think I should answer this first:

> Why a NetworkChaos could execute multiple times in your example (A NetworkChaos Node: Init -> Running -> Holding -> Running -> Succeed)?

The example just executes only once. `Running` does not mean the Chaos Experiment is effective. It means a "worker routine"(called `Actor`) is doing something for applying/recovering this Chaos Experiment. The `Running` state only exists for a little while.

So actually `Holding` means "Chaos Experiment is effective".

The next question: 
> How will a node move forward from Holding to Running and to Succeed? 

Currently, the core "Engine" follows the event-driven pattern. When something happens(it could be watched by "Trigger"), it will let "Scheduler" or "Workflow Manager" to do something. 

And the core "Engine" is absolutely NOT a stateless application, it's stateful. It is just designed to could recover the state from the persistent layer very easily for fault tolerance.

**So here is the answer to this question:**
For this certain situation: "A NetworkChaos from `Holding` to `Running` and to `Succeed`", when NetworkChaos turning into `Holding`, it registers a "Delay Trigger" for itself. But this just gives the "Manager" a chance to re-considering the state of this NetworChaos; The "Manager" should make a judgment from the current time and the state/status of NetworkChaos, to change the next state for this NetworkChaos. 

How to make the judgment in detail? 🤪 It's not accomplished yet, I just "suppose" a "Manager" could make a judgment. It's also the responsibility bound for "Manager".

Why design as this? 

🤔 It just experiments: the real world is working like this, under the early development of a new system, it's better to describe it as what it really is.
