### ISSUE TITLE
IOChaos不生效

### ISSUE THREAD

**Issue by wingyiu** [chaos-mesh/chaos-mesh#1250]
```
  省略
          volumeMounts:
            - name: storage-volume
              mountPath: /data
              subPath: ""
          ports:
            - name: http
              containerPort: 2333
      volumes:
        - name: storage-volume
          emptyDir: {}
---
apiVersion: chaos-mesh.org/v1alpha1
kind: IoChaos
metadata:
  name: io-delay-example
spec:
  action: latency
  mode: one
  selector:
    pods:
      chaos-testing:
        - chaos-dashboard-797d6fdd79-89gdp
  volumePath: /data
  path: '/data/**/*'
  delay: '1000ms'
  percent: 100
  duration: '60s'
  scheduler:
    cron: '@every 1m30s'
```

```
2020-12-04T10:23:49.009Z        INFO    chaos-daemon-server     applying io chaos       {"Request": "actions:\"[{\\\"type\\\":\\\"latency\\\",\\\"path\\\":\\\"/data/**/*\\\",\\\"percent\\\":100,\\\"faults\\\":[{\\\"errno\\\":0,\\\"weight\\\":1}],\\\"latency\\\":\\\"1000ms\\\",\\\"source\\\":\\\"default/io-delay-example\\\"}]\" volume:\"/data\" container_id:\"docker://4475ac94cb94618a335d4ec6ba439068276f9707d4f4bbf6873c17445c0f7123\" "}
2020-12-04T10:23:49.009Z        INFO    chaos-daemon-server     the length of actions   {"length": 1}
2020-12-04T10:23:49.010Z        INFO    chaos-daemon-server     executing       {"cmd": "/usr/local/bin/toda --path /data --pid 416197 --verbose info"}
2020-12-04T10:23:49.010Z        INFO    background-process-manager      build command   {"command": "/usr/local/bin/suicide /usr/local/bin/toda --path /data --pid 416197 --verbose info"}
2020-12-04T10:23:49.013Z        INFO    background-process-manager      process stopped {"pid": 551144}
2020-12-04T10:24:49.003Z        INFO    chaos-daemon-server     applying io chaos       {"Request": "actions:\"null\" volume:\"/data\" container_id:\"docker://4475ac94cb94618a335d4ec6ba439068276f9707d4f4bbf6873c17445c0f7123\" instance:551144 startTime:1607077428000 "}
2020-12-04T10:24:49.003Z        INFO    chaos-daemon-server     killing toda    {"pid": 551144}
2020-12-04T10:24:49.003Z        INFO    chaos-daemon-server     kill toda successfully
2020-12-04T10:24:49.003Z        INFO    chaos-daemon-server     the length of actions   {"length": 0}
```

用ioping /data目录
并没有延时
```
[root@chaos-dashboard-797d6fdd79-89gdp chaos-mesh]# cd /data
[root@chaos-dashboard-797d6fdd79-89gdp data]# ioping .
4 KiB <<< . (ext4 /dev/sda3): request=1 time=1.28 ms (warmup)
4 KiB <<< . (ext4 /dev/sda3): request=2 time=248.1 us
4 KiB <<< . (ext4 /dev/sda3): request=3 time=272.7 us
4 KiB <<< . (ext4 /dev/sda3): request=4 time=245.6 us
4 KiB <<< . (ext4 /dev/sda3): request=5 time=220.1 us
4 KiB <<< . (ext4 /dev/sda3): request=6 time=273.8 us
4 KiB <<< . (ext4 /dev/sda3): request=7 time=199.5 us (fast)
4 KiB <<< . (ext4 /dev/sda3): request=8 time=314.2 us (slow)
4 KiB <<< . (ext4 /dev/sda3): request=9 time=243.9 us
4 KiB <<< . (ext4 /dev/sda3): request=10 time=203.3 us (fast)
4 KiB <<< . (ext4 /dev/sda3): request=11 time=246.2 us
4 KiB <<< . (ext4 /dev/sda3): request=12 time=257.4 us
4 KiB <<< . (ext4 /dev/sda3): request=13 time=243.0 us
4 KiB <<< . (ext4 /dev/sda3): request=14 time=208.7 us
4 KiB <<< . (ext4 /dev/sda3): request=15 time=189.2 us (fast)
4 KiB <<< . (ext4 /dev/sda3): request=16 time=242.9 us
4 KiB <<< . (ext4 /dev/sda3): request=17 time=178.0 us (fast)
4 KiB <<< . (ext4 /dev/sda3): request=18 time=203.2 us
4 KiB <<< . (ext4 /dev/sda3): request=19 time=272.1 us
```

**Comment by zhouqiang-cl** [comment]
> ```
>   省略
>           volumeMounts:
>             - name: storage-volume
>               mountPath: /data
>               subPath: ""
>           ports:
>             - name: http
>               containerPort: 2333
>       volumes:
>         - name: storage-volume
>           emptyDir: {}
> ---
> apiVersion: chaos-mesh.org/v1alpha1
> kind: IoChaos
> metadata:
>   name: io-delay-example
> spec:
>   action: latency
>   mode: one
>   selector:
>     pods:
>       chaos-testing:
>         - chaos-dashboard-797d6fdd79-89gdp
>   volumePath: /data
>   path: '/data/**/*'
>   delay: '1000ms'
>   percent: 100
>   duration: '60s'
>   scheduler:
>     cron: '@every 1m30s'
> ```
> 
> ```
> 2020-12-04T10:23:49.009Z        INFO    chaos-daemon-server     applying io chaos       {"Request": "actions:\"[{\\\"type\\\":\\\"latency\\\",\\\"path\\\":\\\"/data/**/*\\\",\\\"percent\\\":100,\\\"faults\\\":[{\\\"errno\\\":0,\\\"weight\\\":1}],\\\"latency\\\":\\\"1000ms\\\",\\\"source\\\":\\\"default/io-delay-example\\\"}]\" volume:\"/data\" container_id:\"docker://4475ac94cb94618a335d4ec6ba439068276f9707d4f4bbf6873c17445c0f7123\" "}
> 2020-12-04T10:23:49.009Z        INFO    chaos-daemon-server     the length of actions   {"length": 1}
> 2020-12-04T10:23:49.010Z        INFO    chaos-daemon-server     executing       {"cmd": "/usr/local/bin/toda --path /data --pid 416197 --verbose info"}
> 2020-12-04T10:23:49.010Z        INFO    background-process-manager      build command   {"command": "/usr/local/bin/suicide /usr/local/bin/toda --path /data --pid 416197 --verbose info"}
> 2020-12-04T10:23:49.013Z        INFO    background-process-manager      process stopped {"pid": 551144}
> 2020-12-04T10:24:49.003Z        INFO    chaos-daemon-server     applying io chaos       {"Request": "actions:\"null\" volume:\"/data\" container_id:\"docker://4475ac94cb94618a335d4ec6ba439068276f9707d4f4bbf6873c17445c0f7123\" instance:551144 startTime:1607077428000 "}
> 2020-12-04T10:24:49.003Z        INFO    chaos-daemon-server     killing toda    {"pid": 551144}
> 2020-12-04T10:24:49.003Z        INFO    chaos-daemon-server     kill toda successfully
> 2020-12-04T10:24:49.003Z        INFO    chaos-daemon-server     the length of actions   {"length": 0}
> ```
> 
> 用ioping /data目录
> 并没有延时
> 
> ```
> [root@chaos-dashboard-797d6fdd79-89gdp chaos-mesh]# cd /data
> [root@chaos-dashboard-797d6fdd79-89gdp data]# ioping .
> 4 KiB <<< . (ext4 /dev/sda3): request=1 time=1.28 ms (warmup)
> 4 KiB <<< . (ext4 /dev/sda3): request=2 time=248.1 us
> 4 KiB <<< . (ext4 /dev/sda3): request=3 time=272.7 us
> 4 KiB <<< . (ext4 /dev/sda3): request=4 time=245.6 us
> 4 KiB <<< . (ext4 /dev/sda3): request=5 time=220.1 us
> 4 KiB <<< . (ext4 /dev/sda3): request=6 time=273.8 us
> 4 KiB <<< . (ext4 /dev/sda3): request=7 time=199.5 us (fast)
> 4 KiB <<< . (ext4 /dev/sda3): request=8 time=314.2 us (slow)
> 4 KiB <<< . (ext4 /dev/sda3): request=9 time=243.9 us
> 4 KiB <<< . (ext4 /dev/sda3): request=10 time=203.3 us (fast)
> 4 KiB <<< . (ext4 /dev/sda3): request=11 time=246.2 us
> 4 KiB <<< . (ext4 /dev/sda3): request=12 time=257.4 us
> 4 KiB <<< . (ext4 /dev/sda3): request=13 time=243.0 us
> 4 KiB <<< . (ext4 /dev/sda3): request=14 time=208.7 us
> 4 KiB <<< . (ext4 /dev/sda3): request=15 time=189.2 us (fast)
> 4 KiB <<< . (ext4 /dev/sda3): request=16 time=242.9 us
> 4 KiB <<< . (ext4 /dev/sda3): request=17 time=178.0 us (fast)
> 4 KiB <<< . (ext4 /dev/sda3): request=18 time=203.2 us
> 4 KiB <<< . (ext4 /dev/sda3): request=19 time=272.1 us
> ```

Got, we will take a look

**Comment by wingyiu** [comment]
missing nsenter ?
`/usr/local/pause -n 40381 -- /usr/local/bin/suicide /usr/local/bin/toda --path /data --pid 416197 --verbose info` ?

**Comment by fewdan** [comment]
@wingyiu 
![image](https://user-images.githubusercontent.com/16437100/101337003-1d32bd80-38b6-11eb-9a59-2aa8ff7c74e6.png)
It seems that toda's process ended prematurely due to some unexpected accident.
Otherwise, the log should look like this:
![image](https://user-images.githubusercontent.com/16437100/101337020-23289e80-38b6-11eb-82e1-80dd8b9cdca7.png)
I didn't reproduce this problem in v1.0.2. Can you provide your version of "chaos-controller-manager" and "chaos-daemon" ? I'll try.

**Comment by wingyiu** [comment]
> @wingyiu
> ![image](https://user-images.githubusercontent.com/16437100/101337003-1d32bd80-38b6-11eb-9a59-2aa8ff7c74e6.png)
> It seems that toda's process ended prematurely due to some unexpected accident.
> Otherwise, the log should look like this:
> ![image](https://user-images.githubusercontent.com/16437100/101337020-23289e80-38b6-11eb-82e1-80dd8b9cdca7.png)
> I didn't reproduce this problem in v1.0.2. Can you provide your version of "chaos-controller-manager" and "chaos-daemon" ? I'll try.

change the base docker image from our custom base image back to debian:buster-slim and the problem gone .

**Comment by fewdan** [comment]
@wingyiu 
Did you modify the image of "chaos-daemon" and then the problem was solved?
