### ISSUE TITLE
How to delete an archived experiment?

### ISSUE THREAD

**Issue by lizeyan** [chaos-mesh/chaos-mesh#1251]
How to delete an archived experiment?

**Comment by zhouqiang-cl** [comment]
@g1eny0ung PTAL

**Comment by g1eny0ung** [comment]
@lizeyan It can't be deleted at present (unless the record is deleted manually in db). We designed this function so that every experimental record won't be lost, which is also the meaning of archiving.

And it's not difficult to delete the archive. If this function is what you need, we will discuss whether to support it in the future.

**Comment by lizeyan** [comment]
> @lizeyan It can't be deleted at present (unless the record is deleted manually in db). We designed this function so that every experimental record won't be lost, which is also the meaning of archiving.
> 
> And it's not difficult to delete the archive. If this function is what you need, we will discuss whether to support it in the future.

Would you please give me more detail about deleting archives manually? My dashboard looks very bad now.
<img width="2112" alt="image" src="https://user-images.githubusercontent.com/12494243/101240577-014ee080-372b-11eb-91bd-d50a0e333539.png">

**Comment by g1eny0ung** [comment]
I think to solve this problem temporally just go straight into the container of chaos dashboard, find the sqlite db, and manually delete the record in the events table.

The default db name is called core.sqlite.

**Comment by cwen0** [comment]
@lizeyan If you don't want to keep these archived experiments, you can set `TTL_EXPERIMENT` in [value.yaml](https://github.com/chaos-mesh/chaos-mesh/blob/master/helm/chaos-mesh/values.yaml#L179) to a little value. `TTL_EXPERIMENT` is set to `336h` default, which means chaos dashboard will keep the archived experiments for two weeks.

**Comment by lizeyan** [comment]
> @lizeyan If you don't want to keep these archived experiments, you can set `TTL_EXPERIMENT` in [value.yaml](https://github.com/chaos-mesh/chaos-mesh/blob/master/helm/chaos-mesh/values.yaml#L179) to a little value. `TTL_EXPERIMENT` is set to `336h` default, which means chaos dashboard will keep the archived experiments for two weeks.
> 
> ```yaml
> dashboard:
>    env: 
>        TTL_EXPERIMENT: "24h"
> ```

Thank you for your help.
I have manually cleaned the database and solve my problem.

I only need to manually delete those archived experiments which are mistakenly added by my script.
What I need is not a TTL, but an option to manually delete an experiment completely.
I can't wait for the TTL because the experiments to delete occupy too much space in the timeline-view of events.

**Comment by fewdan** [comment]
@lizeyan 
The only way now is to enter the database and delete it manually.
