### ISSUE TITLE
Dashboard: pod status not change until click the button twice

### ISSUE THREAD

**Issue by Yiyiyimu** [chaos-mesh/chaos-mesh#1258]
## Bug Report

**What version of Kubernetes are you using?**
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:58:59Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:43:34Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

**What did you do?**

Install chaos-mesh via `curl -sSL https://mirrors.chaos-mesh.org/v1.0.2/install.sh | bash`

When I try to run/pause the experiment, after the first time click the button, it stays as `Start/Pause` status. Only if I hit it again would it change to `Pause/Start`. However after the first click, via `kubectl` I could find the status of chaos has already changed, so it's just the UI not get synced. 

**What did you expect to see?**
Status changed after the first click

**What did you see instead?**

**Comment by g1eny0ung** [comment]
In #1430, I try to resolve this problem by delay the data fetching after giving an operation on experiments. Now the UI should work as expected.

I will close this issue. Feel free to reopen it if u still have this question.
