### ISSUE TITLE
Bug: chaos would directly start when it got applied, even if the cron doesn't want it be so

### ISSUE THREAD

**Issue by Yiyiyimu** [chaos-mesh/chaos-mesh#1270]
## Bug Report

**What did you do?**
If we use the cron that does not start right away, for example, if I want to start a chaos at 00:00 each day for 10 minutes, we normally should go into Waiting phase. However, in [the current implementation](https://github.com/chaos-mesh/chaos-mesh/blob/cf9e1ca11670df27b2b8995b0f4942cf96142330/controllers/twophase/types.go#L152) or [the new implementation](https://github.com/chaos-mesh/chaos-mesh/pull/1221/files/3542444758bc14fbca49fbec2b6515555dc4779f#diff-04c792dfed57630c1de983400da2e7639c6d5c3a929c0124f7b5c87aa9a19105)  of two-phase controllers, the chaos would directly go into Running state.

To deal with it, if we use standard cron, it would be a good idea to figure out whether right now should be in waiting or running phase, to go into the correct one. Thus we need to get `lastStart` and `lastRecover`. Although someone creates [a PR about this feature](https://github.com/robfig/cron/pull/216) in cron repo, the maintainer thinks it's outside the scope of that repo so we need to implement this ourselves. Plus, this feature would also be of help to implement pausing for duration(#1016)

Related discussion: [1](https://github.com/chaos-mesh/chaos-mesh/pull/1221#discussion_r535293482), [2](https://github.com/chaos-mesh/chaos-mesh/pull/1221#discussion_r539943354)

**What did you expect to see?**
chaos go from uninitialized to waiting, since it's not the time to start

**What did you see instead?**
chaos go from uninitialized to running

**Comment by YasminBZ** [comment]
Hello, 

I see that the issue was fixed, but actually i'm still having the same issue, the pod is deleted directly after the chaos is applied .

I'm using the version 1.1.1, any suggestions please?

Thank you

**Comment by Yiyiyimu** [comment]
Hi @YasminBZ Actually the PR #1286 has not been merged. I'll try to fix it these days

**Comment by YasminBZ** [comment]
@Yiyiyimu  Okay because i really need to use it for my experiments. Please you ping me when it is done. 

Thank you in advance

**Comment by YasminBZ** [comment]
Hello @Yiyiyimu, 

I want to ask please if it is fixed or not yet .

Best regards,

**Comment by Yiyiyimu** [comment]
@YasminBZ I think it would be fixed today or tomorrow. I'll ping you when the PR got merged

**Comment by Yiyiyimu** [comment]
@YasminBZ PR got merged. Welcom give it a try~

**Comment by YasminBZ** [comment]
@Yiyiyimu  Thank you :), i will try it now

**Comment by YasminBZ** [comment]
Hello @Yiyiyimu 

I tried it, but still having the same issue when deploying  my pod-failure.yaml, it kills directly the pod , it doesn't respect the time configured in my yaml file.

**Comment by Yiyiyimu** [comment]
@YasminBZ Could you give us your yaml file?

**Comment by YasminBZ** [comment]
@Yiyiyimu  I used the example: https://github.com/chaos-mesh/chaos-mesh/blob/master/examples/web-show/pod-failure.yaml

**Comment by Yiyiyimu** [comment]
@YasminBZ 
As you could noticed
https://github.com/chaos-mesh/chaos-mesh/blob/26ec8ddc5a65566b8160852280b30bdbf1cb6895/examples/web-show/pod-failure.yaml#L14-L15
The example use `every 2 minutes` to schedule chaos, so the chaos would start immediately, and restart every two minutes.

If you would like to start chaos at every second minute, you could try `*/2 * * * *`. More trial could be tested on https://crontab.guru/#*/2_*_*_*_*

**Comment by YasminBZ** [comment]
@Yiyiyimu Thank you for your answer.
your proposition to use */2 * * * * worked for me few days ago, but now when i'm trying to execute the same script, it starts the chaos immediately. I really don't get it. Is there some changes in the current last version !!?
