### ISSUE TITLE
Support tcpkill to kill tcp connection

### ISSUE THREAD

**Issue by Colstuwjx** [chaos-mesh/chaos-mesh#1275]
## Feature Request

**Is your feature request related to a problem? Please describe:**

We have some rpc-based systems, and we want to confirm that if it could successfully reconnect the target service after tcp connection lost.

**Describe the feature you'd like:**

We may need to install tcpkill inside chaos-daemon, and make NetworkChaos could define tcpkill action, and kill the services tcp connection accordingly.

**Describe alternatives you've considered:**

I'm not sure whether iptables or ipset could do this action, but I think it would make our rules hard to maintain if all these things both rely on iptables.

**Teachability, Documentation, Adoption, Migration Strategy:**

Someone want to make sure that a tcp-based system could re-connect the target service after its original connection lost.

**Comment by Colstuwjx** [comment]
I've been created go version tcpkill, see [ref](https://github.com/Colstuwjx/tcpkill). But there are still some issues:

1. It could not [send packets while binding to "any"](https://github.com/google/gopacket/issues/844), which the original [tcpkill](https://github.com/ggreer/dsniff/blob/master/tcpkill.c) did support;

2. It could not abort idle connections, and tcpwall did support it by [sending SYN](https://github.com/dushixiang/tcpwall/blob/master/main.go#L90) to the connection two sides, I'm still wondering if we actually need this feature;

3. how we port this tool into chaos-mesh, it's a long-running process, rather than ipset\iptables such rule settings, so the implement way need to be considered.

**Comment by zhouqiang-cl** [comment]
> 3\. how we port this tool into chaos-mesh, it's a long-running process, rather than ipset\iptables such rule settings, so the implement way need to be considered.

Did we need to contain it in chaos-daemon? Should chaos-daemon also support start a long-running process(seems it is complex to management progress in chaos-daemon)?  /cc @chaos-mesh/chaos-mesh

**Comment by Colstuwjx** [comment]
> Did we need to contain it in chaos-daemon? Should chaos-daemon also support start a long-running process(seems it is complex to management progress in chaos-daemon)?

I think chaos daemon is already experienced to manage the background process, see the [IOChaos server implementation code](https://github.com/chaos-mesh/chaos-mesh/blob/master/pkg/chaosdaemon/iochaos_server.go#L78). The question is whether running the tcpkill as a long-running process is the best solution for killing the TCP connections.

**Comment by YangKeao** [comment]
@Colstuwjx Why should it be a long-running process? Does it mean that it will kill all connections during the time?

**Comment by Colstuwjx** [comment]
> @Colstuwjx Why should it be a long-running process? Does it mean that it will kill all connections during the time?

Because it's designed behavior from the tcpkill. It would enter the [pcap loop](https://github.com/ggreer/dsniff/blob/master/tcpkill.c#L146) and wouldn't exit even if it already sent RST and killed the connection.
