### ISSUE TITLE
Refine the dependency of Chaos Mesh

### ISSUE THREAD

**Issue by YangKeao** [chaos-mesh/chaos-mesh#1289]
Importing `github.com/chaos-mesh/chaos-mesh/...` will result in an error: 
```
go: k8s.io/kubernetes@v1.17.2 requires                                                    
    k8s.io/api@v0.0.0: reading k8s.io/api/go.mod at revision v0.0.0: unknown revision v0.0.0
```

That's because the version of the dependency of `k8s.io/kubernetes` hasn't been declared.

>Vendoring Kubernetes code is still not trivial, even after eliminating many of the unnecessary dependencies. k8s.io/kubernetes is not meant to be included in other projects and does not define its dependencies in a way that is understood by tools like dep. The other k8s.io packages are meant to be included, but don’t follow semantic versioning yet or don’t tag any releases (k8s.io/kube-openapi, k8s.io/utils).
>PMEM-CSI uses dep. It’s Gopkg.toml file is a good starting point. It enables pruning (not enabled in dep by default) and locks certain projects onto versions that are compatible with the Kubernetes version that is used. When dep doesn’t pick a compatible version, then checking Kubernetes’ Godeps.json helps to determine which revision might be the right one.

In this repo, we use `replace` in `go.mod` to specify a version for the dependency of `k8s.io/kubernetes`. The user of `chaos-mesh` will also meet this problem and will need to add a lot of `replace` in the `go.mod`. It's a bad experience. There are a lot of users reporting this problem on slack or WeChat.

Why do we need to import `k8s.io/kubernetes`? The reason is quite straightforward: for testing. The only thing we import from it is `"k8s.io/kubernetes/test/e2e/framework"`. 

Do you have any ideas on how to solve the problem? The only thing I can think about is to use multiple `go.mod` for some packages (for `e2e` or `api/v1alpha1`).

As I have done in many issues and PRs, I will blame this problem on the poor design of golang. It seems that the designers of golang haven't thought of the difference between `namespace`, `package`, and `workspace` clearly 👎 .

**Comment by YangKeao** [comment]
The Kubernetes solution is creating a new repo `github.com/chaos-mesh/api` and copying files from `github.com/chaos-mesh/chaos-mesh` to it on every release.

**Comment by Colstuwjx** [comment]
Kubernetes did so hacky on this thing, it has a [staging](https://github.com/kubernetes/kubernetes/tree/master/staging) directory which contains the external repos. If we choose this implementation, we may also need this `staging` directory, and do replace like [this](https://github.com/kubernetes/kubernetes/blob/master/go.mod#L494).

**Comment by YangKeao** [comment]
@Colstuwjx Yes. It seems that we don't have another choice (do we?). I prepare to move `api/v1alpha1` into something like `staging` and use a bot to filter-branch / cherry-pick these commits to another repo.

Before that we need to clean the `api/v1alpha1` package, move some of the functions/methods outside. For example: `networkchaos_types.go` imports `github.com/chaos-mesh/chaos-mesh/pkg/chaosdaemon/pb`, because of methods like `ToNetem`. We can rewrite these methods to functions.

**Comment by YangKeao** [comment]
Another problem is that the bot should update / write the `go.mod` file. (A simple solution is to write a `go.mod` under the `/api/v1alpha1` :smile: )
