### ISSUE TITLE
Script Test failed with network delay verification

### ISSUE THREAD

**Issue by Colstuwjx** [chaos-mesh/chaos-mesh#1306]
## Bug Report

**What version of Kubernetes are you using?**

**What did you do?**

Ran CI Test in PR #1277 .

**What did you expect to see?**
Should pass the tests.

**What did you see instead?**
See logs below:

```
****** test delay chaos ******
networkchaos.chaos-mesh.org/network-delay created
verifaction
PING busybox-1.busybox.busybox.svc (10.244.3.3): 56 data bytes
64 bytes from 10.244.3.3: seq=0 ttl=62 time=0.197 ms
64 bytes from 10.244.3.3: seq=1 ttl=62 time=10.169 ms
64 bytes from 10.244.3.3: seq=2 ttl=62 time=10.197 ms
64 bytes from 10.244.3.3: seq=3 ttl=62 time=10.264 ms
64 bytes from 10.244.3.3: seq=4 ttl=62 time=0.068 ms
64 bytes from 10.244.3.3: seq=5 ttl=62 time=0.104 ms
64 bytes from 10.244.3.3: seq=6 ttl=62 time=0.092 ms
64 bytes from 10.244.3.3: seq=7 ttl=62 time=0.096 ms
64 bytes from 10.244.3.3: seq=8 ttl=62 time=0.105 ms
64 bytes from 10.244.3.3: seq=9 ttl=62 time=0.091 ms

--- busybox-1.busybox.busybox.svc ping statistics ---
10 packets transmitted, 10 packets received, 0% packet loss
round-trip min/avg/max = 0.068/3.138/10.264 ms
the chaos dosen't work as expect
Error: Process completed with exit code 1.
```

And we assume that there would be >=4 <=6 packet loss, see [this line](https://github.com/chaos-mesh/chaos-mesh/blob/master/test/integration_test/network/run.sh#L56), but from the logs, I could see ONLY 3 😿

**Output of chaosctl**

**Comment by WangXiangUSTC** [comment]
seems that sometimes apply the networks chaos to chaos-daemon cost about 1~2 seconds, and the chaos duration begin with the apply time, so the latency > 10ms only 3 times.

I will update the script
