### ISSUE TITLE
crd.yaml err

### ISSUE THREAD

**Issue by wingyiu** [chaos-mesh/chaos-mesh#1314]
error: error validating "crd.yaml": error validating data: ValidationError(CustomResourceDefinition.spec): unknown field "preserveUnknownFields" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.CustomResourceDefinitionSpec; if you choose to ignore these errors, turn validation off with --validate=false

**Comment by g1eny0ung** [comment]
Find the same situation in https://github.com/kubernetes/kubernetes/issues/82874.
