### ISSUE TITLE
support custom way to deploy/access chaos-daemon

### ISSUE THREAD

**Issue by Hexilee** [chaos-mesh/chaos-mesh#1322]
## Feature Request

**Is your feature request related to a problem? Please describe:**

Sometimes the target applied chaos is not a pod. For example, in [Naglfar](https://github.com/PingCAP-QE/Naglfar/) we use k8s-operator to manage containers on bare machines. We can deploy a chaos-daemon on each machine and access it, but we still need many extra works to apply chaos.

**Describe the feature you'd like:**

A dynamic interface to register the way on deploying and access chaos-daemon.

**Describe alternatives you've considered:**

A static interface to define a custom implementation and build a custom image.

**Teachability, Documentation, Adoption, Migration Strategy:**

WIP

**Comment by cwen0** [comment]
@Hexilee Maybe we can support this feature on [chaosd](https://github.com/chaos-mesh/chaosd)

**Comment by Hexilee** [comment]
chaosd may be an alternative, but I want full features of chaos-mesh. I will asign this issue to myself and look for a satisfactory solution.

**Comment by STRRL** [comment]
It seems that chaosd would be the alternative solution for VM, bare metal machine,s and other container environments without being orchestrated by Kubernetes. 

I am going to close this issue,
