### ISSUE TITLE
could you  please refresh the demo，the selectspod method arguments are changed

### ISSUE THREAD

**Issue by cchb1990123** [chaos-mesh/chaos-mesh#1326]
## Feature Request

**Is your feature request related to a problem? Please describe:**

**Describe the feature you'd like:**

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

![image](https://user-images.githubusercontent.com/65523829/102980297-54ee6600-4542-11eb-9ff5-b3e35b6024bd.png)

**Comment by g1eny0ung** [comment]
Hi, could u tell me where the demo can be found? 🤣 I didn't find the same code in the repo.

**Comment by cchb1990123** [comment]
https://chaos-mesh.org/docs/development_guides/add_facilities_to_chaos_daemon

**Comment by g1eny0ung** [comment]
Ok, I will try to resolve this problem ASAP. Thx for reminding! 🚀
