### ISSUE TITLE
Wrong permission for iochaos mountpoint

### ISSUE THREAD

**Issue by liwanxue** [chaos-mesh/chaos-mesh#1329]
## Bug Report

**What version of Kubernetes are you using?**

v1.15.7

**What did you do?**

In container, there is a process running as "clickhouse" user, when `kubectl exec -it chi1-events-0-0-0 bash` to container,  it would be as root user. 
When I try to injest iochaos, it will create new files as root user instead of "clickhouse", which lead to process in container can't write and read file in mount point. 

**What did you expect to see?**

"tmp_fetch_20201224_0_0_0" file should follow permission as file "format_version.txt"

**What did you see instead?**

```
root@chi1-events-0-0-0:/# ls -lah /var/lib/__chaosfs__clickhouse__/data/sherlockio/sherlock_test/

drwxr-x---  2 clickhouse clickhouse 4.0K Dec  4 06:02 detached

-rw-r-----  1 clickhouse clickhouse    1 Dec  4 06:02 format_version.txt

drwxr-x---  2 root       root       4.0K Dec 24 08:35 tmp_fetch_20201224_0_0_0
```

**Output of chaosctl**

Not necessary as iochaos injected successfully.

**Comment by liwanxue** [comment]
I found this issue when I using this feature #1159 
Could anyone help me on this issue?

**Comment by g1eny0ung** [comment]
@YangKeao PTAL.

**Comment by liwanxue** [comment]
@YangKeao Any ETA of this issue? or if I have any workaround solution for this? Appreciate your help.

**Comment by YangKeao** [comment]
@liwanxue I will try to fix this problem next Monday🍻 . 

Actually, in the implementation of the error injecting filesystem, the owner has been set [here](https://github.com/chaos-mesh/toda/blob/c2dc371576e3f0552a979f735853aadb8c9b3b67/src/hookfs/mod.rs#L1145-L1147), so this problem is not expected to happen.

**Comment by STRRL** [comment]
HI @liwanxue, could you provide the pod object which contains "clickhouse" container by `kubectl get pod <your-pod-name> -o yaml`?

**Comment by liwanxue** [comment]
`apiVersion: v1
kind: Pod
metadata:
  annotations:
    application.tess.io/id: urn:xxx-marketplace-consumerid:be4f08da-8424-4931-bb5e-0d99c78dd9c8
    application.tess.io/name: umpmonitoringapp
    io.sherlock.metrics.ch-server-sidecar/hosts: ${data.host}:3000/metrics
    io.sherlock.metrics.ch-server-sidecar/module: prometheus
    io.sherlock.metrics.ch-server-sidecar/namespace: sherlock
    io.sherlock.metrics.ch-server-sidecar/period: 10m
    io.sherlock.metrics.clickhouse-sidecar/hosts: ${data.host}:9116/metrics
    io.sherlock.metrics.clickhouse-sidecar/module: prometheus
    io.sherlock.metrics.clickhouse-sidecar/namespace: sherlock
    io.sherlock.metrics.clickhouse-sidecar/period: 1m
    kubernetes.io/psp: default
  creationTimestamp: "2020-12-28T05:04:41Z"
  generateName: chi1-events-0-0-
  labels:
    application.tess.io/name: umpmonitoringapp
    applicationinstance.tess.io/name: sherlockio-events-app
    clickhouse.altinity.com/app: chop
    clickhouse.altinity.com/chi: chi1
    clickhouse.altinity.com/chiScopeCycleIndex: "0"
    clickhouse.altinity.com/chiScopeCycleOffset: "0"
    clickhouse.altinity.com/chiScopeCycleSize: "0"
    clickhouse.altinity.com/chiScopeIndex: "0"
    clickhouse.altinity.com/chop: 0.9.2
    clickhouse.altinity.com/cluster: events
    clickhouse.altinity.com/clusterScopeCycleIndex: "0"
    clickhouse.altinity.com/clusterScopeCycleOffset: "0"
    clickhouse.altinity.com/clusterScopeCycleSize: "0"
    clickhouse.altinity.com/clusterScopeIndex: "0"
    clickhouse.altinity.com/namespace: default
    clickhouse.altinity.com/replica: "0"
    clickhouse.altinity.com/replicaScopeIndex: "0"
    clickhouse.altinity.com/settings-version: 6d991861919015dd93cb5e0090a956c4862f9879
    clickhouse.altinity.com/shard: "0"
    clickhouse.altinity.com/shardScopeIndex: "0"
    clickhouse.altinity.com/zookeeper-version: 4cf91c018384312ace04c6152855c78472ccff96
    controller-revision-hash: chi1-events-0-0-85856676bb
    environment.tess.io/name: dev
    statefulset.kubernetes.io/pod-name: chi1-events-0-0-0
  name: chi1-events-0-0-0
  namespace: default
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: StatefulSet
    name: chi1-events-0-0
    uid: c6486234-8d5c-4644-b3c0-130e1a7fb0d7
  resourceVersion: "54968267"
  selfLink: /api/v1/namespaces/default/pods/chi1-events-0-0-0
  uid: 48f1cfc2-760b-4c7a-9cca-ce709e37d693
spec:
  containers:
  - env:
    - name: pod_ip
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: status.podIP
    image: ecr.vip.xxx.com/sherlockio/clickhouse-server:19.16.14.65
    imagePullPolicy: IfNotPresent
    name: clickhouse-server
    ports:
    - containerPort: 8123
      protocol: TCP
    - containerPort: 9000
      protocol: TCP
    - containerPort: 9009
      protocol: TCP
    - containerPort: 9000
      name: tcp
      protocol: TCP
    - containerPort: 8123
      name: http
      protocol: TCP
    - containerPort: 9009
      name: interserver
      protocol: TCP
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /ping
        port: 8123
        scheme: HTTP
      initialDelaySeconds: 5
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    resources:
      limits:
        cpu: "4"
        memory: 15Gi
      requests:
        cpu: "2"
        memory: 10Gi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/lib/clickhouse
      name: default-volume-claim
    - mountPath: /etc/clickhouse-server/config.d/
      name: chi-chi1-common-configd-federated
    - mountPath: /etc/clickhouse-server/users.d/
      name: chi-chi1-common-usersd
    - mountPath: /etc/clickhouse-server/conf.d/
      name: chi-chi1-deploy-confd-events-0-0
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-gvxn8
      readOnly: true
  - image: ecr.vip.xxxx.com/sherlockio/clickhouse-exporter:latest
    imagePullPolicy: Always
    name: clickhouse-sidecar
    ports:
    - containerPort: 9116
      protocol: TCP
    resources:
      limits:
        cpu: "1"
        memory: 1Gi
      requests:
        cpu: 200m
        memory: 1Gi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /etc/clickhouse-server/config.d/
      name: chi-chi1-common-configd-federated
    - mountPath: /etc/clickhouse-server/users.d/
      name: chi-chi1-common-usersd
    - mountPath: /etc/clickhouse-server/conf.d/
      name: chi-chi1-deploy-confd-events-0-0
    - mountPath: /var/lib/clickhouse
      name: default-volume-claim
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-gvxn8
      readOnly: true
  - env:
    - name: chDatabase
      value: sherlockio
    - name: chEndpoint
      value: http://localhost:8123
    - name: CH_USERNAME
      valueFrom:
        secretKeyRef:
          key: CH_USERNAME
          name: clickhouse-secret
    - name: CH_PASSWORD
      valueFrom:
        secretKeyRef:
          key: CH_PASSWORD
          name: clickhouse-secret
    image: ecr.vip.xxx.com/qzuo/ch-server-sidecar:2.8.2
    imagePullPolicy: IfNotPresent
    name: ch-server-sidecar
    ports:
    - containerPort: 3000
      protocol: TCP
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /replicaReadiness/200
        port: 3000
        scheme: HTTP
      initialDelaySeconds: 5
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    resources:
      limits:
        cpu: "1"
        memory: 1Gi
      requests:
        cpu: 200m
        memory: 1Gi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /etc/clickhouse-server/config.d/
      name: chi-chi1-common-configd-federated
    - mountPath: /etc/clickhouse-server/users.d/
      name: chi-chi1-common-usersd
    - mountPath: /etc/clickhouse-server/conf.d/
      name: chi-chi1-deploy-confd-events-0-0
    - mountPath: /var/lib/clickhouse
      name: default-volume-claim
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-gvxn8
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  hostAliases:
  - hostnames:
    - chi1-events-0-0-513
    ip: 127.0.0.1
  hostname: chi1-events-0-0-0
  nodeName: tess-node-zxspq-4042834.slc07.dev.xxx.com
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  subdomain: chi1-events-0-0-513
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoSchedule
    key: node.kubernetes.io/memory-pressure
    operator: Exists
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 900
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 900
  volumes:
  - name: default-volume-claim
    persistentVolumeClaim:
      claimName: default-volume-claim-chi1-events-0-0-0
  - configMap:
      defaultMode: 420
      name: chi-chi1-common-configd-federated
    name: chi-chi1-common-configd-federated
  - configMap:
      defaultMode: 420
      name: chi-chi1-common-usersd
    name: chi-chi1-common-usersd
  - configMap:
      defaultMode: 420
      name: chi-chi1-deploy-confd-events-0-0
    name: chi-chi1-deploy-confd-events-0-0
  - name: default-token-gvxn8
    secret:
      defaultMode: 420
      secretName: default-token-gvxn8
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2020-12-28T05:04:41Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2020-12-28T05:05:12Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2020-12-28T05:05:12Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2020-12-28T05:04:41Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://dda013160edcc1e3f77d6b47a6518d2c8bc548743cfe865bb87ed5d792cc6496
    image: ecr.vip.xxx.com/qzuo/ch-server-sidecar:2.8.2
    imageID: ecr.vip.xxx.com/qzuo/ch-server-sidecar@sha256:5a99663bd182f6ee5d43a338a3a7b91c14fad2e486bffb49e9acadd74df9bffa
    lastState: {}
    name: ch-server-sidecar
    ready: true
    restartCount: 0
    state:
      running:
        startedAt: "2020-12-28T05:04:59Z"
  - containerID: containerd://6fac74b7033f85cfaf38dbe790f11f38d19c9f37ad6358285b679bac8c467ea9
    image: ecr.vip.xxx.com/xx/clickhouse-server:19.16.14.65
    imageID: ecr.vip.xxx.com/xx/clickhouse-server@sha256:9d28f49387c3b78745292033063951445d4fb744894ff98960a2c7ebb8b0290f
    lastState: {}
    name: clickhouse-server
    ready: true
    restartCount: 0
    state:
      running:
        startedAt: "2020-12-28T05:04:57Z"
  - containerID: containerd://2270433fa56f56eafb0e32c32641dfc545a4e1f14760e4e69011bd6185337654
    image: ecr.vip.xxxx.com/xx/clickhouse-exporter:latest
    imageID: ecr.vip.xxxx.com/xx/clickhouse-exporter@sha256:67d59c0c32a9821f2ba01b87790a023d956d29de05170cd2b31e254993df574f
    lastState: {}
    name: clickhouse-sidecar
    ready: true
    restartCount: 0
    state:
      running:
        startedAt: "2020-12-28T05:04:58Z"
  hostIP: 10.148.208.18
  phase: Running
  podIP: 10.148.208.99
  qosClass: Burstable
  startTime: "2020-12-28T05:04:41Z"`

**Comment by STRRL** [comment]
Hi @liwanxue, I have a try based on docker image `yandex/clickhouse-server`, it seems the file `tmp_fetch_x_x_x` is not created by process `clickhouse`.

> When I try to injest iochaos, it will create new files as root user instead of "clickhouse", ...

I think "it" refers to a process that is not `clickhouse`, and this process executes as "root".

If you could figure out which process will create file `tmp_fetch_x_x_x`, you could run it with `gosu` like clickhouse doing.

**Comment by liwanxue** [comment]
I'm 100% sure tmp_fetch_x_x_x is created by clickhouse process. 
When injected iochaos, **toda** process started as root. it will mirror all file operations which happened in clickhouse process. 
So, you can see the tmp_fetch_x_x_x is created by toda.

**Comment by STRRL** [comment]
Hi @liwanxue, could you give me any documents about file `tmp_fetch_x_x_x`, or how to let clickhouse generate this file?

I let clickhouse runs alone for about 30 mintues, and I failed to reproduce this issue, and no file called `tmp_fetch_x_x_x` created.

**Comment by liwanxue** [comment]
oh, here an example to generate this file 
`CREATE DATABASE sherlockio`
`CREATE TABLE sherlockio.sherlock_test_buffer (`__name__` String, `unixtime` DateTime('Etc/UTC'), `__value__` Int8 DEFAULT CAST(1, 'Int8'), `colo` Nullable(String), `count` Nullable(Int64), `sum` Nullable(Int64)) ENGINE = Buffer('sherlockio', 'sherlock_test', 2, 2, 10, 10000, 100000, 1000000, 100000000)`
`CREATE TABLE sherlockio.sherlock_test (`__name__` String, `unixtime` DateTime('Etc/UTC'), `__value__` Int8 DEFAULT CAST(1, 'Int8'), `colo` Nullable(String), `count` Nullable(Int64), `sum` Nullable(Int64)) ENGINE = ReplicatedMergeTree('/clickhouse/{installation}/{cluster}/tables/{shard}/{database}/{table}', '{replica}') PARTITION BY toYYYYMMDD(unixtime) ORDER BY (__name__, unixtime) SETTINGS index_granularity = 8192`

Then insert data to buffer table 
insert into sherlockio.sherlock_test_buffer values('test',now(),1,'tst',1,1)

**Comment by STRRL** [comment]
Hi @liwanxue, I startup a clickhose cluster with docker-compose based on `tetafro/clickhouse-cluster`, I had executed your given query successfully. But still failed to reproduce this issue, and the file is different from your situation:

```bash
root@clickhouse01:/var/lib/clickhouse/data/sherlockio/sherlock_test# pwd
/var/lib/clickhouse/data/sherlockio/sherlock_test
root@clickhouse01:/var/lib/clickhouse/data/sherlockio/sherlock_test# ls -alhR
.:
total 4.0K
drwxr-x---. 1 clickhouse clickhouse  80 Dec 30 04:03 .
drwxr-x---. 1 clickhouse clickhouse  26 Dec 30 04:03 ..
drwxr-x---. 1 clickhouse clickhouse 570 Dec 30 04:03 20201230_0_0_0
drwxr-x---. 1 clickhouse clickhouse   0 Dec 30 04:03 detached
-rw-r-----. 1 clickhouse clickhouse   1 Dec 30 04:03 format_version.txt

./20201230_0_0_0:
total 96K
drwxr-x---. 1 clickhouse clickhouse 570 Dec 30 04:03 .
drwxr-x---. 1 clickhouse clickhouse  80 Dec 30 04:03 ..
-rw-r-----. 1 clickhouse clickhouse 633 Dec 30 04:03 checksums.txt
-rw-r-----. 1 clickhouse clickhouse  30 Dec 30 04:03 colo.bin
-rw-r-----. 1 clickhouse clickhouse  48 Dec 30 04:03 colo.mrk2
-rw-r-----. 1 clickhouse clickhouse  27 Dec 30 04:03 colo.null.bin
-rw-r-----. 1 clickhouse clickhouse  48 Dec 30 04:03 colo.null.mrk2
-rw-r-----. 1 clickhouse clickhouse 173 Dec 30 04:03 columns.txt
-rw-r-----. 1 clickhouse clickhouse  34 Dec 30 04:03 count.bin
-rw-r-----. 1 clickhouse clickhouse  48 Dec 30 04:03 count.mrk2
-rw-r-----. 1 clickhouse clickhouse  27 Dec 30 04:03 count.null.bin
-rw-r-----. 1 clickhouse clickhouse  48 Dec 30 04:03 count.null.mrk2
-rw-r-----. 1 clickhouse clickhouse   1 Dec 30 04:03 count.txt
-rw-r-----. 1 clickhouse clickhouse   8 Dec 30 04:03 minmax_unixtime.idx
-rw-r-----. 1 clickhouse clickhouse  31 Dec 30 04:03 __name__.bin
-rw-r-----. 1 clickhouse clickhouse  48 Dec 30 04:03 __name__.mrk2
-rw-r-----. 1 clickhouse clickhouse   4 Dec 30 04:03 partition.dat
-rw-r-----. 1 clickhouse clickhouse  18 Dec 30 04:03 primary.idx
-rw-r-----. 1 clickhouse clickhouse  34 Dec 30 04:03 sum.bin
-rw-r-----. 1 clickhouse clickhouse  48 Dec 30 04:03 sum.mrk2
-rw-r-----. 1 clickhouse clickhouse  27 Dec 30 04:03 sum.null.bin
-rw-r-----. 1 clickhouse clickhouse  48 Dec 30 04:03 sum.null.mrk2
-rw-r-----. 1 clickhouse clickhouse  30 Dec 30 04:03 unixtime.bin
-rw-r-----. 1 clickhouse clickhouse  48 Dec 30 04:03 unixtime.mrk2
-rw-r-----. 1 clickhouse clickhouse  27 Dec 30 04:03 __value__.bin
-rw-r-----. 1 clickhouse clickhouse  48 Dec 30 04:03 __value__.mrk2

./detached:
total 0
drwxr-x---. 1 clickhouse clickhouse  0 Dec 30 04:03 .
drwxr-x---. 1 clickhouse clickhouse 80 Dec 30 04:03 ..
root@clickhouse01:/var/lib/clickhouse/data/sherlockio/sherlock_test# clickhouse-server -V
ClickHouse server version 20.4.9.110 (official build).
root@clickhouse01:/var/lib/clickhouse/data/sherlockio/sherlock_test#
```

On my machine, I noticed here is a directory called "20201230_0_0_0" created, the name is different, and the permission is under expectation.

Could you tell us your clickhouse-server version? Or you are using a customized/modified edition.

Actually, `toda` will not create files and change file's mod/permission actively, it based on `fuse` and only resolve the FS requests. 

Could you take a look at the clickhouse cluster without IOChaos? I think whether you inject IOChaos or not, the unexpected `root` permission on `tmp_fetch_x_x_x_x` will still appear.

**Comment by YangKeao** [comment]
@STRRL
> `toda` will not create files and change file's mod/permission actively

No. `toda` will actually create files (to mirror the operation on the filesystem), but it will set the owner and the group correctly ([here](https://github.com/chaos-mesh/toda/blob/c2dc371576e3f0552a979f735853aadb8c9b3b67/src/hookfs/mod.rs#L1145-L1147)).

**Comment by STRRL** [comment]
> No. toda will actually create files (to mirror the operation on the filesystem), but it will set the owner and the group correctly (here).

Oh, I think my words bring ambiguity. 🙈

`toda` will not create extra files which out of your operation.

**Comment by liwanxue** [comment]
tmp_fetch file is created when clickhouse have replications, but I do see there are file was created by root
```
drwxr-x---   2 root       root       4.0K Dec 30 05:54 tmp_insert_20201230_903_903_0
drwxr-x---   2 root       root       4.0K Dec 30 05:54 tmp_insert_20201230_904_904_0
drwxr-x---   2 root       root       4.0K Dec 30 05:54 tmp_insert_20201230_905_905_0
drwxr-x---   2 root       root       4.0K Dec 30 05:54 tmp_insert_20201230_906_906_0
drwxr-x---   2 root       root       4.0K Dec 30 05:54 tmp_insert_20201230_907_907_0
drwxr-x---   2 root       root       4.0K Dec 30 05:55 tmp_insert_20201230_908_908_0
drwxr-x---   2 root       root       4.0K Dec 30 05:55 tmp_insert_20201230_909_909_0
drwxr-x---   2 root       root       4.0K Dec 30 05:55 tmp_insert_20201230_910_910_0
```

**Comment by STRRL** [comment]
Hi @liwanxue, I think I had reproduced a similar issue: 

I inject IOChaos **before** create database and table,  the directory `/var/lib/clickhouse/metadata` has wrong permission.

```bash
root@clickhouse01:/var/lib/clickhouse/metadata# ls -alh
total 8.0K
drwxr-x---. 1 clickhouse clickhouse  96 Dec 30 06:02 .
drwxr-xr-x. 1 clickhouse clickhouse 204 Dec 30 05:59 ..
drwxr-x---. 1 clickhouse clickhouse   0 Dec 30 05:59 default
-rw-r-----. 1 clickhouse clickhouse  42 Dec 30 05:59 default.sql
drwxr-x---. 1 root       root         0 Dec 30 06:02 sherlockio
-rw-r-----. 1 clickhouse clickhouse  45 Dec 30 06:02 sherlockio.sql
drwxr-x---. 1 clickhouse clickhouse   0 Dec 30 05:59 system
```
I am working on this.  😁
