### ISSUE TITLE
Is the dns chaos function included in the v1.0.3 version？

### ISSUE THREAD

**Issue by 912988434** [chaos-mesh/chaos-mesh#1331]
I saw dns chaos in the v1.0.3 version of the document, but dns chaos related resources were not found in crd when helm was installed, and dns related templates were not found in the chart template

**Comment by zhouqiang-cl** [comment]
@912988434 DNS Chaos is not included in v1.0.3, it in latest version(master branch)

**Comment by g1eny0ung** [comment]
@912988434 Sorry for making you confused about this. We inadvertently moved out what was supposed to be the latest document, and it has now been fixed.

**Comment by 912988434** [comment]
> @ 912988434对不起，您对此感到困惑。我们无意间搬走了原本应该是最新的文档，现在已将其修复。

thanks
