### ISSUE TITLE
Support dashboard page edite, not only through yaml

### ISSUE THREAD

**Issue by zhanghuidinah** [chaos-mesh/chaos-mesh#1334]
## Feature Request

**Is your feature request related to a problem? Please describe:**

- When the Chaos Mesh is used by multiple people in other projects, some users in other projects may not know exactly what yaml config should be written, because it is created in the dashboard, can it support changes on the page like creation as shown below.

![image](https://user-images.githubusercontent.com/31201589/103256598-cc037e80-49c8-11eb-9e07-505eb533da1e.png)

**Describe the feature you'd like:**

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by g1eny0ung** [comment]
If I understand correctly, this feature request is about `Update Experiment`?

On the experiment detail page, there already has a YAML viewer like the below image:

![image](https://user-images.githubusercontent.com/15034155/103264498-d122f680-49e5-11eb-944a-ff5f73d26278.png)

And...This feature is only available in the latest version...the old `v1.0.x` only has a rudimentary, temporary JSON editor 😢.

But don't worry! We will plan to release `v1.1.0` these two weeks. At the same time, this feature will be carried 😉.

**Comment by g1eny0ung** [comment]
Close due to `v1.1.0` released.
