### ISSUE TITLE
Some issues shouldn't be closed by time

### ISSUE THREAD

**Issue by YangKeao** [chaos-mesh/chaos-mesh#1339]
The github bot has marked a lot of issues to stale and closed them automatically. However, some valuable and unresolved issues are closed. I think an issue should be marked as `stale` iff it's a bug report and we haven't received enough information to reproduce it. For other situations, like feature request, we could close it or reference to another tracking issue manually (or just left it open, reminding us to implement the feature).

Could we have some methods to mark an issue valuable to avoid it to be closed by the bot?

**Comment by zhouqiang-cl** [comment]
Make sense. @cwen0 could you please adjust some stale rules?

**Comment by g1eny0ung** [comment]
The stale bot has a `exemptLabels` field to make the issue consider to never as stale. We can use it to meet our needs.
