### ISSUE TITLE
StressChaos injects stress only in the first container, not all of them.

### ISSUE THREAD

**Issue by ereOn** [chaos-mesh/chaos-mesh#1353]
## Bug Report

**What version of Kubernetes are you using?**

Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:14:22Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.12-eks-7684af", GitCommit:"7684af4ac41370dd109ac13817023cb8063e3d45", GitTreeState:"clean", BuildDate:"2020-10-20T22:57:40Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

**What did you do?**

I have been toying with chaos-mesh and `StressChaos` in particular. I wanted to simulate CPU load to check that my HorizontalPodAutoscaler is working as intended. As I asked for 100% CPU usage, only one of the three containers in the pod received the CPU load, and so the HPA did not scale up (as the average CPU usage for the pod remained below the configured 80%).

**What did you expect to see?**

I expected to see CPU load injected in all containers (or an option to do so).

**What did you see instead?**

Only one container (the first one defined) received the CPU load.

**Output of chaosctl**

Not relevant.

I am interested in adding support for that if there is a will (and the feature really isn't there - I may just have missed it). I might just need pointers as to where to start.

Thank you for Chaos Mesh! It's really great.

**Comment by WangXiangUSTC** [comment]
Thanks
1. Only one container received the CPU load, I will investigate this issue.
2. What new features do you want to develop for `chaosctl`?

**Comment by WangXiangUSTC** [comment]
Now the stress chaos can only choose one container(default: the first one) to inject chaos, and you can specify the container by container name.
![image](https://user-images.githubusercontent.com/5793595/103726249-67bd6c00-5013-11eb-9baf-9fe700bfae6a.png)

**Comment by WangXiangUSTC** [comment]
Create an issue for it, we will implement it later https://github.com/chaos-mesh/chaos-mesh/issues/1354

**Comment by ereOn** [comment]
Thank you. I will follow the newly created issue.
