### ISSUE TITLE
Error: Specified qdisc not found.

### ISSUE THREAD

**Issue by chenzhenyang** [chaos-mesh/chaos-mesh#1361]
chaos-daemon container logs
```
2021-01-06T08:13:15.401Z        ERROR   chaos-daemon-server     error while adding prio {"error": "error code: exit status 2, msg: Error: Specified qdisc not found.\n"}
```

dashboard:
```
An error occurred: admission webhook "vpodnetworkchaos.kb.io" denied the request: rpc error: code = Unknown desc = error code: exit status 2, msg: Error: Specified qdisc not found.
```

**Comment by WangXiangUSTC** [comment]
this issue is duplicate with https://github.com/chaos-mesh/chaos-mesh/issues/1224

**Comment by WangXiangUSTC** [comment]
I will close this issue, you can try to use the method provided in the issue above to fix it, and you can reopen this issue again if it doesn't work.

**Comment by WangXiangUSTC** [comment]
refer to https://github.com/chaos-mesh/chaos-mesh/issues/1389
