### ISSUE TITLE
How to install chaosmesh on specific kubeconfig?

### ISSUE THREAD

**Issue by nirutgupta** [chaos-mesh/chaos-mesh#1362]
Hi is there any way to install chaos mesh on specific kubernetes cluster? Consider a fact that I have multiple kubeconfig files and I need to select one to install on.

**Comment by nirutgupta** [comment]
the single command which i am talking about is install.sh script which you guys have. 
https://mirrors.chaos-mesh.org/v1.0.3/install.sh

**Comment by WangXiangUSTC** [comment]
You need to switch the context by `kubectl config use-context`, or change your `~/.kube/config` file.
