### ISSUE TITLE
feat: make a common pod manager to replace podio(network)chaosmanager

### ISSUE THREAD

**Issue by Yiyiyimu** [chaos-mesh/chaos-mesh#1364]
## Feature Request

**Is your feature request related to a problem? Please describe:**
Currently, there are two separate podXXchaosmanager for io chaos and network chaos. However, the implementation of them ( [io](https://github.com/chaos-mesh/chaos-mesh/blob/3d3cd87c5448655f8aac9d3115050d82374e66c4/controllers/iochaos/podiochaosmanager/podiochaosmanager.go), [network](https://github.com/chaos-mesh/chaos-mesh/blob/3d3cd87c5448655f8aac9d3115050d82374e66c4/controllers/networkchaos/podnetworkmanager/podnetworkmanager.go) ) are almost the same. Besides, in #1014, we also need a common pod manager to encapsulate the same struct `cleanFinalizersAndRecover`.

**Describe the feature you'd like:**

I made some tests but didn't succeed...

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by WangXiangUSTC** [comment]
could you please provide the tests you do? Maybe you can create a pr with label `WIP` for it.

**Comment by YangKeao** [comment]
I have tried to construct a common `podXXchaosmanager` in two ways: reflect and code generation.

`reflect` is a easy but dangerous method, which may cause runtime error and hard to review, so I prefer code generation. But code generation and type analysis (through [types](https://golang.org/pkg/go/types) pkg) is much harder (but interesting) to write than `reflect`.

Do you have a better idea on how to resolve this issue?

**Comment by Yiyiyimu** [comment]
@WangXiangUSTC I only tried with `reflect`, but it made the code too messy with a lot of type switch, which makes it too intentional. I don't like it that much so I didn't commit it.

And yes I do have that worry about using code generation. @YangKeao Your explanation presents it pretty well! I could take care of it when I got time with it.

**Comment by YangKeao** [comment]
Or a patch instead of `transaction` could be better? But I don't know what will happen if the merge key is the same as delete key, e.g.

```yaml
- $patch: delete
  source: one-network-chaos
- source: one-network-chaos
  xxxx: xxxx
```
