### ISSUE TITLE
How can chaos-mesh be installed in intranet eaily?

### ISSUE THREAD

**Issue by douxiaoniu77** [chaos-mesh/chaos-mesh#1385]
## Question
According to the chaos-mesh wiki or doc,  it is required to download script or file from git or mirrors,  and it is difficult to do that in intranet.  Comparing with another tool chaos-blade, which could be installed easily in intranet via operator image, is chaos mesh supported by that?  Or is there any way to install chaos-mesh in intranet more easily?   Would you please kindly have a look?

Before asking a question, make sure you have:

- Reviewed relevant Kubernetes information: Google your error messages and look at K8s docs.
- Searched open and closed [GitHub issues](https://github.com/chaos-mesh/chaos-mesh/issues?utf8=%E2%9C%93&q=is%3Aissue)
- Read the documentation:
  - [Chaos Mesh Readme](https://github.com/chaos-mesh/chaos-mesh)
  - [Chaos Mesh Doc](https://chaos-mesh.org/docs)

**Output of chaosctl**

**Comment by YangKeao** [comment]
Preload `pingcap/chaos-mesh`, `pingcap/chaos-daemon`, `pingcap/chaos-dashboard` and `pingcap/coredns` to the registry in intranet, and installing through helm while specifying the image by `--set controllerManager.image=xxxxx/pingcap/chaos-mesh  --set chaosDaemon.image=xxxxx/pingcap/chaosDaemon  ...`.

Maybe we should provide easier ways to modify the registry of every images rather than specify them one by one? @cwen0

**Comment by cwen0** [comment]
> Preload `pingcap/chaos-mesh`, `pingcap/chaos-daemon`, `pingcap/chaos-dashboard` and `pingcap/coredns` to the registry in intranet, and installing through helm while specifying the image by `--set controllerManager.image=xxxxx/pingcap/chaos-mesh --set chaosDaemon.image=xxxxx/pingcap/chaosDaemon ...`.
> 
> Maybe we should provide easier ways to modify the registry of every images rather than specify them one by one? @cwen0

Yes, We can abstract a registry flag to define it.

**Comment by douxiaoniu77** [comment]
Thanks for y

> Preload `pingcap/chaos-mesh`, `pingcap/chaos-daemon`, `pingcap/chaos-dashboard` and `pingcap/coredns` to the registry in intranet, and installing through helm while specifying the image by `--set controllerManager.image=xxxxx/pingcap/chaos-mesh --set chaosDaemon.image=xxxxx/pingcap/chaosDaemon ...`.
> 
> Maybe we should provide easier ways to modify the registry of every images rather than specify them one by one? @cwen0

Thanks for your suggestions!   
Now pingcap/chaos-mesh, pingcap/chaos-daemon images could be found and pulled to my local, however I could not find the image of pingcap/chaos-dashboard,  then I'd like to build the image locally, but ran into another issue with following error.   Would you please help to give some suggestions? 

Step 11/11 : COPY bin/chaos-dashboard /usr/local/bin/chaos-dashboard
COPY failed: stat /var/lib/docker/tmp/docker-builder351611802/bin/chaos-dashboard: no such file or directory

xueniudeMacBook-Pro:chaos-dashboard xueniu$ ls bin/.gitkeep 
xueniudeMacBook-Pro:chaos-dashboard xueniu$ pwd
/Users/xueniu/chaos-mesh/images/chaos-dashboard

**Comment by YangKeao** [comment]
@douxiaoniu77 Why the `pingcap/chaos-dashboard` cannot be found? https://hub.docker.com/r/pingcap/chaos-dashboard 

If you want to build the image locally, run `make UI=1 SWAGGER=1 image-chaos-dashboard`

**Comment by douxiaoniu77** [comment]
> @douxiaoniu77 Why the `pingcap/chaos-dashboard` cannot be found? https://hub.docker.com/r/pingcap/chaos-dashboard
> 
> If you want to build the image locally, run `make UI=1 SWAGGER=1 image-chaos-dashboard`

Thanks again, YangKeao！  
It works now, not sure why it wasn't listed yesterday when searched.

**Comment by douxiaoniu77** [comment]
@YangKeao   Would you please help on my another question?   Most scenarios supported by chaos-mesh are focused on the application on k8s platform，eg pod killing, pod cpu burn and so on.   Will more chaos scenario be supported for k8s clusters or k8s platform? like master or worker node crash,  infrastructure chaos.

**Comment by YangKeao** [comment]
@douxiaoniu77 

> Will more chaos scenario be supported for k8s clusters or k8s platform? like master or worker node crash, infrastructure chaos.

It would be really cool to inject chaos on that level. However, `chaos-mesh` depends on the kubernetes to communicate with its components, so it would be hard to make sure it will recover after the chaos. We haven't came up with a good idea on how to implement it :crying_cat_face: .

**Comment by douxiaoniu77** [comment]
Thank you for the comments, YangKeao!
Is there client for the chaos-mesh operator? Sorry to say I didn't find the operator client to call. You know, just for a test, I'd like to get the operator encapsulated using beego via calling client. Would you please help to give some suggestion?

**Comment by YangKeao** [comment]
@douxiaoniu77 You can use the resource type in API package `github.com/chaos-mesh/chaos-mesh/api/v1alpha1` and [the client in `controller-runtime`](https://godoc.org/sigs.k8s.io/controller-runtime/pkg/client#New), it works well with the custom resource.

```go
scheme   = runtime.NewScheme()
v1alpha1.AddToScheme(scheme)

cl, err := client.New(config.GetConfigOrDie(), client.Options{
    Scheme: scheme,
})
if err != nil {
    fmt.Println("failed to create client")
    os.Exit(1)
}

networkList := &v1alpha1.NetworkChaosList()

err = cl.List(context.Background(), networkList, client.InNamespace("default"))
if err != nil {
    fmt.Printf("failed to list network chaos in namespace default: %v\n", err)
    os.Exit(1)
}
```

Or if you like, you could use the dynamic client of `client-go`, which use `unstructured` data.

**Comment by douxiaoniu77** [comment]
> @douxiaoniu77 You can use the resource type in API package `github.com/chaos-mesh/chaos-mesh/api/v1alpha1` and [the client in `controller-runtime`](https://godoc.org/sigs.k8s.io/controller-runtime/pkg/client#New), it works well with the custom resource.
> 
> ```go
> scheme   = runtime.NewScheme()
> v1alpha1.AddToScheme(scheme)
> 
> cl, err := client.New(config.GetConfigOrDie(), client.Options{
>     Scheme: scheme,
> })
> if err != nil {
>     fmt.Println("failed to create client")
>     os.Exit(1)
> }
> 
> networkList := &v1alpha1.NetworkChaosList()
> 
> err = cl.List(context.Background(), networkList, client.InNamespace("default"))
> if err != nil {
>     fmt.Printf("failed to list network chaos in namespace default: %v\n", err)
>     os.Exit(1)
> }
> ```
> 
> Or if you like, you could use the dynamic client of `client-go`, which use `unstructured` data.

Many thanks!
