### ISSUE TITLE
Release: v1.2.0

### ISSUE THREAD

**Issue by cwen0** [chaos-mesh/chaos-mesh#1395]
## New Feature & Enhancements

- [x] Support JVMChaos #1264
- [ ] Support HTTPChaos
- [x] Support AWSChaos
- [x] Support opening privilege filed for chaos daemon by an easier way
- [x] Support CRI-O #1530
- [x] Use tls mutual authentication for chaos-daemon #1504
- [x] Support batch deletion of experiments and archives #1723

## Release Date 

2021.02 - 2021.03 

If you have some features want to release in v1.2.0, just leave a comment.

**Comment by wuxiaohui94** [comment]
I want to know what the HTTPChaos does. Is Mock Server?

**Comment by zhouqiang-cl** [comment]
> I want to know what the HTTPChaos does. Is Mock Server?

@Andrewmatilde PTAL

**Comment by Andrewmatilde** [comment]
> I want to know what the HTTPChaos does. Is Mock Server?
It will be a transparent proxy live in the pod network namespace and rewrite | drop | block the selected http request/responses.

**Comment by zhouqiang-cl** [comment]
> > I want to know what the HTTPChaos does. Is Mock Server?
> 
> It will be a transparent proxy live in the pod network namespace and rewrite | drop | block the selected http request/responses.

Cloud you post the doc link here?

**Comment by cwen0** [comment]
[v1.2.0](https://github.com/chaos-mesh/chaos-mesh/releases/tag/v1.2.0) has been released! This issue will be closed!
