### ISSUE TITLE
Network Chaos TCP

### ISSUE THREAD

**Issue by leoncard** [chaos-mesh/chaos-mesh#1401]
## Question

Hello, I'm trying to block all connections from `myapp` service which lives in Kubernetes, to `myexternalhost`, which is external to Kubernetes. The http connections are being blocked as expected,, but the tcp are still going through, for instance I can still telnet to `myexternalhost` from within `myapp` pod. Does the Network Chaos only allow to break http requests?

I am sending the NetworkChaos object below:

```apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: externalChaos
  namespace: integration
  labels: null
  annotations:
    experiment.chaos-mesh.org/pause: 'true'
spec:
  action: loss
  mode: all
  value: ''
  selector:
    namespaces:
      - integration
    labelSelectors:
      app: myapp
  loss:
    loss: '100'
    correlation: '100'
  direction: to
  externalTargets:
    - myexternalhost.ext
```

**Comment by YangKeao** [comment]
It seems that the `NetworkChaos` is paused now. Are you sure it's not paused when you are testing with `telnet`?

I don't think there are any different between a HTTP request or other TCP connections (as the netem qdisc works on layer 3, ip packets). What is the output of `telnet`? Are you sure the `telnet` TCP connection is established? For example, you can send a simple HTTP request with `telnet` :cry:, e.g.

```
> telnet myexternalhost.ext 80
GET / HTTP/1.1
Host: myexternalhost.ext
```

Then you could get the http response if the connection is well.

**Comment by leoncard** [comment]
Hello, thanks for the reply.

TCP is getting blocked as expected.

I think something was misconfigured as I was trying to telnet to myexternalhost.ext and the connection was still going through, where it should be blocked. 

 I repeated the very same test today and it started working for the services I would like to test.
 
 After that I've completely purged chaos mesh and installed it again, after that telnet started to be blocked as well.

Maybe I've done too many updates on the test to make it work and perhaps the changes were not being saved, or creating conflict, or perhaps there was something wrong with my network.

Thanks for replying once again.

**Comment by STRRL** [comment]
Hi @leoncard, dose domain `myexternalhost.ext`  have stable DNS records?

When we use a domain name for externalTargets, chaos-mesh will query this domain from DNS, then add it's IP(s) to a certain ipset for filtering network packets.
