### ISSUE TITLE
ls shows error "Invalid argument" after ingest IOChaos

### ISSUE THREAD

**Issue by liwanxue** [chaos-mesh/chaos-mesh#1403]
## Bug Report

**What version of Kubernetes are you using?**
v1.15.7

**What did you do?**
after ingested iochaos, 

Bash shows: 

root@chi1-events-1-0-0:/# ls -lah  /var/lib/clickhouse/data/
**ls: /var/lib/clickhouse/data/: Invalid argument**
total 32K
drwxr-x---  6 clickhouse clickhouse 4.0K Jan 14 06:26 .
drwxr-xr-x 10 clickhouse clickhouse 4.0K Jan 12 07:25 ..
drwxr-x---  2 clickhouse clickhouse 4.0K Jan 12 07:25 default
drwxr-x---  2 clickhouse clickhouse 4.0K Jan 12 07:25 system
-rw-r--r--  1 root       root          5 Jan 14 06:23 test111
drwxr-xr-x  2 root       root       4.0K Jan 14 06:26 test123
-rw-r--r--  1 root       root          5 Jan 14 06:24 test222
drwxr-xr-x  2 root       root       4.0K Jan 14 06:26 test321
root@chi1-events-1-0-0:/# lsof -p 1ls -a^C
root@chi1-events-1-0-0:/# ls -alh /var/lib/__chaosfs__clickhouse__/data/
total 32K
drwxr-x---  6 clickhouse clickhouse 4.0K Jan 14 06:26 .
drwxr-xr-x 10 clickhouse clickhouse 4.0K Jan 12 07:25 ..
drwxr-x---  2 clickhouse clickhouse 4.0K Jan 12 07:25 default
drwxr-x---  2 clickhouse clickhouse 4.0K Jan 12 07:25 system
-rw-r--r--  1 root       root          5 Jan 14 06:23 test111
drwxr-xr-x  2 root       root       4.0K Jan 14 06:26 test123
-rw-r--r--  1 root       root          5 Jan 14 06:24 test222
drwxr-xr-x  2 root       root       4.0K Jan 14 06:26 test321

Application error log shows: 
2021.01.12 10:17:24.496297 [ 32 ] {32accab8-5f77-40ae-a0d5-77042a4c21ac} <Error> executeQuery: Poco::Exception. Code: 1000, e.code() = 2, e.displayText() = File not found: /var/lib/clickhouse/data/sherlockio/sherlock_test/20210112_2_2_0/__name__.mrk2 (version 19.16.14.65 (official build) (from [::ffff:10.148.208.112]:37712) (in query: select * from sherlockio.sherlock_test)
2021.01.12 10:17:24.496535 [ 32 ] {32accab8-5f77-40ae-a0d5-77042a4c21ac} <Error> virtual DB::UnionBlockInputStream::~UnionBlockInputStream(): Code: 107, e.displayText() = DB::ErrnoException: Cannot open file /var/lib/clickhouse/data/sherlockio/sherlock_test/20210112_1_1_0/__name__.bin, errno: 2, strerror: No such file or directory, Stack trace:
...

Chaos Daemonset  log shows: 
[2021-01-12 10:27:32.427422 +00:00] INFO [toda] src/main.rs:82: replacer detached
[2021-01-12 10:27:32.427438 +00:00] INFO [toda] src/main.rs:84: enable injection
[2021-01-12 10:27:32.427462 +00:00] INFO [toda] src/main.rs:141: waiting for signal to exit
[2021-01-12 10:41:37.309886 +00:00] ERROR [fuser::channel] /root/.cargo/registry/src/github.com-1ecc6299db9ec823/fuser-0.6.0/src/channel.rs:194: Failed to send FUSE reply: Invalid argument (os error 22)
[2021-01-13 02:48:09.974640 +00:00] ERROR [fuser::channel] /root/.cargo/registry/src/github.com-1ecc6299db9ec823/fuser-0.6.0/src/channel.rs:194: Failed to send FUSE reply: Invalid argument (os error 22)
[2021-01-13 03:09:42.409584 +00:00] ERROR [fuser::channel] /root/.cargo/registry/src/github.com-1ecc6299db9ec823/fuser-0.6.0/src/channel.rs:194: Failed to send FUSE reply: Invalid argument (os error 22)
[2021-01-14 03:13:35.667241 +00:00] ERROR [fuser::channel] /root/.cargo/registry/src/github.com-1ecc6299db9ec823/fuser-0.6.0/src/channel.rs:194: Failed to send FUSE reply: Invalid argument (os error 22)

**What did you expect to see?**
I should be able to ls without error. and application should works

**Comment by liwanxue** [comment]
The issue I submitted before: https://github.com/chaos-mesh/chaos-mesh/issues/1329

**Comment by liwanxue** [comment]
BTW, I am not sure if this is similar issue: 

My application write data to those disks. __chaosfs__xxx works good. but original path doesn't. 
root@chi1-events-0-0-0:/# ls -alh /var/lib/__chaosfs__clickhouse__/data/sherlockio/sherlock_test/20210112_6_6_0
total 104K
drwxr-x--- 2 clickhouse clickhouse 4.0K Jan 12 10:28 .
drwxr-x--- 9 clickhouse clickhouse 4.0K Jan 12 10:28 ..
-rw-r----- 1 clickhouse clickhouse  652 Jan 12 10:28 checksums.txt
-rw-r----- 1 clickhouse clickhouse   30 Jan 12 10:28 colo.bin
-rw-r----- 1 clickhouse clickhouse   48 Jan 12 10:28 colo.mrk2
-rw-r----- 1 clickhouse clickhouse   27 Jan 12 10:28 colo.null.bin
-rw-r----- 1 clickhouse clickhouse   48 Jan 12 10:28 colo.null.mrk2
-rw-r----- 1 clickhouse clickhouse  173 Jan 12 10:28 columns.txt
-rw-r----- 1 clickhouse clickhouse   34 Jan 12 10:28 count.bin
-rw-r----- 1 clickhouse clickhouse   48 Jan 12 10:28 count.mrk2
-rw-r----- 1 clickhouse clickhouse   27 Jan 12 10:28 count.null.bin
-rw-r----- 1 clickhouse clickhouse   48 Jan 12 10:28 count.null.mrk2
-rw-r----- 1 clickhouse clickhouse    1 Jan 12 10:28 count.txt
-rw-r----- 1 clickhouse clickhouse    8 Jan 12 10:28 minmax_unixtime.idx
-rw-r----- 1 clickhouse clickhouse   34 Jan 12 10:28 __name__.bin
-rw-r----- 1 clickhouse clickhouse   48 Jan 12 10:28 __name__.mrk2
-rw-r----- 1 clickhouse clickhouse    4 Jan 12 10:28 partition.dat
-rw-r----- 1 clickhouse clickhouse   24 Jan 12 10:28 primary.idx
-rw-r----- 1 clickhouse clickhouse   34 Jan 12 10:28 sum.bin
-rw-r----- 1 clickhouse clickhouse   48 Jan 12 10:28 sum.mrk2
-rw-r----- 1 clickhouse clickhouse   27 Jan 12 10:28 sum.null.bin
-rw-r----- 1 clickhouse clickhouse   48 Jan 12 10:28 sum.null.mrk2
-rw-r----- 1 clickhouse clickhouse   30 Jan 12 10:28 unixtime.bin
-rw-r----- 1 clickhouse clickhouse   48 Jan 12 10:28 unixtime.mrk2
-rw-r----- 1 clickhouse clickhouse   27 Jan 12 10:28 __value__.bin
-rw-r----- 1 clickhouse clickhouse   48 Jan 12 10:28 __value__.mrk2
root@chi1-events-0-0-0:/# ls -alh /var/lib/clickhouse/data/sherlockio/sherlock_test/20210112_6_6_0
ls: /var/lib/clickhouse/data/sherlockio/sherlock_test/20210112_6_6_0: Invalid argument
ls: cannot open directory '/var/lib/clickhouse/data/sherlockio/sherlock_test/20210112_6_6_0': No such file or directory
root@chi1-events-0-0-0:/# ls -alh /var/lib/clickhouse/data/sherlockio/sherlock_test/
ls: /var/lib/clickhouse/data/sherlockio/sherlock_test/: Invalid argument
ls: /var/lib/clickhouse/data/sherlockio/sherlock_test/detached: Input/output error
total 40K
drwxr-x--- 9 clickhouse clickhouse 4.0K Jan 12 10:28 .
drwxr-x--- 3 clickhouse clickhouse 4.0K Jan 12 07:45 ..
drwxr-x--- 2 clickhouse clickhouse 4.0K Jan 12 07:47 20210112_1_1_0
drwxr-x--- 2 clickhouse clickhouse 4.0K Jan 12 07:48 20210112_2_2_0
drwxr-x--- 2 clickhouse clickhouse 4.0K Jan 12 10:26 20210112_3_3_0
drwxr-x--- 2 clickhouse clickhouse 4.0K Jan 12 10:27 20210112_4_4_0
drwxr-x--- 2 clickhouse clickhouse 4.0K Jan 12 10:27 20210112_5_5_0
drwxr-x--- 2 clickhouse clickhouse 4.0K Jan 12 10:28 20210112_6_6_0
drwxr-x--- 2 clickhouse clickhouse 4.0K Jan 12 07:45 detached
-rw-r----- 1 clickhouse clickhouse    1 Jan 12 07:47 format_version.txt
root@chi1-events-0-0-0:/#

**Comment by liwanxue** [comment]
any update? @YangKeao @STRRL

**Comment by STRRL** [comment]
Hi @liwanxue , we are still working on that.

**Comment by YangKeao** [comment]
We have fixed tons of bugs for the filesystem. It seems that this problem has been fixed in #1423. We will release a `1.1.1` version in recent days (or you could try the master version after it gets merged :yum: )

**Comment by liwanxue** [comment]
sure, I will try and get back to you. Thanks!

**Comment by liwanxue** [comment]
Build image with latest code, and upgrade chaos-mesh deployment and chaos-daemon daemonset in k8s cluster. 
I still can see error from clickhouse side as below. 
2021.01.21 08:48:48.589015 [ 37 ] {} <Error> DB::MergeTreeDataPart::~MergeTreeDataPart(): Poco::Exception. Code: 1000, e.code() = 13, e.displayText() = Access to file denied: /var/lib/clickhouse/data/sherlockio/sherlock_test/tmp_insert_20210121_74_74_0 (version 19.16.14.65 (official build)

and cmd as:
`root@chi1-events-0-0-0:/# ls -lah /var/lib/clickhouse/data/sherlockio/sherlock_test/tmp_insert_20210121_74_74_0
ls: /var/lib/clickhouse/data/sherlockio/sherlock_test/tmp_insert_20210121_74_74_0: Input/output error
ls: /var/lib/clickhouse/data/sherlockio/sherlock_test/tmp_insert_20210121_74_74_0/.: Input/output error
total 8.0K
drwxr-x---  2 root       root       4.0K Jan 21 08:48 .
drwxr-x--- 12 clickhouse clickhouse 4.0K Jan 21 08:48 ..
root@chi1-events-0-0-0:/# ls -lah /var/lib/__chaosfs__clickhouse__/data/sherlockio/sherlock_test/tmp_insert_20210121_74_74_0
total 8.0K
drwxr-x---  2 root       root       4.0K Jan 21 08:48 .
drwxr-x--- 25 clickhouse clickhouse 4.0K Jan 21 08:50 ..`


To reproduce this: 
Execute `insert into sherlockio.sherlock_test_buffer values('test12300000',now(),1,'tst',2,1)` in clickhouse-client 
check logs in `/var/log/clickhouse-server/clickhouse-server.err.log`

Please help check this. Thanks!

**Comment by liwanxue** [comment]
And still same error in toda. 
`[2021-01-21 08:48:59.532314 +00:00] ERROR [fuser::channel] /root/.cargo/registry/src/github.com-1ecc6299db9ec823/fuser-0.6.0/src/channel.rs:194: Failed to send FUSE reply: Invalid argument (os error 22)
[2021-01-21 08:48:59.532138 +00:00] ERROR [fuser::channel] /root/.cargo/registry/src/github.com-1ecc6299db9ec823/fuser-0.6.0/src/channel.rs:194: Failed to send FUSE reply: Invalid argument (os error 22)`

Could you tell me how to enable trace log for toda as well? Thanks. 
@YangKeao @STRRL

**Comment by YangKeao** [comment]
@liwanxue Are you sure it's the latest code / image? Can you check the image id? 

We have replaced the logging library and have a different log style, however, it's still the old style in your error message. In the latest version of Chaos Mesh, the first several lines of toda log would be like:

```
Jan 21 17:21:31.228  INFO inject: toda: inject with config [Latency(LatencyConfig { filter: FilterConfig { path: Some("/var/run/test/**/*"), methods: None, percent: 100 }, latency: 10ms })]
Jan 21 17:21:31.228  INFO inject: toda: canonicalizing path /mnt/a
Jan 21 17:21:31.230  INFO inject: toda::injector::filter: build filter
Jan 21 17:21:31.230  INFO toda::mount_injector: mount with flags ["-o", "allow_other", "-o", "fsname=toda", "-o", "default_permissions"]
```

**Comment by liwanxue** [comment]
oh, sorry, I built wrong image. rebuild works. I didn't see error with latest image right now. Will continue testing to see if there are any other issues. Thank you all for help.

**Comment by liwanxue** [comment]
found another issue in new version, I'm not sure if it's expected or not. 
I try to `DROP TABLE sherlockio.sherlock_test`
but 
2021.01.21 10:36:56.157064 [ 6 ] {e660499b-676b-4fe5-b9b9-9057f53a12fb} <Error> executeQuery: Poco::Exception. Code: 1000, e.code() = 2, e.displayText() = File not found: /var/lib/clickhouse/metadata/sherlockio/sherlock_test.sql (version 19.16.14.65 (official build) (from 0.0.0.0:0) (in query: /* ddl_entry=query-0000000004 */ DROP TABLE sherlockio.sherlock_test)

It doesn't mirror write/read operation on /var/lib/clickhouse/ to /var/lib/__chaosfs__clickhouse__. 


Could you help test this for me? Thanks! @STRRL @YangKeao 

Seeing this in toda

Jan 22 02:40:24.581  INFO inject:trace{pid=7067}:attach_task{task=Task { pid: 7067, tid: 7067, root: "/proc/7067/task/7067" }}: toda::ptrace: attach task: 7067 successfully
Jan 22 02:40:24.581  INFO inject:trace{pid=7067}:attach_task{task=Task { pid: 7067, tid: 7067, root: "/proc/7067/task/7067" }}: toda::ptrace: wait status: Stopped(Pid(7067), SIGSTOP)
Jan 22 02:40:24.581  INFO inject:trace{pid=7067}: toda::ptrace: trace process: 7067 successfully
Jan 22 02:40:24.581  INFO inject:detach{pid=7067}: toda::ptrace: detach process: 7067
Jan 22 02:40:24.581  INFO inject:detach{pid=7067}: toda::ptrace: successfully detached task: 7067
Jan 22 02:40:24.581  INFO inject:detach{pid=7067}: toda::ptrace: detach process: 7067 successfully
Error: source: /var/lib/clickhouse, target: /var/lib/__chaosfs__clickhouse__

Caused by:
    EINVAL: Invalid argument

Stack backtrace:
   0: <E as anyhow::context::ext::StdError>::ext_context
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/anyhow-1.0.38/src/backtrace.rs:26
      anyhow::context::<impl anyhow::Context<T,E> for core::result::Result<T,E>>::context::{{closure}}
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/anyhow-1.0.38/src/context.rs:50
      core::result::Result<T,E>::map_err
             at ./rustc/16957bd4d3a5377263f76ed74c572aad8e4b7e59/src/libcore/result.rs:612
      anyhow::context::<impl anyhow::Context<T,E> for core::result::Result<T,E>>::context
             at ./root/.cargo/registry/src/github.com-1ecc6299db9ec823/anyhow-1.0.38/src/context.rs:50
      toda::mount::MountsInfo::move_mount
             at src/mount.rs:42
   1: toda::mount_injector::MountInjector::mount
             at src/mount_injector.rs:115
   2: toda::inject
             at src/main.rs:88
      toda::main
             at src/main.rs:165
   3: std::rt::lang_start::{{closure}}
             at ./rustc/16957bd4d3a5377263f76ed74c572aad8e4b7e59/src/libstd/rt.rs:67
   4: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:52
      std::panicking::try::do_call
             at src/libstd/panicking.rs:342
      std::panicking::try
             at src/libstd/panicking.rs:319
      std::panic::catch_unwind
             at src/libstd/panic.rs:394
      std::rt::lang_start_internal
             at src/libstd/rt.rs:51
   5: main
   6: <unknown>
   7: _start
2021-01-22T02:40:24.638Z	INFO	background-process-manager	process stopped	{"pid": 17022}

**Comment by STRRL** [comment]
Hi @liwanxue , I failed to reproduce this issue. 😰  Could you provide more detailed information for us? Such as:

- IOChaos CRD object
- number of lines of data in table `sherlockio.sherlock_test`
- If you could provide detailed SQL you executed is much better

And it seems this issue occurs when `toda` is trying to recover chaos. I also tried this situation, it will not reproduce this issue.

**Comment by liwanxue** [comment]
`apiVersion: chaos-mesh.org/v1alpha1
kind: IoChaos
metadata:
  name: chdiskdegrading
  namespace: default
spec:
  action: latency
  delay: 100ms
  mode: all
  path: /var/lib/clickhouse/data/**/**/**/**/*
  percent: 100
  containerName: clickhouse-server
  methods:
  - read
  - write
  selector:
    labelSelectors:
      clickhouse.altinity.com/chi: chi1
    namespaces:
    - default
  value: ""
  volumePath: /var/lib/clickhouse`
  
  Maybe I should wait official release of new version then have a try. Probably, there are some gap on image I built with offical one.

**Comment by liwanxue** [comment]
The issue resolved. Thanks all for your help.
