### ISSUE TITLE
dashboard: Expired tokens cannot be deleted

### ISSUE THREAD

**Issue by torblerone** [chaos-mesh/chaos-mesh#1414]
## Bug Report

**What version of Kubernetes are you using?**
`Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.15-gke.800", GitCommit:"fa6f8f9671a3ba4b1790bac677bb72b04204e8fc", GitTreeState:"clean", BuildDate:"2020-12-21T09:19:13Z", GoVersion:"go1.13.15b4", Compiler:"gc", Platform:"linux/amd64"}
`

**What version of Chaos Mesh are you using?**
`Controller manager Version: version.Info{GitVersion:"v1.0.1", GitCommit:"f4f15091713bcf0fe7ec87f46e723a89e3184b46", BuildDate:"2020-10-16T15:10:29Z", GoVersion:"go1.14.6", Compiler:"gc", Platform:"linux/amd64"}
`

**What did you do?**

I installed a fresh chaos-mesh by using the official helm chart and entered my Kubernetes Auth Token yesterday. When accessing the dashboard today, my auth token was expired.

**What did you expect to see?**
I expect the token to be set on expire i.e. 24 hours or something. Also, I expected the Token to be able to be deleted. For company compliance, our tokens are only active for max. 24h. After that, they expire and via `oidc-plugin` our `kubectl` gets itself a new token. It's a bit of a hassle to enter a new token everyday btw, but that's not was this issue is about.

**What did you see instead?**
I see an error message telling me to "Please check the validity of the token". I can navigate to "Settings" and enter a new token, but I can not delete the old expired one. This way, for a daily usage of 30 days, I'd have 30 entered inactive and useless tokens which only bloat. 

![grafik](https://user-images.githubusercontent.com/64590448/104734578-c041e700-5740-11eb-82cc-6e435555aef3.png)

![grafik](https://user-images.githubusercontent.com/64590448/104734540-b4562500-5740-11eb-8da9-62d30123d9a8.png)

**Output of chaosctl**
Not neccessary to reproduce this issue. Just let your k8s token expire.

**Comment by STRRL** [comment]
PTAL @g1eny0ung

**Comment by g1eny0ung** [comment]
@torblerone I test in my local machine. Nothing seems unusual. Have you try to delete it by clicking this button as the below image:

![image](https://user-images.githubusercontent.com/15034155/104875230-bbbf3d80-598f-11eb-97ca-7ff34b3effd9.png)

BTW, I think the set the tokens expired is a good enhancement. I will try to implement it in the later versions.

**Comment by torblerone** [comment]
@g1eny0ung I must've been blind as this button is also visible in my screenshot..

Nevertheless, thank you for considerating expering tokens. Shall I open a new issue for that enhancement?

**Comment by g1eny0ung** [comment]
> Shall I open a new issue for that enhancement?

Sure. It's better to record it to prevent we forget it.

**Comment by torblerone** [comment]
@g1eny0ung New feature request is opened on https://github.com/chaos-mesh/chaos-mesh/issues/1421
