### ISSUE TITLE
Can chaos-dashboard dashboard show current version?

### ISSUE THREAD

**Issue by laixintao** [chaos-mesh/chaos-mesh#1424]
## Feature Request

It would be better if the web ui (chaso-dashboard) of chaos-mesh can show a version number at the bottom.

**Describe alternatives you've considered:**
Or we can show the version number near by chaso-mesh logo?

**Teachability, Documentation, Adoption, Migration Strategy:**
Just want to know which version of chaos-mesh we are currently running..

**Comment by g1eny0ung** [comment]
Good idea! I will implement this feature.
