### ISSUE TITLE
enable/disable Chaos mesh by specifying annotation or label at namespace level or deployment level.

### ISSUE THREAD

**Issue by zhiqiang-xu** [chaos-mesh/chaos-mesh#1452]
## Feature Request

**Is your feature request related to a problem? Please describe:**

We don't want to specify namespaces to enable or disable ChaosMesh at installation time, which would require reinstallation every time.
Instead we prefer to enable or disable it after installation by specifying annotation or label at namespace level or deployment level.

**Describe the feature you'd like:**

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by YangKeao** [comment]
As there is an `allowedNamespace` field in the configuration, I don't think provide several different ways to do the same thing is good for a product (and will confuse both developers and users).

However, now, configuring `allowedNamespace` (and all other configuration) needs to reinstall Chaos Mesh, which is really disappointing.

To fix this problem, we could make this field (`allowedNamespace` ) dynamically configurable through `ConfigMap`. Is it acceptable for you? If this feature (dynamically configuration) can suit your needs, it can be developed and land in the next week :beers: .

**Comment by cwen0** [comment]
We have supported this feature in PR #1550
