### ISSUE TITLE
using dashboard to update StressChaos experiment failed

### ISSUE THREAD

**Issue by zhuwenxing** [chaos-mesh/chaos-mesh#1474]
## Bug Report

**What version of Kubernetes are you using?**

Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:40:16Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:32:14Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
**What version of Chaos Mesh are you using?**

Controller manager Version: version.Info{GitVersion:"v1.1.1", GitCommit:"88e265c1ad2bcc3931645371a71683dd52b576fb", BuildDate:"2021-01-21T11:24:39Z", GoVersion:"go1.14.6", Compiler:"gc", Platform:"linux/amd64"}
**What did you do?**

apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: test-kafka-stress-2
  namespace: default
  labels: null
  annotations:
    experiment.chaos-mesh.org/pause: 'false'
spec:
  mode: one
  value: ''
  selector:
    namespaces:
      - default
    labelSelectors:
      app: kafka
  stressors:
    memory:
      workers: 1
    cpu:
      workers: 1
      load: 100
  containerName: ''
  duration: 30s
  scheduler:
    cron: '@every 2m'

change 30s to 60s
**What did you expect to see?**
update sucess
**What did you see instead?**
code: "error.api.internal_server_error"
full_text: "error.api.internal_server_error: admission webhook "vstresschaos.kb.io" denied the request: stresschaos.spec.stressors: Invalid value: v1alpha1.Stressors{MemoryStressor:(*v1alpha1.MemoryStressor)(nil), CPUStressor:(*v1alpha1.CPUStressor)(nil)}: missing stressors↵ at github.com/chaos-mesh/chaos-mesh/pkg/apiserver/experiment.(*Service).updateExperiment()↵	/mnt/pkg/apiserver/experiment/experiment.go:1176↵ at github.com/gin-gonic/gin.(*Context).Next()↵	/tmp/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161↵ at github.com/chaos-mesh/chaos-mesh/pkg/apiserver/utils.MWHandleErrors.func1()↵	/mnt/pkg/apiserver/utils/error.go:50↵ at github.com/gin-gonic/gin.(*Context).Next()↵	/tmp/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161↵ at github.com/gin-gonic/gin.RecoveryWithWriter.func1()↵	/tmp/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/recovery.go:83↵ at github.com/gin-gonic/gin.(*Context).Next()↵	/tmp/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161↵ at github.com/gin-gonic/gin.LoggerWithConfig.func1()↵	/tmp/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/logger.go:241↵ at github.com/gin-gonic/gin.(*Context).Next()↵	/tmp/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161↵ at github.com/gin-gonic/gin.(*Engine).handleHTTPRequest()↵	/tmp/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/gin.go:409↵ at github.com/gin-gonic/gin.(*Engine).ServeHTTP()↵	/tmp/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/gin.go:367↵ at net/http.serverHandler.ServeHTTP()↵	/usr/local/go/src/net/http/server.go:2836↵ at net/http.(*conn).serve()↵	/usr/local/go/src/net/http/server.go:1924↵ at runtime.goexit()↵	/usr/local/go/src/runtime/asm_amd64.s:1373"
message: "error.api.internal_server_error: admission webhook "vstresschaos.kb.io" denied the request: stresschaos.spec.stressors: Invalid value: v1alpha1.Stressors{MemoryStressor:(*v1alpha1.MemoryStressor)(nil), CPUStressor:(*v1alpha1.CPUStressor)(nil)}: missing stressors"
status: "error"
**Output of chaosctl**

**Comment by fewdan** [comment]
Ok, we will deal with this problem.

**Comment by g1eny0ung** [comment]
This problem has been fixed in #1461 (master) and #1471 (release-1.1).
