### ISSUE TITLE
can't delete or pause the experiment if the pod of experiment has been deleted

### ISSUE THREAD

**Issue by zhuwenxing** [chaos-mesh/chaos-mesh#1475]
## Bug Report

**What version of Kubernetes are you using?**

Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:40:16Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:32:14Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
**What version of Chaos Mesh are you using?**

Controller manager Version: version.Info{GitVersion:"v1.1.1", GitCommit:"88e265c1ad2bcc3931645371a71683dd52b576fb", BuildDate:"2021-01-21T11:24:39Z", GoVersion:"go1.14.6", Compiler:"gc", Platform:"linux/amd64"}
**What did you do?**

pause a experiment
**What did you expect to see?**
experiment paused
**What did you see instead?**
code: "error.api.invalid_request"
full_text: "error.api.invalid_request: the experiment is not found↵ at github.com/chaos-mesh/chaos-mesh/pkg/apiserver/experiment.(*Service).pauseExperiment()↵	/mnt/pkg/apiserver/experiment/experiment.go:1017↵ at github.com/gin-gonic/gin.(*Context).Next()↵	/tmp/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161↵ at github.com/chaos-mesh/chaos-mesh/pkg/apiserver/utils.MWHandleErrors.func1()↵	/mnt/pkg/apiserver/utils/error.go:50↵ at github.com/gin-gonic/gin.(*Context).Next()↵	/tmp/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161↵ at github.com/gin-gonic/gin.RecoveryWithWriter.func1()↵	/tmp/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/recovery.go:83↵ at github.com/gin-gonic/gin.(*Context).Next()↵	/tmp/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161↵ at github.com/gin-gonic/gin.LoggerWithConfig.func1()↵	/tmp/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/logger.go:241↵ at github.com/gin-gonic/gin.(*Context).Next()↵	/tmp/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161↵ at github.com/gin-gonic/gin.(*Engine).handleHTTPRequest()↵	/tmp/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/gin.go:409↵ at github.com/gin-gonic/gin.(*Engine).ServeHTTP()↵	/tmp/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/gin.go:367↵ at net/http.serverHandler.ServeHTTP()↵	/usr/local/go/src/net/http/server.go:2836↵ at net/http.(*conn).serve()↵	/usr/local/go/src/net/http/server.go:1924↵ at runtime.goexit()↵	/usr/local/go/src/runtime/asm_amd64.s:1373"
message: "error.api.invalid_request: the experiment is not found"
status: "error"
**Output of chaosctl**

**Comment by fewdan** [comment]
Understand, we will look at this issue.

**Comment by STRRL** [comment]
similar issue, can not delete stresschaos after the set of pod changes, see  https://github.com/chaos-mesh/chaos-mesh/issues/1474

**Comment by AsterNighT** [comment]
This is no a chaos-dashboard issue. Deleting it directly from kuebctl results in the same thing.
