### ISSUE TITLE
Total state's display problem

### ISSUE THREAD

**Issue by zhuwenxing** [chaos-mesh/chaos-mesh#1476]
## Bug Report

**What version of Kubernetes are you using?**

**What version of Chaos Mesh are you using?**

**What did you do?**

**What did you expect to see?**
all items can display well
**What did you see instead?**
![image](https://user-images.githubusercontent.com/12268675/106424942-05cf1580-649e-11eb-9ab9-51708be375dd.png)

**Output of chaosctl**

**Comment by fewdan** [comment]
@g1eny0ung PTAL.
