### ISSUE TITLE
Is there any way to make Pod's RESTARTS increase

### ISSUE THREAD

**Issue by zhuwenxing** [chaos-mesh/chaos-mesh#1484]
## Question
Yesterday, I made a pod failure with  running continuously, I can obverse that the RESTARTS will increase, and this is what i want. However today , I did the same thing, the pod's status is imagepullbackoff ,but RESTARTS remains  0. So Is there any way to stabilize the previous phenomenon?
Before asking a question, make sure you have:

- Reviewed relevant Kubernetes information: Google your error messages and look at K8s docs.
- Searched open and closed [GitHub issues](https://github.com/chaos-mesh/chaos-mesh/issues?utf8=%E2%9C%93&q=is%3Aissue)
- Read the documentation:
  - [Chaos Mesh Readme](https://github.com/chaos-mesh/chaos-mesh)
  - [Chaos Mesh Doc](https://chaos-mesh.org/docs)

**Output of chaosctl**

**Comment by cwen0** [comment]
`pod-failure` will use a fake image to replace the origin image. The fake image is `gcr.io/google-containers/pause:latest"`. If your environment can't access this fake image, the pod status will change to `imagepullbackoff`.  `pod-failure` just simulate the pod out of work and can't make sure that the RESTARTS will increase.

**Comment by cwen0** [comment]
If you can make sure your environment can pull  the fake image, the RESTARTS of the target pod will increase
