### ISSUE TITLE
Dashboard takes into account base URL for redirects

### ISSUE THREAD

**Issue by kanor1306** [chaos-mesh/chaos-mesh#1500]
## Feature Request

**Is your feature request related to a problem? Please describe:**
The chaos-mesh dashboard is hardcoded to the URL path `/dashboard` and this prevents in some cases from exposing the dashboard through Ingress. i.e. because there is already something deployed in that path, or certain paths are not allowed. 
For example if you configure chaos-mesh with the following configuration:

```
dashboard:
  create: true
  securityMode: true
  service:
    type: ClusterIP
  ingress:
    enabled: true
    hosts:
      - name: localhost.localdomain
        paths: ["/admin/chaos-mesh"]
```

When you access `https://localhost.localdomain/admin/chaos-mesh` you get redirected to `https://localhost.localdomain/dashboard`. 

**Describe the feature you'd like:**
The dashboard will be exposed in the path that you set in the Ingress rule. If you take the mentioned configuration, the desired result would be that the dashboard is available in `https://localhost.localdomain/admin/chaos-mesh/dashboard`. This means that it will take into account the base url when doing the redirect to `/dashboard`

**Describe alternatives you've considered:**
In my case I could use port forwarding to access the dashboard, but there are cases where the only available interface will be the GUI, and in those cases port forwarding is not an option.
It has been suggested too that some Ingress Controller have configurations to avoid this problem, although in my Ingress Controller of choice (Traefik) I couldn't get any configuration to prevent this, specially as the UI of Traefik was deployed in `https://localhost.localdomain/dashboard`.

**Teachability, Documentation, Adoption, Migration Strategy:**
This feature will be beneficial in the cases where kubectl is not available to do port forwarding, or in cases where, for any reason, the path `/dashboard` is not a valid option.

**Comment by cwen0** [comment]
@g1eny0ung PTAL
