### ISSUE TITLE
Controller-manager enables leader election 

### ISSUE THREAD

**Issue by cwen0** [chaos-mesh/chaos-mesh#1516]
## Feature Request

**Describe the feature you'd like:**
 

Enable leader election and make controller-manager HA. 

**Describe alternatives you've considered:**
 

HA is important for most applications, including Chaos Mesh. We support setting `replicas: 1` on helm chart files, but we have not tested it., and we don't recommend users to enable it at present. I think we should test it and make it available. 

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by anuragpaliwal80** [comment]
We will love to have this feature as we are having large clusters and HA is very much required.

**Comment by Muscule** [comment]
When do you plan to add HA?

**Comment by Muscule** [comment]
up

**Comment by YangKeao** [comment]
> When do you plan to add HA?

@iguoyr Could it land before release 2.1? It would be really awesome.

**Comment by iguoyr** [comment]
@YangKeao yes! I will start to work on it soon.
