### ISSUE TITLE
uninstallation error 

### ISSUE THREAD

**Issue by zhuwenxing** [chaos-mesh/chaos-mesh#1519]
## Question

Before asking a question, make sure you have:

- Reviewed relevant Kubernetes information: Google your error messages and look at K8s docs.
- Searched open and closed [GitHub issues](https://github.com/chaos-mesh/chaos-mesh/issues?utf8=%E2%9C%93&q=is%3Aissue)
- Read the documentation:
  - [Chaos Mesh Readme](https://github.com/chaos-mesh/chaos-mesh)
  - [Chaos Mesh Doc](https://chaos-mesh.org/docs)

**Output of chaosctl**

Hi,I want to uninstallation chaos mesh,so i exec the command  `curl -sSL https://mirrors.chaos-mesh.org/v1.1.1/install.sh | bash -s -- --template | kubectl delete -f -` in documentation . the output is 
```shell
customresourcedefinition.apiextensions.k8s.io "dnschaos.chaos-mesh.org" deleted
customresourcedefinition.apiextensions.k8s.io "httpchaos.chaos-mesh.org" deleted
customresourcedefinition.apiextensions.k8s.io "iochaos.chaos-mesh.org" deleted
customresourcedefinition.apiextensions.k8s.io "jvmchaos.chaos-mesh.org" deleted
customresourcedefinition.apiextensions.k8s.io "kernelchaos.chaos-mesh.org" deleted
customresourcedefinition.apiextensions.k8s.io "networkchaos.chaos-mesh.org" deleted
customresourcedefinition.apiextensions.k8s.io "podchaos.chaos-mesh.org" deleted
customresourcedefinition.apiextensions.k8s.io "podiochaos.chaos-mesh.org" deleted
customresourcedefinition.apiextensions.k8s.io "podnetworkchaos.chaos-mesh.org" deleted
customresourcedefinition.apiextensions.k8s.io "stresschaos.chaos-mesh.org" deleted
customresourcedefinition.apiextensions.k8s.io "timechaos.chaos-mesh.org" deleted
namespace "chaos-testing" deleted
serviceaccount "chaos-daemon" deleted
serviceaccount "chaos-controller-manager" deleted
secret "chaos-mesh-webhook-certs" deleted
clusterrole.rbac.authorization.k8s.io "chaos-mesh-chaos-controller-manager-target-namespace" deleted
clusterrole.rbac.authorization.k8s.io "chaos-mesh-chaos-controller-manager-cluster-level" deleted
clusterrolebinding.rbac.authorization.k8s.io "chaos-mesh-chaos-controller-manager-cluster-level" deleted
clusterrolebinding.rbac.authorization.k8s.io "chaos-mesh-chaos-controller-manager-target-namespace" deleted
role.rbac.authorization.k8s.io "chaos-mesh-chaos-controller-manager-control-plane" deleted
rolebinding.rbac.authorization.k8s.io "chaos-mesh-chaos-controller-manager-control-plane" deleted
service "chaos-daemon" deleted
service "chaos-dashboard" deleted
service "chaos-mesh-controller-manager" deleted
daemonset.apps "chaos-daemon" deleted
deployment.apps "chaos-dashboard" deleted
deployment.apps "chaos-controller-manager" deleted
mutatingwebhookconfiguration.admissionregistration.k8s.io "chaos-mesh-mutation" deleted
validatingwebhookconfiguration.admissionregistration.k8s.io "chaos-mesh-validation" deleted
^C
```
But it stop at `validatingwebhookconfiguration.admissionregistration.k8s.io "chaos-mesh-validation" deleted`  this step for a long time. 
So I exec `ctrl + c` to break it
When i exec `kubectl get pod -n chaos-testing`, there is no resource. But the status of chaos-testing namespace is still terminating.
Then i exec `curl -sSL https://mirrors.chaos-mesh.org/v1.1.1/install.sh | bash` to install it again
But the output is 
```shell
customresourcedefinition.apiextensions.k8s.io "networkchaos.chaos-mesh.org" deleted
customresourcedefinition.apiextensions.k8s.io "podchaos.chaos-mesh.org" deleted
customresourcedefinition.apiextensions.k8s.io "stresschaos.chaos-mesh.org" deleted
Error from server (NotFound): error when deleting "STDIN": customresourcedefinitions.apiextensions.k8s.io "dnschaos.chaos-mesh.org" not found
Error from server (NotFound): error when deleting "STDIN": customresourcedefinitions.apiextensions.k8s.io "httpchaos.chaos-mesh.org" not found
Error from server (NotFound): error when deleting "STDIN": customresourcedefinitions.apiextensions.k8s.io "iochaos.chaos-mesh.org" not found
Error from server (NotFound): error when deleting "STDIN": customresourcedefinitions.apiextensions.k8s.io "jvmchaos.chaos-mesh.org" not found
Error from server (NotFound): error when deleting "STDIN": customresourcedefinitions.apiextensions.k8s.io "kernelchaos.chaos-mesh.org" not found
Error from server (NotFound): error when deleting "STDIN": customresourcedefinitions.apiextensions.k8s.io "podiochaos.chaos-mesh.org" not found
Error from server (NotFound): error when deleting "STDIN": customresourcedefinitions.apiextensions.k8s.io "podnetworkchaos.chaos-mesh.org" not found
Error from server (NotFound): error when deleting "STDIN": customresourcedefinitions.apiextensions.k8s.io "timechaos.chaos-mesh.org" not found
Error from server (Conflict): error when deleting "STDIN": Operation cannot be fulfilled on namespaces "chaos-testing": The system is ensuring all content is removed from this namespace.  Upon completion, this namespace will automatically be purged by the system.
Error from server (NotFound): error when deleting "STDIN": serviceaccounts "chaos-daemon" not found
Error from server (NotFound): error when deleting "STDIN": serviceaccounts "chaos-controller-manager" not found
Error from server (NotFound): error when deleting "STDIN": secrets "chaos-mesh-webhook-certs" not found
Error from server (NotFound): error when deleting "STDIN": clusterroles.rbac.authorization.k8s.io "chaos-mesh-chaos-controller-manager-target-namespace" not found
Error from server (NotFound): error when deleting "STDIN": clusterroles.rbac.authorization.k8s.io "chaos-mesh-chaos-controller-manager-cluster-level" not found
Error from server (NotFound): error when deleting "STDIN": clusterrolebindings.rbac.authorization.k8s.io "chaos-mesh-chaos-controller-manager-cluster-level" not found
Error from server (NotFound): error when deleting "STDIN": clusterrolebindings.rbac.authorization.k8s.io "chaos-mesh-chaos-controller-manager-target-namespace" not found
Error from server (NotFound): error when deleting "STDIN": roles.rbac.authorization.k8s.io "chaos-mesh-chaos-controller-manager-control-plane" not found
Error from server (NotFound): error when deleting "STDIN": rolebindings.rbac.authorization.k8s.io "chaos-mesh-chaos-controller-manager-control-plane" not found
Error from server (NotFound): error when deleting "STDIN": services "chaos-daemon" not found
Error from server (NotFound): error when deleting "STDIN": services "chaos-dashboard" not found
Error from server (NotFound): error when deleting "STDIN": services "chaos-mesh-controller-manager" not found
Error from server (NotFound): error when deleting "STDIN": daemonsets.apps "chaos-daemon" not found
Error from server (NotFound): error when deleting "STDIN": deployments.apps "chaos-dashboard" not found
Error from server (NotFound): error when deleting "STDIN": deployments.apps "chaos-controller-manager" not found
Error from server (NotFound): error when deleting "STDIN": mutatingwebhookconfigurations.admissionregistration.k8s.io "chaos-mesh-mutation" not found
Error from server (NotFound): error when deleting "STDIN": validatingwebhookconfigurations.admissionregistration.k8s.io "chaos-mesh-validation" not found
```
So is there a way to solve this problem?

BTW, when exec `kubectl delete podchaos --all --all-namespaces`, it will also stop at a step for a long time.
Is this normal? What is the expected time for these two commands ?

Thanks in advance

**Comment by zhuwenxing** [comment]
sorry, it is a very common question. I solve it by myself according to [怎样删除一直terminating的k8s的pod或者ns资源](https://blog.csdn.net/weixin_38499215/article/details/101301363?utm_medium=distribute.pc_relevant_t0.none-task-blog-BlogCommendFromMachineLearnPai2-1.control&dist_request_id=41a0cfbf-1698-40df-bbe7-70628d7464a8&depth_1-utm_source=distribute.pc_relevant_t0.none-task-blog-BlogCommendFromMachineLearnPai2-1.control)

But I still want to know the answer to the following questions
> BTW, when exec kubectl delete podchaos --all --all-namespaces, it will also stop at a step for a long time.
Is this normal? What is the expected time for these two commands?

**Comment by STRRL** [comment]
> But it stop at validatingwebhookconfiguration.admissionregistration.k8s.io "chaos-mesh-validation" deleted this step for a long time.

This operation indeed will take several minutes, please keep waiting on it.

> So is there a way to solve this problem?

Sorry, I do not get your point. 🙈 Do you want to re-install the Chaos Mesh? And failed to install it?

> BTW, when exec kubectl delete podchaos --all --all-namespaces, it will also stop at a step for a long time.
Is this normal? What is the expected time for these two commands ?

I think it might related to https://github.com/chaos-mesh/chaos-mesh/issues/1465. It means the pods might changes during chaos effecting, so there are some orphans in finalized of podchaos.

**Comment by zhuwenxing** [comment]
> Sorry, I do not get your point.  Do you want to re-install the Chaos Mesh? And failed to install it?

Yes, I want to re-install the Chaos Mesh and hope it is a fresh one, but I encountered a problem when uninstalling as mentioned above.

I reinstalled it through the method in the link https://github.com/chaos-mesh/chaos-mesh/issues/1519#issuecomment-784939743
But encountered a new problem today: The previous experiment can still be seen in the dashboard(all of them can't be deleted), and the new experiment will have errors `error.api.internal_server_error: the server does not allow this method on the requested resource (post podchaos.chaos-mesh.org)`

**Comment by STRRL** [comment]
> I think it might be related to #1465. It means the pods might changes during chaos effecting, so there are some orphans in finalized of podchaos.

If you want to **forcely delete** that chaos object, you could remove its finalizers by `kubectl edit` or `kubectl patch`. 

It's a **dangerous** operation, it might causes chaos never recover on your pod(but when you delete the pod, the chaos experiments will gone, so do not fear about it), please check the finalizers and make sure they are cleaned on your kubernetes cluster.

**Comment by STRRL** [comment]
Appending communication with adoptor: After deleting the dangling chaos resource, chaos mesh could uninstall cleanly.

I think I could close this issue.
