### ISSUE TITLE
inactive Slack link

### ISSUE THREAD

**Issue by juzhiyuan** [chaos-mesh/chaos-mesh#1534]
## Bug Report

![image](https://user-images.githubusercontent.com/2106987/109793896-31d1e800-7c50-11eb-817e-5473d6e75e5a.png)

**Comment by STRRL** [comment]
HI @juzhiyuan, that's a little weird, I tried this link, it links to `https://cloud-native.slack.com/join/shared_invite/zt-lo88vmyc-9e3jSdUXf3dLP2yKql4A0Q#/`, I think it is correct.

Would you mind clearing the browser cache and try again?  🥺

If you did not join the #CNCF slack channel before, you need to register an account for that.
