### ISSUE TITLE
Update makefile, making the default recipe is building something

### ISSUE THREAD

**Issue by STRRL** [chaos-mesh/chaos-mesh#1540]
As the document [Set up the development environment
](https://chaos-mesh.org/docs/development_guides/set_up_the_development_environment/) says, the default recipe of makefile should use the toolchain:
> If there is no error in the output, the compiling toolchain is successfully configured.

As common usage, a single `make` often builds the project.

Currently, the default recipe of the makefile is `go_build_cache_directory`.

How about using the recipe `all` or `binary` as the first recipe of the makefile?

**Comment by STRRL** [comment]
OK @Debanitrkl

**Comment by AsterNighT** [comment]
closed due to #1554
