### ISSUE TITLE
Can each version release a corresponding arm64 image?

### ISSUE THREAD

**Issue by dploop** [chaos-mesh/chaos-mesh#1541]
Thank you for providing Chaos Mesh such a good tool, but in the process of using it, a large part of the environment is based on the arm architecture, although I found a latest-arm image on dockerhub, but that is four month ago. I also tried to compile an arm image by myself, but found it very difficult and never succeeded. 

So I would like to ask if you can compile a corresponding arm architecture image for each release version, such as v1.1.1-arm, v1.2.0-arm, and latest-arm. This will help me a lot. If it doesn't work, I hope there will be a document telling me how to compile the corresponding version of the image by myself, thank you.

**Comment by dploop** [comment]
I use your commit to have a try on my macbook, chaos-mesh and chaos-daemon are succeeded while chaos-dashboard is blocked, the message is

```
yarn install --frozen-lockfile
Unknown QEMU_IFLA_INFO_KIND ipip
Unknown QEMU_IFLA_INFO_KIND ip6tnl
yarn install v1.22.10
Unknown QEMU_IFLA_INFO_KIND ipip
Unknown QEMU_IFLA_INFO_KIND ip6tnl
warning Skipping preferred cache folder "/.cache/yarn" because it is not writable.
warning Selected the next writable cache folder in the list, will be "/tmp/.yarn-cache-501".
[1/4] Resolving packages...
[2/4] Fetching packages...
Unknown QEMU_IFLA_INFO_KIND ipip
Unknown QEMU_IFLA_INFO_KIND ip6tnl
info There appears to be trouble with your network connection. Retrying...
Unknown QEMU_IFLA_INFO_KIND ipip
Unknown QEMU_IFLA_INFO_KIND ip6tnl
info There appears to be trouble with your network connection. Retrying...
Unknown QEMU_IFLA_INFO_KIND ipip
Unknown QEMU_IFLA_INFO_KIND ip6tnl
info There appears to be trouble with your network connection. Retrying...
```

By the way, there is a warning message
```
WARNING: The requested image's platform (linux/arm64) does not match the detected host platform (linux/amd64) and no specific platform was requested
```

**Comment by YangKeao** [comment]
Have you tried to build an arm image? If you have any question about this document / modification, feel free to reopen this issue :smile_cat: .

Thank you.

**Comment by dploop** [comment]
@YangKeao Thank you very much, I have successfully compiled it.
