### ISSUE TITLE
Dispatch the config in a better way

### ISSUE THREAD

**Issue by YangKeao** [chaos-mesh/chaos-mesh#1548]
```go
pods, err := selector.SelectAndFilterPods(ctx, r.Client, r.Reader, &dnschaos.Spec, config.ControllerCfg.ClusterScoped, config.ControllerCfg.TargetNamespace, config.ControllerCfg.AllowedNamespaces, config.ControllerCfg.IgnoredNamespaces)
```

This line of code occurs several times in Chaos Mesh code base, and most of these `config.xxx.xxx` won't change during the runtime. Please construct a "Selector" struct from config (or something similar) to select, rather than passing these arguments everytime.

**Comment by AsterNighT** [comment]
Shoule this go after #1550 ?
