### ISSUE TITLE
Dashboard requests events without pagination

### ISSUE THREAD

**Issue by dploop** [chaos-mesh/chaos-mesh#1557]
On the dashboard page, when I click on an experiment, theoretically, I should only request events related to this experiment, and it should be paged. But it seems that the current implementation does not do this, but requests the full amount of events. When the number of events is particularly large, this request will consume performance.

<img width="1440" alt="截屏2021-03-11 下午8 14 45" src="https://user-images.githubusercontent.com/12315670/110786649-5872cd00-82a7-11eb-8a69-baaf86de7ac5.png">

<img width="1440" alt="截屏2021-03-11 下午8 15 38" src="https://user-images.githubusercontent.com/12315670/110786670-5dd01780-82a7-11eb-8039-0250313ae117.png">

**Comment by fewdan** [comment]
@g1eny0ung
I took a look at the current api/events request, and there is indeed no filtering information. Here you can modify the code to attach the experimental information to the request when sending the request.

**Comment by g1eny0ung** [comment]
The event filtering problem on the detail page has also been fixed. Thanks for pointing it!

**Comment by dploop** [comment]
@g1eny0ung The integration test seems failed.
