### ISSUE TITLE
Unable to install chaos mesh on minikube

### ISSUE THREAD

**Issue by DmitriyVorobey** [chaos-mesh/chaos-mesh#1566]
## Bug Report

Unable to install chaos mesh on minikube with getting started tutorial https://chaos-mesh.org/docs/get_started/get_started_on_minikube.

**What version of Kubernetes are you using?**
minikube v1.17.1 on Microsoft Windows 10 Pro 10.0.18363 Build 18363

**What version of Chaos Mesh are you using?**
1.1.2

**What did you do?**
1. minikube start
2. curl -sSL https://mirrors.chaos-mesh.org/v1.1.2/install.sh | bash
Logs:
```
Install Chaos Mesh chaos-mesh
Warning: apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
customresourcedefinition.apiextensions.k8s.io/dnschaos.chaos-mesh.org created
customresourcedefinition.apiextensions.k8s.io/httpchaos.chaos-mesh.org created
customresourcedefinition.apiextensions.k8s.io/iochaos.chaos-mesh.org created
customresourcedefinition.apiextensions.k8s.io/jvmchaos.chaos-mesh.org created
customresourcedefinition.apiextensions.k8s.io/kernelchaos.chaos-mesh.org created
customresourcedefinition.apiextensions.k8s.io/networkchaos.chaos-mesh.org created
customresourcedefinition.apiextensions.k8s.io/podchaos.chaos-mesh.org created
customresourcedefinition.apiextensions.k8s.io/podiochaos.chaos-mesh.org created
customresourcedefinition.apiextensions.k8s.io/podnetworkchaos.chaos-mesh.org created
customresourcedefinition.apiextensions.k8s.io/stresschaos.chaos-mesh.org created
customresourcedefinition.apiextensions.k8s.io/timechaos.chaos-mesh.org created
error: no objects passed to apply
```
3. Run `kubectl get pod -n chaos-testing `
Response: No resources found in chaos-testing namespace.

**What did you expect to see?**
Expected output:
NAME                                        READY   STATUS    RESTARTS   AGE
chaos-controller-manager-6d6d95cd94-kl8gs   1/1     Running   0          3m40s
chaos-daemon-5shkv                          1/1     Running   0          3m40s
chaos-dashboard-d998856f6-vgrjs             1/1     Running   0          3m40s

**What did you see instead?**
Response: No resources found in chaos-testing namespace.

**Output of chaosctl**

**Comment by fewdan** [comment]
I'm sorry, I didn't reproduce this problem in my computer. I saw that you didn't encounter this problem in the next issue. How did you solve it later?

**Comment by DmitriyVorobey** [comment]
Hey, I used manual installation with helm. That works better for me https://chaos-mesh.org/docs/user_guides/installation#install-by-helm.

**Comment by fewdan** [comment]
@DmitriyVorobey 
I am in a Mac OS environment, but I installed it in kind, and there is no problem. The command used is "curl -sSL https://mirrors.chaos-mesh.org/v1.1.2/install.sh | bash -s - --local kind".

**Comment by DmitriyVorobey** [comment]
@fewdan Is `kind` recommended tool for chaos mesh experiments in the local environment? Can I use minikube instead?

**Comment by DmitriyVorobey** [comment]
I got the same result with the `kind` tool.
```
customresourcedefinition.apiextensions.k8s.io/dnschaos.chaos-mesh.org created
customresourcedefinition.apiextensions.k8s.io/httpchaos.chaos-mesh.org created
customresourcedefinition.apiextensions.k8s.io/iochaos.chaos-mesh.org created
customresourcedefinition.apiextensions.k8s.io/jvmchaos.chaos-mesh.org created
customresourcedefinition.apiextensions.k8s.io/kernelchaos.chaos-mesh.org created
customresourcedefinition.apiextensions.k8s.io/networkchaos.chaos-mesh.org created
customresourcedefinition.apiextensions.k8s.io/podchaos.chaos-mesh.org created
customresourcedefinition.apiextensions.k8s.io/podiochaos.chaos-mesh.org created
customresourcedefinition.apiextensions.k8s.io/podnetworkchaos.chaos-mesh.org created
customresourcedefinition.apiextensions.k8s.io/stresschaos.chaos-mesh.org created
customresourcedefinition.apiextensions.k8s.io/timechaos.chaos-mesh.org created
error: no objects passed to apply
```

**Comment by YangKeao** [comment]
> @fewdan Is `kind` recommended tool for chaos mesh experiments in the local environment? Can I use minikube instead?

I think `minikube` is a stabler environment than `kind`. I don't know whether this problem is caused by `git bash` on windows (as I'm a Linux user). I will try with my windows laptop tomorrow :yum: .

**Comment by DmitriyVorobey** [comment]
@YangKeao Thank you 🙂

**Comment by AsterNighT** [comment]
Well, I'll have a try on this. /assign

**Comment by AsterNighT** [comment]
I'm having great trouble running minikube on windows. I'm using vmware so I cannot use hyper-v (so no wsl2 either, therefore no docker as well). But I encounter lots of error on minikube vmware driver. Help needed on this. Could you pls provide some more information on your environment, like which driver of minikube are you using?
