### ISSUE TITLE
Unable to run chaos experiment from the getting started tutorial

### ISSUE THREAD

**Issue by DmitriyVorobey** [chaos-mesh/chaos-mesh#1567]
## Bug Report

Link to chaos mesh tutorial https://chaos-mesh.org/docs/user_guides/run_chaos_experiment

**What version of Kubernetes are you using?**
minikube v1.17.1 on Microsoft Windows 10 Pro 10.0.18363 Build 18363

**What version of Chaos Mesh are you using?**
1.1.2

**What did you do?**
1. minikube start
2. curl -sSL https://mirrors.chaos-mesh.org/v1.1.2/web-show/deploy.sh | sh

**What did you expect to see?**
No errors in outputs

**What did you see instead?**
```
deployment.apps/web-show created
Waiting for pod running
Waiting for pod running
Waiting for pod running
Waiting for pod running
sh: line 120: lsof: command not found

```
**Output of chaosctl**

**Comment by fewdan** [comment]
If you run "kubectl get pod -n chaos-testing", what will be the result?

**Comment by DmitriyVorobey** [comment]
`No resources found in chaos-testing namespace.`
But, web-show pod was created in the default Kubernetes namespace.
I am using git bash to run the deploy script. Might it cause an issue?

**Comment by fewdan** [comment]
@DmitriyVorobey 
Oh, I know, it’s because the script "https://mirrors.chaos-mesh.org/v1.1.2/web-show/deploy.sh" deploys the "web-show" application, not "chaos-mesh", so it is normal that there is no pod under the "chaos-testing" namespace, which is in line with expectations.

**Comment by DmitriyVorobey** [comment]
Yes, but I still don`t understand why scripts execution fails on the last step with error:
`sh: line 120: lsof: command not found`. I would assume that it's because of the windows environment

**Comment by fewdan** [comment]
I also tend to think that it is an environment-related issue.

**Comment by AsterNighT** [comment]
Would you please try to run `lsof` directly from your shell?

**Comment by DmitriyVorobey** [comment]
@AsterNighT 
The result is: `bash: lsof: command not found. `
It looks like lsof is a Linux-specific tool. That is why it doesn`t work for windows.

**Comment by AsterNighT** [comment]
To summarize, our scripts don't work properly on windows now. I would recommend you retry it in a vm. Issues about windows scripts should be discussed elsewhere. If there're no furthur information, I'm closing this issue.
