### ISSUE TITLE
Upgrading admissionregistration to v1

### ISSUE THREAD

**Issue by STRRL** [chaos-mesh/chaos-mesh#1570]
## Feature Request

**Is your feature request related to a problem? Please describe:**

As https://github.com/chaos-mesh/chaos-mesh/pull/1558 says, we want to upgrade to v1.
Related issue: https://github.com/chaos-mesh/chaos-mesh/issues/1007

**Describe the feature you'd like:**

If we want to upgrade to v1, we need to keep compatibility with 1.15. helm built-in [Compatibility](https://helm.sh/docs/chart_template_guide/builtin_objects/) might be helpful.

**Describe alternatives you've considered:**

Keep using v1beta1, it's still available.

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by STRRL** [comment]
Hi @anuragpaliwal80 , I think you could take a look at the helm charts, and keep compatibility with kubernetes 1.15.6 which e2e test based on.

And I think the version of `k8s.io/api/admission` is not needed to upgrade.

**Comment by anuragpaliwal80** [comment]
Sure, let me explore on this. Thx for sharing.

**Comment by anuragpaliwal80** [comment]
I tried using `.Capabilities.APIVersions.Has` as part of #1558 and looks like we need to change other pkg, etc as well to make it work.

**Comment by anuragpaliwal80** [comment]
@STRRL As said earlier, it looks like other pkg also needs to be updated to get it working. I made all changes in  #1558 Please check.

**Comment by anuragpaliwal80** [comment]
The sub task #1558 is still open.

**Comment by STRRL** [comment]
closed by #1558
