### ISSUE TITLE
Magic word `/run-all-tests` actually won't run the all tests

### ISSUE THREAD

**Issue by Colstuwjx** [chaos-mesh/chaos-mesh#1573]
## Bug Report

**What version of Kubernetes are you using?**

**What version of Chaos Mesh are you using?**

v1.1.1

**What did you do?**

Typed `/run-all-tests` in PR #1569 .

**What did you expect to see?**
The bot should help me re-run all the tests, including the integration test, script test, ci test, and e2e test.

**What did you see instead?**
Only the e2e test was triggered by the bot.

**Output of chaosctl**

**Comment by WangXiangUSTC** [comment]
The integration test is run by github action，it seems that it can't be triggered by comments now 🤣

**Comment by AsterNighT** [comment]
That can be done with things like https://github.com/Khan/pull-request-comment-trigger

**Comment by WangXiangUSTC** [comment]
> That can be done with things like https://github.com/Khan/pull-request-comment-trigger

Oh, I can try it

**Comment by AsterNighT** [comment]
nuts, Github action has a limited support on pr comments. We may have to use a turn around.

**Comment by STRRL** [comment]
Does ti-chi (our community bot) could make this better?

**Comment by AsterNighT** [comment]
I don't think github action is good for it. I tried to trigger the actions with `issue_comment` and `pull_request_review` event provided by github, and ran into different issues. The `issue_comment` event runs on default branch thus is not acceptable at all. `pull_request_review` triggers another check different from the original one triggered by pull_request (see https://github.com/AsterNighT/test/pull/2) , which is not what we want as well. I suppose there have to be a bot doing such things.
