### ISSUE TITLE
Failed to create NetworkChaos in arm environment

### ISSUE THREAD

**Issue by dploop** [chaos-mesh/chaos-mesh#1579]
```
failedMessage: 'admission webhook "vpodnetworkchaos.kb.io" denied the request:
      rpc error: code = Unknown desc = error code: fork/exec /usr/local/bin/nsexec:
      exec format error, msg: 
```

[#1541](https://github.com/chaos-mesh/chaos-mesh/issues/1541)  @YangKeao  add support for build arm image, but some tools seems still amd64. I found in Dockerfile:

```
RUN curl -L https://github.com/chaos-mesh/toda/releases/download/v0.1.17/toda-linux-amd64.tar.gz -o /usr/local/bin/toda.tar.gz
RUN curl -L https://github.com/chaos-mesh/nsexec/releases/download/v0.1.5/nsexec-linux-amd64.tar.gz -o /usr/local/bin/nsexec.tar.gz
```

**Comment by YangKeao** [comment]
Oops. My bad :man_facepalming:. The CI of `nsexec` doesn't build an arm binary now. I will try to modify it.

**Comment by dploop** [comment]
Is there a specific repair plan for this problem? Does it only need to compile the arm version of toda and nsexec? Or maybe some additional adaptation work is needed?

**Comment by STRRL** [comment]
Hi @YangKeao, PTAL.

**Comment by YangKeao** [comment]
Arm environment is officially supported in `ghcr.io/chaos-mesh/chaos-daemon` image (several months ago, sorry I forgot to update this issue 😢 ). If you have any further problem about running Chaos Mesh on arm, feel free to reopen this issue (or create a new one).
