### ISSUE TITLE
pause experiment and chaos controller manager will update chaos forever

### ISSUE THREAD

**Issue by WangXiangUSTC** [chaos-mesh/chaos-mesh#1585]
## Bug Report

**What version of Chaos Mesh are you using?**

v1.0.1

**What did you do?**

create a pod failure chaos experiment, and then pause the experiment. will see that there are a lot of logs in controller manager,  and it will not 

**What did you expect to see?**

The experiment will pause success, and see the paused log in controller manager.

**What did you see instead?**

The experiment paused, but there are a lot of logs in the controller manager, and it keeps writing new logs.

**Comment by WangXiangUSTC** [comment]
when the state is `Paused`, will update here https://github.com/chaos-mesh/chaos-mesh/blob/f4f15091713bcf0fe7ec87f46e723a89e3184b46/controllers/twophase/types.go#L218, and reconcile again, endless...

**Comment by WangXiangUSTC** [comment]
and this issue also happened in v1.1.2

**Comment by cwen0** [comment]
> and this issue also happened in v1.1.2

If only the status field will be updated, this issue should happen in v.1.1.2

**Comment by WangXiangUSTC** [comment]
> and this issue also happened in v1.1.2

I made a mistake, v1.1.2 doesn't have this issue.

**Comment by e06084** [comment]
+1

**Comment by WangXiangUSTC** [comment]
upgrade to v1.1.2 to fix this issue
