### ISSUE TITLE
Issues about applying kubernetes optimistic lock

### ISSUE THREAD

**Issue by AsterNighT** [chaos-mesh/chaos-mesh#1597]
Optimistic locks (like `retry.RetryOnConflict`) are adopted widely in chaos-mesh. But there are misuses and still somewhere in lack of locks. Take this as an example

https://github.com/chaos-mesh/chaos-mesh/blob/6ee0cb9f67c671eefb9110a99e021a260e2f5ac7/controllers/common/types.go#L112-L114

from my knowledge this retry will not work. And a lack of lock here

https://github.com/chaos-mesh/chaos-mesh/blob/6ee0cb9f67c671eefb9110a99e021a260e2f5ac7/controllers/common/types.go#L129-L132

I believe this is somewhat a reason for #1559, I will try to reproduce it locally.

**Comment by AsterNighT** [comment]
@WangXiangUSTC PTAL

**Comment by AsterNighT** [comment]
After a talk with @YangKeao, we decide this could be delayed and wait for a controller refactor in #1578

**Comment by YangKeao** [comment]
Oops. The original issue was closed by the bot https://github.com/chaos-mesh/chaos-mesh/issues/791 :facepalm:

**Comment by AsterNighT** [comment]
LOL
