### ISSUE TITLE
`ContainerKill` e2e test is not stable

### ISSUE THREAD

**Issue by YangKeao** [chaos-mesh/chaos-mesh#1602]
## Bug Report

If your machine is too fast, and the container was quickly resumed, it would be always "Ready", and the following condition will never meet:

https://github.com/chaos-mesh/chaos-mesh/blob/master/test/e2e/chaos/podchaos/container_kill.go#L86

```go
if cs.Name == "nginx" && !cs.Ready && cs.LastTerminationState.Terminated != nil
```

**Comment by AsterNighT** [comment]
I quote ”竟有这事“. A deep dive into k8s log should be a workaround for this, I guess.

**Comment by AsterNighT** [comment]
Would the same problem apply to `podkill` too?
