### ISSUE TITLE
gzip: stdin: not in gzip format

### ISSUE THREAD

**Issue by advancedwebdeveloper** [chaos-mesh/chaos-mesh#1605]
Hi. I got a bug here:

> $ make
> cd ./api/v1alpha1 ;\
>         /home/oceanfish81/go/bin/controller-gen "crd:trivialVersions=true,preserveUnknownFields=false" rbac:roleName=manager-role paths="./..." output:crd:artifacts:config=../../config/crd/bases ;\
>         /home/oceanfish81/go/bin/controller-gen "crd:trivialVersions=true,preserveUnknownFields=false" rbac:roleName=manager-role paths="./..." output:crd:artifacts:config=../../helm/chaos-mesh/crds ;
> ensuring kustomize
> ROOT=/home/oceanfish81/chaos-mesh && source ./hack/lib.sh && hack::ensure_kustomize
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 100     9  100     9    0     0     46      0 --:--:-- --:--:-- --:--:--    46
> 
> gzip: stdin: not in gzip format
> tar: Child returned status 1
> tar: Error is not recoverable: exiting now
> chmod: cannot access '/home/oceanfish81/chaos-mesh/output/bin/kustomize': No such file or directory
> make: *** [Makefile:383: ensure-kustomize] Error 1

## Bug Report

**What version of Kubernetes are you using?**

> $ kubectl version
> Client Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.0-beta.1.446+9c9af69ea60519", GitCommit:"9c9af69ea60519b610a70261fb1b8bb81a2a5d04", GitTreeState:"clean", BuildDate:"2021-03-26T22:19:57Z", GoVersion:"go1.16.2", Compiler:"gc", Platform:"linux/arm64"}
> Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:20:00Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/arm64"}

**What version of Chaos Mesh are you using?**

> $ git log -1
> commit 6ee0cb9f67c671eefb9110a99e021a260e2f5ac7 (HEAD -> master, origin/master, origin/HEAD)
> Author: Yihao Fu <fewdan@hotmail.com>
> Date:   Thu Mar 25 10:36:07 2021 +0800

 

> $ make --version && go version && go env && uname -a
> GNU Make 4.2.1
> Built for aarch64-unknown-linux-gnu
> Copyright (C) 1988-2016 Free Software Foundation, Inc.
> License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
> This is free software: you are free to change and redistribute it.
> There is NO WARRANTY, to the extent permitted by law.
> go version go1.16.2 linux/arm64
> GO111MODULE=""
> GOARCH="arm64"
> GOBIN=""
> GOCACHE="/home/oceanfish81/.cache/go-build"
> GOENV="/home/oceanfish81/.config/go/env"
> GOEXE=""
> GOFLAGS=""
> GOHOSTARCH="arm64"
> GOHOSTOS="linux"
> GOINSECURE=""
> GOMODCACHE="/home/oceanfish81/go/pkg/mod"
> GONOPROXY=""
> GONOSUMDB=""
> GOOS="linux"
> GOPATH="/home/oceanfish81/go"
> GOPRIVATE=""
> GOPROXY="https://proxy.golang.org,direct"
> GOROOT="/usr/local/go"
> GOSUMDB="sum.golang.org"
> GOTMPDIR=""
> GOTOOLDIR="/usr/local/go/pkg/tool/linux_arm64"
> GOVCS=""
> GOVERSION="go1.16.2"
> GCCGO="gccgo"
> AR="ar"
> CC="gcc"
> CXX="g++"
> CGO_ENABLED="1"
> GOMOD="/home/oceanfish81/chaos-mesh/go.mod"
> CGO_CFLAGS="-g -O2"
> CGO_CPPFLAGS=""
> CGO_CXXFLAGS="-g -O2"
> CGO_FFLAGS="-g -O2"
> CGO_LDFLAGS="-g -O2"
> PKG_CONFIG="pkg-config"
> GOGCCFLAGS="-fPIC -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build2302269440=/tmp/go-build -gno-record-gcc-switches"
> Linux ams1-c1-large-arm-01 5.4.0-40-generic #44-Ubuntu SMP Mon Jun 22 23:59:48 UTC 2020 aarch64 aarch64 aarch64 GNU/Linux

**Comment by STRRL** [comment]
Hi @advancedwebdeveloper, I found that it failed at downloading `kustomize`, please check your network and try again.
