### ISSUE TITLE
 admission webhook "vauth.kb.io" denied the request: <redacted_user> is forbidden on namespace <redacted_namespace>

### ISSUE THREAD

**Issue by jasonstack** [chaos-mesh/chaos-mesh#1613]
## Bug Report

**What version of Kubernetes are you using?**
1.16.15-gke.12500 

**What version of Chaos Mesh are you using?**
latest -> 0.4.2

**What did you do?**
try to apply chaos mesh experiment

**What did you expect to see?**
chaos experiment applied

**What did you see instead?**
 error -> admission webhook "vauth.kb.io" denied the request: <redacted> is forbidden on namespace <redacted_namespace>

downgrading to 0.4.1 works

**Output of chaosctl**
no

**Comment by YangKeao** [comment]
#1535

In the latest version, Chaos Mesh avoids the chaos under namespace A to inject chaos into pods in namespace B (so that the injection scope can be fully controlled by the RBAC).

**Comment by jasonstack** [comment]
> Chaos Mesh avoids the chaos under namespace A to inject chaos into pods in namespace B

In my test, chaos-mesh is installed into namespace `chaos-testing`, experiments (no namespace defined in the YAML) are applied to target namespace `target_namespace` which contains target pods, using `apply --namespace target_namespace -f experiment.yaml`. 

btw, in the latest version, rbac file was removed from `./manifest` folder.

**Comment by YangKeao** [comment]
@WangXiangUSTC PTAL

**Comment by WangXiangUSTC** [comment]
@jasonstack could you please provide more details about the error log, include usernames, etc.

**Comment by WangXiangUSTC** [comment]
In addition, please check the privileges of the user, make sure it has the privileges on < redacted_namespace >

**Comment by avacaru** [comment]
Hi everyone!

I am seeing the same issue and after trying to debug a little bit it looks like there is an issue with the admission webhook. I wonder if it has to do with the way the auth API works. What is the difference between what kubectl is using for `kubectl auth can-i` and what the validate-auth webhook is using? ref: https://github.com/chaos-mesh/chaos-mesh/pull/1535/files#diff-9d5caeab1ced9e778bbe3477bb7ffe42a42484bbd1eac63cd55b86682b74d341R22

I have checked that my user is allowed to create the resource in namespace default:
```
$>>> cat kill-nginx.yaml
apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: kill-nginx
spec:
  action: pod-failure
  mode: all
  duration: 5m
  selector:
    labelSelectors:
      app: nginx
  scheduler:
    cron: '@every 5m1s'
$>>> kubectl auth can-i create podchaos
yes
$>>> kubectl apply -f kill-nginx.yaml
Error from server (avacaru is forbidden on namespace default):
  error when creating "kill-nginx.yaml":
    admission webhook "vauth.kb.io" denied the request:
      avacaru is forbidden on namespace default
```

The only thing I would like to mention that might help you pin down the problem is that my cluster running on Azure AKS with managed AAD. There is a clusterrole that allows all resources and all verbs on "chaos-mesh.org" and there is a clusterrolebinding between this role and an AD Group my user is part of.

One other thing I tried was to edit the `validate-auth` validationwebhook and change the rules.operations from [CREATE, UPDATE] to [DELETE] just to make sure my RBAC is working and `kubectl auth can-i` doesn't give me a false positive. And yes, I was able to create the CR in the default namespace.

**Comment by YangKeao** [comment]
> What is the difference between what kubectl is using for kubectl auth can-i and what the validate-auth webhook is using?

It seems that the only difference is `kubectl` called `SelfSubjectAccessReview` ([cani.go#L247](https://github.com/kubernetes/kubectl/blob/652881798563c00c1895ded6ced819030bfaa4d7/pkg/cmd/auth/cani.go#L247)), and Chaos Mesh uses `SubjectAccessReview` (with username and groupds) to validate user.

**Comment by aido123** [comment]
Looks like it's a case issue with the resource name:

Example:

`./kubectl create -f - -o yaml << EOF
> apiVersion: authorization.k8s.io/v1
> kind: SelfSubjectAccessReview
> spec:
>   resourceAttributes:
>     group: chaos-mesh.org
>     resource: podchaos
>     verb: create
>     namespace: mynamespace
> EOF
apiVersion: authorization.k8s.io/v1
kind: SelfSubjectAccessReview
metadata:
  creationTimestamp: null
  managedFields:
  - apiVersion: authorization.k8s.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:spec:
        f:resourceAttributes:
          .: {}
          f:group: {}
          f:namespace: {}
          f:resource: {}
          f:verb: {}
    manager: kubectl
    operation: Update
    time: "2021-04-02T08:29:07Z"
spec:
  resourceAttributes:
    group: chaos-mesh.org
    namespace: mynamespace
    resource: podchaos
    verb: create
status:
  allowed: true
  reason: 'RBAC: allowed by ClusterRoleBinding "<REDACTED>" of ClusterRole "<REDACTED>"
    to Group "<REDACTED>"'`


`./kubectl create -f - -o yaml << EOF
> apiVersion: authorization.k8s.io/v1
> kind: SelfSubjectAccessReview
> spec:
>   resourceAttributes:
>     group: chaos-mesh.org
>     resource: PodChaos
>     verb: create
>     namespace: mynamespace
> EOF
apiVersion: authorization.k8s.io/v1
kind: SelfSubjectAccessReview
metadata:
  creationTimestamp: null
  managedFields:
  - apiVersion: authorization.k8s.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:spec:
        f:resourceAttributes:
          .: {}
          f:group: {}
          f:namespace: {}
          f:resource: {}
          f:verb: {}
    manager: kubectl
    operation: Update
    time: "2021-04-02T08:30:52Z"
spec:
  resourceAttributes:
    group: chaos-mesh.org
    namespace: mynamespace
    resource: PodChaos
    verb: create
status:
  allowed: false`

Setting the resource to lower case ( strings.ToLower(resource) ) works when I build locally
https://github.com/chaos-mesh/chaos-mesh/blob/release-1.2/api/webhook/validate_auth.go#L146

**Comment by STRRL** [comment]
Oh, thanks! Would you like to make a PR for that? @aido123 😁

**Comment by aido123** [comment]
> Oh, thanks! Would you like to make a PR for that? @aido123 😁

Sure thing

**Comment by WangXiangUSTC** [comment]
> > What is the difference between what kubectl is using for kubectl auth can-i and what the validate-auth webhook is using?
> 
> It seems that the only difference is `kubectl` called `SelfSubjectAccessReview` ([cani.go#L247](https://github.com/kubernetes/kubectl/blob/652881798563c00c1895ded6ced819030bfaa4d7/pkg/cmd/auth/cani.go#L247)), and Chaos Mesh uses `SubjectAccessReview` (with username and groupds) to validate user.

`SelfSubjectAccessReview` can only validate the connection is used, but `SubjectAccessReview` can validate other user
