### ISSUE TITLE
Better logs for developing and debugging

### ISSUE THREAD

**Issue by AsterNighT** [chaos-mesh/chaos-mesh#1642]
## Feature Request
Now chaos-mesh's log is not so well-organized. It has become an obstacle for debugging and developing.

**Describe the feature you'd like:**
A better logging format could be adopted, Including but not limited to
1. Unified log level
2. Unified log manager (chaosctl could do the job), providing pod-wise log manipulation.
3. Source of the log (which module, file and line)
4. A colored log output

**Comment by STRRL** [comment]
> 3. Source of the log (which module, file and line)

I wondering that we could also unify the creation of error, attaching the stack. We use zap as the logging framework, and zap will print the stack when printing an error, that's a little confusing.
