### ISSUE TITLE
dashboard: can't insert experiment in MySQL NO_ZERO_IN_DATE mode

### ISSUE THREAD

**Issue by g1eny0ung** [chaos-mesh/chaos-mesh#1659]
## Bug Report

**What version of Kubernetes are you using?**

> Client Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.4-dirty", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"dirty", BuildDate:"2021-03-15T09:58:13Z", GoVersion:"go1.16.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:20:00Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}

**What version of Chaos Mesh are you using?**

> Latest

**What did you do?**

Helm install with MySQL driver:

```sh
helm install chaos-mesh helm/chaos-mesh --namespace=chaos-testing --set dashboard.create=true,dashboard.securityMode=false,dashboard.env.DATABASE_DRIVER=mysql,dashboard.env.DATABASE_DATASOURCE="root@tcp(docker.for.mac.localhost:3306)/chaosmesh?parseTime=True"
```

**What did you expect to see?**

After creating an experiment, the database should insert its record successfully.

**What did you see instead?**

Data insertion failed.

After my test, seems this related to https://dev.mysql.com/doc/refman/5.7/en/date-and-time-types.html.

Because the experiment will not set an exact finish time in the beginning. So we will get an error like: `Incorrect datetime value: '0000-00-00'`.

A temporary solution:

```sql
show variables like 'sql_mode';
-- Copy all values except NO_ZERO_IN_DATE.
set global sql_mode=xxx  -- set again
```

Since zero time is not recommended, we need to set the unknown time to 1970-01-01(an example) to avoid this problem.

**Comment by Atrbear** [comment]
Then it is fixed? I meet this problem when using 2.5.1 version

**Comment by Atrbear** [comment]
I am using mysql 8.0.32; 

> show variables like 'sql_mode';
> ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION

-- Copy all values except NO_ZERO_IN_DATE and NO_ZERO_DATE
set global sql_model="ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION";  

that is how I solve this problem.

**Comment by g1eny0ung** [comment]
This problem has not been fully solved yet. I will assign it to myself.
