### ISSUE TITLE
how to build go demo using ptrace lib

### ISSUE THREAD

**Issue by jarrodcal** [chaos-mesh/chaos-mesh#1666]
## Question

use github.com/chaos-mesh/chaos-mesh/pkg/time  as lib

write a demo like this:

package main

import (
	"flag"
	"fmt"
	"github.com/chaos-mesh/chaos-mesh/pkg/time"
	"strconv"
)

var pid = flag.String("pid", "", "pid")

func main()  {
	flag.Parse()
	val, err := strconv.Atoi(*pid)
	if err != nil {
		fmt.Println(err)
		return
	}

	err = time.ModifyTime(val, -10000, 0, 1)
	if err != nil {
		fmt.Println(err)
	}
}

on linux platform build demo:  CGO_ENABLED=1  go build demo.go 
error：# github.com/chaos-mesh/chaos-mesh/pkg/ptrace
pkg/ptrace/cwrapper_linux.go:25:23: could not determine kind of name for C.int

how  to  build?  thanks!

**Comment by YangKeao** [comment]
There is also a simple demo of using `github.com/chaos-mesh/chaos-mesh/pkg/time` as lib in the chaos mesh repo (the source code located at https://github.com/chaos-mesh/chaos-mesh/blob/master/cmd/watchmaker/main_linux.go). Could you try to clone the `chaos-mesh` and run `CGO_ENABLED=1 go build ./cmd/watchmaker/`? It should compile and generate a binary `watchmaker`.

**Comment by YangKeao** [comment]
It turns out to be the compatibility issue of low version gcc and go. `cgo` requires gcc version >= 4.6

**Comment by jarrodcal** [comment]
Thanks，it's ok now!
