### ISSUE TITLE
ui: long text is not truncated

### ISSUE THREAD

**Issue by e06084** [chaos-mesh/chaos-mesh#1671]
![image](https://user-images.githubusercontent.com/24450527/114339023-e253d580-9b86-11eb-88cc-5fc83fa89382.png)

**Comment by g1eny0ung** [comment]
In the recent changes, I have already optimized these two places. I think the screenshot below can show the latest effect:

![image](https://user-images.githubusercontent.com/15034155/114341198-c6066780-9b8b-11eb-87d8-0a45589ab196.png)

These fixes will be released in the next version. I will also cherry-pick them into the old versions (if needed).

**Comment by cwen0** [comment]
@g1eny0ung Does `release-1.1` branch include this fix?

**Comment by g1eny0ung** [comment]
> @g1eny0ung Does `release-1.1` branch include this fix?

I am merging the fixes to the v1.1 branch. I will open a PR later.
