### ISSUE TITLE
Error while deleting networkchaos

### ISSUE THREAD

**Issue by liwanxue** [chaos-mesh/chaos-mesh#1675]
## Question

When I try delete networkchaos, it failed. Below are informations when I describe this networkchaos. 

  Failed Message:  1 error occurred:
                   * admission webhook "vpodnetworkchaos.kb.io" denied the request: rpc error: code = Unknown desc = no running task found: task 7c4f1fea194c06fc543b69b0478141495acb3b17ea6a34bb3eabfde309ceb48c not found: not found

  Scheduler:
Events:
  Type     Reason              Age                From                     Message
  ----     ------              ----               ----                     -------
  Warning  ChaosRecoverFailed  58m (x2 over 58m)  networkchaos-controller  1 error occurred:
           * admission webhook "vpodnetworkchaos.kb.io" denied the request: rpc error: code = Unknown desc = no running task found: task dc086e0666d5ebd711b6584de66ca6a69ac38d51aff69478a05bcb1106d663d8 not found: not found
  Warning  ChaosRecoverFailed  42m (x2 over 42m)  networkchaos-controller  1 error occurred:
           * admission webhook "vpodnetworkchaos.kb.io" denied the request: rpc error: code = Unknown desc = no running task found: task 63b513062a7b2e66c338d43405b050255158159ba928345d42043af4949f0ee4 not found: not found
  Warning  ChaosRecoverFailed  25m (x2 over 25m)  networkchaos-controller  1 error occurred:
           * admission webhook "vpodnetworkchaos.kb.io" denied the request: rpc error: code = Unknown desc = no running task found: task ec3a16a88ab34467f07d9474bfd44b611a37664702a08ef404a8e210c109daaa not found: not found
  Warning  ChaosRecoverFailed  8m58s (x2 over 8m58s)  networkchaos-controller  1 error occurred:
           * admission webhook "vpodnetworkchaos.kb.io" denied the request: rpc error: code = Unknown desc = no running task found: task 7c4f1fea194c06fc543b69b0478141495acb3b17ea6a34bb3eabfde309ceb48c not found: not found

**Comment by liwanxue** [comment]
How can I fix it or workaround it quickly? Thanks!

**Comment by liwanxue** [comment]
The step I can reproduce and workaround as below. I think it might be a bug. 
1.  apply a chaos. 
2. some pod which applied this chaos somehow the container is dead, and it will try restart.
3. but because of this chaos, this container can not start. 
4. then this error shows up when I try to delete this chaos.

**Comment by STRRL** [comment]
Hi @liwanxue , could you tell us the version of chaos-mesh, kubernetes and your container runtime?

**Comment by liwanxue** [comment]
chaos mesh is v1.1.1
k8s: release-0.46.10
chaosDaemon.runtime=containerd

**Comment by STRRL** [comment]
Please make sure that your container is still alive, it mostly like chaos-mesh failed to fetch pid information from your container runtime.

**Comment by liwanxue** [comment]
yes. I have to make sure container is alive during failure test.  so, I think it's a bug.

**Comment by STRRL** [comment]
Yeah, the reaction with the pod status changes is a big improvement in the 2.0 Roadmap. Please keep looking forward to that. 😁
