### ISSUE TITLE
Investigate subresource to resolve conflict of multiple controller

### ISSUE THREAD

**Issue by YangKeao** [chaos-mesh/chaos-mesh#1705]
Use subresource may resolve the conflict update of mutliple controller (as controllers manage different fields)

**Comment by AsterNighT** [comment]
It seems that `status` subresource is completely independant to the CR. I wonder if it will cause some inconsistency if not handled carefully

**Comment by YangKeao** [comment]
> It seems that `status` subresource is completely independant to the CR. I wonder if it will cause some inconsistency if not being handled carefully

Not `status` subresource. It needs a more fine-grained subresource, like a field (e.g. the `.Status.Records` and `.Status.DesiredPhase` can be updated independently to avoid conflict.). I don't know whether it is possible :crying_cat_face:

**Comment by AsterNighT** [comment]
I was referring to https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#subresources. So we are talking about different things?

**Comment by YangKeao** [comment]
> I was referring to https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#subresources. So we are talking about different things?

Oops, so only `.Status` and `.Scale` is supported? I will close this issue sadly :crying_cat_face:
