### ISSUE TITLE
Ability to set annotation on dnsServer

### ISSUE THREAD

**Issue by ericjohansson89** [chaos-mesh/chaos-mesh#1714]
## Feature Request

**Is your feature request related to a problem? Please describe:**
I am running istio in my cluster and I would like to have sidecars enabled in the chaos controller manager, chaos dashboard and chaos daemon pods. That setup is working fine but when I am trying to run the coredns part of chaos mesh for DNSChaos I am not able to toggle of istio sidecar injection through pod annotations in the settings for `dnsServer` values.

**Describe the feature you'd like:**
Ability to set annotations on core-dns pods.

**Teachability, Documentation, Adoption, Migration Strategy:**

https://github.com/chaos-mesh/chaos-mesh/blob/master/helm/chaos-mesh/values.yaml#L252-L287
Add part for
`podAnnotations`

**Comment by Hexilee** [comment]
Implemented, you can use it on the latest master branch.
