### ISSUE TITLE
NetworkChaos has been deleted , but still in dashboard

### ISSUE THREAD

**Issue by hantmac** [chaos-mesh/chaos-mesh#1751]
## Bug Report

**What version of Kubernetes are you using?**

```
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.8-aliyun.1", GitCommit:"5959bcb", GitTreeState:"", BuildDate:"2021-03-11T11:16:47Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**What version of Chaos Mesh are you using?**

1.20

**What did you do?**

I delete a NetworkChaos but the `NetworkChaos` still showed in dashboard, when I click it the dashboard get an error. See the next pics:

the deleted NetworkChaos still in dashboard :

![image](https://user-images.githubusercontent.com/7600925/116214326-2e9f3800-a779-11eb-9bcb-8c92133c6de7.png)

When I click on it got an error:

![image](https://user-images.githubusercontent.com/7600925/116214237-17f8e100-a779-11eb-9efe-d868d0b38f64.png)

**What did you expect to see?**
The deleted resources not in dashboard.

**What did you see instead?**
Still in dashboard.

**Comment by Muscule** [comment]
See same bug not only in network chaos.
