### ISSUE TITLE
Support Workflow for Nirvana

### ISSUE THREAD

**Issue by YangKeao** [chaos-mesh/chaos-mesh#1754]
Add the `Workflow` object in `Schedule`. There are two things to modify:

1. Modify the definition and types, to make it possible to write a workflow under the `Schedule`
2. Add a function to assert whether `Workflow` has stopped, so that the `gc` controller could remove it.

**Comment by STRRL** [comment]
> Add a function to assert whether Workflow has stopped, so that the gc controller could remove it.

`Workflow` has a condition called `ConditionAccomplished`, I think we could use that to make the assertion.

**Comment by AsterNighT** [comment]
Would it be a better way to treat `workflow` exactly as if it is a `chaos`, or treat it differently?

**Comment by YangKeao** [comment]
> which will be a better way to treat `workflow`, exactly as if it is a `chaos`, or treat it differently?

I can also add a `ConditionAccomplished` for workflow :smile_cat: to make them the same :smile_cat:

**Comment by AsterNighT** [comment]
> > Add a function to assert whether Workflow has stopped, so that the gc controller could remove it.
> 
> `Workflow` has a condition called `ConditionAccomplished`, I think we could use that to make the assertion.

It seems that `ConditionAccomplished` is a condition for `WorkflowNode` rather than `Workflow`, why is it that? Do I have to do one more step to get the entry node in order to get the workflow status?

**Comment by STRRL** [comment]
> It seems that ConditionAccomplished is a condition for WorkflowNode rather than Workflow, why is it that?

Both Workflow and WorkflowNode have the condition "ConditionAccomplished".

> Do I have to do one more step to get the entry node in order to get the workflow status?

NO. This step is actually made by workflow's controller, https://github.com/chaos-mesh/chaos-mesh/blob/c5c1bac9c9f603f449e986e9b3026ec56bf6dad9/pkg/workflow/controllers/workflow_entry_reconciler.go#L150

**Comment by AsterNighT** [comment]
whoops, it seems that `nirvana` is a bit behind `master`
