### ISSUE TITLE
Why does DNSChaos need get/list/watch for services within clusterScoped mode

### ISSUE THREAD

**Issue by STRRL** [chaos-mesh/chaos-mesh#1756]
## Question

I found a question while reviewing https://github.com/chaos-mesh/chaos-mesh/pull/1725, locate at https://github.com/chaos-mesh/chaos-mesh/blob/c86e97fad6720a2be53204827bc66b656fad8b8a/helm/chaos-mesh/templates/controller-manager-rbac.yaml#L56

Why controller-manager could get/list/watch service **only** with the cluster scoped mode? I think it relates to https://github.com/chaos-mesh/chaos-mesh/blob/c86e97fad6720a2be53204827bc66b656fad8b8a/controllers/dnschaos/types.go#L71, but it will only list services within the namespace which installed the chaos-mesh.

**Comment by STRRL** [comment]
PTAL @WangXiangUSTC

**Comment by WangXiangUSTC** [comment]
It seems that we can remove it from the cluster role, and I take a try, but get an error:
```log
pkg/mod/k8s.io/client-go@v0.17.0/tools/cache/reflector.go:108: Failed to list *v1.Service: services is forbidden: User "system:serviceaccount:chaos-testing:chaos-controller-manager" cannot list resource "services" in API group "" at the cluster scope
```

There are two problems:
1. Use get in code, but require the list privileges, here is the issue https://github.com/kubernetes-sigs/controller-runtime/issues/1220
2. Get services in a namespace, but require cluster privileges, and find a similar issue https://github.com/operator-framework/operator-sdk/issues/2608
