### ISSUE TITLE
Running Chaos on Init Containers

### ISSUE THREAD

**Issue by adbjo** [chaos-mesh/chaos-mesh#1772]
## Question
Hi,

We have an Init Container that is used to get credentials for services from a secrets manager.
We want to test it by running NetworkChaos experiments on one of the services that uses it, and then kill the pods for this service to see what happens if the Init Container has connection issues when communicating with the secrets manager.

Doing this throws these errors:
`pod not running`
`Internal error occurred: failed calling webhook "vpodnetworkchaos.kb.io": Post https://chaos-mesh-controller-manager.chaos.svc:443/validate-chaos-mesh-org-v1alpha1-podnetworkchaos?timeout=5s: context deadline exceeded`

Are these errors expected?
Is it possible to test Init Containers like this with Chaos Mesh?

Thanks!

**Comment by fewdan** [comment]
Yes, this is the expected result. If the pod is not in the running state, it is currently not possible to inject networkchaos.

**Comment by adbjo** [comment]
I this the expected result for other experiments as well? (StressChaos, TimeChaos, IOChaos, etc.)

**Comment by AsterNighT** [comment]
> Is this the expected result for other experiments as well? (StressChaos, TimeChaos, IOChaos, etc.)

AFAIK, Yes
