### ISSUE TITLE
execute `go mod tidy` with e2e-test and api/v1alpha1 during make check

### ISSUE THREAD

**Issue by STRRL** [chaos-mesh/chaos-mesh#1786]
currently, we have more than one go.mod file, and we should also cleanup these file during `make check`.

**Comment by STRRL** [comment]
We could lint like modifications in #1776

**Comment by DARK-art108** [comment]
Can I work on this? Please describe a little bit more, What we need to achieve!

**Comment by STRRL** [comment]
Hi @DARK-art108, I have resolved that lint issue by https://github.com/chaos-mesh/chaos-mesh/pull/1823, and I forgot to close this issue. 😅

I am going to close it now, if you have any brilliant ideas or other questions, feel free to reopen it! 😁
