### ISSUE TITLE
Add auth check for nirvana controller

### ISSUE THREAD

**Issue by YangKeao** [chaos-mesh/chaos-mesh#1794]
As described in the code, please add auth check for `Schedule` object.

```go
// TODO: check the auth
// The resouce will be created by the SA of controller-manager, so checking the auth of Schedule is needed.
if chaosKind == v1alpha1.KindSchedule {
    return admission.Allowed("")
}
```

**Comment by STRRL** [comment]
I think we'd better create an Interface like:

```go
type AffectedInterfaceAuditable interface {
	RequireClusterPrivileges() bool
	AffectedNamespaces() []string
}
```

And implement this interface for each chaos, schedule, and workflow kind.

**Comment by YangKeao** [comment]
> I think we'd better create an Interface like:
> 
> ```go
> type AffectedInterfaceAuditable interface {
> 	RequireClusterPrivileges() bool
> 	AffectedNamespaces() []string
> }
> ```
> 
> And implement this interface for each chaos, schedule, and workflow kind.

Good! I will do it right now.
