### ISSUE TITLE
Implement migration script from `scheduler: ""` to `Schedule` object

### ISSUE THREAD

**Issue by YangKeao** [chaos-mesh/chaos-mesh#1821]
There is no more `scheduler` field in the specification of `*Chaos` object, so we need to add a script to migration from `scheduler:""` to `Schedule` object.

**Comment by AsterNighT** [comment]
Does this mean a bash script or sth to modify yaml?

**Comment by YangKeao** [comment]
> Does this mean a bash script or sth to modify yaml?

Yes. It should be done in 3 steps:

1. Download and modify all chaos with a scheduler into a `Schedule`
2. Apply new CRD
3. Apply new experiment definition.

**Comment by YangKeao** [comment]
@AsterNighT It seems that we should remove the CRD before applying the new one, because `.spec.names.kind` field is immutable.

![图片](https://user-images.githubusercontent.com/5244316/120973644-c98c2880-c7a1-11eb-9ddd-cba66c9a4ebb.png)

**Comment by AsterNighT** [comment]
BTW, are we still planning to provide a script to fetch all resources from the cluster, update them and reapply them?

**Comment by YangKeao** [comment]
> 
> 
> BTW, are we still planning to provide a script to fetch all resources from the cluster, update them and reapply them?

Yes. But may need to remove the CRD and apply new CRD (but not only update the CRD).

**Comment by AsterNighT** [comment]
> > BTW, are we still planning to provide a script to fetch all resources from the cluster, update them and reapply them?
> 
> Yes. But may need to remove the CRD and apply new CRD (but not only update the CRD).

Remove and reapply seems easy. I'll look into how to do the fetch&apply part.

**Comment by STRRL** [comment]
closed by #1938
