### ISSUE TITLE
use chart-0.5.0 to upgrade chaos-mesh 1.2.0，controller-manager and dashboard crash

### ISSUE THREAD

**Issue by lcwus2** [chaos-mesh/chaos-mesh#1834]
## Bug Report

**What version of Kubernetes are you using?**

v1.18.9

**What version of Chaos Mesh are you using?**

1.1.4 - 1.2.0

**What did you do?**

download chart 1.2.0 in local，and upgrade `helm upgrade chaos-mesh helm/chaos-mesh --namespace=chaos-testing -f helm/chaos-mesh/values.yaml`

**What did you expect to see?**

**What did you see instead?**
controller-manager’s log：
![image](https://user-images.githubusercontent.com/30100640/118087435-25a89a80-b3f8-11eb-8ea3-f26f9fb5ef88.png)

**Output of chaosctl**

**Comment by AsterNighT** [comment]
Would you try running
```
kubectl get crd
```

**Comment by fewdan** [comment]
It seems that the crd of "awschaos" is missing, you can update the crd.

**Comment by lcwus2** [comment]
> It seems that the crd of "awschaos" is missing, you can update the crd.

use chart to update, but containing no crd update?

**Comment by AsterNighT** [comment]
FYI, check https://github.com/helm/helm/issues/6581
