### ISSUE TITLE
Seeing error.api.no_cluster_privilege: can't list resource in the cluster when "All" is selected in "Choose namespace"

### ISSUE THREAD

**Issue by alperkokmen** [chaos-mesh/chaos-mesh#1838]
## Bug Report

**What version of Kubernetes are you using?**
```
❯ kubectl version --short
Client Version: v1.19.0
Server Version: v1.18.9-eks-d1db3c
```

**What version of Chaos Mesh are you using?**
1.2.0

**What did you do?**
I installed chaos-mesh by running the install script with `--template` option and then making some changes to use `CLUSTER_MODE=false`. Dashboard and controller started up fine; but, then in the dashboard UI, I keep getting failed XHR requests (401) and an error message when "All" is selected from the namespaces dropdown.

<img width="553" alt="image" src="https://user-images.githubusercontent.com/1657578/118206187-d2921000-b416-11eb-8227-e2cf763de0e4.png">

It seems like `All` is always present in that dropdown.
https://github.com/chaos-mesh/chaos-mesh/blob/5f6c2f0ede375ee057d7375532b5e2b853910280/ui/src/components/TopContainer/Namespace.tsx#L48-L52

I was not expecting an error by default when `All` is selected from the dropdown. Alternatively, maybe `All` shouldn't be there when `CLUSTER_SCOPED=false` and there is a `TARGET_NAMESPACE` set. excerpt from my `chaos-dashboard` `env` –

```
                {
                  name: 'CLUSTER_SCOPED',
                  value: 'false',
                },
                {
                  name: 'TARGET_NAMESPACE',
                  value: config.ChaosMesh.TargetNamespace,
                },
```

Here's the response for the XHR request from the web UI –
```json
{
    "message": "error.api.no_cluster_privilege: can't list resource in the cluster",
    "code": "error.api.no_cluster_privilege",
    "full_text": "error.api.no_cluster_privilege: can't list resource in the cluster\n at github.com/chaos-mesh/chaos-mesh/pkg/apiserver/utils.AuthRequired()\n\t/mnt/pkg/apiserver/utils/auth.go:64\n at github.com/gin-gonic/gin.(*Context).Next()\n\t/tmp/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161\n at github.com/chaos-mesh/chaos-mesh/pkg/apiserver/utils.MWHandleErrors.func1()\n\t/mnt/pkg/apiserver/utils/error.go:50\n at github.com/gin-gonic/gin.(*Context).Next()\n\t/tmp/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161\n at github.com/gin-gonic/gin.RecoveryWithWriter.func1()\n\t/tmp/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/recovery.go:83\n at github.com/gin-gonic/gin.(*Context).Next()\n\t/tmp/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161\n at github.com/gin-gonic/gin.LoggerWithConfig.func1()\n\t/tmp/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/logger.go:241\n at github.com/gin-gonic/gin.(*Context).Next()\n\t/tmp/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161\n at github.com/gin-gonic/gin.(*Engine).handleHTTPRequest()\n\t/tmp/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/gin.go:409\n at github.com/gin-gonic/gin.(*Engine).ServeHTTP()\n\t/tmp/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/gin.go:367\n at net/http.serverHandler.ServeHTTP()\n\t/usr/local/go/src/net/http/server.go:2843\n at net/http.(*conn).serve()\n\t/usr/local/go/src/net/http/server.go:1925\n at runtime.goexit()\n\t/usr/local/go/src/runtime/asm_amd64.s:1374",
    "status": "error"
}
```

Here's the full `chaos-mesh-chaos-controller-manager-cluster-level`.
```
  {
    kind: 'ClusterRole',
    apiVersion: 'rbac.authorization.k8s.io/v1',
    metadata: {
      name: 'chaos-mesh-chaos-controller-manager-cluster-level',
      labels: {
        'app.kubernetes.io/name': 'chaos-mesh',
        'app.kubernetes.io/instance': 'chaos-mesh',
        'app.kubernetes.io/component': 'controller-manager',
      },
    },
    rules: [
      {
        apiGroups: [
          '',
        ],
        resources: [
          'nodes',
          // NOTE: entries below are commented out because we are deploying in CLUSTER_SCOPED=false.
          // 'namespaces',
          // 'services',
        ],
        verbs: [
          'get',
          'list',
          'watch',
        ],
      },
      {
        apiGroups: [
          'authorization.k8s.io',
        ],
        resources: [
          'subjectaccessreviews',
        ],
        verbs: [
          'create',
        ],
      },
    ],
  }
```

**Comment by AsterNighT** [comment]
@g1eny0ung PTAL

**Comment by g1eny0ung** [comment]
After debugging, I think this behavior is a bug. I will remove the `All` option when the `targetNamespace` is set.

**Comment by g1eny0ung** [comment]
Finally, after discussing with @WangXiangUSTC, we found that it's related to:

https://github.com/chaos-mesh/chaos-mesh/blob/master/pkg/apiserver/experiment/experiment.go#L904

When `clusterScoped = false`, the `listExperiments` API will automatically set the `namespace` by `TargetNamespace` when the namespace query is undefined.

We will unify this behavior in this function: https://github.com/chaos-mesh/chaos-mesh/blob/master/pkg/apiserver/utils/auth.go#L26
