### ISSUE TITLE
nirvana: waitForApplySync and waitForRecoverSync should be a part of API

### ISSUE THREAD

**Issue by STRRL** [chaos-mesh/chaos-mesh#1839]
Hi @YangKeao, I noticed that there are some extra `v1alpha1.Phase` declared in the package `controllers`:

https://github.com/chaos-mesh/chaos-mesh/blob/cae993e2ddc4078b03fd8ad18419fbbdd63feabc/controllers/chaosimpl/networkchaos/partition/impl.go#L50-L53

https://github.com/chaos-mesh/chaos-mesh/blob/cae993e2ddc4078b03fd8ad18419fbbdd63feabc/controllers/chaosimpl/networkchaos/trafficcontrol/impl.go#L45-L48

It should be a part of API definition, how about moving them into `api/v1alpha1`?

If you say yes, I could make a PR for that.

**Comment by AsterNighT** [comment]
Hmm yes, I suppose `httpchaos` will need this mechanism, too.
