### ISSUE TITLE
helm upgrade: helm upgrade does NOT update the CRD 

### ISSUE THREAD

**Issue by STRRL** [chaos-mesh/chaos-mesh#1849]
## Feature Request

**Is your feature request related to a problem? Please describe:**

Bug reported by @g1eny0ung , when he upgrades the chaos mesh by `helm upgrade`, the CRD is not updated automatically. 

> And we update the Status in workflow/workflownode to be SubResource, if CRD is not updated, the controller-manager was stuck in updating status subresource with log "can not found "${workflow-name}"".

**Describe the feature you'd like:**

So is there a way to let helm upgrade could update the CRD as well? 👍

Or we need to write another script and mention it in the document. 👎

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by g1eny0ung** [comment]
Related to https://github.com/helm/helm/issues/6581.

**Comment by FuyuanChu** [comment]
@g1eny0ung should chaos-mesh controller manage CRDs' lifecycle since helm only set up initial CRDs to ensure that CRs in charts are installed successfully.

**Comment by YangKeao** [comment]
A better way is to manage the version of CRDs: start moving forwards from v1alpha1...
