### ISSUE TITLE
User's token expired, and the user can't change it. 

### ISSUE THREAD

**Issue by Muscule** [chaos-mesh/chaos-mesh#1851]
## Bug Report

**What version of Kubernetes are you using?**
OpenShift 4.7.0

**What version of Chaos Mesh are you using?**
1.2.0

**What did you do?**
I press "-" near the token. Chaos-Mesh installed with the help of helm.
**What did you expect to see?**
User was deleted.
**What did you see instead?**
Nothing happened. User's token expired, and the user can't change it.

**Comment by AsterNighT** [comment]
PTAL @g1eny0ung ,check https://github.com/chaos-mesh/chaos-mesh/discussions/1846 for a screenshot

**Comment by Muscule** [comment]
Installed 1.2.1. Nothing changed - can't remove user with the help of dashboard.

**Comment by g1eny0ung** [comment]
> Installed 1.2.1. Nothing changed - can't remove user with the help of dashboard.

I test in my local and can't reproduce this situation. Would u mind open a thread in our slack channel to provide some screenshots so I can determine the problem more accurately?

**Comment by Muscule** [comment]
> > Installed 1.2.1. Nothing changed - can't remove user with the help of dashboard.
> 
> I test in my local and can't reproduce this situation. Would u mind open a thread in our slack channel to provide some screenshots so I can determine the problem more accurately?

Sorry. I chose wrong version to test. It is reakky fixed.

**Comment by g1eny0ung** [comment]
> > > Installed 1.2.1. Nothing changed - can't remove user with the help of dashboard.
> > 
> > 
> > I test in my local and can't reproduce this situation. Would u mind open a thread in our slack channel to provide some screenshots so I can determine the problem more accurately?
> 
> Sorry. I chose wrong version to test. It is really fixed.

Never mind. 😆
