### ISSUE TITLE
Cannot list resource in API group

### ISSUE THREAD

**Issue by nupur2030** [chaos-mesh/chaos-mesh#1869]
## Bug Report

**What version of Kubernetes are you using?**
Server Version: v1.16.15-eks-ad4801

**What version of Chaos Mesh are you using?**
chaos version 3.x

**What did you see instead?**
cannot list resource in API resource

Please refer below snapshot

**Output of chaosctl**

![image](https://user-images.githubusercontent.com/31813709/118968737-d84f9e80-b99e-11eb-976b-157e651e3334.png)
![image](https://user-images.githubusercontent.com/31813709/118970008-55c7de80-b9a0-11eb-8ec5-87bd59313e43.png)

**Comment by fewdan** [comment]
Please tell the information about how do you fill in the "duration" field?

**Comment by nupur2030** [comment]
Thanks fewdan,

We have regenerated new token with cluster scope and now i am facing another issue #1874 
and in duration i am giving 10s
https://github.com/chaos-mesh/chaos-mesh/issues/1874

**Comment by fewdan** [comment]
@nupur2030 
Understand, let me look at #1874.
