### ISSUE TITLE
TLS bad Certificate 

### ISSUE THREAD

**Issue by nupur2030** [chaos-mesh/chaos-mesh#1874]
## Bug Report

**What version of Kubernetes are you using?**

Server Version: v1.16.15-eks-ad4801

**What version of Chaos Mesh are you using?**

chaos version 3.x
**What did you do?**

While clicking submit experiment on chaos-dashboard

**What did you see instead?**
certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "chaos-mesh-ca")

**Output of chaosctl**

![image](https://user-images.githubusercontent.com/31813709/119113560-cc73e300-ba57-11eb-8700-bffb7485a22b.png)

**please revert and thanks in advance :)**

**Comment by fewdan** [comment]
How did you install chaos-mesh? If it is installed via helm, you can try "helm upgrade".

**Comment by nupur2030** [comment]
Does helm upgrade require administrative role? i am unable to upgrade

**Comment by fewdan** [comment]
> Does helm upgrade require administrative role? i am unable to upgrade

@nupur2030 
I'm sorry to reply you so late. Could you tell me how you installed it before? If it can be installed, the updated permissions are also possible.
