### ISSUE TITLE
magic value "managed-by" in api/v1aplha1

### ISSUE THREAD

**Issue by STRRL** [chaos-mesh/chaos-mesh#1930]
here is a magic value "managed-by" at controllers/schedule/cron/controller.go:149, it will be used for listing children elements. It's better to use const.

**Comment by fewdan** [comment]
In the schedule part of the dashboard, I also used "managed-by". If we want to modify it, we have to deal with it together.

**Comment by Shatakshi0805** [comment]
Hello @STRRL. I would like to take up this issue. I am currently new to Chaos Mesh but really want to contribute. Could you please tell if I have to replace `managed-by` in controller.go with `const` ?

**Comment by STRRL** [comment]
> Could you please tell if I have to replace `managed-by` in controller.go with `const` ?

Yes! :)

**Comment by Shatakshi0805** [comment]
Thanks for replying. I would like to take this issue. Please assign this to me.

**Comment by Shatakshi0805** [comment]
Thanks for replying. Just want to know as I'm a bit confused do I have to change "managed-by" in all the files that exist in api/v1alpha1 folder as well?
