### ISSUE TITLE
Provider Docker arm64 image on each release

### ISSUE THREAD

**Issue by nlamirault** [chaos-mesh/chaos-mesh#1955]
## Feature Request

**Is your feature request related to a problem? Please describe:**

**Describe the feature you'd like:**

Provide a Docker image for arm64 platform on each release.
There is only a Docker image named `latest-arm` https://registry.hub.docker.com/layers/pingcap/chaos-mesh/latest-arm/images/sha256-a6c497eb81f9284b352611cca5e1df6c6d941dc73daf33662c57b23800042c64?context=explore

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by nlamirault** [comment]
any news ?

**Comment by YangKeao** [comment]
I will work on this issue. Some dependencies have provided an arm64 binary, so it wouldn't be too difficult to build an arm image.

**Comment by nlamirault** [comment]
Great ! @YangKeao

**Comment by nlamirault** [comment]
@YangKeao Do you know when new Docker images will be available ? on next release ?

**Comment by YangKeao** [comment]
> @YangKeao Do you know when new Docker images will be available ? on next release ?

 For release version,  yes, the next release (in one or two weeks, I think) will include an arm image.

Meanwhile, the (nightly built) arm docker image has already been available on `ghcr.io/chaos-mesh/chaos-mesh`, like `ghcr.io/chaos-mesh/chaos-mesh/chaos-mesh:latest` and `ghcr.io/chaos-mesh/chaos-mesh/chaos-daemon:latest`... 

#2462 is to make them the default image of our helm chart.
