### ISSUE TITLE
cheat sheet of useful commands while developing

### ISSUE THREAD

**Issue by STRRL** [chaos-mesh/chaos-mesh#1963]
`Makefile` and other scripts under `/hack` are soo complicated! 

I always take a long time to find out the correct commands to compile binary,or run a specific e2e testcase. :cry: 

I want a `CHEATSHEET.MD` to introduce the commonly used commands while developing and testing.

**Comment by CIPHERTron** [comment]
Seems like this would be a great enhancement 😁 
I would love to work on it 🚀

**Comment by YangKeao** [comment]
If you need any help while reading the `Makefile`, feel free to contact me. 

The wild usage of `template` in `Makefile` has made it a little hard to understand.

**Comment by CIPHERTron** [comment]
> If you need any help while reading the `Makefile`, feel free to contact me.
> 
> The wild usage of `template` in `Makefile` has made it a little hard to understand.

Yeah, the `Makefile` is slightly perplexing but I'll reach out to you in case of any queries. Thank you @YangKeao 🙌🏻

**Comment by Garima-Negi** [comment]
Hi, is this issue still looking for assignees? I'd like to contribute.

**Comment by YangKeao** [comment]
> Hi, is this issue still looking for assignees? I'd like to contribute.

As @CIPHERTron doesn't proceed on this issue, I think YES.

And I also think it's a good time to start working on this issue, as the `Makefile` has been much shorter and easier to understand than one year ago :laughing: . If you need any help on understanding the `Makefile` or scripts in `hack/`, feel free to contact us under this issue or in the slack channel :beers:. I'll assign it to you.

**Comment by STRRL** [comment]
closed by #3888
