### ISSUE TITLE
Chaos Dashboard: can not show stress chaos as expected

### ISSUE THREAD

**Issue by STRRL** [chaos-mesh/chaos-mesh#1992]
## Bug Report

**What version of Kubernetes are you using?**

```
k version                          
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:18:45Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:20:00Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```

**What version of Chaos Mesh are you using?**

fork & branch: https://github.com/g1eny0ung/chaos-mesh/tree/nirvana-ui  
commit: ead62cd49a458b5eb698ce49ce193fcf7611cc2a

**What did you do?**

- startup chaos mesh on minikube 
- `k apply -f ./examples/burn-cpu.yaml`

**What did you expect to see?**

Could view stress chaos on dashboard.

**What did you see instead?**

I could see that experiment when listing experiment, but I can not access the detail.

![image](https://user-images.githubusercontent.com/20221408/122406775-b0f6ec00-cfb3-11eb-8a94-eee858e3fcd5.png)

![image](https://user-images.githubusercontent.com/20221408/122406654-96bd0e00-cfb3-11eb-9b83-31cb311b297e.png)

**Output of chaosctl**

**Comment by g1eny0ung** [comment]
Fixed in 895e2da.
