### ISSUE TITLE
I want see controlled Experiment when I viewing Schedule

### ISSUE THREAD

**Issue by STRRL** [chaos-mesh/chaos-mesh#1993]
## Feature Request

**Is your feature request related to a problem? Please describe:**

No.

**Describe the feature you'd like:**

I want to see the "Experiment" created (also controlled/managed) by certain "Schedule" when I viewing at the "Schedule" page.

Also, I want to see the parent "Schedule" when I viewing at the "Experiment"(If this "Experiment" has one parent).

Also, this feature could be applied to Workflow. :D

**Describe alternatives you've considered:**

No.

**Teachability, Documentation, Adoption, Migration Strategy:**

The relationship between "Schedule" and managed "Experiement" is introduced as label "managed-by":

https://github.com/chaos-mesh/chaos-mesh/blob/d343189d3ccb6e882720461903084fa8f84cc417/controllers/schedule/cron/controller.go#L148-L150
https://github.com/chaos-mesh/chaos-mesh/blob/d343189d3ccb6e882720461903084fa8f84cc417/controllers/schedule/utils/list.go#L39-L44

We could list controlled "Experiment" by this label and given "Schdule" name, and also could find the "parnet" Schedule by this label on the "Experiment".

Workflow also have a similar lable called "controlled-by", I think we should unify these at first. Then we could build this requested feature.

Alternative solution: find "Experiments" by event on "Schedule":

We have related events when "Schedule" spawning managed "Chaos", but these events might be aggregated, so we are not able to find out the specific managed "Chaos Experiement".

Actually I think this is a bad idea.

**Comment by YangKeao** [comment]
Actually, the `active` in the `.Status` of a `Schedule` introduces which experiments are managed by it.

**Comment by STRRL** [comment]
> Actually, the `active` in the `.Status` of a `Schedule` introduces which experiments are managed by it.

Oh, I get that. That field is maintained by "active controller" and ActiveLister, it could stay in sync with the controlled Experiment.

Which way is preferred to use for you? use label selector "managed-by" or use `Status.Active`? @YangKeao

**Comment by STRRL** [comment]
As https://github.com/chaos-mesh/chaos-mesh/pull/2002 has been merged, events will not be aggregated anymore. I am going to close this issue.
