### ISSUE TITLE
We need use upper case with some name of chaos

### ISSUE THREAD

**Issue by STRRL** [chaos-mesh/chaos-mesh#2014]
## Question

As https://github.com/golang/go/wiki/CodeReviewComments#initialisms says, we should keep the consistent case with words: AWS, GCP, etc. And we have rename `IoChaos` to `IOChaos`

Related chaos:

- AwsChaos -> AWSChaos
- GcpChaos -> GCPChaos

**Comment by STRRL** [comment]
PTAL @fewdan

**Comment by fewdan** [comment]
I agree with you that we should keep the naming style consistent.
