### ISSUE TITLE
Hi I am Unable to launch dashboard for Chos Mesh i ran the command  # kubectl port-forward -n chaos-testing svc/chaos-dashboard 2333:2333 bt it is stck over here only not able to access through http://localhost:2333/

### ISSUE THREAD

**Issue by Bhumika1997** [chaos-mesh/chaos-mesh#2019]
### Discussed in https://github.com/chaos-mesh/chaos-mesh/discussions/1333

<div type='discussions-op-text'>

<sup>Originally posted by **satya-h** December 28, 2020</sup>
Hi, 
I am trying to use chaos-mesh for our project. I followed the steps given in documents. It has been installed successfully. All daemon, dashboard, controller pods are in running state. But when I hit the dashboard url it is redirecting to /dashboard url. 
It is showing as /dashboard url is not available in server. 

#I am not allowed to share any screenshots as per our company policy. 

Kindly help me</div>

**Comment by fewdan** [comment]
What is your version of kubernetes and chaos-mesh? Are all pods running normally now?

**Comment by Bhumika1997** [comment]
> What is your version of kubernetes and chaos-mesh? Are all pods running normally now?

![image](https://user-images.githubusercontent.com/33874082/123203397-ea5bba00-d4d3-11eb-8fe5-2969bb8b66c4.png)
![image](https://user-images.githubusercontent.com/33874082/123203498-1b3bef00-d4d4-11eb-9a88-5ea9d822d158.png)

**Comment by fewdan** [comment]
Would you please provide the log of "chaos-controller-manager-7bbxxxxx" ?  In the log of "controller-manager" you can see the version of chaos-mesh. 

And would you please provide the log of "chaos-dashboard" too ? 

You can get the log by "kubectl logs chaos-controller-manager-xxxx -n your-namespace "  .

**Comment by Bhumika1997** [comment]
Chaos-controller manager logs:
![image](https://user-images.githubusercontent.com/33874082/123236493-78e33200-d4fa-11eb-8a94-2a4c57583b9f.png)

Chaos dashboard logs

**Comment by fewdan** [comment]
From the log, it seems that the "2333" port is not monitored. Did you "ctrl+c" directly after kubectl portforward?

You can try "kubectl portforward" and press nothing, then visit "localhost:2333" to try?

**Comment by Bhumika1997** [comment]
> From the log, it seems that the "2333" port is not monitored. Did you "ctrl+c" directly after kubectl portforward?
> 
> You can try "kubectl portforward" and press nothing, then visit "localhost:2333" to try?
I tried but no luck 

![image](https://user-images.githubusercontent.com/33874082/123367864-5acc0f00-d598-11eb-9e56-e99739766701.png)
![image](https://user-images.githubusercontent.com/33874082/123367895-661f3a80-d598-11eb-80c9-c70e12ab4cc3.png)
![image](https://user-images.githubusercontent.com/33874082/123367937-7afbce00-d598-11eb-9aa0-dff75f76a947.png)

**Comment by STRRL** [comment]
it seems you execute `kubectl port-forward` on the remote host called `kmaster`, and open browser on your windows. :cold_sweat: 

you should use `kubectl port-forward --address=0.0.0.0` and visit `<ip-of-kmaster>:2333` instead.

**Comment by Bhumika1997** [comment]
> it seems you execute `kubectl port-forward` on the remote host called `kmaster`, and open browser on your windows. 😰
> 
> you should use `kubectl port-forward --address=0.0.0.0` and visit `<ip-of-kmaster>:2333` instead.

It worked fine now.
Thanku so much for your help @STRRL
