### ISSUE TITLE
网络分区混沌场景，在第一次注入的时候，会告诉那个是source pod，那个是target pod，第二次注入之后，只能看到target pod

### ISSUE THREAD

**Issue by teachersun** [chaos-mesh/chaos-mesh#2032]
chaosmesh版本：v1.2.0
kubernetes版本：1.21.0
使用的yaml文件如下
apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: network-partition-example
  namespace: test
spec:
  action: partition
  mode: one
  selector:
    labelSelectors:
      "app": "zzweb"
  direction: to
  target:
    selector:
      namespaces:
        - test
      labelSelectors:
        "app": "zzweb"
    mode: one
  duration: "300s"
  scheduler:
    cron: "@every 600s"

**Comment by STRRL** [comment]
我注意到你的 selector 与 target selector 是相同的，而且都为 mode: one，发生这种情况的可能是因为两个 selector 都选中了同一个 pod。

在 source 和 target 都为同一个 pod 的这种情况下，网络分区其实是不会生效的，从直觉上来说你无法对一个节点自己网络分区自己，而且同一个 pod 内的网络通信 **一般** 都会通过 loopback 网卡。
