### ISSUE TITLE
Chaos Dashboard: misordering of schedule object from API

### ISSUE THREAD

**Issue by cwen0** [chaos-mesh/chaos-mesh#2035]
## Bug Report

**What version of Kubernetes are you using?**
 

v1.17.2

**What version of Chaos Mesh are you using?**
 

v2.0.0.beta.1

**What did you do?**
 

Create many schedule objects 

**What did you expect to see?**

The schedule objects from API is ordered by "create time"

**What did you see instead?** 

![image](https://user-images.githubusercontent.com/22956341/123375289-1867f980-d5bb-11eb-8d69-db04092edb2f.png)

**Output of chaosctl**

**Comment by fewdan** [comment]
Okay, I will deal with this problem.
