### ISSUE TITLE
why the experiment in gke chaos-mesh that didn't work

### ISSUE THREAD

**Issue by jj891070** [chaos-mesh/chaos-mesh#2038]
### My gke version: 1.19.10-gke.1600

* I install chaos-mesh seems ok
`
$ curl -sSL https://mirrors.chaos-mesh.org/v1.2.1/install.sh | bash
`

* But running this experiment([official example](https://chaos-mesh.org/docs/user_guides/run_chaos_experiment)) 
`
$ curl -sSL https://mirrors.chaos-mesh.org/v1.2.1/web-show/deploy.sh | bash
`

* but the dashboard show this error([error image](https://storage.googleapis.com/test-audere-lab/problem.png)) 
`
 An error occurred: admission webhook "vpodnetworkchaos.kb.io" denied the request: rpc error: code = Unknown desc = expected docker:// but got container
`

**Comment by cwen0** [comment]
@jj891070 Hi, the container runtime of your GKE cluster is not docker. Can you make sure what container runtime you are using? At present, Chaos Mesh supports `docker`, `containerd` and `cri-o`, but which need to be configured when to install.  

```
curl -sSL https://mirrors.chaos-mesh.org/v1.2.1/install.sh | bash -s -- -r containerd 
``` 
If you want to use helm, you can refer to this document https://chaos-mesh.org/docs/user_guides/installation#step-2-install-chaos-mesh.

**Comment by jj891070** [comment]
* Hello @cwen0.  Thanks, It's worked.
* But the experiment is still not working. I found the error log from chaos-controller-manager([error image](https://storage.googleapis.com/test-audere-lab/problem2.png))
`
got runtime.Object without object metadata
`

**Comment by cwen0** [comment]
> * Hello @cwen0.  Thanks, It's worked.
> * But the experiment is still not working. I found the error log from chaos-controller-manager([error image](https://storage.googleapis.com/test-audere-lab/problem2.png))
>   `got runtime.Object without object metadata`

@jj891070 Can you provide more logs and check the if admission webhook is enabled in your environment?

**Comment by jj891070** [comment]
Thanks @cwen0. It's like you said it's not enabled, how do I enable admission webhook on gke(v1.19.10-gke.1600)?

* this is chaos-controller-manager error message ([error image](https://storage.googleapis.com/test-audere-lab/chaos-controller-manager.png))

* this is chaos-dashboard error message ([error image](https://storage.googleapis.com/test-audere-lab/chaos-dashboard.png))

**Comment by cwen0** [comment]
@jj891070 https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#how-do-i-turn-on-an-admission-controller You can refer to this document. `ValidatingAdmissionWebhook` and `MutatingAdmissionWebhook` are required by Chaos Mesh.

**Comment by YangKeao** [comment]
It seems that at beginning it's enabled (as it's reported that `admission webhook "vpodnetworkchaos.kb.io" denied the request`),  but why it's disabled later?

**Comment by shawnho1018** [comment]
@jj891070  I could successfully execute it in gke v1.19.10. I encountered your earlier problem since I didn't apply the containerd crd correctly. (I do think the document could be improved a bit to make it more explicit). I found if you apply any networkChaos earlier, those objects will stuck and cannot be removed. I manually edit the object to have it removed (by removing its finalizer value). 
![network chaos in GKE](https://user-images.githubusercontent.com/28553789/125764005-d33b295a-47f8-410b-ab90-4eb0db523d60.png)

**Comment by Hawachurl** [comment]
I am using chaos-dashboard to run this experiment and had same issue.
Installing chaos-mesh in containerd environment fixed the problem for me.

Or so I thought.
The experiment runs without any error but I do not see any change in web-show:
![image](https://user-images.githubusercontent.com/86557959/125869827-c877c267-fb1e-4f61-8626-0266445f7021.png)

I am using the same configuration file as defined [here](https://chaos-mesh.org/docs/user_guides/run_chaos_experiment#step-2-define-the-experiment-configuration-file).

Is there anything that I am missing here?

**Comment by jj891070** [comment]
It's work.
I change the official yaml provided, it does not bring the value into the --target-ip. But I don't know where it will call for the empty value and how to generate the graphs.
![Screen Shot 2021-07-20 at 10 48 22 AM](https://user-images.githubusercontent.com/25993190/126255185-b50e06ea-a359-4c08-9314-83cd5effef0e.png)
