### ISSUE TITLE
Unable to view any Labels in the Dashboard

### ISSUE THREAD

**Issue by Prashanth-BP** [chaos-mesh/chaos-mesh#2057]
Hi Team,
I work on a client project and we have installed the Chaos Mesh on the EKS cluster. There are many namespaces however, we have installed the tool on a NS Called "Services". When we login to the Dashboard, we see the labels and the pods available only under the "Services" Namespace however, we Do not see any Labels or Pod in any other NS and the drop down is blank. We are not able to run any experiments from the Dashboard as we are unable to see the Labels or Select the Pods. Any help would be highly appreciated. Unfortunately, I can't attach any screenshots as per the client security procedures. 

Regards,
Prashanth

**Comment by fewdan** [comment]
Hello,
When you use the dashboard, did you specify "ClusterScoped"? If there is no special instructions, "ClusterScoped" is turned on by default. Then another question is, when you use the dashboard, does the token you fill in meet the requirements?

**Comment by Prashanth-BP** [comment]
Hi, Thanks for getting back to us. The issue is resolved. We realized that we were using an old image that we deployed in our env few months ago. We used the latest helm available on your repository and that sorted everything. Thanks again. However, the above two points you asked will be saved for our future reference incase we have any issues.

**Comment by Prashanth-BP** [comment]
Thanks. Appreciate your quick response.
