### ISSUE TITLE
create workflow failed: no such table: workflow_entities

### ISSUE THREAD

**Issue by WangXiangUSTC** [chaos-mesh/chaos-mesh#2077]
## Bug Report

**What version of Chaos Mesh are you using?**

d69a37e63aef9296b73b9072089f4be813e6f654

**What did you do?**

create a workflow, and click it to see the detail.

**What did you expect to see?**
can see the detail

**What did you see instead?**

dashboard report a error: error.api.internal_server_error: no such table: workflow_entities

And can see the error log in dashboard:
```log
Error #01: error.api.internal_server_error: no such 
table: workflow_entities

(/mnt/pkg/store/workflow/workflow.go:80) 
[2021-07-06 03:05:48]  no such table: workflow_entities 
```

**Comment by STRRL** [comment]
It might be caused by the outdated Chaos Mesh Dashboard docker image. Please recompile and rebuild the image of Chaos Mesh Dashboard, then take a retry. :)
