### ISSUE TITLE
[Node] Kubernetes Worker Node Level Experiments for Azure based Kubernetes Deployments

### ISSUE THREAD

**Issue by chirangaalwis** [chaos-mesh/chaos-mesh#2084]
## Feature Request

**Is your feature request related to a problem? Please describe:**
Missing Node level experiments for Azure based Kubernetes deployments

**Describe the feature you'd like:**
This is for requesting Kubernetes Worker Node level experiments for Azure based Kubernetes deployments (e.g. in [AKS](https://azure.microsoft.com/en-us/services/kubernetes-service/)).

The feature should be similar to the already available feature for [AWS](https://chaos-mesh.org/docs/chaos_experiments/awschaos_experiment/).

**Comment by STRRL** [comment]
hi @fewdan, how's going on? :D

**Comment by chirangaalwis** [comment]
Hi folks, any update on this?

**Comment by STRRL** [comment]
> Hi folks, any update on this?

This feature is not going to be introduced with release v2.1 recently. I think we could finish that in the next ongoing release, v2.2.
I am sorry for that message.

**Comment by STRRL** [comment]
closed by https://github.com/chaos-mesh/chaos-mesh/pull/2821
