### ISSUE TITLE
PSP RoleBinding has hardcoded namespace

### ISSUE THREAD

**Issue by Niksko** [chaos-mesh/chaos-mesh#2095]
## Bug Report

**What did you do?**
Install chaos mesh with `--set chaosDaemon.podSecurityPolicy=true`, setting the target namespace as `chaos-mesh`.

**What did you expect to see?**

Helm chart installs properly

**What did you see instead?**

Error message from helm controller: `Helm upgrade failed: failed to create resource: namespaces "chaos-testing" not found`

This occurs because of the following chart configuration: https://github.com/chaos-mesh/chaos-mesh/blob/0ff6d685c98b2302ea28ae01f465eedd0aef583b/helm/chaos-mesh/templates/chaos-daemon-rbac.yaml#L19

The namespace of the PSP rolebinding is hardcoded to `chaos-testing`. This should either be configurable via `values.yaml`, or should just be set to the global `.Release.Namespace`

**Comment by fewdan** [comment]
Yes, I think it is more reasonable to set it to ".Release.Namespace".  We will modify "chaos-mesh/helm/chaos-mesh/templates/chaos-daemon-rbac.yaml".

**Comment by Niksko** [comment]
I'm happy to provide a PR
