### ISSUE TITLE
Upgrade admission webhook API version 

### ISSUE THREAD

**Issue by cwen0** [chaos-mesh/chaos-mesh#2100]
## Feature Request

**Is your feature request related to a problem? Please describe:**
 

Get some `Warning when installing Chaos Mesh by Helm or `install.sh`:

```
Warning: admissionregistration.k8s.io/v1beta1 MutatingWebhookConfiguration is deprecated in v1.16+, unavailable in v1.22+; use admissionregistration.k8s.io/v1 MutatingWebhookConfiguration
mutatingwebhookconfiguration.admissionregistration.k8s.io/chaos-mesh-mutation created
Warning: admissionregistration.k8s.io/v1beta1 ValidatingWebhookConfiguration is deprecated in v1.16+, unavailable in v1.22+; use admissionregistration.k8s.io/v1 ValidatingWebhookConfiguration
```

**Describe the feature you'd like:**
  

We should upgrade the admission webhook from `admissionregistration.k8s.io/v1beta1` to `admissionregistration.k8s.io/v1`

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by STRRL** [comment]
related issue and pr:

- #2179
- #2193 
- #1558

**Comment by agilob** [comment]
Will this make chaos-mesh more disposable on a single cluster? Currently it's not possible to install, uninstall and install again it creates cluster wide objects:

>│ error": "Helm install failed: rendered manifests contain a resource that already exists. Unable to continue with install: MutatingWebhookConfiguration \"chaos-mesh-mutation\" in namespace \"\" exists and cannot be  │
│ imported into the current release: invalid ownership metadata; annotation validation error: key \"meta.helm.sh/release-namespace\" must equal \"chaos-mesh\": current value is \"cranky-visvesvaraya-08\""}

validating and mutating webhooks need to be removed manually (or automated ofc) before installation.

**Comment by STRRL** [comment]
> Will this make chaos-mesh more disposable on a single cluster? Currently it's not possible to install, uninstall and install again it creates cluster wide objects:
> 
> > │ error": "Helm install failed: rendered manifests contain a resource that already exists. Unable to continue with install: MutatingWebhookConfiguration "chaos-mesh-mutation" in namespace "" exists and cannot be  │
> > │ imported into the current release: invalid ownership metadata; annotation validation error: key "meta.helm.sh/release-namespace" must equal "chaos-mesh": current value is "cranky-visvesvaraya-08""}
> 
> validating and mutating webhooks need to be removed manually (or automated ofc) before installation.

No. 

I think the lack of documents about uninstalling Chaos Mesh is the reason for hard of uninstall/reinstall Chaos Mesh.

I would raise an issue for tracing that.

**Comment by STRRL** [comment]
closed by https://github.com/chaos-mesh/chaos-mesh/pull/2292
