### ISSUE TITLE
Create not allowed while CRD is terminating

### ISSUE THREAD

**Issue by gaoran10** [chaos-mesh/chaos-mesh#2109]
## Bug Report

**What version of Kubernetes are you using?**
```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:59:11Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.7", GitCommit:"4a4913e790a033f1101af2f0fb7be189b106e3ae", GitTreeState:"clean", BuildDate:"2021-05-25T17:37:03Z", GoVersion:"go1.15.12", Compiler:"gc", Platform:"linux/amd64"}
```

**What version of Chaos Mesh are you using?**
```
Controller manager Version: version.Info{GitVersion:"v1.2.2", GitCommit:"828bf42814704794fc55772b811bd31d53c99eb3", BuildDate:"2021-06-29T03:58:58Z", GoVersion:"go1.15.11", Compiler:"gc", Platform:"linux/amd64"}
```

**What did you do?**

I'm failed to create an experiment by chaos-mesh dashboard, when I click the submit button, it shows the error message `error.api.internal_server_error: create not allowed while custom resource definition is terminating`.

The runtime is containerd.

The components `chaos-daemon` and `chaos-controller-manager` are running.

**chaos-daemon logs**
```
Chaos-daemon Version: version.Info{GitVersion:"v1.2.2", GitCommit:"828bf42814704794fc55772b811bd31d53c99eb3", BuildDate:"2021-06-29T03:58:58Z", GoVersion:"go1.15.11", Compiler:"gc", Platform:"linux/amd64"}
2021-07-13T02:33:36.800Z INFO chaos-daemon grant access to /dev/fuse
2021-07-13T02:33:36.804Z INFO chaos-daemon-server Starting grpc endpoint {"address": "0.0.0.0:31767", "runtime": "containerd"}
2021-07-13T02:33:36.804Z INFO chaos-daemon-server Starting http endpoint {"address": "0.0.0.0:31766"}
```

**What did you expect to see?**

The experiment should be created successfully.

**Comment by cwen0** [comment]
@gaoran10 Can you check the status of CRD and make sure which CRD is terminating? `kubectl get crd | grep chaos`

**Comment by gaoran10** [comment]
I'm not sure about how to check the status of CRD, this is my chaos-mesh pods.

```
➜  charts git:(master) ✗ kubectl get pods -n chaos-testing
NAME                                      READY   STATUS    RESTARTS   AGE
chaos-controller-manager-777fd875-fxbt9   1/1     Running   0          2m46s
chaos-daemon-dblm7                        1/1     Running   0          2m47s
chaos-daemon-rmntk                        1/1     Running   0          2m47s
chaos-daemon-v2cmb                        1/1     Running   0          2m47s
chaos-dashboard-7b56cd6757-7zsfn          1/1     Running   0          2m46s
```

**Comment by cwen0** [comment]
@gaoran10 Can you check the status of networkchaos CRD object by `kubectl get crd networkchaos.chaos-mesh.org -o yaml`?

**Comment by gaoran10** [comment]
I create a new Kubernetes cluster in Azure, the chaos-mesh could work well.

I think maybe the un-cleared CRD caused this issue. At first, I create chaos-mesh by command `curl -sSL https://mirrors.chaos-mesh.org/v1.2.2/install.sh | bash`, but the runtime is not matched our environments, then I uninstall use command `curl -sSL https://mirrors.chaos-mesh.org/v1.2.2/install.sh | bash -s -- --template | kubectl delete -f -`, but this delete command isn't finished in normally. When I use the helm to install chaos-mesh, this issue appeared.

**Comment by fewdan** [comment]
> I create a new Kubernetes cluster in Azure, the chaos-mesh could work well.
> 
> I think maybe the un-cleared CRD caused this issue. At first, I create chaos-mesh by command `curl -sSL https://mirrors.chaos-mesh.org/v1.2.2/install.sh | bash`, but the runtime is not matched our environments, then I uninstall use command `curl -sSL https://mirrors.chaos-mesh.org/v1.2.2/install.sh | bash -s -- --template | kubectl delete -f -`, but this delete command isn't finished in normally. When I use the helm to install chaos-mesh, this issue appeared.

Judging from this information, it should be caused by the previous crd not being deleted cleanly.

**Comment by gaoran10** [comment]
@fewdan Yes, maybe the previous CRD didn't delete completely. I re-install the chaos-mesh and I didn't find this issue again. I close this issue first.
