### ISSUE TITLE
Dashboard becomes blank after creating schedule

### ISSUE THREAD

**Issue by FingerLeader** [chaos-mesh/chaos-mesh#2110]
## Bug Report

**What version of Kubernetes are you using?**
client:v1.21.2
server:v1.21.2

**What version of Chaos Mesh are you using?**
```
Controller manager Version: version.Info{GitVersion:"master-g2bc0fa81544659", GitCommit:"2bc0fa815446599852116ac0dfb612f659376745", BuildDate:"2021-07-12T09:58:17Z", GoVersion:"go1.15.11", Compiler:"gc", Platform:"linux/amd64"}
```

**What did you do?**
After creating a schedule, the whole page will be a blank, and go back also doesn't work. I must re-enter the address to see the dashboard. And I still can not get details after clicking the schedule I created.

**What did you expect to see?**
See the schedule page.

**Comment by cwen0** [comment]
@FingerLeader Can you provide the definition of the schedule object?

**Comment by STRRL** [comment]
Cause by the namething, https://github.com/chaos-mesh/chaos-mesh/blob/491fd55a66f51ec5d31ed9f1a62208b5e0b84efd/ui/src/components/ObjectConfiguration/index.tsx#L30.

It uses `toCamelCase()` for mapping from`TemplateType` to the field name in the spec:

`inSchedule` is `true`, and the `spec.type` is `IOChaos`, after mapping by `toCamelCase`, we get `iOChaos`, but the field name in spec is `ioChaos` which is expected.


To fix that quickly, I think we need a mapping that stores the `TemplateType` to the field name, but for the long future, we need the HTTP client with the schema that structs.

How do you think about it @g1eny0ung @fewdan ?
