### ISSUE TITLE
Installation of Chaos Mesh

### ISSUE THREAD

**Issue by Bhumika1997** [chaos-mesh/chaos-mesh#2128]
I am getting the status as pending and evicted while installing chaos mesh 
Can somebody help me on this?
NAME                                                                READY   STATUS    RESTARTS   AGE
chaos-controller-manager-54c8b4479-dj7gw   0/1     Pending   0          7m13s
chaos-daemon-nhv66                                        0/1     Evicted   0          2m51s

Before asking a question, make sure you have:

- Reviewed relevant Kubernetes information: Google your error messages and look at K8s docs.
- Searched open and closed [GitHub issues](https://github.com/chaos-mesh/chaos-mesh/issues?utf8=%E2%9C%93&q=is%3Aissue)
- Read the documentation:
  - [Chaos Mesh Readme](https://github.com/chaos-mesh/chaos-mesh)
  - [Chaos Mesh Doc](https://chaos-mesh.org/docs)

**Output of chaosctl**

**Comment by Hexilee** [comment]
There may be some overloaded nodes in your k8s cluster, could you provide more information about "chaos-daemon-nhv66" by `kubectl describe`?

**Comment by Bhumika1997** [comment]
It's working now
