### ISSUE TITLE
Does it support http or other remote access?

### ISSUE THREAD

**Issue by fanglixuezi** [chaos-mesh/chaos-mesh#2134]
Whether to support remote connection via protocol for pod kill and other pod operatations?

**Comment by Hexilee** [comment]
Do you mean to control the pods in another k8s cluster?

**Comment by YangKeao** [comment]
The `chaos-dashboard` has exported an HTTP api to create/remove/list experiments. However, we don't give any guarantee on the compatibility (between versions) of the HTTP API. The most suggested way is still to use kubernetes client to create / remove chaos resource.

Can you tell me the situation? I think in most case, creating experiments through kubernetes http client is enough.
