### ISSUE TITLE
SchedulerSpec undefind

### ISSUE THREAD

**Issue by sanxun0325** [chaos-mesh/chaos-mesh#2144]
## Question

SchedulerSpec undefind is prompted during the process of developing new chaos.
reference:https://chaos-mesh.org/docs/development_guides/develop_a_new_chaos
![image](https://user-images.githubusercontent.com/28588342/126621017-d25db3e9-8b89-42ce-9953-4d246801a6e8.png)

I need to customize it？can you give me some reference?

**Comment by Hexilee** [comment]
No, you needn't, the [SchedulerUpdater](https://github.com/chaos-mesh/chaos-mesh/blob/release-1.2/controllers/twophase/update_scheduler.go#L34) will handle it.

**Comment by sanxun0325** [comment]
I'm sorry, I didn't get it, did you say schedulerUpdater will create SchedulerSpec?  
when can I get ScheulerSpec，because if I write helloWorldChaos_types i get an error.

**Comment by YangKeao** [comment]
This document is out of date for 2.0. I'm writing a new one and here is the [PR](https://github.com/chaos-mesh/website/blob/83d6c65f4b731b94d82d3746a0f0ac9624e04f60/versioned_docs/version-2.0.0/development_guides/dev_hello_world.md)

**Comment by sanxun0325** [comment]
> This document is out of date for 2.0. I'm writing a new one and here is the [PR](https://github.com/chaos-mesh/website/blob/83d6c65f4b731b94d82d3746a0f0ac9624e04f60/versioned_docs/version-2.0.0/development_guides/dev_hello_world.md)

thanks
