### ISSUE TITLE
use code generation and linter tools with docker instead of binary on host

### ISSUE THREAD

**Issue by STRRL** [chaos-mesh/chaos-mesh#2146]
# Feature Requests

Chaos Mesh need lots of tools for code generation, include:

- controller-gen
- protoc
- kukustomize
- failpoint-ctl

and some other tools as linter:

- revive
- gosec
- goimports

And we will use these binaries that already exist in PATH priority, and try to install with `go get` if it does not exist.

So here are two issues about that:

- if the user already installed a binary with the same name as our required, we do not check the version, for example, user already installed controller-gen v0.5.2, but we still expect v0.4.1, the generated file would have many changes
- `go get` will read `go.mod` at the current directory, so the behaviors of compiled binary might be changed if `go.mod` has changed.

We want to make these tools into one(or several) docker image(s) to keep the binary is stable.

So the goal is very simple:
- replace that direct usage of these binary with docker
- change the related recipes in makefile
- notice the uid and gid when using docker

**Comment by YangKeao** [comment]
I will work on this. `go fmt` has different behavior after upgrading to `1.17` :cry:
