### ISSUE TITLE
Failed to access the dashboard according to the online manual  

### ISSUE THREAD

**Issue by sanxun0325** [chaos-mesh/chaos-mesh#2150]
## Question

This site cannot be accessed https://2886795273-31111-kira01.environments.katacoda.com.
Do I need to configure hosts?  How to configure the corresponding IP address  

![image](https://user-images.githubusercontent.com/28588342/126902834-548bfbf0-57c8-4a85-9587-ec380c8dd347.png)

**Comment by STRRL** [comment]
Hi @sanxun0325, this katacoda scenario use NodePort to expose service dashboard, but NodePort is not set **by default**. So you should execute that `kubectl path` to modify the service, make it be exposed on port 3111.

![image](https://user-images.githubusercontent.com/20221408/126934653-4bbbd3f3-f56b-47ac-a990-c779c804dce1.png)
