### ISSUE TITLE
reload from a paused experiment, and the new experiment's state is paused too

### ISSUE THREAD

**Issue by WangXiangUSTC** [chaos-mesh/chaos-mesh#2162]
## Question

I create a new experiment exp1 by reloading from another experiment exp2, and the exp2's state is paused. After finishing the creation, the exp1's state is paused too, is it reasonable? I think it should run directly.

**Comment by fewdan** [comment]
Can you take a look at the annotation of the newly created exp2? It looks like it was suspended because the annotation and exp1 are consistent. . .

**Comment by WangXiangUSTC** [comment]
Yeah, that's true, I mean it looks not reasonable, do we need to update the annotation when load from an exit experiment.

**Comment by fewdan** [comment]
Well, I understand, this should indeed need to be revised.
