### ISSUE TITLE
codebase: static interface checks

### ISSUE THREAD

**Issue by STRRL** [chaos-mesh/chaos-mesh#2163]
## Feature Request

This issue will not introduce any NEW features or any changes to the current architecture. It's only about improving the style of codes, and let it be easier to understand Chaos Mesh's codes.

As [Effective Go/Interface checks](https://golang.org/doc/effective_go#blank_implements) introduced, we do not need to declare explicitly that one struct implements an interface. So that brings some trouble when reading the code: it's hard to find all the implementations of one interface, even you are working with modern IDE like goland.

For example: 

https://github.com/chaos-mesh/chaos-mesh/blob/1eb4025c68580e16045bba4273b07d50768feffc/controllers/common/controller.go#L44-L47

Here is an interface called `ChaosImpl`, and all of the chaos should implement this interface. If we could add one line of code here:

https://github.com/chaos-mesh/chaos-mesh/blob/1eb4025c68580e16045bba4273b07d50768feffc/controllers/chaosimpl/iochaos/impl.go#L40-L47

```go
var _ common.ChaosImpl = (*Impl)(nil)
```

to declare the implementation explicitly, will give huge help for understanding codes.

I will list several (not all) interfaces and their implements, which could be applied with "static interface checks", this list will keep growing if we find the same situation at new place.

- [x] interface `ChaosImpl` at controllers/common/controller.go https://github.com/chaos-mesh/chaos-mesh/pull/2224
  - struct `Delegate` at controllers/action/delegate.go
  - struct `Impl` at controllers/chaosimpl/awschaos/detachvolume/impl.go
  - struct `Impl` at controllers/chaosimpl/awschaos/ec2restart/impl.go
  - struct `Impl` at controllers/chaosimpl/awschaos/ec2stop/impl.go
  - struct `Impl` at controllers/chaosimpl/dnschaos/types.go
  - struct `Impl` at controllers/chaosimpl/gcpchaos/diskloss/impl.go
  - struct `Impl` at controllers/chaosimpl/gcpchaos/nodereset/impl.go
  - struct `Impl` at controllers/chaosimpl/gcpchaos/nodestop/impl.go
  - struct `Impl` at controllers/chaosimpl/httpchaos/impl.go
  - struct `Impl` at controllers/chaosimpl/iochaos/impl.go
  - struct `Impl` at controllers/chaosimpl/jvmchaos/impl.go
  - struct `Impl` at controllers/chaosimpl/kernelchaos/types.go
  - struct `Impl` at controllers/chaosimpl/networkchaos/trafficcontrol/impl.go
  - struct `Impl` at controllers/chaosimpl/networkchaos/partition/impl.go
  - struct `Impl` at controllers/chaosimpl/podchaos/containerkill/impl.go
  - struct `Impl` at controllers/chaosimpl/podchaos/podfailure/impl.go
  - struct `Impl` at controllers/chaosimpl/podchaos/podkill/impl.go
  - struct `Impl` at controllers/chaosimpl/stresschaos/impl.go
  - struct `Impl` at controllers/chaosimpl/timechaos/impl.go
- [x] interface `InnerObjectWithCustomStatus`  at controllers/common/controller.go (refactor required: move this interface to api/v1alpha1) https://github.com/chaos-mesh/chaos-mesh/pull/2262
  - struct `GCPChaos` at api/v1alpha1/gcpchaos_types.go
  - struct `HTTPChaos` at api/v1alpha1/httpchaos_types.go
  - struct `IOChaos` at api/v1alpha1/iochaos_types.go
  - struct `NetworkChaos` at api/v1alpha1/networkchaos_types.go
  - struct `StressChaos` at api/v1alpha1/stresschaos_types.go
- [x] interface `InnerObjectWithSelector` at controllers/common/controller.go (refactor required: move this interface to api/v1alpha1)
  - struct `AWSChaos` at api/v1alpha1/awschaos_types.go
  - struct `DNSChaos` at api/v1alpha1/dnschaos_type.go
  - struct `GCPChaos` at api/v1alpha1/gcpchaos_types.go
  - struct `HTTPChaos` at api/v1alpha1/httpchaos_types.go
  - struct `IOChaos` at api/v1alpha1/iochaos_types.go
  - struct `JVMChaos` at api/v1alpha1/jvmchaos_types.go
  - struct `KernelChaos` at api/v1alpha1/kernelchaos_types.go
  - struct `NetworkChaos` at api/v1alpha1/networkchaos_types.go
  - struct `PodChaos` at api/v1alpha1/podchaos_types.go 
  - struct `StressChaos` at api/v1alpha1/stresschaos_types.go
  - struct `TimeChaos` at api/v1alpha1/timechaos_types.go
- [ ] interface `InnerObject` at api/v1alpha1/common_types.go
  - struct `AWSChaos` at api/v1alpha1/awschaos_types.go
  - struct `DNSChaos` at api/v1alpha1/dnschaos_type.go
  - struct `GCPChaos` at api/v1alpha1/gcpchaos_types.go
  - struct `HTTPChaos` at api/v1alpha1/httpchaos_types.go
  - struct `IOChaos` at api/v1alpha1/iochaos_types.go
  - struct `JVMChaos` at api/v1alpha1/jvmchaos_types.go
  - struct `KernelChaos` at api/v1alpha1/kernelchaos_types.go
  - struct `NetworkChaos` at api/v1alpha1/networkchaos_types.go
  - struct `PodChaos` at api/v1alpha1/podchaos_types.go 
  - struct `StressChaos` at api/v1alpha1/stresschaos_types.go
  - struct `TimeChaos` at api/v1alpha1/timechaos_types.go

**Comment by STRRL** [comment]
Hi @ReigenDing , thanks for your contribution.

It seems the integration test is unstable in PR #2224, I will make a retry.


> How can I run the test for it in local env?

You could just execute `make test` for unit test, it will install related tools automatically.

for integration test and script test, you could take a look on .github/workflows/integration_test.yml.

for e2e test, you could just execute `./hack/e2e.sh`

**Comment by ReigenDing** [comment]
Got it, thanks.

**Comment by ReigenDing** [comment]
By the way. Could you release `k8s_dns_chaos` version or update image   `pingcap/coredns:latest`.Because there is bug `rpc nil response` with  `k8s_dns_chaso` version `0.2.2` and it has been fixed in newest commit.

**Comment by STRRL** [comment]
> Because there is bug `rpc nil response` with `k8s_dns_chaso` version `0.2.0` and it has been fixed in newest commit.

do you mean https://github.com/chaos-mesh/k8s_dns_chaos/pull/17?

@WangXiangUSTC PTAL, do we need to release a bugfix version `0.2.1` for k8s_dns_chaos? :smile:

**Comment by ReigenDing** [comment]
Yep!

**Comment by WangXiangUSTC** [comment]
> > Because there is bug `rpc nil response` with `k8s_dns_chaso` version `0.2.0` and it has been fixed in newest commit.
> 
> do you mean [chaos-mesh/k8s_dns_chaos#17](https://github.com/chaos-mesh/k8s_dns_chaos/pull/17)?
> 
> @WangXiangUSTC PTAL, do we need to release a bugfix version `0.2.1` for k8s_dns_chaos? 😄

I release v0.2.1 for pingcap/coredns image just now

**Comment by ReigenDing** [comment]
Thanks！！I'll make one pr for updating the helm values.yaml later!  right?
https://github.com/chaos-mesh/chaos-mesh/blob/12acd0c293613e85dd53bc245d1247ad65e882c4/helm/chaos-mesh/values.yaml#L269

**Comment by ReigenDing** [comment]
> > > Because there is bug `rpc nil response` with `k8s_dns_chaso` version `0.2.0` and it has been fixed in newest commit.
> > 
> > 
> > do you mean [chaos-mesh/k8s_dns_chaos#17](https://github.com/chaos-mesh/k8s_dns_chaos/pull/17)?
> > @WangXiangUSTC PTAL, do we need to release a bugfix version `0.2.1` for k8s_dns_chaos? smile
> 
> I release v0.2.1 for pingcap/coredns image just now
Thanks!! I'll make one pr for updating helm values.yaml later!  right?
https://github.com/chaos-mesh/chaos-mesh/issues/2163#issuecomment-899354774

**Comment by ReigenDing** [comment]
Thanks!! I'll make one pr for updating helm values.yaml later!  right?
https://github.com/chaos-mesh/chaos-mesh/blob/12acd0c293613e85dd53bc245d1247ad65e882c4/helm/chaos-mesh/values.yaml#L269

**Comment by WangXiangUSTC** [comment]
> Thanks!! I'll make one pr for updating helm values.yaml later! right?
> https://github.com/chaos-mesh/chaos-mesh/blob/12acd0c293613e85dd53bc245d1247ad65e882c4/helm/chaos-mesh/values.yaml#L269

You are right, thanks!

**Comment by PrayagS** [comment]
@ReigenDing Can you please let me know if you're working on the remaining changes? If not, I'd like to take this up.

**Comment by STRRL** [comment]
> @ReigenDing Can you please let me know if you're working on the remaining changes? If not, I'd like to take this up.

It seems @ReigenDing is not working on that now. Feel free to take this.

**Comment by PrayagS** [comment]
> > @ReigenDing Can you please let me know if you're working on the remaining changes? If not, I'd like to take this up.
> 
> It seems @ReigenDing is not working on that now. Feel free to take this.

Sounds good. I'll get started then.
