### ISSUE TITLE
Missed translation

### ISSUE THREAD

**Issue by Muscule** [chaos-mesh/chaos-mesh#2164]
## Bug Report

**What version of Kubernetes are you using?**
Openshift 4.8

**What version of Chaos Mesh are you using?**
2.0.0

**What did you do?**
Launched experiment and choose events in menu to the left

**What did you expect to see?**
All page in English
**What did you see instead?**
One column titled in Chinese
**Output of chaosctl**

**Comment by Muscule** [comment]
<img width="700" alt="Снимок экрана 2021-07-29 в 13 17 46" src="https://user-images.githubusercontent.com/14834949/127475623-1f47f3e0-b46c-4d83-bdd0-5acd3571fdd2.png">

**Comment by STRRL** [comment]
hi @g1eny0ung  PTAL
