### ISSUE TITLE
Be ready for k8s v1.22+

### ISSUE THREAD

**Issue by Colstuwjx** [chaos-mesh/chaos-mesh#2172]
## Feature Request

**Is your feature request related to a problem? Please describe:**

Since k8s v1.22 is nearly released ( due date: 2021.08.04 ), some API versions would be removed, we should update those resources accordingly. Here are some warning texts I could see when I try to install chaos-mesh v1.2.3:

```
...
Warning: apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
...
Warning: admissionregistration.k8s.io/v1beta1 MutatingWebhookConfiguration is deprecated in v1.16+, unavailable in v1.22+; use admissionregistration.k8s.io/v1 MutatingWebhookConfiguration
...
Warning: admissionregistration.k8s.io/v1beta1 ValidatingWebhookConfiguration is deprecated in v1.16+, unavailable in v1.22+; use admissionregistration.k8s.io/v1 ValidatingWebhookConfiguration
...
```

**Describe the feature you'd like:**

We need to follow the k8s release plan, and update the API versions.

**Describe alternatives you've considered:**

None.

**Teachability, Documentation, Adoption, Migration Strategy:**

See v1.22 [API Changes](https://kubernetes.io/blog/2021/07/14/upcoming-changes-in-kubernetes-1-22/#api-changes).

**Comment by STRRL** [comment]
Thanks for noticing. :heart: 

We have several issues/PRs for tracing that things:

- https://github.com/chaos-mesh/chaos-mesh/issues/1570
- https://github.com/chaos-mesh/chaos-mesh/pull/1558

I think we could finish that in the next several weeks!

**Comment by STRRL** [comment]
As https://github.com/chaos-mesh/chaos-mesh/pull/2292 has been merged! I think we're ready for k8s v1.22! :heart:

**Comment by Colstuwjx** [comment]
How about add a new version k8s cluster into the [CI script](https://github.com/chaos-mesh/chaos-mesh/blob/f728fbf/ci/pingcap_chaos_mesh_build_kind.groovy#L253), or just replace the v1.20, to guarantee this.

**Comment by STRRL** [comment]
> How about add a new version k8s cluster into the [CI script](https://github.com/chaos-mesh/chaos-mesh/blob/f728fbf/ci/pingcap_chaos_mesh_build_kind.groovy#L253), or just replace the v1.20, to guarantee this.
> 

On the way! ❤️❤️
