### ISSUE TITLE
codebase: some questions about podxxxchaos

### ISSUE THREAD

**Issue by Colstuwjx** [chaos-mesh/chaos-mesh#2176]
It's a good design for creating a podxxxchaos to build the bridge for Pod and Chaos object, and I have some questions which are not very clear in my mind.

I do know it's not a good place to ask questions, but I think it would help some new-coming contributors to get a more clear understanding about podxxxchaos:

1. Once chaos, e.g. `NetworkChaos`, has been created, it will create a `PodNetworkChaos` object corresponding to the target `Pod` object, and the `PodNetworkChaos` object's `OwnerReference` would be the target `Pod`. If the target `Pod` was deleted, the `PodNetworkChaos` would be deleted as well. **But if we delete the `NetworkChaos`, the `PodNetworkChaos` would be left**. My question is: **if NetworkChaos has been deleted, why not delete the relevant PodNetworkChaos ?**

2. We did the event mapping from podxxxchaos to xxxchaos, see the relevant code [here](https://github.com/chaos-mesh/chaos-mesh/blob/master/controllers/common/fx.go#L79). My question is: **why do we need this mapping? In order to protect the unexpected podxxxchaos modification from a user ?**
 
Thanks.

**Comment by YangKeao** [comment]
> if NetworkChaos has been deleted, why not delete the relevant PodNetworkChaos ?

Because multiple `NetworkChaos` will control the same `PodNetworkChaos`, the relationship between `NetworkChaos` and `PodNetworkChaos` is not one-to-one, but many-to-many.

> why do we need this mapping? In order to protect the unexpected podxxxchaos modification from a user ?

No. It's because this controller is used to reconcile `NetworkChaos`, and it cannot handle `PodNetworkChaos` (as the `controller-runtime` even doesn't give you the type of the resource.)
