### ISSUE TITLE
Accessing configured Chaos Mesh image version via kubectl

### ISSUE THREAD

**Issue by brrusino** [chaos-mesh/chaos-mesh#2181]
## Question

A general question that I have not been able to find an answer to - I'm trying to find a reliable way to verify which Chaos Mesh image version is installed and operating in a given cluster. The best way I have found is by pulling one of the Chaos Mesh pods (chaos controller manager, for example) and accessing pod.Spec.Containers[0].Image, which gives a value of "pingcap/chaos-mesh:**v1.1.4**", which could theoretically be parsed out. Is there a more appropriate way to find this value? The concern here is that if Chaos Mesh is installed in a custom namespace, I would need to know when querying pods which namespace was used to acquire this value.

**Comment by YangKeao** [comment]
As you said, without knowing the namespace, we cannot give you a script that can work for every users.

The concrete version (with commit hash) is included in the first several lines of logs of every components (like chaos-daemon and chaos-controller-manager)

**Comment by brrusino** [comment]
Got it - thanks for the confirmation.
