### ISSUE TITLE
Installing version 2 error on workflownodes.chaos-mesh.org

### ISSUE THREAD

**Issue by semos2k** [chaos-mesh/chaos-mesh#2186]
Hi, i have tried to install version 2.0 but the process show the next error: "The CustomResourceDefinition "workflownodes.chaos-mesh.org" is invalid: metadata.annotations: Too long: must have at most 262144 bytes" and the definition yes is too long.

The yml files for install was generated by the command:

`curl -sSL https://mirrors.chaos-mesh.org/v2.0.0/install.sh | bash -s -- --template --runtime containerd > chaos-mesh-v2.yml`

Can you help me please, the most feature to me is the workflows.

**Comment by YangKeao** [comment]
`kubectl apply -f` will result in this problem. You could use `kubectl create -f` instead.

**Comment by tuxknight** [comment]
it's more complicated to solve this problem when involving DevOps tools such as Argo-CD/helm to manage the deploy of chaos-mesh. Happy to do any testing if it would be helpful.

**Comment by yishaihl** [comment]
> it's more complicated to solve this problem when involving DevOps tools such as Argo-CD/helm to manage the deploy of chaos-mesh. Happy to do any testing if it would be helpful.

it's true i had to exclude this CRD from argocd and deploy it manually to be able to sync properly.

**Comment by anuragpaliwal80** [comment]
We need fix for this as applying manually or via create command is not an option for us.
@YangKeao Can you please help us out ?

**Comment by STRRL** [comment]
Hi @anuragpaliwal80 and @debek, I noticed that there is a related issue: https://github.com/argoproj/argo-cd/issues/2730

Enable `REPLACE` on ArgoCD could be a temporary bypass solution, it will use `create` if object not exists, and `replace` if object already exists.

**Comment by anuragpaliwal80** [comment]
@STRRL We are not using argo for our cluster as of now. We just apply the k8s yaml files during our cluster upgrade, that's all.

**Comment by anuragpaliwal80** [comment]
@STRRL @YangKeao Just want to know do you guys have any plan to fix this issue so that we can plan 2.x upgrade activity tasks accordingly.  Thanks in advance.

**Comment by anuragpaliwal80** [comment]
Or this is any k8s side issue which can't be fixed from chaos mesh side.

**Comment by STRRL** [comment]
> @STRRL @YangKeao Just want to know do you guys have any plan to fix this issue so that we can plan 2.x upgrade activity tasks accordingly. Thanks in advance.

We do not have a plan to "fix" this issue recently, it relates to the upstream issues. And only make modification on Chaos Mesh for resolving that needs lots of effort: we need to restructure our CRD entirly, especially the validation part.

You could use `kubectl create -f` and enable `Replace` on ArgoCD for bypassing this issue. :D

**Comment by anuragpaliwal80** [comment]
Got it. Thx for the update @STRRL

**Comment by yishaihl** [comment]
@STRRL hey unfortenitly the 'Replace' flag in ArgoCD creates new issue as you can see here:
[https://ibb.co/DChHkPR]

**Comment by STRRL** [comment]
> @STRRL hey unfortenitly the 'Replace' flag in ArgoCD creates new issue as you can see here:
> [https://ibb.co/DChHkPR]

how about taking a try with `--force`?

**Comment by yishaihl** [comment]
@STRRL i'm using declarative argo manifest and unfortunately i didn't found a way to add  'FORCE" operation there ..unless you know how can i declare it?
