### ISSUE TITLE
Release: v2.1.0

### ISSUE THREAD

**Issue by cwen0** [chaos-mesh/chaos-mesh#2200]
## New Feature & Enhancements

* Ease of use / Observability
  - [x] #2229
  - [x] #2259
  - [ ] Unified restful API. #2218, #2231, #2238
  - [x] Support HTTPChaos and JVMChaos on Dashboard.  https://github.com/chaos-mesh/chaos-mesh/pull/2460 https://github.com/chaos-mesh/chaos-mesh/pull/2529
  - [x] JVMChaos: support dynamic injection (without Sidecar). #2366
  - [x] #2212
  - [x] #2122
  - [x] #2459
* Chaos experiments on non-kubernetes
  - [x] Chaosd: reuse the code of the chaos mesh. 
  - [x] Support creating chaos experiments on non-Kubernetes nodes on Chaos Dashbaord. 
  - [x] Support managing physical/VM nodes.  
* Security 
  - [x] #2213 

- [x] Compatible with Kubernetes v1.22.

## Planned Release Date 

2021.11

If there are any features you'd like to see in v2.1.0, leave a comment down below!

**Comment by fewdan** [comment]
Add ProgressChaos:
    we can kill the specified progress in the container.

**Comment by YangKeao** [comment]
> Add ProgressChaos:
> we can kill the specified progress in the container.

Do you mean `Process`?

**Comment by cwen0** [comment]
This version was released! So I will close this issue.

**Comment by ChanKunggc** [comment]
hi，which hub could pull the v2.1.0 images ?  Docker hub  don‘t have v2.1.0 .
