### ISSUE TITLE
Development guides for v2.0.0 are not displayed

### ISSUE THREAD

**Issue by sergioarmgpl** [chaos-mesh/chaos-mesh#2216]
## Bug Report: Development guides for v2.0.0 are not displayed

**What did you do?**
I clicked on https://chaos-mesh.org/docs/configure-development-environment

**What did you expect to see?**
The documentation of how to prepare my environment like version  1.2.3

**What did you see instead?**
Edit this page

If I can help, just tell me how. :)

**Comment by fewdan** [comment]
I don't understand your question too much. If my understanding is correct, this part should be no different from version 1.2.3?

**Comment by sergioarmgpl** [comment]
Well, the content doesn't appear on the page, is a clean page. @fewdan

**Comment by STRRL** [comment]
Hi @sergioarmgpl, it seems that url works fine on my machine: https://chaos-mesh.org/docs/configure-development-environment/, :thinking: 

Would you mind taking a look again? :heart:

**Comment by sergioarmgpl** [comment]
For sure @STRRL, for the version 2.0.0 the following menus in the website appear like the attached image(Just and edit option without content, apparently empty):
- Add New Chaos Experiment Type
- Extend Chaos Daemon interface
- https://chaos-mesh.org/docs/extend-chaosd

![image](https://user-images.githubusercontent.com/26422502/129504061-c8af12f3-e505-4325-b414-7588e7201dbf.png)

**Comment by fewdan** [comment]
@sergioarmgpl 
Yes, we are still working on the content in this area, and it is blank for the time being.
