### ISSUE TITLE
apiserver: adapting to the new utils

### ISSUE THREAD

**Issue by g1eny0ung** [chaos-mesh/chaos-mesh#2231]
After #2218, some new `utils` were introduced in the codebase, includes:

- common API error handler
- common `gin` related structs and functions, like `utils.Response`

There are still some packages that do not fully use the new utils. Need to be done in the future.

### Progress

- [ ] #2429

**Comment by STRRL** [comment]
Hi @g1eny0ung , maybe we could close this issue? Or remove it from "Release 2.2" milestone?

**Comment by g1eny0ung** [comment]
@STRRL As the API is still in an unstable status, I agree to close this issue temporarily. If we need to revisit something relevant in the future, It's not too late to quote this issue again.
