### ISSUE TITLE
Proposal: run different CI depending on the modified files

### ISSUE THREAD

**Issue by g1eny0ung** [chaos-mesh/chaos-mesh#2233]
## Feature Request

**Is your feature request related to a problem? Please describe:**

Yes, this proposal relates to the long-standing question of why our CI has to be run every time, even if just one `.md` file is modified.

**Describe the feature you'd like:**

Run tests based on the type of change files.

**Teachability, Documentation, Adoption, Migration Strategy:**

https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#example-including-paths

**Comment by g1eny0ung** [comment]
@chaos-mesh/maintainers @chaos-mesh/committers Looking forward to your views.

**Comment by milasuperstar** [comment]
👏 agreed. Ridiculous that when people fix a typo and the whole CI is run...
