### ISSUE TITLE
2.0.0 and newer helm can't support older k8s(1.13)?

### ISSUE THREAD

**Issue by kxzonly** [chaos-mesh/chaos-mesh#2268]
## Question

when I used helm install version 2.0.0 , i got an error . 
"no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1""

i search on github,
Such as   https://github.com/operator-framework/operator-lifecycle-manager/issues/1818
i get this conclusion

It's not supported apiextensions.k8s.io/v1 CRD ,because i used olded k8s(1.13.3),it only supported apiextensions.k8s.io/v1beta1
Due to some reason，i can't update my k8s,
if have some method that use 2.0.0 and newer chaos-mesh
if not ,i can only use 1.2.3 instead

**Comment by Andrewmatilde** [comment]
Hi, maybe you can use apiextensions.k8s.io/v1beta1 CRD in https://github.com/chaos-mesh/chaos-mesh/blob/release-2.0/manifests/crd-v1beta1.yaml. I found quick installation script had considered it.

**Comment by kxzonly** [comment]
> Hi, maybe you can use apiextensions.k8s.io/v1beta1 CRD in https://github.com/chaos-mesh/chaos-mesh/blob/release-2.0/manifests/crd-v1beta1.yaml. I found quick installation script had considered it.

ok,thanks ,i try it

**Comment by kxzonly** [comment]
resolved，and close
