### ISSUE TITLE
NetworkChaos event problem - unable to flush ip sets for pod...

### ISSUE THREAD

**Issue by faraktingi** [chaos-mesh/chaos-mesh#2270]
## Bug Report

**What version of Chaos Mesh are you using?**

Controller manager Version: version.Info{GitVersion:"v2.0.0", GitCommit:"8055e259680adbedd728ca121b33ce2f94f72aac", BuildDate:"2021-07-23T07:27:10Z", GoVersion:"go1.15.11", Compiler:"gc", Platform:"linux/amd64"}

**What did you do?**

- Trying to perform NetworkChaos within an Openshift 4.6 project hosted in a multi-zone cluster environment.
- Following documentation of chaos-mesh v2 here: https://chaos-mesh.org/docs/simulate-network-chaos-on-kubernetes/

- Using the following YAML:

> apiVersion: chaos-mesh.org/v1alpha1
> kind: NetworkChaos
> metadata:
>   name: delay
> spec:
>   action: delay
>   mode: one
>   selector:
>     namespaces:
>       - cp4i-ddd509
>     labelSelectors:
>       'statefulset.kubernetes.io/pod-name': 'mq-ddd-qm-test-ibm-mq-1'
>   delay:
>     latency: '10ms'
>     correlation: '100'
>     jitter: '0ms'

**What did you expect to see?**
NetworkChaos experiment running without error.

**What did you see instead?**
in the event (from Dashboard) I can see the following message:
Failed to apply chaos: unable to flush ip sets for pod 

**Output of chaosctl**
	

> 2021-09-01T15:09:12.348Z	ERROR	ipset	error while flushing ip sets for containerID cri-o://4270e8dee47ced18fa6c295675f170cfa14aedc5cfcb442f9f7754af033c1392	{"error": "rpc error: code = Unknown desc = expected docker:// but got cri-o://4"}
> 	github.com/go-logr/zapr.(*zapLogger).Error
> 		/tmp/go/pkg/mod/github.com/go-logr/zapr@v0.1.0/zapr.go:128
> 	github.com/chaos-mesh/chaos-mesh/controllers/podnetworkchaos/ipset.FlushIPSets
> 		/mnt/controllers/podnetworkchaos/ipset/ipset.go:81
> 	github.com/chaos-mesh/chaos-mesh/controllers/podnetworkchaos.(*Reconciler).SetIPSets
> 		/mnt/controllers/podnetworkchaos/controller.go:174
> 	github.com/chaos-mesh/chaos-mesh/controllers/podnetworkchaos.(*Reconciler).Reconcile
> 		/mnt/controllers/podnetworkchaos/controller.go:133
> 	sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
> 		/tmp/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.0/pkg/internal/controller/controller.go:256
> 	sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
> 		/tmp/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.0/pkg/internal/controller/controller.go:232
> 	sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker
> 		/tmp/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.0/pkg/internal/controller/controller.go:211
> 	k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1
> 		/tmp/go/pkg/mod/k8s.io/apimachinery@v0.17.0/pkg/util/wait/wait.go:152
> 	k8s.io/apimachinery/pkg/util/wait.JitterUntil
> 		/tmp/go/pkg/mod/k8s.io/apimachinery@v0.17.0/pkg/util/wait/wait.go:153
> 	k8s.io/apimachinery/pkg/util/wait.Until
> 		/tmp/go/pkg/mod/k8s.io/apimachinery@v0.17.0/pkg/util/wait/wait.go:88
> 	2021-09-01T15:09:12.348Z	ERROR	podnetworkchaos	fail to set ipsets	{"error": "unable to flush ip sets for pod mq-ddd-qm-test-ibm-mq-1"}
> 	github.com/go-logr/zapr.(*zapLogger).Error
> 		/tmp/go/pkg/mod/github.com/go-logr/zapr@v0.1.0/zapr.go:128
> 	github.com/chaos-mesh/chaos-mesh/controllers/podnetworkchaos.(*Reconciler).Reconcile
> 		/mnt/controllers/podnetworkchaos/controller.go:135
> 	sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
> 		/tmp/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.0/pkg/internal/controller/controller.go:256
> 	sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
> 		/tmp/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.0/pkg/internal/controller/controller.go:232
> 	sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker
> 		/tmp/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.0/pkg/internal/controller/controller.go:211
> 	k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1
> 		/tmp/go/pkg/mod/k8s.io/apimachinery@v0.17.0/pkg/util/wait/wait.go:152
> 	k8s.io/apimachinery/pkg/util/wait.JitterUntil
> 		/tmp/go/pkg/mod/k8s.io/apimachinery@v0.17.0/pkg/util/wait/wait.go:153
> 	k8s.io/apimachinery/pkg/util/wait.Until
> 		/tmp/go/pkg/mod/k8s.io/apimachinery@v0.17.0/pkg/util/wait/wait.go:88

**Comment by fewdan** [comment]
Oh, this is because your container runtime is cri-o, but when chaos-mesh is installed, the default chaos-daemon runtime is docker, which causes this error. 

You can reinstall chaos-mesh, but use this command to install :
```
helm install chaos-mesh chaos-mesh/chaos-mesh -n=chaos-testing --set chaosDaemon.runtime=crio --set chaosDaemon.socketPath=/var /run/crio/crio.sock
```

**Comment by faraktingi** [comment]
Thanks for your message fewdan.

Can I just execute the command as-is in my existing installation or should I need to uninstall or perform something else before?

I appreciate your help.

Fabien

**Comment by fewdan** [comment]
@faraktingi 
Thanks. You should uninstall chaos-mesh, then install it....

**Comment by faraktingi** [comment]
Thanks a lot, I did that and now all works correctly.

I'd like to mention juts one thing about uninstalling part: When I performed the uninstallation everything worked correctly but I noticed that  the chaos-mesh Dashboard route was not removed from the project.

Thanks for your help.
I think that you can close this issue now.

Fabien
