### ISSUE TITLE
dose networkchaos support to drop the packages that send to a specific port ?

### ISSUE THREAD

**Issue by GoneLikeAir** [chaos-mesh/chaos-mesh#2272]
Hi, dose networkchaos support to drop the packages that send to a specific port ?

For example, I want to run iptables command like this,  how can I do it via networkchaos:
iptables -A OUTPUT -p tcp --dport 5805 -j DROP

**Comment by Andrewmatilde** [comment]
I have not found it. But I think it could be inject manually using 'ip netns exec'.

**Comment by GoneLikeAir** [comment]
> I have not found it. But I think it could be inject manually using 'ip netns exec'.

Got it, I will try it later. Thanks a lot.
