### ISSUE TITLE
Docs on NetworkChaos Bandwidth example provide incorrect yaml file

### ISSUE THREAD

**Issue by mladedav** [chaos-mesh/chaos-mesh#2287]
## Question
When deployed as is the error is
```
error: error validating ".\\bandwidth.yaml": error validating data: [ValidationError(NetworkChaos.spec.bandwidth): missing required field "buffer" in org.chaos-mesh.v1alpha1.NetworkChaos.spec.bandwidth, ValidationError(NetworkChaos.spec.bandwidth): missing required field "limit" in org.chaos-mesh.v1alpha1.NetworkChaos.spec.bandwidth]; if you choose to ignore these errors, turn validation off with --validate=false
```

If I add the fields `buffer` and `limit` it does work, but `limit` is not even documented.

Version of chaos mesh and the documentation are both 2.0.1.

**Comment by fewdan** [comment]
Thanks for your feedback, we will revise the document.

**Comment by mladedav** [comment]
@fewdan and if you don't mind me highjacking this issue for further documentation error, on the page 
https://chaos-mesh.org/docs/run-a-chaos-experiment/
there is `kubectl annoate` instead of anno**t**ate (missing t)

**Comment by fewdan** [comment]
> @fewdan and if you don't mind me highjacking this issue for further documentation error, on the page
> https://chaos-mesh.org/docs/run-a-chaos-experiment/
> there is `kubectl annoate` instead of anno**t**ate (missing t)

Okay, thank you.

**Comment by fewdan** [comment]
The document has been updated, so close this issue.
