### ISSUE TITLE
Enriching error logs in chaos-controller-manager

### ISSUE THREAD

**Issue by iguoyr** [chaos-mesh/chaos-mesh#2310]
## Feature Request

**Is your feature request related to a problem? Please describe:**

There are not enough logs in the chaos-controller-manger.

for example:
```
2021-09-10T09:05:32.724Z ERROR records fail to recover chaos {"error": "strconv.ParseFloat: parsing \"\": invalid syntax"}
github.com/go-logr/zapr.(*zapLogger).Error
 /tmp/go/pkg/mod/github.com/go-logr/zapr@v0.1.0/zapr.go:128
github.com/chaos-mesh/chaos-mesh/controllers/common.(*Reconciler).Reconcile
 /mnt/controllers/common/controller.go:193
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
 /tmp/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.0/pkg/internal/controller/controller.go:256
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
 /tmp/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.0/pkg/internal/controller/controller.go:232
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker
 /tmp/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.0/pkg/internal/controller/controller.go:211
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1
 /tmp/go/pkg/mod/k8s.io/apimachinery@v0.17.0/pkg/util/wait/wait.go:152
k8s.io/apimachinery/pkg/util/wait.JitterUntil
 /tmp/go/pkg/mod/k8s.io/apimachinery@v0.17.0/pkg/util/wait/wait.go:153
k8s.io/apimachinery/pkg/util/wait.Until
 /tmp/go/pkg/mod/k8s.io/apimachinery@v0.17.0/pkg/util/wait/wait.go:88
```

The error log is printed without details, we cannot know the original error context, including the point at which the error occurred and the object of the error(like the chaos name or other detail info)

**Describe the feature you'd like:**

print error log with the original error context, maybe we can use wrapping errors or other log framework.

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by YangKeao** [comment]
This issue can be solved (or has been solved) by refining log and error in this semester. See https://github.com/chaos-mesh/chaos-mesh/issues/2752 and https://github.com/chaos-mesh/chaos-mesh/issues/2779
