### ISSUE TITLE
StressChaos doesn't work in intranet

### ISSUE THREAD

**Issue by likangjian01** [chaos-mesh/chaos-mesh#2321]
deployed in offline enviroment, it seems to fail to inject a cpu_burn into specific pod

![c8b34a003429d06382db5da1d306ed3](https://user-images.githubusercontent.com/60882548/133732266-c5b3959a-41c8-4fa2-afcb-134d8ddf9ca1.jpg)
![d596792e998dd33f663dafa8ceeecd4](https://user-images.githubusercontent.com/60882548/133732765-56da3f2d-ab9b-456d-9549-198b38512228.jpg)

there is no stress-ng-cpu process in the target pod
![1e97f7e370fa82ad283ccac8943532a](https://user-images.githubusercontent.com/60882548/133733013-a147a04a-b786-47a9-a2a9-685115d857bd.jpg)

the chaos-controller-manager log
![67fc777a19bf72ebb4779ef5f55b07d](https://user-images.githubusercontent.com/60882548/133733071-ccfc1d66-3e0f-43d0-a185-bfa8beb6c74d.jpg)

**Comment by likangjian01** [comment]
What may be the possible cause？

**Comment by cwen0** [comment]
@likangjian01 Can you check if your Kubernetes cluster enable admission-webhook? https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/

**Comment by likangjian01** [comment]
> @likangjian01 Sorry for the late reply！Can you check if your Kubernetes cluster enables admission-webhook? https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/

well, i have found a similar issue which has been closed in #2178，seemingly a bug in JSON deserialization. Thanks

**Comment by liyangzbx** [comment]
解决这个问题了吗，我这边也是内网，压力测试一直是注入中，容器内没有stress-ng进程。
