### ISSUE TITLE
Make `Makefile` easier to read

### ISSUE THREAD

**Issue by iguoyr** [chaos-mesh/chaos-mesh#2342]
## Feature Request

**Is your feature request related to a problem? Please describe:**

The `Makefile` is a little hard to read now, for example:

* lack of help document
* the `eval` function is not easy to understand
* It's more difficult to use conditional statements in `Makefile`, such as `switch`

**Describe the feature you'd like:**

We can improve the readability by the following methods:

* add help document in `Makefile`
* use `bash` script instead on complex logic (btw, all the usage entrypoint is still in the `Makefile`)

We could refer to the following file to make changes:

* [Makefile](https://github.com/kubernetes/kubernetes/blob/master/build/root/Makefile)
* [build environment README](https://github.com/kubernetes/kubernetes/blob/master/build/README.md)

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by Hexilee** [comment]
I think documents may be helpful, but bash scripts are also not easy enough to read.

**Comment by iguoyr** [comment]
> I think documents may be helpful, but bash scripts are also not easy enough to read.

I mean use `bash` on some complex logic, for example:
* the condition statement, `Makefile` can only support `ifeq` and `ifdef`
* the escape character `$` and `$$` and `$$$$`, it is quite confusing to know when to use which one
* the combination of `eval`, `call` and `xxx_TEMPLATE` is less intuitive than `function`(or `method`), but this is actually not very important, we could use documents to describe

BTW, I agree with adding documents first.

**Comment by YangKeao** [comment]
One more positive evidence for `bash` script is that, the intention of `Makefile` is really limited, which makes it really hard to read the embedded `if` expression.
