### ISSUE TITLE
Cannot install Chaos Mess with helm

### ISSUE THREAD

**Issue by aangoulvant** [chaos-mesh/chaos-mesh#2344]
## Bug Report

**What version of Kubernetes are you using?**
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.4", GitCommit:"3cce4a82b44f032d0cd1a1790e6d2f5a55d20aae", GitTreeState:"clean", BuildDate:"2021-08-11T18:16:05Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"linux/amd64"}

Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2", GitCommit:"8b5a19147530eaac9476b0ab82980b4088bbc1b2", GitTreeState:"clean", BuildDate:"2021-09-15T21:32:41Z", GoVersion:"go1.

My cluster is a "minikube" cluster:
- minikube v1.23.2 on Centos 7.9.2009 (vbox/amd64)
- Kubernetes v1.22.2 on Docker 20.10.

I also tried on a Oracle-Linux 8

**What version of Chaos Mesh are you using?**
- I could not install successfully install it with helm - the targeted version was 2.0.1
- the helm version is: v3.6.3

**What did you do?**
I tried to install chaos-mesh with help, with the command:
helm install chaos-mesh chaos-mesh/chaos-mesh -n=chaos-testing --version v2.0.1

**What did you expect to see?**
No error or a success message

**What did you see instead?**
Error: unable to build kubernetes objects from release manifest: [unable to recognize "": no matches for kind "MutatingWebhookConfiguration" in version "admissionregistration.k8s.io/v1beta1", unable to recognize "": no matches for kind "ValidatingWebhookConfiguration" in version "admissionregistration.k8s.io/v1beta1"]

$ kubectl get po -n chaos-testing
No resources found in chaos-testing namespace.

**Output of chaosctl**
N/A

**Comment by Hexilee** [comment]
Hi, I am sorry that Chaos Mesh v2.0.1 does not support Kubernetes v1.22. However, the Chaos Mesh v2.0.2 is ready to be released, which will support Kubernetes v1.22. Thanks for your report.

**Comment by aangoulvant** [comment]
Thanks a lot for pointing this out! Closing.
