### ISSUE TITLE
Webhook gets empty response

### ISSUE THREAD

**Issue by Muscule** [chaos-mesh/chaos-mesh#2359]
## Bug Report

**What version of Kubernetes are you using?**
OpenShift 4.7.22 Kubernetes v1.20.0

**What version of Chaos Mesh are you using?**
2.0.1

**What did you do?**
I tried to create pod-kill experiment.

**What did you expect to see?**
Experiment started succesfully. ChaosMesh kills pods in namespace.

**What did you see instead?**
error.api.internal_server_error: Internal error occurred: failed calling webhook "mpodchaos.kb.io": expected response.uid="967a44f3-141f-4b5b-b1b5-65af48ecce54", got ""

**Output of chaosctl**

**Comment by Hexilee** [comment]
Sorry for the late reply. Could you provide logs from the chaos-controller? You can list the components by ` kubectl get pods --namespace chaos-testing -l app.kubernetes.io/instance=chaos-mesh`.

**Comment by Muscule** [comment]
> This issue should occur on k8s v1.22. What k8s version are you using? (Please list nodes by `kubectl get node`)

v1.21.1

**Comment by Hexilee** [comment]
I reproduced this issue. It seems you installed newer CRDs instead of v2.0.1, could you try to uninstall chaos-mesh(`kubectl delete ns chaos-testing`) and [reinstall](https://chaos-mesh.org/docs/production-installation-using-helm/) it?

**Comment by Hexilee** [comment]
> > I reproduced this issue. It seems you installed newer CRDs instead of v2.0.1, could you try to uninstall chaos-mesh(`kubectl delete ns chaos-testing`) and [reinstall](https://chaos-mesh.org/docs/production-installation-using-helm/) it?
> 
> I can use only offline installation. I reinstalled chaos-mesh with version 2.0.2 and got the same result and the same error. Was it neccessary to delete CRDs before installation?

Yes, could you please delete CRDs and try again?

**Comment by Muscule** [comment]
> > > I reproduced this issue. It seems you installed newer CRDs instead of v2.0.1, could you try to uninstall chaos-mesh(`kubectl delete ns chaos-testing`) and [reinstall](https://chaos-mesh.org/docs/production-installation-using-helm/) it?
> > 
> > 
> > I can use only offline installation. I reinstalled chaos-mesh with version 2.0.2 and got the same result and the same error. Was it neccessary to delete CRDs before installation?
> 
> Yes, could you please delete CRDs and try again?

I uninstalled chaos-mesh, deleted all CRDs, installed v2.0.3 and got the same error.

**Comment by Hexilee** [comment]
Could you please describe the ValidatingWebhookConfiguration by `kubectl describe ValidatingWebhookConfiguration chaos-mesh-validation`?

**Comment by Muscule** [comment]
> > Admission Review Versions:
> > v1
> > v1beta1
> 
> There should only be v1beta1 in Chaos Mesh v2.0.3, it seems you don't reinstall Chaos Mesh completely. Could you please uninstall it by the [guide](https://chaos-mesh.org/docs/quick-start/#uninstall-chaos-mesh)?

I have no opportunity to follow the guide. Cluster is in intranet and has no connection to internet.

**Comment by Hexilee** [comment]
> > > Admission Review Versions:
> > > v1
> > > v1beta1
> > 
> > 
> > There should only be v1beta1 in Chaos Mesh v2.0.3, it seems you don't reinstall Chaos Mesh completely. Could you please uninstall it by the [guide](https://chaos-mesh.org/docs/quick-start/#uninstall-chaos-mesh)?
> 
> I have no opportunity to follow the guide. Cluster is in intranet and has no connection to internet. So I can use only "helm uninstall chaos-mesh -n chaos-testing"

Well, could you download https://mirrors.chaos-mesh.org/v2.0.4/install.sh manually (or copy and paste)? And what steps do you install Chaos Mesh offline? Have you followed the https://chaos-mesh.org/docs/offline-installation?

**Comment by Muscule** [comment]
> > > > Admission Review Versions:
> > > > v1
> > > > v1beta1
> > > 
> > > 
> > > There should only be v1beta1 in Chaos Mesh v2.0.3, it seems you don't reinstall Chaos Mesh completely. Could you please uninstall it by the [guide](https://chaos-mesh.org/docs/quick-start/#uninstall-chaos-mesh)?
> > 
> > 
> > I have no opportunity to follow the guide. Cluster is in intranet and has no connection to internet. So I can use only "helm uninstall chaos-mesh -n chaos-testing"
> 
> Well, could you download https://mirrors.chaos-mesh.org/v2.0.4/install.sh manually (or copy and paste)? And what steps do you install Chaos Mesh offline? Have you followed the https://chaos-mesh.org/docs/offline-installation?

Yes, I can, but script tries to download different yamls from internet, and the server is in intranet. Yes, I follow exactly that guide.

**Comment by Muscule** [comment]
Installed version 2.0.5. The error does not appear any more.
