### ISSUE TITLE
Create a program to replace stress-ng to realize mem stress

### ISSUE THREAD

**Issue by FingerLeader** [chaos-mesh/chaos-mesh#2383]
## Feature Request

**Describe the feature you'd like:**
Because stress-ng realize memory stress by applying read and write pressure instead of occupying memory space, a program which purely occupies memory space is need to generate a memory StressChaos.

**Describe alternatives you've considered:**
Maybe it's a program that uses mmap's system call to allocate memory space.

**Comment by craig-seeman** [comment]
Possible Feature Ideas - Different modes:

Instant allocation - Instantly allocate specified amount of memory
Gradual allocation - Let user specify time that the program will slowly allocate memory to help simulate a memory leak (Example, during value specified minutes, slowly grow to specified memory size|. Over 10 minutes, grow from 0kb to 2GB)
