### ISSUE TITLE
gopsutil-v2.20.5+incompatible causes bugs

### ISSUE THREAD

**Issue by Hexilee** [chaos-mesh/chaos-mesh#2388]
## Bug Report

Currently, the dependency of gopsutil-v2.20.5+incompatible results in the [building fails](https://github.com/kubernetes/minikube/issues/10101) on Apple M1. We can upgrade gopsutil to v3.x.x to fix this bug.

Another bug we met is the unstable create time of process. Two results of `*Process.CreateTime()` may be different by 1s error, I guess it's caused by float calculating. It caused a bug in chaos-daemon/bpm, and we fixed it by caching the result of `*Process.CreateTime()`. I cannot find relevant bug-fix in the release notes of gopsutil, upgrading may be ineffective.

**Comment by YangKeao** [comment]
For the second problem, I have submitted a fix https://github.com/shirou/gopsutil/pull/1204
