### ISSUE TITLE
Helm install chaos-mesh failed

### ISSUE THREAD

**Issue by adengdai** [chaos-mesh/chaos-mesh#2400]
## Bug Report

**What version of Kubernetes are you using?**
I used minikube to create the Kubernetes, the version is 1.22.2

**What version of Chaos Mesh are you using?**
When I trying to run the command "helm install chaos-mesh chaos-mesh/chaos-mesh -n=chaos-testing", it shown me this error: Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: [unable to recognize "": no matches for kind "MutatingWebhookConfiguration" in version "admissionregistration.k8s.io/v1beta1", unable to recognize "": no matches for kind "ValidatingWebhookConfiguration" in version "admissionregistration.k8s.io/v1beta1"]

**What did you do?**
I fallow the Command where shown in this website to install the chaos-mesh : https://chaos-mesh.org/website-zh/docs/production-installation-using-helm/

**What did you expect to see?**

**What did you see instead?**

**Output of chaosctl**

**Comment by chirangaalwis** [comment]
@YangKeao when will this be released?

**Comment by cwen0** [comment]
@chirangaalwis Sorry for my late reply! Chaos Mesh v2.1.0 has been released. You can follow the docs https://chaos-mesh.org/docs/production-installation-using-helm/ to install chaos mesh. I will close this issue now. If you have new issue, free to reopen it.

**Comment by adengdai** [comment]
Thank you so much for reply！
I will try it tomorrow.
Sincerely



发自我的iPhone


------------------ Original ------------------
From: CWen ***@***.***&gt;
Date: Wed,Dec 1,2021 7:56 PM
To: chaos-mesh/chaos-mesh ***@***.***&gt;
Cc: adengdai ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [chaos-mesh/chaos-mesh] Helm install chaos-mesh failed (Issue#2400)
