### ISSUE TITLE
DNSChaos experiment don't work as intended when multiple chaos-dns-server pods are available

### ISSUE THREAD

**Issue by gmiam** [chaos-mesh/chaos-mesh#2409]
## Bug Report

**What version of Kubernetes are you using?**
kubernetes v1.21

**What version of Chaos Mesh are you using?**
Controller manager Version: version.Info{GitVersion:"v2.0.0", GitCommit:"8055e259680adbedd728ca121b33ce2f94f72aac", BuildDate:"2021-07-23T07:27:10Z", GoVersion:"go1.15.11", Compiler:"gc", Platform:"linux/amd64"}

**What did you do?**
A bit of context:
We generate an outage on our platform launching a very simple DNSChaos experiment that was supposed to prevent DNS request to succeed for one of our external partners. It represents a small subset of our endpoints and is very well covered by a cache. But we noticed that a lot of unrelated DNS requests started to fails. 

At this point we suspect a problem of throttling or resource contention at the DNS server level (we had a DNS server per node before experiment (~80 at that time), and only one provided by chaos-mesh during the experiment). That's why we decided to try to scale up the chaos-dns-server deployment.

_**Scale chaos-dns-server to 10 pods**_
kubectl -n chaos-testing scale deploy chaos-dns-server --replicas=10

Launch a DNSChaos experiment to generate error to <mydnsalias.com> for a specific pod.
Connect to the pod using kubectl exec
nslookup <mydnsalias.com> fails approximatively 10% of the times (expected 100%).

**What did you expect to see?**
I would expect to see all DNS requests to fail. 
/etc/resolv.conf of the pod redirect to chaos-dns-server svc as expected.

**What did you see instead?**
I would expect to have all the DNS request in error.

I imagine this is something already known, but can you please provide some explanation on the behavior and tell us if something is planned to solve the issue?

Thanks

cc: @sterchelen

**Comment by sterchelen** [comment]
Hi @WangXiangUSTC,
Could you share the implementation you have been thinking about to fix this issue? This way, we might be able to help you develop it.

**Comment by WangXiangUSTC** [comment]
> Hi @WangXiangUSTC, Could you share the implementation you have been thinking about to fix this issue? This way, we might be able to help you develop it.

That's great! You can see the code here https://github.com/chaos-mesh/chaos-mesh/blob/84e432d6d2aa03108577b4c2c6ec2e9d68ffbffa/controllers/chaosimpl/dnschaos/types.go#L64

The logic is:
1. Find the DNS server
2. Send a gRPC request to the server's cluster IP, and only one chaos DNS pod behind the server receive the request

I think the easiest way is to change the logic to:
1. Find all the Pods belong to the DNS server
2. Send grpc request to all these Pods

**Comment by sterchelen** [comment]
Thank you @WangXiangUSTC,
IIUC the code, the `Apply` fct  is called for each pod that fulfills the chaos selector?  https://github.com/chaos-mesh/chaos-mesh/blob/61114328c4dffdb9b204658987c1d9dbf7930108/controllers/chaosimpl/dnschaos/types.go#L48
Which also means that `setDNSServerRules` will be called `n (number of pods) * y (number of dns servers)`?

**Comment by WangXiangUSTC** [comment]
> Thank you @WangXiangUSTC, IIUC the code, the `Apply` fct is called for each pod that fulfills the chaos selector?
> 
> https://github.com/chaos-mesh/chaos-mesh/blob/61114328c4dffdb9b204658987c1d9dbf7930108/controllers/chaosimpl/dnschaos/types.go#L48
> 
> 
> Which also means that `setDNSServerRules` will be called `n (number of pods) * y (number of dns servers)`?

Yeah, you are right, the `y(number of dns servers) is` 1, because Chaos Mesh will only deploy one Chaos Server.

**Comment by sterchelen** [comment]
> Yeah, you are right, the y(number of dns servers) is 1, because Chaos Mesh will only deploy one Chaos Server.


Indeed currently with only have 1 dns server in Chaos Mesh... but we are talking about adding more.
I am afraid that we'll make unneeded calls to those dns servers as I mentioned in my previous message, the `Apply` fct is called for each pod that fulfills the chaos selector.

For example, if we have a selector that selects 15 pods and we have 10 dns servers then for each `Apply` call (15 times) we'll have 10 calls to dns servers. In total 150 calls... whereas only one series of 10 calls would suffice (for each dns server).

Is using the `index` parameter to send those 10 calls only once by checking `index == 0` conceivable?

**Comment by sterchelen** [comment]
Hey 👋🏼  @WangXiangUSTC, wdyt of my preceding explanation?

**Comment by WangXiangUSTC** [comment]
> > Yeah, you are right, the y(number of dns servers) is 1, because Chaos Mesh will only deploy one Chaos Server.
> 
> Indeed currently with only have 1 dns server in Chaos Mesh... but we are talking about adding more. I am afraid that we'll make unneeded calls to those dns servers as I mentioned in my previous message, the `Apply` fct is called for each pod that fulfills the chaos selector.
> 
> For example, if we have a selector that selects 15 pods and we have 10 dns servers then for each `Apply` call (15 times) we'll have 10 calls to dns servers. In total 150 calls... whereas only one series of 10 calls would suffice (for each dns server).
> 
> Is using the `index` parameter to send those 10 calls only once by checking `index == 0` conceivable?

Only require one DNS server for Chaos Mesh, the problem is that only supports one Pod for this DNS server now.

**Comment by gmiam** [comment]
Hi @WangXiangUSTC,

Sorry, I'm not sure to fully understand your last answer. Isn't it the whole point of this issue to enable the possibility to support multiple DNS pods with Chaos Mesh?

We mainly want to avoid making useless call that will take time, consume resources and increase the risk of errors?

Do you think we can rely on the index to only call once all the DNS pods to patch them? In that case we will loop over all the pods matching with the DNS service.

**Comment by WangXiangUSTC** [comment]
> 

I think calling all the Pods in the DNS server is the simplest way to fix this issue, though it is not perfect.

`rely on the index to only call once all the DNS pods to patch them`, In fact, I'm not clear about what it is mean. 🤔

**Comment by gmiam** [comment]
I'll try my best to explain what we have in mind!

If I understand correctly, the function you mention earlier:
https://github.com/chaos-mesh/chaos-mesh/blob/84e432d6d2aa03108577b4c2c6ec2e9d68ffbffa/controllers/chaosimpl/dnschaos/types.go#L64

Is included in the Apply function which is originally called here:
https://github.com/chaos-mesh/chaos-mesh/blob/84e432d6d2aa03108577b4c2c6ec2e9d68ffbffa/controllers/common/records/controller.go#L149

And this call is embedded in a for loop:
https://github.com/chaos-mesh/chaos-mesh/blob/84e432d6d2aa03108577b4c2c6ec2e9d68ffbffa/controllers/common/records/controller.go#L115

Where `records` is more or less (in this context) the list of pods matching the selector, and `index` is the index of the pod in the list we want interact with.

So if we want in the first function loop over all the DNS pods matching the service (hence supporting multiple DNS pods) instead of one today, maybe we can consider doing it only for the first pod in the `records` list?
IIUC doing it for all the "target pods" is just patching all the DNS pods the same way n times (where n can be high for a deployment with a lot of replicas).

I hope this can clarify what we have in mind.

**Comment by WangXiangUSTC** [comment]
> 

Oh, I got it, it is reasonable. To reduce the call times to the DNS server, requires optimization here. you can see the function `setDNSServerRules`:

https://github.com/chaos-mesh/chaos-mesh/blob/84e432d6d2aa03108577b4c2c6ec2e9d68ffbffa/controllers/chaosimpl/dnschaos/types.go#L84

It contains an argument `pod`, it will send grpc request to the DNS server for each pod. We can update it to `pods`, and it should contain all the target Pods in records. So for N target Pods, and M DNS Pods, only require M requests(to these Pods belong to DNS server).

**Comment by gmiam** [comment]
Thanks!

Last question. In my understanding, here:
https://github.com/chaos-mesh/chaos-mesh/blob/84e432d6d2aa03108577b4c2c6ec2e9d68ffbffa/controllers/chaosimpl/dnschaos/types.go#L64

We call the DNS pod using the service IP. I thought the goal was to retrieve al the pods IP from the service and then loop over to make the call to all DNS pods instead of just one (the one handling the request made to the service IP).
In my understanding the `pod` argument referred to the pod which is the target of the experiment and not the DNS. Did I miss something?

**Comment by WangXiangUSTC** [comment]
> Thanks!
> 
> Last question. In my understanding, here:
> 
> https://github.com/chaos-mesh/chaos-mesh/blob/84e432d6d2aa03108577b4c2c6ec2e9d68ffbffa/controllers/chaosimpl/dnschaos/types.go#L64
> 
> We call the DNS pod using the service IP. I thought the goal was to retrieve al the pods IP from the service and then loop over to make the call to all DNS pods instead of just one (the one handling the request made to the service IP). In my understanding the `pod` argument referred to the pod which is the target of the experiment and not the DNS. Did I miss something?

Yeah, you are right. `pod` refer to the target Pod of the experiment, we need to update it to Pods(all target Pod of the experiment), and then change the `service.Spec.ClusterIP` to the DNS Pod's IP, and execute `setDNSServerRules` for each DNS Pod.
