### ISSUE TITLE
NetworkChaos unable to flush ip sets for pod 

### ISSUE THREAD

**Issue by chamilzr** [chaos-mesh/chaos-mesh#2413]
## Bug Report

**What version of Kubernetes are you using?**
v1.14.1

**What version of Chaos Mesh are you using?**
Controller manager Version: version.Info{GitVersion:"master-g72d2bc17febc7f", GitCommit:"72d2bc17febc7f2a4a10c97417f11c5eb1d86a13", BuildDate:"2021-09-27T04:43:36Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"linux/amd64"}

**What did you do?**
kubectl  apply -f network-delay.yaml

**What did you expect to see?**
simulate network delay for one pod

**What did you see instead?**
1.kubectl describe networkchaos network-delay
 Failed to apply chaos: unable to flush ip sets for pod podname
2. get log of chaos-daemon 
2021-10-26T03:43:50.861Z        INFO    chaos-daemon-server     flush ipset     {"request": "container_id:\"docker://fd45fcf95997dc0917925bd22ddc782ec577675f23b78ac9f842b1739710653a\" enterNS:true"}
2021-10-26T03:43:50.864Z        ERROR   chaos-daemon-server     error while getting PID {"error": "Error response from daemon: client version 1.41 is too new. Maximum supported API version is 1.39"}
github.com/chaos-mesh/chaos-mesh/pkg/chaosdaemon.(*DaemonServer).FlushIPSets
        /mnt/pkg/chaosdaemon/ipset_server.go:38
github.com/chaos-mesh/chaos-mesh/pkg/chaosdaemon/pb._ChaosDaemon_FlushIPSets_Handler.func1
        /mnt/pkg/chaosdaemon/pb/chaosdaemon.pb.go:3222
github.com/grpc-ecosystem/go-grpc-prometheus.(*ServerMetrics).UnaryServerInterceptor.func1
        /tmp/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-prometheus@v1.2.0/server_metrics.go:107
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1
        /tmp/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.2.0/chain.go:25
github.com/chaos-mesh/chaos-mesh/pkg/grpc.TimeoutServerInterceptor
        /mnt/pkg/grpc/utils.go:186
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1
        /tmp/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.2.0/chain.go:25
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1
        /tmp/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.2.0/chain.go:34
github.com/chaos-mesh/chaos-mesh/pkg/chaosdaemon/pb._ChaosDaemon_FlushIPSets_Handler
        /mnt/pkg/chaosdaemon/pb/chaosdaemon.pb.go:3224
google.golang.org/grpc.(*Server).processUnaryRPC
        /tmp/go/pkg/mod/google.golang.org/grpc@v1.33.2/server.go:1210
google.golang.org/grpc.(*Server).handleStream
        /tmp/go/pkg/mod/google.golang.org/grpc@v1.33.2/server.go:1533
google.golang.org/grpc.(*Server).serveStreams.func1.2
        /tmp/go/pkg/mod/google.golang.org/grpc@v1.33.2/server.go:871
2021-10-26T04:00:30.921Z        INFO    chaos-daemon-server     flush ipset     {"request": "container_id:\"docker://fd45fcf95997dc0917925bd22ddc782ec577675f23b78ac9f842b1739710653a\" enterNS:true"}
2021-10-26T04:00:30.924Z        ERROR   chaos-daemon-server     error while getting PID {"error": "Error response from daemon: client version 1.41 is too new. Maximum supported API version is 1.39"}
github.com/chaos-mesh/chaos-mesh/pkg/chaosdaemon.(*DaemonServer).FlushIPSets
        /mnt/pkg/chaosdaemon/ipset_server.go:38
github.com/chaos-mesh/chaos-mesh/pkg/chaosdaemon/pb._ChaosDaemon_FlushIPSets_Handler.func1
        /mnt/pkg/chaosdaemon/pb/chaosdaemon.pb.go:3222
github.com/grpc-ecosystem/go-grpc-prometheus.(*ServerMetrics).UnaryServerInterceptor.func1
        /tmp/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-prometheus@v1.2.0/server_metrics.go:107
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1
        /tmp/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.2.0/chain.go:25
github.com/chaos-mesh/chaos-mesh/pkg/grpc.TimeoutServerInterceptor
        /mnt/pkg/grpc/utils.go:186
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1
        /tmp/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.2.0/chain.go:25
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1
        /tmp/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.2.0/chain.go:34
github.com/chaos-mesh/chaos-mesh/pkg/chaosdaemon/pb._ChaosDaemon_FlushIPSets_Handler
        /mnt/pkg/chaosdaemon/pb/chaosdaemon.pb.go:3224
google.golang.org/grpc.(*Server).processUnaryRPC
        /tmp/go/pkg/mod/google.golang.org/grpc@v1.33.2/server.go:1210
google.golang.org/grpc.(*Server).handleStream
        /tmp/go/pkg/mod/google.golang.org/grpc@v1.33.2/server.go:1533
google.golang.org/grpc.(*Server).serveStreams.func1.2
        /tmp/go/pkg/mod/google.golang.org/grpc@v1.33.2/server.go:871

**Output of chaosctl**

**Comment by chamilzr** [comment]
@g1eny0ung Is there any update for this issue?

**Comment by g1eny0ung** [comment]
After I asked other maintainers, they say maybe the problem is that the client used by `chaos-daemon` is too old. But I see that you are using the image built from the master branch, the latest `chaos-daemon` image should already support the Docker API `1.41`. What version of docker are you using?

**Comment by chamilzr** [comment]
@g1eny0ung Docker version 18.09.9, build 039a7df9ba

**Comment by g1eny0ung** [comment]
@chamilzr I submitted a PR to fix this issue, which allows users to run the latest chaos daemon without upgrading the version of docker.

**Comment by g1eny0ung** [comment]
Updated to documentation: https://chaos-mesh.org/docs/next/faqs/#q-daemon-throws-an-error-similar-to-version-141-is-too-new-the-maximum-supported-api-version-is-139.
