### ISSUE TITLE
chaos-controller-manager containter failed to activate！

### ISSUE THREAD

**Issue by Ai-yoo** [chaos-mesh/chaos-mesh#2420]
chaos-controller-manager pod is CrashLoopBackOff！use decribe pod get ”Back-off restarting failed container“，use logs -f pod get this information：

2021/10/27 01:06:51 [Fx] fx.Invoke(github.com/chaos-mesh/chaos-mesh/pkg/workflow/controllers.BootstrapWorkflowControllers()) called from:
github.com/chaos-mesh/chaos-mesh/controllers.init
	/mnt/controllers/fx.go:67
runtime.doInit
	/usr/local/go/src/runtime/proc.go:5652
runtime.doInit
	/usr/local/go/src/runtime/proc.go:5647
runtime.main
	/usr/local/go/src/runtime/proc.go:191
Failed: could not build arguments for function "github.com/chaos-mesh/chaos-mesh/pkg/workflow/controllers".BootstrapWorkflowControllers (/mnt/pkg/workflow/controllers/bootstrap.go:27): failed to build manager.Manager: received non-nil error from function "github.com/chaos-mesh/chaos-mesh/cmd/chaos-controller-manager/provider".NewManager (/mnt/cmd/chaos-controller-manager/provider/controller.go:82): LeaderElectionID must be configured
2021/10/27 01:06:51 [Fx] ERROR		Failed to start: could not build arguments for function "github.com/chaos-mesh/chaos-mesh/pkg/workflow/controllers".BootstrapWorkflowControllers (/mnt/pkg/workflow/controllers/bootstrap.go:27): failed to build manager.Manager: received non-nil error from function "github.com/chaos-mesh/chaos-mesh/cmd/chaos-controller-manager/provider".NewManager (/mnt/cmd/chaos-controller-manager/provider/controller.go:82): LeaderElectionID must be configured

**Comment by g1eny0ung** [comment]
Please use `ghcr.io` images currently like `ghcr.io/chaos-mesh/chaos-mesh/chaos-mesh`. We will be syncing the latest images to Docker Hub shortly.

**Comment by Ai-yoo** [comment]
> Please use `ghcr.io` images currently like `ghcr.io/chaos-mesh/chaos-mesh/chaos-mesh`. We will be syncing the latest images to Docker Hub shortly.

**Comment by Ai-yoo** [comment]
> Please use `ghcr.io` images currently like `ghcr.io/chaos-mesh/chaos-mesh/chaos-mesh`. We will be syncing the latest images to Docker Hub shortly.

Ok，Thanks！Wait a moment for me to try, the scene at that time is gone

**Comment by STRRL** [comment]
I am going to close this issue, feel free to reopen it.
