### ISSUE TITLE
PhysicalMachineChaos support multipe records

### ISSUE THREAD

**Issue by WangXiangUSTC** [chaos-mesh/chaos-mesh#2434]
## Bug Report

**What version of Chaos Mesh are you using?**
a5589134dd2a9735cecd627d34c55582f3dc6aee

**What did you do?**

Create a PhysicalMachineChaos with more than one chaosd, and one chaosd run chaos failed, and then recover this experiment.

**What did you expect to see?**

Can recover success

**What did you see instead?**

Recover success, but fault in some chaosd is not recovered. PhysicalMachineChaos support multipe records, and can fix this bug.

**Comment by STRRL** [comment]
closed by #2499
