### ISSUE TITLE
yaml update fail

### ISSUE THREAD

**Issue by eLife-long** [chaos-mesh/chaos-mesh#2443]
## Bug Report

**What version of Kubernetes are you using?**
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-13T11:23:11Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.13", GitCommit:"39a145ca3413079bcb9c80846488786fed5fe1cb", GitTreeState:"clean", BuildDate:"2020-07-15T16:10:14Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

**What version of Chaos Mesh are you using?**
2.0.3

**What did you do?**
modify  experments  yaml
modify  succeed

**What did you expect to see?**
notice  modify succeed，but  yaml  is not  update succeed

**What did you see instead?**
yes

**Output of chaosctl**

![image](https://user-images.githubusercontent.com/20318700/139770932-02f3bebb-f879-44c6-aa3c-00992826565e.png)

**Comment by WangXiangUSTC** [comment]
Which field did you update?

**Comment by eLife-long** [comment]
> Which field did you update?

duration，
for example，change 30s to 31s and click the update button
F5 refresh，auto restore to 30s

Google Chrome，version:95.0.4638.54       64bit

**Comment by WangXiangUSTC** [comment]
> > Which field did you update?
> 
> duration， for example，change 30s to 31s and click the update button F5 refresh，auto restore to 30s
> 
> Google Chrome，version:95.0.4638.54 64bit

OK, I will try it

**Comment by eLife-long** [comment]
> > > Which field did you update?
> > 
> > 
> > duration， for example，change 30s to 31s and click the update button F5 refresh，auto restore to 30s
> > Google Chrome，version:95.0.4638.54 64bit
> 
> OK, I will try it

**Comment by eLife-long** [comment]
OK

**Comment by WangXiangUSTC** [comment]
I confirm that we do not support modifying the configuration under spec at present. We will delete the `update` button and add it after modifying the experimental configuration is supported

**Comment by eLife-long** [comment]
> I confirm that we do not support modifying the configuration under spec at present. We will delete the `update` button and add it after modifying the experimental configuration is supported

OK!
Hope to support as soon as possible, which will provide convenience for us

**Comment by WangXiangUSTC** [comment]
https://github.com/chaos-mesh/chaos-mesh/issues/2227
We have an issue to discuss this feature

**Comment by eLife-long** [comment]
> #2227 We have an issue to discuss this feature

OK
