### ISSUE TITLE
Database Password Logged on Error When Using DSN

### ISSUE THREAD

**Issue by craig-seeman** [chaos-mesh/chaos-mesh#2463]
## Bug Report

**What version of Kubernetes are you using?**
1.19

**What version of Chaos Mesh are you using?**
2.0.2

**What did you do?**
Setup DSN with password and connected to a mysql server that didn't have correct setup, resulting in error connecting.

**What did you expect to see?**
A normal error message about not being able to connect.

```
{"driver": "mysql", "error": "dial tcp REDACTED:3306: connect: connection refused"}
```
**What did you see instead?**
Error message with full DSN credentials logged in plain text.

```
{"driver": "mysql", "datasource": "REDACTED:REDACTED@tcp(REDACTED:3306)/mysql", "error": "dial tcp REDACTED:3306: connect: connection refused"}
```

**Possible Offending line of Code**
```go

log.Error(err, "Failed to open DB: ", "driver => ", conf.Database.Driver, " datasource => ", conf.Database.Datasource)
```
https://github.com/chaos-mesh/chaos-mesh/blob/master/pkg/dashboard/store/store.go#L61

**Comment by WangXiangUSTC** [comment]
Yeah，the account and password is sensitive information, we should not show them in the log, I will modify it.
