### ISSUE TITLE
Dashboard MySQL 8 Bootstrapping Issue In Workflows

### ISSUE THREAD

**Issue by craig-seeman** [chaos-mesh/chaos-mesh#2464]
## Bug Report

**What version of Kubernetes are you using?**
1.19

**What version of Chaos Mesh are you using?**
2.0.2

**What did you do?**
Tried using mysql 8.0 version for backend database

**What did you expect to see?**
Successful database bootstrapping

**What did you see instead?**
```
(/app/chaos-mesh/pkg/store/workflow/workflow.go:30) 
[2021-11-03 17:06:15]  Error 1074: Column length too big for column 'workflow' (max = 16383); use BLOB or TEXT instead 
panic: Error 1146: Table 'chaos-mesh.workflow_entities' doesn't exist
```

**Comment by craig-seeman** [comment]
Issue possibly exists:

`vendor/chaos-mesh/pkg/core/workflow.go`

Possible fix by adding `type:blob` to the gorm definition:

```go
// WorkflowEntity is the gorm entity, refers to a row of data
type WorkflowEntity struct {
	WorkflowMeta
	Workflow string `gorm:"type:blob;size:32768"`
}
```

**Comment by WangXiangUSTC** [comment]
> Issue possibly exists:
> 
> `vendor/chaos-mesh/pkg/core/workflow.go`
> 
> Possible fix by adding `type:blob` (or TEXT probably) to the gorm definition:
> 
> ```go
> // WorkflowEntity is the gorm entity, refers to a row of data
> type WorkflowEntity struct {
> 	WorkflowMeta
> 	Workflow string `gorm:"type:blob;size:32768"`
> }
> ```

Do you willing to fix this issue? I see you have already provided the solution.

**Comment by craig-seeman** [comment]
Absolutely! Please feel free to assign this to me @WangXiangUSTC :) I will run through the testing workflows - I only tested to see if it fixed the error happening. 

Sadly, though, it seems the version of mysql this affects has issues later on with the time 00-00-0000 bug #1659 But this will get the project closer to running under mysql 8.0

**Comment by WangXiangUSTC** [comment]
> Absolutely! Please feel free to assign this to me @WangXiangUSTC :) I will run through the testing workflows - I only tested to see if it fixed the error happening.
> 
> Sadly, though, it seems the version of mysql this affects has issues later on with the time 00-00-0000 bug #1659 But this will get the project closer to running under mysql 8.0

Thanks, already assigned it to you.
