### ISSUE TITLE
 images: short the image name

### ISSUE THREAD

**Issue by STRRL** [chaos-mesh/chaos-mesh#2475]
## Feature Request

**Is your feature request related to a problem? Please describe:**

Currently, we publish our docker images like:
- `ghcr.io/chaos-mesh/chaos-mesh/chaos-mesh:latest`
- `ghcr.io/chaos-mesh/chaos-mesh/chaos-dashboard:latest`
- etc.

The disadvantages are:
- the name pattern is not the familiar `<container-registry>/<owner>/<project>:<tag>` style
- might have compatibility issues with some container registry.(works on ghcr.io and self-hosted harbor, not works on docker hub, not sure on other container registry)

**Describe the feature you'd like:**

use the image name like `ghcr.io/chaos-mesh/chaos-mesh:latest`.

**Describe alternatives you've considered:**

No other alternative solution.

**Teachability, Documentation, Adoption, Migration Strategy:**

two parts of that:

- [x] images for `chaos-mesh`, `chaos-daemon`, `chaos-dashboard` and `chaos-kernel` https://github.com/chaos-mesh/chaos-mesh/pull/2482
  - [x] cherry-pick to `release-2.0` #2487
- [ ] images for `build-env`, `dev-env`  https://github.com/chaos-mesh/chaos-mesh/pull/2528
- [ ] update helm charts https://github.com/chaos-mesh/chaos-mesh/pull/2496

**Comment by STRRL** [comment]
I move this issue to milestone 2.2, because it miss the release train for 2.1

**Comment by cwen0** [comment]
> I move this issue to milestone 2.2, because it miss the release train for 2.1

@STRRL I found this feature has been merged in master.  v2.1 branch will be checkout from the master branch, and this feature also will be included in v2.1 branch.

**Comment by STRRL** [comment]
> > I move this issue to milestone 2.2, because it miss the release train for 2.1
> 
> @STRRL I found this feature has been merged in master. v2.1 branch will be checkout from the master branch, and this feature also will be included in v2.1 branch.

oops! I comment and operate with the wrong issue. 😂   I want to move https://github.com/chaos-mesh/chaos-mesh/issues/2314 into release 2.2
