### ISSUE TITLE
podnetworkchaos fail to update  {"error": "the server could not find the requested resource (put podnetworkchaos.chaos-mesh.org xxx)"}

### ISSUE THREAD

**Issue by ChanKunggc** [chaos-mesh/chaos-mesh#2478]
## Bug Report

**What version of Kubernetes are you using?**

v1.14.3
**What version of Chaos Mesh are you using?**

v2.0.3
**What did you do?**

just make network loss experiment 
![image](https://user-images.githubusercontent.com/56463479/140507723-3be46876-c8bd-4ff5-b8bd-9ce764910f63.png)
print this error both of experiment start and  archive action。
![image](https://user-images.githubusercontent.com/56463479/140507892-2d366faa-0184-4caf-9523-0205f86bdda8.png)
archive also print this error but i think the reason is daemon didn‘t  in this node because of taint.
![image](https://user-images.githubusercontent.com/56463479/140508311-7c5d1330-aa43-408f-bbdd-de802419d04d.png)
**What did you expect to see?**
 normal start and archive 
**What did you see instead?**

**Output of chaosctl**

![image](https://user-images.githubusercontent.com/56463479/140508716-df6ae153-e33e-43bc-9f62-8953128ac6cf.png)

**Comment by Andrewmatilde** [comment]
Hi @ChanKunggc , could you give some info about the work status or error log of chaos-daemon ?

**Comment by ChanKunggc** [comment]
Sorry,i didn't see the comment.
Now i try a new network chaos ,it.s worked,but the status may be not correct.
network chaos status
![image](https://user-images.githubusercontent.com/56463479/143800263-b8ba5bdd-2769-4059-a981-722efbbead3f.png)
the daemon logs
![image](https://user-images.githubusercontent.com/56463479/143800386-c23c61e3-7c5f-44d8-81a1-4cef0d2a8d84.png)

**Comment by iguoyr** [comment]
@ChanKunggc Hi, could you try this command `kubectl get podnetworkchaos <pod-name>` (for example, in the previous picture, it could be `kubectl get podnetworkchaos oom-test-78889d8c6c-j48l8`)?

**Comment by ChanKunggc** [comment]
@iguoyr 
![image](https://user-images.githubusercontent.com/56463479/143854322-a017fafd-419e-4130-8a96-ffac060c2183.png)

**Comment by ChanKunggc** [comment]
> @ChanKunggc Hi, could you try this command `kubectl get podnetworkchaos <pod-name>` (for example, in the previous picture, it could be `kubectl get podnetworkchaos oom-test-78889d8c6c-j48l8`)?

**Comment by iguoyr** [comment]
> @iguoyr ![image](https://user-images.githubusercontent.com/56463479/143854322-a017fafd-419e-4130-8a96-ffac060c2183.png)

Hi, there are a few things that I want to check:
1. How many etcd instance in your cluster? If more than one instance, could you help to verify that the data is consistent? If the data in etcd cluster is inconsistent, it can lead to this problem.
2. Does this error occur frequently, does it keep recurring steadily or does it recur occasionally?

**Comment by ChanKunggc** [comment]
> > @iguoyr ![image](https://user-images.githubusercontent.com/56463479/143854322-a017fafd-419e-4130-8a96-ffac060c2183.png)
> 
> Hi, there are a few things that I want to check:
> 
> 1. How many etcd instance in your cluster? If more than one instance, could you help to verify that the data is consistent? If the data in etcd cluster is inconsistent, it can lead to this problem.
> 2. Does this error occur frequently, does it keep recurring steadily or does it recur occasionally?

1、 3 instance that i have . 
2、 it does inevitable that i think. does the CRD version caused the effort ?

now i try again.  same as first result.
![image](https://user-images.githubusercontent.com/56463479/144016727-cc443999-ac9f-4937-99ee-722ac0efad05.png)
![image](https://user-images.githubusercontent.com/56463479/144017014-c0583724-8101-435a-ad7b-8967c66aefb1.png)
![image](https://user-images.githubusercontent.com/56463479/144017116-b731f9c7-2349-420d-950e-8e3d4ee2304a.png)
![image](https://user-images.githubusercontent.com/56463479/144017119-08ed0bcf-edba-4290-a8cd-3262a294e828.png)
![image](https://user-images.githubusercontent.com/56463479/144018008-bf91a02b-774b-4c0f-a6c8-7e16351ca4e0.png)

[controller-manager.log](https://github.com/chaos-mesh/chaos-mesh/files/7624367/controller-manager.log)

**Comment by ChanKunggc** [comment]
i updated every  CRD yaml  in 'helm/crd' to 'apiextensions.k8s.io/v1beta1'. in 1.14 ,we don‘t have 'apiextensions.k8s.io/v1'.

**Comment by iguoyr** [comment]
> I updated every CRD yaml in 'helm/crd' to 'apiextensions.k8s.io/v1beta1'. in 1.14 ,we don‘t have 'apiextensions.k8s.io/v1'.

Could you check the crd of podnetworkchaos using `kubectl get crd podnetworkchaos -o yaml`? Maybe the `status` of podnetworkchaos has some problems.

**Comment by ChanKunggc** [comment]
i tried in k8s 1.19.9. and k8s 1.21.0 ,it injected. 
'v1beta1' in  k8s 1.14.3
![image](https://user-images.githubusercontent.com/56463479/144177043-b725acf9-dc6d-417c-99c1-777d1d30411d.png)
'v1'   in k8s 1.21.0
![image](https://user-images.githubusercontent.com/56463479/144177688-92442c04-7fce-444f-b1b0-5af60c0c2cf8.png)
complete yaml
[v1.log](https://github.com/chaos-mesh/chaos-mesh/files/7631137/v1.log)

**Comment by iguoyr** [comment]
@ChanKunggc How did you install the v1alpha1 crd in kubernetes v1.14?

I tested it on my local cluster (kubernetes v1.14), it should return the result likes:

```yaml
$ kubectl get crd podnetworkchaos.chaos-mesh.org -o yaml
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.4.1
  creationTimestamp: "2021-12-01T07:08:49Z"
  generation: 1
  name: podnetworkchaos.chaos-mesh.org
  resourceVersion: "1764"
  selfLink: /apis/apiextensions.k8s.io/v1beta1/customresourcedefinitions/podnetworkchaos.chaos-mesh.org
  uid: 882789a2-5275-11ec-af60-0242ac120004
spec:
  conversion:
    strategy: None
  group: chaos-mesh.org
  names:
    kind: PodNetworkChaos
    listKind: PodNetworkChaosList
    plural: podnetworkchaos
    singular: podnetworkchaos
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: PodNetworkChaos is the Schema for the PodNetworkChaos API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
...
...
```

Here, the `subresources` field is important, if crd have not declare the `subresource` field, it will produce this error `the server could not find the requested resource` when updating the `status` field.

```yaml
subresources:
    status: {}
```

**Comment by STRRL** [comment]
> I updated every CRD yaml in 'helm/crd' to 'apiextensions.k8s.io/v1beta1'. in 1.14 ,we don‘t have 'apiextensions.k8s.io/v1'.

Hi @ChanKunggc, maybe you could try this: https://github.com/chaos-mesh/chaos-mesh/blob/v2.0.3/manifests/crd-v1beta1.yaml, instead of manually updating.

**Comment by ChanKunggc** [comment]
> > I updated every CRD yaml in 'helm/crd' to 'apiextensions.k8s.io/v1beta1'. in 1.14 ,we don‘t have 'apiextensions.k8s.io/v1'.
> 
> Hi @ChanKunggc, maybe you could try this: https://github.com/chaos-mesh/chaos-mesh/blob/v2.0.3/manifests/crd-v1beta1.yaml, instead of manually updating.

my fault ..... , it does work now
