### ISSUE TITLE
Impact of SecurityMode flag

### ISSUE THREAD

**Issue by ashishgoyal111** [chaos-mesh/chaos-mesh#2490]
## Question

Can you please me understand the importance of **SecurityMode** flag. Also, what will be the security impacts if we set this flag to **False** in our chaos-mesh 2.0 installation.
Please refer me the document related to this if this is already addressed.

**Output of chaosctl**
NA

**Comment by cwen0** [comment]
@ashishgoyal111 This `SecurityMode` flag is used to control permission authentication. If you set it to `False`, you can use chaos dashboard without any limit. More info refers to https://chaos-mesh.org/docs/manage-user-permissions/#enable-or-disable-permission-authentication
