### ISSUE TITLE
unable to create a new plan

### ISSUE THREAD

**Issue by kz2318nkd** [chaos-mesh/chaos-mesh#2492]
## Bug Report

**What version of Kubernetes are you using?**
1.13.3

**What version of Chaos Mesh are you using?**
2.0.3

**What did you do?**
create a scheduler task
![image](https://user-images.githubusercontent.com/56473340/140845751-35f7888e-4bef-42a5-87e5-9380628f8901.png)

**What did you expect to see?**
created successfully

**What did you see instead?**
can't save it successfully

**Output of chaosctl**
![image](https://user-images.githubusercontent.com/56473340/140845445-5ab7390f-5671-4860-b48b-e3f5ecae1706.png)

**Comment by Andrewmatilde** [comment]
Hi @kz2318nkd , could you give more information about the network delay part? It seems I couldn't recurrent the problem.

**Comment by kz2318nkd** [comment]
![image](https://user-images.githubusercontent.com/56473340/140893381-19ce5897-a5f6-4d39-9222-038208a62ebb.png)
I copied the sample code in this page:"https://chaos-mesh.org/zh/docs/define-scheduling-rules/" and use the 'BY YAML' function and save it,But still the same error is reported. It seems that this plan function cannot be used?

**Comment by STRRL** [comment]
Hi @kz2318nkd, Chaos Mesh 2.0 is NOT supported on Kubernetes v1.13. (I think it relates to the migration from OpenAPI v2 to v3.) And Kubernetes 1.15 is the minimum supported version. Please consider upgrading the Kubernetes cluster.

A kindly suggestion, please upgrade the Kubernetes, and 1.13 has been NOT maintained almost 2 years ago, there are so many enhancements and security patches missed. :heart:

**Comment by kz2318nkd** [comment]
Ok, thank you very much for your answer. The k8s version of our current product integration has always been 1.13, which is relatively old and has lasted for several years. I have to communicate with the development classmates about this upgrade issue. It is estimated that it is more difficult. Maybe they are worried that the underlying upgrade will affect the business. Haha, in short, thank you again.

**Comment by STRRL** [comment]
Thanks for your response, you're so welcome, @kz2318nkd! 

I am going to close this issue, feel free to reopen it. :D
