### ISSUE TITLE
Dashboard: show chaos mesh icon in the browser tab

### ISSUE THREAD

**Issue by cwen0** [chaos-mesh/chaos-mesh#2498]
![image](https://user-images.githubusercontent.com/22956341/140910180-24f26c18-cce4-4717-a0d2-6567c99fe672.png)

**Comment by rksharma95** [comment]
i set it up on my local machine and everything is looking fine. can you verify it at your end ?
![chaos-dashboard-screenshot](https://user-images.githubusercontent.com/81104646/150556316-de482bfc-a8fd-4d70-acd6-dc6672a02f03.png)

**Comment by cwen0** [comment]
@rksharma95 Sorry for my late reply! Yes, this issue has been fixed. Thanks for your time.
