### ISSUE TITLE
workflow ui: http request task does not need task number input-box

### ISSUE THREAD

**Issue by iguoyr** [chaos-mesh/chaos-mesh#2505]
## Bug Report

**What version of Kubernetes are you using?**

**What version of Chaos Mesh are you using?**

this issue is related to https://github.com/chaos-mesh/chaos-mesh/pull/2308

**What did you do?**

1. create a new workflow
2. create a 'task' type task node
3. change the task type to 'httprequest', then the task number input-box is still on the page

**What did you expect to see?**
the task number input-box will not show in http request task 

**What did you see instead?**
<img width="1552" alt="截屏2021-11-10 下午2 57 45" src="https://user-images.githubusercontent.com/11804251/141065124-283f40c1-8228-4eea-9c75-1832650407b1.png">

**Output of chaosctl**

**Comment by STRRL** [comment]
This issue could be fixed with c8ffc90 in #2308
