### ISSUE TITLE
Dashboard: load schedule experiment object from archives

### ISSUE THREAD

**Issue by cwen0** [chaos-mesh/chaos-mesh#2508]
## Feature Request

**Is your feature request related to a problem? Please describe:**
 

latest, v2.0.x

**Describe the feature you'd like:**
 

I can find `schedules` object on the archives page, but I can't load it when creating a new one.  

![image](https://user-images.githubusercontent.com/22956341/141118233-6dc5ddd6-6b33-4fa8-94d6-5392f4898bc3.png)

![image](https://user-images.githubusercontent.com/22956341/141118303-5e15f1f9-3dcb-4796-8236-c80da9b08dff.png)

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by cwen0** [comment]
@g1eny0ung I think `LOAD FROM` feature is imperfect yet. We have some TODOs. 
1. support loading the whole workflow. 
2. only show the `schedules` when loading `schedules`.

**Comment by g1eny0ung** [comment]
> @g1eny0ung I think `LOAD FROM` feature is imperfect yet. We have some TODOs.
> 
> 1. support loading the whole workflow.
> 2. only show the `schedules` when loading `schedules`.

Yep, the first function is needed when you want to reuse a big workflow sometimes. I will support it ASAP.

And the second is easier to fix, I will do this first.
