### ISSUE TITLE
Network attacks, how does chaos-mess restrict blast radius of specific pods. 

### ISSUE THREAD

**Issue by zheyu001** [chaos-mesh/chaos-mesh#2527]
## Question
Hi there, 

I'm wondering for networks attacks experiment, how does chaos-mess restrict blast radius of specific pods?

My current understanding is: chaos-mesh created a daemon pod on each legal node, and this daemon pod takes over the network device of labeled pod. But for example, if I'm doing a network bandwidth experiment, what exactly action does daemon pod do to limit ? Does it spam labeled pod directly from daemon pod with a lot of writing? Or it uses [tc](https://wiki.gentoo.org/wiki/Traffic_shaping) to shape the traffic? If using tc, I'm not sure how come it doesn't impact other pods on the same node. Because if I understand correctly, the pods on the same node should share the same physical network device. 

Before asking a question, make sure you have:

- Reviewed relevant Kubernetes information: Google your error messages and look at K8s docs.
- Searched open and closed [GitHub issues](https://github.com/chaos-mesh/chaos-mesh/issues?utf8=%E2%9C%93&q=is%3Aissue)
- Read the documentation:
  - [Chaos Mesh Readme](https://github.com/chaos-mesh/chaos-mesh)
  - [Chaos Mesh Doc](https://chaos-mesh.org/docs)

**Output of chaosctl**

**Comment by FingerLeader** [comment]
Hi, @zheyu001 , sorry for the late response. 
>what exactly action does daemon pod do to limit ?

Chaos Daemon will use `nsexec` to enter the target Pod's network namespace and then use `tc` to add limitation.
>how come it doesn't impact other pods on the same node?

Chaos Daemon will only effect the target Pod's virtual NIC, so other Pods' network can work properly. Each Pod can be treated like VM, but all containers within a Pod share a same network namespace.

**Comment by zheyu001** [comment]
Thanks for the info @FingerLeader ! That's really helpful. 
Since chaos-deamon directly interact with pods virtual NIC, I guess it will never flood the whole network in order to generate a traffic chaos. Is this assumption correct? 

If so, I can understand tc can shape traffic by manipulate qdisc, but how about network delay chaos?

**Comment by FingerLeader** [comment]
I'm glad it helps you.
> I guess it will never flood the whole network in order to generate a traffic chaos. Is this assumption correct?

You are right, only processes in the target processes will be affected.

> how about network delay chaos?

We also use `tc` to add network delay. Actually, most networkChaos use `ipset` and `iptables` to filter network traffic, and then use `tc` to simulate chaos.
