### ISSUE TITLE
time chaos doesn't work on k8s pod

### ISSUE THREAD

**Issue by serlina** [chaos-mesh/chaos-mesh#2533]
## Bug Report

**What version of Kubernetes are you using?**
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.9", GitCommit:"7a576bc3935a6b555e33346fd73ad77c925e9e4a", GitTreeState:"clean", BuildDate:"2021-07-15T20:56:38Z", GoVersion:"go1.15.14", Compiler:"gc", Platform:"linux/amd64"}

**What version of Chaos Mesh are you using?**
chaos mesh 2.0.4
https://chaos-mesh.org/docs/production-installation-using-helm/

**What did you do?**

I install chaos mesh 2.0.4 according to the website using helm.
https://chaos-mesh.org/docs/production-installation-using-helm/

I do time shift chaos to nginx pod, but nothing happens
"""
apiVersion: chaos-mesh.org/v1alpha1
kind: TimeChaos
metadata:
  name: nginxtime
  namespace: chaos-testing
spec:
  mode: all
  selector:
    namespaces:
      - 'default'
    labelSelectors:
      "app": "nginx"
  timeOffset: '-60m'
"""

I get the related events using command "k describe TimeChaos nginxtime -n chaos-testing"
"""
Events:
  Type    Reason           Age   From          Message
  ----    ------           ----  ----          -------
  Normal  Started          21m   desiredphase  Experiment has started
  Normal  FinalizerInited  21m   finalizer     Finalizer has been inited
  Normal  Updated          21m   finalizer     Successfully update finalizer of resource
  Normal  Updated          21m   desiredphase  Successfully update desiredPhase of resource
  Normal  Updated          21m   records       Successfully update records of resource
  Normal  Applied          21m   records       Successfully apply chaos for default/nginx-deployment-5d59d67564-fxjwn/nginx
  Normal  Applied          21m   records       Successfully apply chaos for default/nginx-deployment-5d59d67564-v7jzt/nginx
  Normal  Applied          21m   records       Successfully apply chaos for default/nginx-deployment-5d59d67564-brnl2/nginx
  Normal  Updated          21m   records       Successfully update records of resource
"""

**What did you expect to see?**
time shift injection can work

**What did you see instead?**
time didn't change at all
 **k exec -it nginx-deployment-5d59d67564-fxjwn bash
root@nginx-deployment-5d59d67564-fxjwn:/# date
Wed Nov 17 08:00:48 UTC 2021**

**Comment by YangKeao** [comment]
`TimeChaos` will only affect the running process (at the time when it's injected) in the pod. The process executed later (like the `date` command in your example) will not be affected.

**Comment by serlina** [comment]
> `TimeChaos` will only affect the running process (at the time when it's injected) in the pod. The process executed later (like the `date` command in your example) will not be affected.

@YangKeao , Thanks for your reply, but I thought the " **### timeOffset: '-60m**' " will affect the time in the container , It will produce an offset of one hour. so I just checked this using date command
But from what you said, it will only affect the running process,  when I run the timechaos, there are several processes in the pod, and then how to check whether it worked or not?

**Comment by serlina** [comment]
@YangKeao 
I created a busybox container, and want to see what will happen if we use the timechaos injection, details are as below:

"""
apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox-deployment
  labels:
    app: busybox
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: busybox
  template:
    metadata:
      labels:
        app: busybox
    spec:
      containers:
      - name: busybox
        image: busybox
        imagePullPolicy: IfNotPresent
        command: ['sh', '-c', 'watch -d date']

"""

after I create the deploy, I run the timechaos injection to select the busybox container. Then I used below command to check its result

k get pods | grep busy
busybox-deployment-748ccf74cd-rsc9k                               1/1     Running     0          15m
busybox-deployment-748ccf74cd-srp7z                               1/1     Running     0          15m

 k logs -f busybox-deployment-748ccf74cd-rsc9k
Every 2.0s: date                                            2021-11-19 06:52:59

Fri Nov 19 06:52:59 UTC 2021

From the logs information, I didn't see any change of time, it's just as normal

Could you please help me about this, I really want to know what will happen when we use timechaos, and how to check wether it works or not.

**Comment by YangKeao** [comment]
> > `TimeChaos` will only affect the running process (at the time when it's injected) in the pod. The process executed later (like the `date` command in your example) will not be affected.
> 
> @YangKeao , Thanks for your reply, but I thought the " **### timeOffset: '-60m**' " will affect the time in the container , It will produce an offset of one hour. so I just checked this using date command But from what you said, it will only affect the running process, when I run the timechaos, there are several processes in the pod, and then how to check whether it worked or not?

The most common way to verify the injection is to setup an application who gets the time and print. For example:

```go
package main

import (
        "time"
        "fmt"
)

func main() {
        for {
                fmt.Println(time.Now())
                time.Sleep(1 * time.Second)
        }
}
```

This program will print the time every seconds. If this container is injected with a `TimeChaos`, it will print a wrong time.

**Comment by YangKeao** [comment]
> @YangKeao I created a busybox container, and want to see what will happen if we use the timechaos injection, details are as below:
> 
> """ apiVersion: apps/v1 kind: Deployment metadata: name: busybox-deployment labels: app: busybox spec: replicas: 2 strategy: type: RollingUpdate selector: matchLabels: app: busybox template: metadata: labels: app: busybox spec: containers: - name: busybox image: busybox imagePullPolicy: IfNotPresent command: ['sh', '-c', 'watch -d date']
> 
> """
> 
> after I create the deploy, I run the timechaos injection to select the busybox container. Then I used below command to check its result
> 
> k get pods | grep busy busybox-deployment-748ccf74cd-rsc9k 1/1 Running 0 15m busybox-deployment-748ccf74cd-srp7z 1/1 Running 0 15m
> 
> k logs -f busybox-deployment-748ccf74cd-rsc9k Every 2.0s: date 2021-11-19 06:52:59
> 
> Fri Nov 19 06:52:59 UTC 2021
> 
> From the logs information, I didn't see any change of time, it's just as normal
> 
> Could you please help me about this, I really want to know what will happen when we use timechaos, and how to check wether it works or not.

Yes. The `date` is a process who starts later than the chaos injecting, so it will not be affected. Chaos Mesh doesn't track every newly created program.

I have though about tracking every newly created process. However, the implementation will be ugly (like hooking `fork/exec` system call) and it seems that there are not strong requirement for this feature, so it's finally not implemented.

**Comment by YangKeao** [comment]
If there is not further questions / bug reports, I will close this PR.

Feel free to reopen it (or create a new one), if you are facing any difficulties using Chaos Mesh :smiley_cat:
