### ISSUE TITLE
Sporadic error: Cannot update chaos spec

### ISSUE THREAD

**Issue by noamzafrir** [chaos-mesh/chaos-mesh#2561]
## Bug Report

**What version of Kubernetes are you using?**
1.21

**What version of Chaos Mesh are you using?**
2.0.2

**What did you do?**
Applying pod-kill and pod-failure

**What did you expect to see?**
The failure being applied on the pod.

**What did you see instead?**
I am **sporadically** getting the following error (it can happen on both types of failures: pod-kill, pod-failure)
Error from server (Cannot update chaos spec): error when applying patch:
{"metadata":{"annotations":{"kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"chaos-mesh.org/v1alpha1\",\"kind\":\"PodChaos\",\"metadata\":{\"annotations\":{},\"name\":\"pod-kill-test\",\"namespace\":\"chaos-testing\"},\"spec\":{\"action\":\"pod-kill\",\"mode\":\"one\",\"selector\":{\"labelSelectors\":{\"service\":\"flow-m1-fyykae-m1-fyykae\"},\"namespaces\":[\"default\"]}}}\n"}},"spec":{"selector":{"labelSelectors":{"service":"flow-m1-fyykae-m1-fyykae"}}}}
to:
Resource: "chaos-mesh.org/v1alpha1, Resource=podchaos", GroupVersionKind: "chaos-mesh.org/v1alpha1, Kind=PodChaos"
Name: "pod-kill-test", Namespace: "chaos-testing"
for: "STDIN": admission webhook "vpodchaos.kb.io" denied the request: Cannot update chaos spec

**Output of chaosctl**

**Comment by iguoyr** [comment]
> Error from server (Cannot update chaos spec): error when applying patch:
{"metadata":{"annotations":{"kubectl.kubernetes.io/last-applied-configuration":"{"apiVersion":"chaos-mesh.org/v1alpha1","kind":"PodChaos","metadata":{"annotations":{},"name":"pod-kill-test","namespace":"chaos-testing"},"spec":{"action":"pod-kill","mode":"one","selector":{"labelSelectors":{"service":"flow-m1-fyykae-m1-fyykae"},"namespaces":["default"]}}}\n"}},"spec":{"selector":{"labelSelectors":{"service":"flow-m1-fyykae-m1-fyykae"}}}}
to:
Resource: "chaos-mesh.org/v1alpha1, Resource=podchaos", GroupVersionKind: "chaos-mesh.org/v1alpha1, Kind=PodChaos"
Name: "pod-kill-test", Namespace: "chaos-testing"
for: "STDIN": admission webhook "vpodchaos.kb.io" denied the request: Cannot update chaos spec

@noamzafrir Hi, where did you see this error? (for example, from chaos-controller-manager logs or dashboard events). And did you try to update chaos spec on dashboard?

**Comment by noamzafrir** [comment]
Hi @iguoyr 
Thank you for your quick response.
I see the error on my terminal. I have a "runner" that invokes cli commands and if there's an error it returns the error's info.
Specifically here I invoked "kubectl apply -f"
I am not working with the chaos dashboard at all.

**Comment by iguoyr** [comment]
> Hi @iguoyr Thank you for your quick response. I see the error on my terminal. I have a "runner" that invokes cli commands and if there's an error it returns the error's info. Specifically here I invoked "kubectl apply -f" I am not working with the chaos dashboard at all.

It seems like the PodChaos named `pod-kill-test` already exists in your kubernetes cluster, and Chaos Mesh don't support to modify the spec of chaos object for now, so you'll see this error info. For more details, you could read this issue(https://github.com/chaos-mesh/chaos-mesh/issues/1905).

**Comment by iguoyr** [comment]
If so, you could clean the old PodChaos first (using `kubectl delete podchaos <podchaos-name> -n <podchaos-namespace>` or `kubectl delete -f <podchaos-filename>`) and then re-apply the resource to cluster.

**Comment by noamzafrir** [comment]
Yes, I'm aware of the limitation that it's not possible to modify existing test, but I think that wasn't the case here.
Any additional information I can provide you next time it happens to verify the root cause of this problem?

**Comment by iguoyr** [comment]
> Yes, I'm aware of the limitation that it's not possible to modify existing test, but I think that wasn't the case here. Any additional information I can provide you next time it happens to verify the root cause of this problem?

Sorry, I misunderstand the problem 😢 . If it happens next time, you could put chaos-controller-manager logs in this issue(using `kubectl logs -n <chaos-mesh-namespace> <chaos-controller-manager-pod-name>`), it's helpful to find root cause. :) 

And just in case, put the result of `kubectl get podchaos -n <podchaos-namespace>` and the manifest file content of podchaos would be better. (This message `Cannot update chaos spec` will only show when update webhook is triggered, so it seems like kube-apiserver think the object is already in cluster, which is a bit weird.)

**Comment by noamzafrir** [comment]
OK, will do.
Where is the manifest file located?

**Comment by iguoyr** [comment]
> OK, will do. Where is the manifest file located?

It's the file that `kubectl apply -f <file>` using, it depends on your specific command :) 

here is an example of manifest file from [Chaos Mesh documents](https://chaos-mesh.org/docs/simulate-pod-chaos-on-kubernetes/#pod-failure-example):
```yaml
apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: pod-failure-example
  namespace: chaos-testing
spec:
  action: pod-failure
  mode: one
  duration: '30s'
  selector:
    labelSelectors:
      'app.kubernetes.io/component': 'tikv'
```

**Comment by noamzafrir** [comment]
Understood.
I will update as soon as it happens again.
Thanks.
