### ISSUE TITLE
`trivy` gets a lot of potential security issues

### ISSUE THREAD

**Issue by YangKeao** [chaos-mesh/chaos-mesh#2566]
## Bug Report

Running `trivy image ghcr.io/chaos-mesh/chaos-daemon:latest` gets a lot of security issues. I have taken a look at the list, and they are not that kind of security issue that could be utilized to attack the user of Chaos Mesh, but they are still potential to cause misbehavior or bugs of Chaos Mesh. 

There are two possible solutions:

1. Upgrade the `debian:buster-slim` to `debain:bulleyes-slim`.
2. Add a `buster-backport` source to the apt registry.

I've tried the first solution, the report is not fine (even worse than the older one on the number, because new version brings new bugs). Here is the report.

[chaos-daemon.txt](https://github.com/chaos-mesh/chaos-mesh/files/7606613/chaos-daemon.txt)

Do you have any suggestion on fixing the problem? I don't have experience on handling the security issues (especially the security issues in dependent environment, most of which are irrelative with the function of Chaos Mesh). I don't know what is the correct attitude I need to pay to 😟 (and don't know what a hacker can do or harm our users through these bugs)

**Comment by craig-seeman** [comment]
@YangKeao Have you tried to add a `apt-get upgrade -y` directly after the `apt-get update` in the dockerfile(s) on a build and then try another scan? I'm curious if it will have some positive effects as well.

**Comment by YangKeao** [comment]
> @YangKeao Have you tried to add a `apt-get upgrade -y` after the `apt-get update` in the dockerfile(s) on a build and then try another scan? I'm curious if it will have some positive effects as well.

No. I have checked the version of "curl" (which is the source of a "CRITICAL" error) is the newest as described in the [registry](https://packages.debian.org/search?searchon=sourcenames&keywords=curl). (However, the two versions of "curl": `7.64.0-4+deb10u2` and `7.74.0-1.3` have different "CRITICAL" problems 😿

**Comment by STRRL** [comment]
Maybe the situation is worse than we recognize, there are hundreds of vulnerabilities (425 with v2.1.5) in our container images.

https://artifacthub.io/packages/helm/chaos-mesh/chaos-mesh?modal=security-report
