### ISSUE TITLE
Swagger API not appears in Dashboard

### ISSUE THREAD

**Issue by ivgenis** [chaos-mesh/chaos-mesh#2574]
Hi, I've upgraded to v2.0.5.
In my previous version (it was v0.3.1 I think) There was a link to swagger API from the Chaos Dashboard.
In the new version I can't find it in the Dashboard.
Is it still exists?
Thanks

**Comment by cwen0** [comment]
@ivgenis The API page was hidden. You can open URL "host:port/api/swagger/index.html" to access it.

**Comment by STRRL** [comment]
I am going to close this issue. Feel free to reopen it.
