### ISSUE TITLE
模拟loss网络故障后抓包容器网卡未看到丢包

### ISSUE THREAD

**Issue by lklkxcxc** [chaos-mesh/chaos-mesh#2583]
## Question
模拟loss网络故障，tcpdump抓包容器eth0网卡，没有看到很多丢包的现象，请问是正常的吗？
 mode: one
  action: loss
  duration: 10m
  loss:
    loss: '1'
    correlation: '0'
  direction: to
chaos-mesh版本为: 2.0.5

**Comment by cwen0** [comment]
@lklkxcxc `loss: '1'` represents the percent of network loss is 1%.

**Comment by lklkxcxc** [comment]
@cwen0 Set loss to 99 .Tcpdump failed to see a large number of lost packets, resulting in retransmission. Great tool anyway!
