### ISSUE TITLE
JVMChaos: target process doesn't respond within 10500ms or hotspot vm not loaded

### ISSUE THREAD

**Issue by haizi-cui** [chaos-mesh/chaos-mesh#2588]
The error is shown below：
![image](https://user-images.githubusercontent.com/63744634/144251968-8752a899-e712-4fd4-983e-4ee10c17256d.png)

**Comment by WangXiangUSTC** [comment]
Would you please check the permissions of this file? Which user started the Java process?

**Comment by haizi-cui** [comment]
> 你能检查一下这个文件的权限吗？哪个用户启动了 Java 进程？

**Comment by haizi-cui** [comment]
> 你能检查一下这个文件的权限吗？哪个用户启动了 Java 进程？

No .java_ Pid25385 file

**Comment by haizi-cui** [comment]
Solution：Because the host kernel version is too low, the experiment is normal after upgrading to 4.2

**Comment by WangXiangUSTC** [comment]
The reason was that the Java Attach API involved a bug in the container, which was then fixed using Linux kernel 4.1 features
https://bugs.openjdk.java.net/browse/JDK-8179498

**Comment by STRRL** [comment]
It seems here is another way to bypass the issue caused by cross-container JVM attach. We are going to make more work in the future. Thanks to our contributors!
