### ISSUE TITLE
helm install error（when i use pvcs，it occured）

### ISSUE THREAD

**Issue by kxzonly** [chaos-mesh/chaos-mesh#2589]
## Bug Report

**What version of Kubernetes are you using?**
1.19.8
Actually，it will occur at any version

**What version of Chaos Mesh are you using?**
2.1.0

**What did you do?**
when i change pvc config ，helm install failed
当我开启helm脚本中的pvc配置时，将会出现此问题
Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: apiVersion not set
![image](https://user-images.githubusercontent.com/37934520/144348587-be1eff9e-95d3-41b9-9793-3d261680e7c9.png)

use "helm template -f values.yaml . >deployChart.yaml",i found this annotation in deployChart.yaml
使用helm template -f values.yaml . >deployChart.yaml查看deployChart.yaml，发现apiVersion字段被注释掉了
![image](https://user-images.githubusercontent.com/37934520/144348620-59c8a994-7c39-4186-9f4b-26a264967009.png)

Compared with the previous version, it seems to be caused by the license statement in the chaos-dashboard-pvc.yaml file, but I tried to modify it and it couldn’t be restored. Finally, I had to delete all the licenses and restore them to normal.
对比了一下之前的版本，貌似是由于chaos-dashboard-pvc.yaml文件中的license声明导致的，但我尝试修改也不能恢复，最后只能把license全部删除后恢复正常

**What did you expect to see?**
helm install success
helm安装成功

**What did you see instead?**

**Output of chaosctl**

**Comment by cwen0** [comment]
@kxzonly Thanks for your report! You can remove `-` to fix this issue.  https://github.com/chaos-mesh/chaos-mesh/blob/master/helm/chaos-mesh/templates/chaos-dashboard-pvc.yaml#L16-L17 

Fixed code : 

```
{{- if .Values.dashboard.create }}
{{- if .Values.dashboard.persistentVolume.enabled }}
{{- if not .Values.dashboard.persistentVolume.existingClaim }}
``` 

Can you create a pr to fix it?

**Comment by kxzonly** [comment]
OK,I forked code and fix it now

> @kxzonly Thanks for your report! You can remove `-` to fix this issue. https://github.com/chaos-mesh/chaos-mesh/blob/master/helm/chaos-mesh/templates/chaos-dashboard-pvc.yaml#L16-L17
> 
> Fixed code :
> 
> ```
> {{- if .Values.dashboard.create }}
> {{- if .Values.dashboard.persistentVolume.enabled }}
> {{- if not .Values.dashboard.persistentVolume.existingClaim }}
> ```
> 
> Can you create a pr to fix it?

**Comment by kxzonly** [comment]
@cwen0 I finished pr #2591 ,Can I close this issue or trans to you?

**Comment by cwen0** [comment]
> @cwen0 I finished pr #2591 ,Can I close this issue or trans to you?

@kxzonly When pr #2591 merged, this issue will be closed automatically.
