### ISSUE TITLE
`make generate should` not depend on `make generate-ctrl`

### ISSUE THREAD

**Issue by FingerLeader** [chaos-mesh/chaos-mesh#2594]
## Bug Report

**What version of Chaos Mesh are you using?**
latest
**What did you do?**
I tried to use `make generate` to generate `zz_generated.deepcopy.go` after changing a struct in `stresschaos_type.go`. 

**What did you expect to see?**
New `DeepCopyInto` method be generated.

**What did you see instead?**
![image](https://user-images.githubusercontent.com/43462394/144543732-80a0fc1e-1bed-4ed0-9d51-f8424df71372.png)
`make generate` depends on `make generate-ctrl`, but `maek generate-ctrl` can not work when `zz_generated.deepcopy.go` is not generated.

**Comment by iguoyr** [comment]
related to https://github.com/chaos-mesh/chaos-mesh/issues/2419 :)
