### ISSUE TITLE
Enable object selector for permission control. 

### ISSUE THREAD

**Issue by zheyu001** [chaos-mesh/chaos-mesh#2599]
## Feature Request

**Describe the feature you'd like:**
Currently chaos-mesh support namespace filtering which is pretty good. We are wondering is there any chance chaos-mesh can extend this one step further by ~~using object selector while injecting daemon set~~ implicit label checking.

I know currently when schedule an experiment, I can use label selector and etc. But goal of this request is to prevent experiment launched on wrong pod. 

Consider below **use case**:
Team A has a pod "test1" in namespace "teamA", while teamB has a similar pod "test1" in namespace "teamB", and teamB operator trying to launch an experiment for pod "test1" but accidentally chose pod "test1" in teamA namespace. 

If team A ever run chaos-mesh experiment, their namespace will be annotated with "chaos-mesh.org/inject: enabled", thus team B can still successfully launch experiment in team A's namespace. But if use object selector, as long as team A doesn't explicitly label their pod with specific label, this accident can be avoid. 

When I say object selector I mean something like [this](https://github.com/kubernetes-sigs/aws-load-balancer-controller/pull/1958/files), basically AWS LB controller is using it to decide whether to path a pod with readiness gate. I guess chaos-mesh can use similar logic to decide to ~~inject daemon set~~ run an experiment or not or similar permission control like namespace filtering.

**Comment by Hexilee** [comment]
Does it mean users need to label all pods they want to inject? I think users can add `objectSelector` manually in admission webhooks by their requirements.

**Comment by zheyu001** [comment]
> Does it mean users need to label all pods they want to inject? 

Forgive my wordings. I just realized the real thing I'm requesting is: chaos-mesh should allow user to configure whether allowing all pods to run experiment or only pods with chaos-mesh label can run, it doesn't necessarily means DS injection. 
The chaos-mesh label should be added by users explicitly, this means users aware their pods are at risk and should pay attention to them. It also means users' pods without label is safe from experiment.

Now let's get back to use cases in the description, team B accidentally applied an experiment for pod: test1 in namespace teamA. But teamA didn't label any of their pods, the experiment will fail, team A will not be impacted. In the case team A does labeled their pods, they are aware of their pods are at risk, thus even there's an accidental experiment from other team, team A are still prepared, to some extent. Worst case they can remove the label from their pods to prevent further impact.  

This is different from the existing feature of using label selector to select pods. As my request forced users to pay attention to their labeled pods. 

Another use case of this feature is: team A has 100 pods serving an online application, they want to run experiment on pod: 99 and only labeled this pod with chaos mesh label.  While operator creating experiment, he/she accidentally select pod from 1 to 99. In this case, the experiment will still not impact any pods other than 99. 

> I think users can add objectSelector manually in admission webhooks by their requirements.

This is definitely doable. But, chaos-experiment is dangerous, better build-in blast radius control will make chaos-mesh more persuasive to be installed even in production stage. This feature request can help extend the blast radius control in my humble opinion. Please do correct me if chaos-mesh is already providing this kind of feature.

**Comment by Hexilee** [comment]
I think I understand your requirements, but I prefer a build-in label to protect pods as the `objectSelector` supports the `NotIn` operator.

For example, add the following `objectSelector` in the admission webhooks configuration:

```YAML
objectSelector:
  matchExpressions:
    - key: app.chaos-mesh.io/injection
      operator: NotIn
      values:
        - protected
```

Then, team A can protect their pods from experiments by adding the label `app.chaos-mesh.io/injection: protected`.

**Comment by zheyu001** [comment]
If I want to upgrade chaos-mesh to new version in future, will this change be override?

**Comment by Hexilee** [comment]
I'm going to talk about it with my team this week, then I will update the decision and progress in this issue.

**Comment by zheyu001** [comment]
Sure. Thanks a lot! 

BTW, [this thread](https://github.com/chaos-mesh/chaos-mesh/issues/2222) basically is concerning about similar issue:
