### ISSUE TITLE
Issue about gRPC chaos

### ISSUE THREAD

**Issue by chenhy97** [chaos-mesh/chaos-mesh#2611]
The roadmap shows that chaos-mesh has supported gRPC chaos. 
However, I can only find the HTTPChaos guidance in the docs.
Are there any example about how to use gRPC chaos with chaos-mesh?

**Comment by Hexilee** [comment]
Sorry, the roadmap is wrong, we do not support gRPC chaos now.  We will support it after https://github.com/chaos-mesh/rs-tproxy/pull/19 is complete.
