### ISSUE TITLE
feat: openapi to typescript schemas

### ISSUE THREAD

**Issue by g1eny0ung** [chaos-mesh/chaos-mesh#2615]
## Feature Request

**Is your feature request related to a problem? Please describe:**

The chaos types are split between the front-end and back-end, and we can‘t reuse types that have already been defined.

This leads to several problems:

1. The front-end needs to be manually synchronized when there is an update to the type definition.
2. As **`1`** continues to emerge, there are more and more things to maintain manually.

So the best solution is to automate the generation of the schemas needed for the front-end.

**Describe the feature you'd like:**

There has an automation tool that can sync changes from openapi definition.

**Describe alternatives you've considered:**

No.

**Teachability, Documentation, Adoption, Migration Strategy:**

https://swagger.io/specification/v2/

https://github.com/ferdikoomen/openapi-typescript-codegen

**Comment by STRRL** [comment]
I also found a library called `openapi-generator-cli`, it seems it's the official cli tool.
