### ISSUE TITLE
Failed to apply chaos: rpc error: code = Unknown desc = Error response from daemon: client version 1.41 is too new. Maximum supported API version is 1.40

### ISSUE THREAD

**Issue by chenpfeisoo** [chaos-mesh/chaos-mesh#2625]
![image](https://user-images.githubusercontent.com/18147157/145406787-5c003fd8-c647-47bc-add4-c3d2b16fe30c.png)

![image](https://user-images.githubusercontent.com/18147157/145406727-0e186a7c-359a-4a53-af1d-5dcca7fb9c65.png)

**Comment by Hexilee** [comment]
Please refer to https://chaos-mesh.org/zh/docs/faqs/#q-daemon-throws-an-error-similar-to-version-141-is-too-new-the-maximum-supported-api-version-is-139, is this problem resolved?

**Comment by YangKeao** [comment]
If the former comment doesn't solve your problem. Feel free to reopen this issue.

**Comment by caozhaoliang** [comment]
我遇到了这个问题，但是我的k8s节点上的docker版本API却是1.39 能否问一下，这个报错中的daemon版本具体是指什么版本呢？
![企业微信截图_17025230298914](https://github.com/chaos-mesh/chaos-mesh/assets/24834513/1800f915-4f89-421b-a84d-f941c06dc0ca)
