### ISSUE TITLE
使用JVMChaos作用于SpringBoot APP异常

### ISSUE THREAD

**Issue by lovelybowen** [chaos-mesh/chaos-mesh#2632]
## Question
版本：chaos-mesh v2.1.0

操作步骤：
1、在chaos-dashboard页面添加JVMChaos，配置如下：

kind: JVMChaos
apiVersion: chaos-mesh.org/v1alpha1
metadata:
  namespace: dev
  name: aaada
  annotations:
    experiment.chaos-mesh.org/pause: 'true'
spec:
  selector:
    namespaces:
      - dev
    labelSelectors:
      app: coupon-demo
  mode: one
  action: exception
  name: aaada
  class: CouponManageController
  method: detail
  value: ''
  exception: java.io.IOException("BOOM")
  latency: 0
  cpuCount: 0
  memType: ''
  port: 9277
  ruleData: ''

2、chaos dashboard日志报错：
![image](https://user-images.githubusercontent.com/80300619/145607030-1add3bf9-daff-4e90-a441-55c4bcae7396.png)

3、待测试的SpringBoot APP 日志报错：
![image](https://user-images.githubusercontent.com/80300619/145607190-e122e57e-75bc-4bf1-82a4-5b1f9864079b.png)

**Comment by lovelybowen** [comment]
之前用的是open-jdk:8u302的镜像，就会注入不了JVMChaos。刚试了下，用的demo(https://github.com/WangXiangUSTC/byteman-example/blob/main/example.helloworld/Dockerfile)中的镜像，是可以正常注入JVMChaos了。

**Comment by WangXiangUSTC** [comment]
Hi, the error `attempting to load Byteman agent more than once` means have already loaded Byteman agent success, can't load again, and Chaos Mesh will ignore this error, So maybe it is not the real problem. Do you run success on your SpringBoot APP later?
