### ISSUE TITLE
refractor build script

### ISSUE THREAD

**Issue by YangKeao** [chaos-mesh/chaos-mesh#2636]
Here is a tracking issue for the implementation of https://github.com/chaos-mesh/rfcs/pull/27, and the roadmap:

- [ ] Add a script to rewrite the `COMPILE_GO_TEMPLATE`, `IMAGE_TEMPLATE` and `BUILD_IN_DOCKER_TEMPLATE` #2640
- [ ] Manage the lifecycle of `build-env` and `dev-env` (check whether they are outdated and needed to update)
- [ ] Review the scripts inside `./hack`, maybe some of them is not needed now.
- [ ] Review the environment variable and documents in `Makefile`, some of them can be removed.

This issue can stop at any step, or add / remove some of them, if the code base is clean enough to read or extend.

**Comment by STRRL** [comment]
👏 https://github.com/chaos-mesh/chaos-mesh/issues/2640

**Comment by STRRL** [comment]
closed by #2640
