### ISSUE TITLE
Some specified chaos experiment returns "not found" on Chaos Dashboard

### ISSUE THREAD

**Issue by cwen0** [chaos-mesh/chaos-mesh#2641]
## Bug Report

**What version of Kubernetes are you using?**
 

v1.22

**What version of Chaos Mesh are you using?**

master-g63345a39946779

**What did you do?**
 

A chaos experiments always keep the `Injecting` status and return a `not found` error when clicking it.  
![image](https://user-images.githubusercontent.com/22956341/145957307-3bc9416d-999f-4367-95b2-d0aa84d28f33.png)

Then click the `Archive` button, return a `not found` error too. 

![image](https://user-images.githubusercontent.com/22956341/145957554-476b5c9e-4933-495a-b028-8ebde3d45f12.png)
![image](https://user-images.githubusercontent.com/22956341/145957589-f53cbc7e-837c-41f8-a159-b53e99c03b08.png)

**What did you expect to see?**

**What did you see instead?**

**Output of chaosctl**

**Comment by cwen0** [comment]
Dashboard log: 

```
[GIN] 2021/12/16 - 09:53:11 | 200 |   87.597026ms |      10.244.0.0 | GET      "/api/experiments"
2021-12-16T09:53:16.141Z        ERROR   apiserver       error.api.resource_not_found
github.com/chaos-mesh/chaos-mesh/pkg/dashboard/apiserver/utils.SetAPIError
        /mnt/pkg/dashboard/apiserver/utils/error.go:70
github.com/chaos-mesh/chaos-mesh/pkg/dashboard/apiserver/experiment.(*Service).delete
        /mnt/pkg/dashboard/apiserver/experiment/experiment.go:332
github.com/gin-gonic/gin.(*Context).Next
        /tmp/go/pkg/mod/github.com/gin-gonic/gin@v1.7.2/context.go:165
github.com/gin-gonic/gin.CustomRecoveryWithWriter.func1
        /tmp/go/pkg/mod/github.com/gin-gonic/gin@v1.7.2/recovery.go:99
github.com/gin-gonic/gin.(*Context).Next
        /tmp/go/pkg/mod/github.com/gin-gonic/gin@v1.7.2/context.go:165
github.com/gin-gonic/gin.LoggerWithConfig.func1
        /tmp/go/pkg/mod/github.com/gin-gonic/gin@v1.7.2/logger.go:241
github.com/gin-gonic/gin.(*Context).Next
        /tmp/go/pkg/mod/github.com/gin-gonic/gin@v1.7.2/context.go:165
github.com/gin-gonic/gin.(*Engine).handleHTTPRequest
        /tmp/go/pkg/mod/github.com/gin-gonic/gin@v1.7.2/gin.go:489
github.com/gin-gonic/gin.(*Engine).ServeHTTP
        /tmp/go/pkg/mod/github.com/gin-gonic/gin@v1.7.2/gin.go:445
net/http.serverHandler.ServeHTTP
        /usr/local/go/src/net/http/server.go:2867
net/http.(*conn).serve
        /usr/local/go/src/net/http/server.go:1932
[GIN] 2021/12/16 - 09:53:16 | 404 |     762.681µs |      10.244.0.0 | DELETE   "/api/experiments/b59eeed0-54aa-4c2c-9538-0a8e65488235"
```

**Comment by cwen0** [comment]
Chaos Dashboard pod was recreated, and then chaos experiments had nothing updated. So the chaos experiment record won't be stored in Chaos Dashboard. When users want to delete this experiment, the chaos dashboard will search in Chaos Dashboard Database, and then `not found` will be returned.

**Comment by YangKeao** [comment]
> Chaos Dashboard pod was recreated, and then chaos experiments had nothing updated. So the chaos experiment record won't be stored in Chaos Dashboard. When users want to delete this experiment, the chaos dashboard will search in Chaos Dashboard Database first, and then `not found` will be returned.

It seems that the collector will reconcile all existing request at first, and I cannot reproduce this problem in my development environment with following steps:

1. create a continuous network chaos
2. this networkchaos steps into running phase
3. delete the dashboard pod, a new one will be created
4. click `Archive` button.

It works well.

**Comment by YangKeao** [comment]
Is there any error related with collector reported in the log?

**Comment by cwen0** [comment]
> Is there any error related with collector reported in the log? 

I didn't find the related error info in the dashboard log. 

![image](https://user-images.githubusercontent.com/22956341/146924693-df01c255-4d38-4006-b4f7-1e76c810e65c.png)

[dashboard.log](https://github.com/chaos-mesh/chaos-mesh/files/7755019/dashboard.log)

**Comment by cwen0** [comment]
The issue was caused by that chaos experiments being blocked by delete action, and then chaos dashboard restarted and the collector will ignore the deleting chaos experiment.
