### ISSUE TITLE
Inaccurate title for non-K8s chaos experiments on Chaos Dashboard

### ISSUE THREAD

**Issue by milasuperstar** [chaos-mesh/chaos-mesh#2643]
## Feature Request

**Is your feature request related to a problem? Please describe:**
The button for non-K8s chaos experiments on Chaos Dashboard is inaccurate.  And "Physic" doesn't correspond with the naming convention on the docs site.
![image](https://user-images.githubusercontent.com/72733948/145965876-8a93b464-9ac3-466c-bbfb-0dd205ac344c.png)

**Describe the feature you'd like:**
Rename the button to "PHYSICAL MACHINE"

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by cwen0** [comment]
How about renaming it to 'Hosts"?
