### ISSUE TITLE
does new experiment will generate new Deepcopy file when execute make generate？

### ISSUE THREAD

**Issue by ChanKunggc** [chaos-mesh/chaos-mesh#2644]
## Question

Before asking a question, make sure you have:

- Reviewed relevant Kubernetes information: Google your error messages and look at K8s docs.
- Searched open and closed [GitHub issues](https://github.com/chaos-mesh/chaos-mesh/issues?utf8=%E2%9C%93&q=is%3Aissue)
- Read the documentation:
  - [Chaos Mesh Readme](https://github.com/chaos-mesh/chaos-mesh)
  - [Chaos Mesh Doc](https://chaos-mesh.org/docs)

’make generate‘ didn't update  deepcopy file

**Comment by ChanKunggc** [comment]
‘2.0.3’ is succeed,but ‘2.1.0’ couldn't.

**Comment by ChanKunggc** [comment]
@YangKeao @iguoyr

**Comment by YangKeao** [comment]
It should! (and it's a bug not to generate). I'm not sure whether you are facing the same problem as #2594 and #2419. If so, I've already submit a PR #2600 to fix this problem (however, there are still some confusing CI errors left)

**Comment by ChanKunggc** [comment]
> It should! (and it's a bug not to generate). I'm not sure whether you are facing the same problem as #2594 and #2419. If so, I've already submit a PR #2600 to fix this problem (however, there are still some confusing CI errors left)

i resolved yesterday ，same as #2594 problem，it took me a long long time. 心累- -
![image](https://user-images.githubusercontent.com/56463479/146119747-fa891a63-bdef-4571-af9a-fb71184484c4.png)
