### ISSUE TITLE
subprocesses of chaos-daemon cannot gracefully stop

### ISSUE THREAD

**Issue by Hexilee** [chaos-mesh/chaos-mesh#2650]
## Bug Report

**What version of Chaos Mesh are you using?**

v2.x.x

**What did you do?**
delete or upgrade chaos-daemon.

**What did you expect to see?**
all injected faults are recovered after chaos-daemon stops.

**What did you see instead?**
some faults (like http chaos) are not recovered.

**The Reason**
I found subprocesses of chaos-daemon are killed forcibly by the `runc`:

![image](https://user-images.githubusercontent.com/25378640/146162033-ff160e5a-68f1-449c-bd7b-a7041aa17645.png)
![ps](https://user-images.githubusercontent.com/25378640/146162045-044741eb-705e-4234-975e-795751323eb3.png)

`runc` sends SIGTERM to chaos-daemon, and the subprocesses (`nsexec` and `tproxy`) become orphans. Then, `runc` sends SIGKILL to `nsexec` and `tproxy` and they exit without graceful shutdown.

**Solutions**
We can handle SIGTERM in chaos-daemon, kill all subprocesses managed by the `bpm`, and wait for their shutdowns.

**Comment by Andrewmatilde** [comment]
@YangKeao ,does iochaos have the same problem?

**Comment by STRRL** [comment]
> runc sends SIGTERM to chaos-daemon, and the subprocesses (nsexec and tproxy) become orphans. Then, runc sends SIGKILL to nsexec and tproxy and they exit without graceful shutdown.

I think the SIGKILL is sent by kernel, related to the pid cgroup controller. IIRC, kernel would send SIGKILL to all the processes in a pid namespace, if PID 1 has exited.
