### ISSUE TITLE
apply fail: fail to set routes: code: 2, msg: iptables v1.8.2 (legacy): Couldn't load match `socket':No such file or directory Try `iptables -h' or 'iptables --help' for more information.

### ISSUE THREAD

**Issue by ChanKunggc** [chaos-mesh/chaos-mesh#2651]
## Bug Report

**What version of Kubernetes are you using?**

1.14.4
**What version of Chaos Mesh are you using?**

2.1.0 made by myself
**What did you do?**

add httpchaos
**What did you see instead?**
![image](https://user-images.githubusercontent.com/56463479/146202297-dfb54631-35a6-4788-9535-3763dc448a57.png)
**Output of chaosctl**

yaml
![image](https://user-images.githubusercontent.com/56463479/146207182-cfb811f4-a38a-4bca-9a85-ef3a9f556cfc.png)

**Comment by ChanKunggc** [comment]
Hi @Andrewmatilde ,Is this problem related to kernel modules in physical machine ?

**Comment by Andrewmatilde** [comment]
Do you mind telling us your Linux distribution & it's version?

**Comment by Andrewmatilde** [comment]
> @Andrewmatilde ![image](https://user-images.githubusercontent.com/56463479/146295038-c8517134-a4fd-462a-8338-8b75d8ca3921.png) ![image](https://user-images.githubusercontent.com/56463479/146295064-8bbf2aab-1236-4c95-8ede-43e462897820.png) lsmod ![image](https://user-images.githubusercontent.com/56463479/146295171-b4b185cf-cb11-4444-a57e-05346bb90892.png)

@ChanKunggc , thanks for your reply.
Can you run command :
```
iptables -t mangle -N DIVERT
iptables -t mangle -A DIVERT -j MARK --set-mark 1
iptables -t mangle -A DIVERT -p tcp -m socket -j DIVERT
```
in your physical machine?
If the command returns error, I think the problem may also be related to some missing parts in kernel , because the iptables socket extension works well on my centos 7.3 with kernel version 3.10.0-1127.19.1.el7.x86_64.
If it works the problem is caused by `HTTP Chaos didn't mount /lib/modules in to chaos-daemon` , we will merge the fix into the later release versions.

**Comment by ChanKunggc** [comment]
> > @Andrewmatilde ![image](https://user-images.githubusercontent.com/56463479/146295038-c8517134-a4fd-462a-8338-8b75d8ca3921.png) ![image](https://user-images.githubusercontent.com/56463479/146295064-8bbf2aab-1236-4c95-8ede-43e462897820.png) lsmod ![image](https://user-images.githubusercontent.com/56463479/146295171-b4b185cf-cb11-4444-a57e-05346bb90892.png)![image](https://user-images.githubusercontent.com/56463479/146314980-1f5416fb-4a3f-47cc-b50d-8813c3b77c9d.png)> 
> @ChanKunggc , thanks for your reply. Can you run command :
> 
> ```
> iptables -t mangle -N DIVERT
> iptables -t mangle -A DIVERT -j MARK --set-mark 1
> iptables -t mangle -A DIVERT -p tcp -m socket -j DIVERT
> ```
> 
> in your physical machine? If the command returns error, I think the problem may also be related to some missing parts in kernel , because the iptables socket extension works well on my centos 7.3 with kernel version 3.10.0-1127.19.1.el7.x86_64. If it works the problem is caused by `HTTP Chaos didn't mount /lib/modules in to chaos-daemon` , we will merge the fix into the later release versions.


this command didn't success.
`iptables -t mangle -A DIVERT -p tcp -m socket -j DIVERT`
![image](https://user-images.githubusercontent.com/56463479/146315122-cdcda1f1-cb38-40c9-8e55-5be686c8a049.png)

**Comment by Andrewmatilde** [comment]
> iptables -t mangle -A DIVERT -p tcp -m socket -j DIVERT

Sorry , that's my fault `iptables -t mangle -A DIVERT -p tcp -m socket -j DROP ` may work.

**Comment by ChanKunggc** [comment]
> @ChanKunggc
> 
> > iptables -t mangle -A DIVERT -p tcp -m socket -j DIVERT
> 
> Sorry , that's my fault `iptables -t mangle -A DIVERT -p tcp -m socket -j DROP ` may work.


@Andrewmatilde 
![image](https://user-images.githubusercontent.com/56463479/146318418-0fb48f54-e195-4b2a-8db5-52c835269cd7.png)

**Comment by Andrewmatilde** [comment]
> > @ChanKunggc
> > > iptables -t mangle -A DIVERT -p tcp -m socket -j DIVERT
> > 
> > 
> > Sorry , that's my fault `iptables -t mangle -A DIVERT -p tcp -m socket -j DROP ` may work.
> 
> @Andrewmatilde ![image](https://user-images.githubusercontent.com/56463479/146318418-0fb48f54-e195-4b2a-8db5-52c835269cd7.png)

Do you mind telling us your iptables version?

**Comment by ChanKunggc** [comment]
> 
@Andrewmatilde 
![image](https://user-images.githubusercontent.com/56463479/146319597-3f1525be-87a0-4cc4-a499-488179e52148.png)

**Comment by ChanKunggc** [comment]
> 
> @ChanKunggc Do you mind telling us your iptables version?

@Andrewmatilde 
![image](https://user-images.githubusercontent.com/56463479/146319715-eabf0d0f-58f0-4fe0-af96-e6c201ccc072.png)

**Comment by Andrewmatilde** [comment]
![image](https://user-images.githubusercontent.com/32479514/146320022-81c9b124-dded-4bc8-bd55-c02d67b86476.png)
@ChanKunggc , I tihnk the problem may caused by some missing parts in your kernel.

**Comment by STRRL** [comment]
> ![image](https://user-images.githubusercontent.com/32479514/146320022-81c9b124-dded-4bc8-bd55-c02d67b86476.png) @ChanKunggc , I tihnk the problem may caused by some missing parts in your kernel.

Is it possible to provide a list of kernel modules required by Chaos Mesh? IIRC, @YangKeao have made a list for that, but I could not find it on our document site.

**Comment by Andrewmatilde** [comment]
> > ![image](https://user-images.githubusercontent.com/32479514/146320022-81c9b124-dded-4bc8-bd55-c02d67b86476.png) @ChanKunggc , I tihnk the problem may caused by some missing parts in your kernel.
> 
> Is it possible to provide a list of kernel modules required by Chaos Mesh? IIRC, @YangKeao have made a list for that, but I could not find it on our document site.

I think the problem may not caused by a leak of kernel modules, but some code inside the kernel modules is not compiled well or some other problem.

**Comment by YangKeao** [comment]
> > > ![image](https://user-images.githubusercontent.com/32479514/146320022-81c9b124-dded-4bc8-bd55-c02d67b86476.png) @ChanKunggc , I tihnk the problem may caused by some missing parts in your kernel.
> > 
> > 
> > Is it possible to provide a list of kernel modules required by Chaos Mesh? IIRC, @YangKeao have made a list for that, but I could not find it on our document site.
> 
> I think the problem may not caused by a leak of kernel modules, but some code inside the kernel modules is not compiled well or some other problem.

I guess the related config (and module) is `CONFIG_NETFILTER_XT_MATCH_SOCKET`, and I'm not sure whether it's included by the package `kernel-modules-extra` (but in most case, it is).

**Comment by ChanKunggc** [comment]
@YangKeao It may be caused by [Tencent kernel ](https://github.com/Tencent/TencentOS-kernel) that i guess .
Can you give me some opinion ? like some ways of  check kernel modules or else .

**Comment by ChanKunggc** [comment]
> @YangKeao It may be caused by [Tencent kernel ](https://github.com/Tencent/TencentOS-kernel) that i guess . Can you give me some opinions ? like some ways of check kernel modules or else .

**Comment by ChanKunggc** [comment]
may be `CONFIG_NETFILTER_XT_MATCH_SOCKET` and `NETFILTER_XT_TARGET_TPROXY`  are missing ,  [kernal-doc](https://www.kernel.org/doc/Documentation/networking/tproxy.txt)
![image](https://user-images.githubusercontent.com/56463479/146482139-3f595364-069f-4f05-b529-d9f1d74fbd3a.png)
and Tencent kernel didn't set in [default-config](https://github.com/Tencent/TencentOS-kernel/blob/0f77c3ff8f15da8a3a7337a1aca88cb7d72636df/package/default/config.default#L1126-L1127)
![image](https://user-images.githubusercontent.com/56463479/146482502-061faa36-8a41-416b-869d-d951e8d38396.png)

**Comment by YangKeao** [comment]
> May be `CONFIG_NETFILTER_XT_MATCH_SOCKET` and `NETFILTER_XT_TARGET_TPROXY` are missing , [kernal-doc](https://www.kernel.org/doc/Documentation/networking/tproxy.txt) ![image](https://user-images.githubusercontent.com/56463479/146482139-3f595364-069f-4f05-b529-d9f1d74fbd3a.png) And Tencent kernel didn't set in [default-config](https://github.com/Tencent/TencentOS-kernel/blob/0f77c3ff8f15da8a3a7337a1aca88cb7d72636df/package/default/config.default#L1126-L1127) ![image](https://user-images.githubusercontent.com/56463479/146482502-061faa36-8a41-416b-869d-d951e8d38396.png)

😢 A better way to check kernel config is `zcat /proc/config.gz`. If `/proc/config.gz` doesn't exist, you can find some `config-` files under `/boot`, which may contain the kernel config. I have checked this config is `CONFIG_NETFILTER_XT_MATCH_SOCKET=m` on centos 7, which means it's compiled as module.

@Andrewmatilde @Hexilee I wonder why httpchaos needs to `-m socket`?

**Comment by Andrewmatilde** [comment]
> > May be `CONFIG_NETFILTER_XT_MATCH_SOCKET` and `NETFILTER_XT_TARGET_TPROXY` are missing , [kernal-doc](https://www.kernel.org/doc/Documentation/networking/tproxy.txt) ![image](https://user-images.githubusercontent.com/56463479/146482139-3f595364-069f-4f05-b529-d9f1d74fbd3a.png) And Tencent kernel didn't set in [default-config](https://github.com/Tencent/TencentOS-kernel/blob/0f77c3ff8f15da8a3a7337a1aca88cb7d72636df/package/default/config.default#L1126-L1127) ![image](https://user-images.githubusercontent.com/56463479/146482502-061faa36-8a41-416b-869d-d951e8d38396.png)
> 
> 😢 A better way to check kernel config is `zcat /proc/config.gz`. If `/proc/config.gz` doesn't exist, you can find some `config-` files under `/boot`, which may contain the kernel config. I have checked this config is `CONFIG_NETFILTER_XT_MATCH_SOCKET=m` on centos 7, which means it's compiled as module.
> 
> @Andrewmatilde @Hexilee I wonder why httpchaos needs to `-m socket`?

HTTPchaos need both `CONFIG_NETFILTER_XT_MATCH_SOCKET` & `NETFILTER_XT_TARGET_TPROXY` , HTTPChaos implement the  proxy function base on [linux transparent proxy](https://www.kernel.org/doc/Documentation/networking/tproxy.txt) tech.

**Comment by ChanKunggc** [comment]
> Hi @ChanKunggc, did you retry/test Chaos Mesh HTTPChaos after rebuilding kernel with updated kernel configs? Does it work? :D

Hi @STRRL  , I try to recompile kernel ，and patch `xt_socket.ko  xt_TPROXY.ko` ，it worked ! 　
![image](https://user-images.githubusercontent.com/56463479/146939330-2ba0775b-18aa-488c-a95e-9bd1d0ff5681.png)

**Comment by vivek-dr** [comment]
Hi @seriousgong : I have the exact same error signature but for iptables v1.8.7 (legacy). I do see CONFIG_NETFILTER_XT_MATCH_SOCKET & NETFILTER_XT_TARGET_TPROXY are unset on host machine /proc/config.gz. May I please know how  was xt_socket.ko  xt_TPROXY.ko patched and kernel recompiled ?
