### ISSUE TITLE
Chaos Dashboard panic when creating new chaos experiment 

### ISSUE THREAD

**Issue by cwen0** [chaos-mesh/chaos-mesh#2654]
## Bug Report

**What version of Kubernetes are you using?**

**What version of Chaos Mesh are you using?**

**What did you do?**

**What did you expect to see?**

**What did you see instead?**  

![27641639493373_ pic_hd](https://user-images.githubusercontent.com/22956341/146300040-e6078675-7435-449a-aa74-1f22e060e758.jpg)

**Output of chaosctl**

**Comment by STRRL** [comment]
Affected version: 2.0.5

**Comment by cwen0** [comment]
This issue was fixed by #2655

**Comment by STRRL** [comment]
closed by #2655
