### ISSUE TITLE
Pod Network block for a few seconds after pause or stop HTTP Chaos(Master)

### ISSUE THREAD

**Issue by Andrewmatilde** [chaos-mesh/chaos-mesh#2664]
## Bug Report

**What version of Chaos Mesh are you using?**

master

**What did you do?**

Inject HTTPChaos into a Pod & pause it

**What did you expect to see?**

Network works well just after HTTPChaos paused.
**What did you see instead?**

Pod Network block for a few seconds

**Reason**

1. The recovering of tproxy will clear arp rules of  the target pod.
2. The auto recover of arp rules in container is slow.

**Solutions**
1. Add arp rules manually.

**Comment by cwen0** [comment]
Same to https://github.com/chaos-mesh/chaos-mesh/issues/2658 ?

**Comment by STRRL** [comment]
It seems this issue did not occur on my machine before.🤔 When I remove a httpchaos (body replace within demo), it could be recovered quickly, as I could fetch the origin response body in one second.

**Comment by Andrewmatilde** [comment]
> Same to #2658 ?

Yes, a duplicate issue.

**Comment by Andrewmatilde** [comment]
> It seems this issue did not occur on my machine before.🤔 When I remove a httpchaos (body replace within demo), it could be recovered quickly, as I could fetch the origin response body in one second.

The problem cannot be reproduced stably because the arp frequency is not stable.

**Comment by EfratHershowitz1** [comment]
What was the solution here ?
