### ISSUE TITLE
how could i change the root url of dashboard? 

### ISSUE THREAD

**Issue by pengliangyou** [chaos-mesh/chaos-mesh#2669]
## Question
Thanks , i want to change the root url of dashboard , how could i do this change? thanks very much
ex. 127.0.0.1:2333  -> 127.0.0.1:2333/chaos-mesh/

**Comment by pengliangyou** [comment]
ignored

**Comment by RoyceShen1** [comment]
just curious, how did you manage to make it work?  by changing root URL variable in helm value file?
