### ISSUE TITLE
fix for bug #2626 in next chaos-mesh release ?

### ISSUE THREAD

**Issue by alelerac** [chaos-mesh/chaos-mesh#2688]
## Question
Hi,
I would appreciate if you can already indicate if bug reported in  https://github.com/chaos-mesh/chaos-mesh/issues/2626 will be fixed in the next chaos-mesh release.
Thanks!

Before asking a question, make sure you have:

- Reviewed relevant Kubernetes information: Google your error messages and look at K8s docs.
- Searched open and closed [GitHub issues](https://github.com/chaos-mesh/chaos-mesh/issues?utf8=%E2%9C%93&q=is%3Aissue)
- Read the documentation:
  - [Chaos Mesh Readme](https://github.com/chaos-mesh/chaos-mesh)
  - [Chaos Mesh Doc](https://chaos-mesh.org/docs)

**Output of chaosctl**

**Comment by STRRL** [comment]
Hi @Hexilee  PTAL
