### ISSUE TITLE
JVM chaos failed  : install com.sun.tools.attach.AgentLoadException: 0

### ISSUE THREAD

**Issue by ChanKunggc** [chaos-mesh/chaos-mesh#2690]
## Bug Report

**What version of Kubernetes are you using?**

1.14.3
**What version of Chaos Mesh are you using?**

2.1.0 made by myself
**What did you do?**

add  jvm  chaos with gc action
**What did you expect to see?**
inject success
**What did you see instead?**
inject failed.
**Output of chaosctl**

target jvm is oracle jdk 1.8.0_201-b09
![image](https://user-images.githubusercontent.com/56463479/147044750-2b9d9bfe-d056-4119-976c-4465d72780b9.png)

![image](https://user-images.githubusercontent.com/56463479/147044128-69327316-8c80-48ff-b852-26f00936cdb6.png)

Here are my print message , just ignore it.
![image](https://user-images.githubusercontent.com/56463479/147044225-78472462-6114-404c-9b62-016e6e02856e.png)

**Comment by ChanKunggc** [comment]
Hi @WangXiangUSTC ,is it caused by this [question](https://stackoverflow.com/questions/54340438/virtualmachine-attach-throws-com-sun-tools-attach-agentloadexception-0-when-usi) ?

**Comment by WangXiangUSTC** [comment]
I've reproduced the problem. I'll look into it

**Comment by WangXiangUSTC** [comment]
seems that the agent is loading success but return error, can ignore it here just like other errors https://github.com/chaos-mesh/chaos-mesh/blob/45feccd5db9731a761ac1ce817708711dd539a56/pkg/chaosdaemon/jvm_server.go#L92. I will fix it

**Comment by ChanKunggc** [comment]
> seems that the agent is loading success but return error, can ignore it here just like other errors
> 
> https://github.com/chaos-mesh/chaos-mesh/blob/45feccd5db9731a761ac1ce817708711dd539a56/pkg/chaosdaemon/jvm_server.go#L85-L92
> 
> . I will fix it

@WangXiangUSTC  OK,i will remake daemon image  with your  commitment
