### ISSUE TITLE
does test environment dashboard could add user token permission?

### ISSUE THREAD

**Issue by lddlww** [chaos-mesh/chaos-mesh#2707]
when use k3s environment, installing chaos-mesh, i can't find ```add user token``` option in settings on dashboard；how can i set ```user token``` in k3s environment？

version:
```
v2.1.0
```

**Comment by YangKeao** [comment]
As I know, multi-user support has been removed in v2.1.0. If you have enabled the dashboard securityMode (which is the default), you will need to input the token the first time you login to the dashboard. And you can logout in the settings.

Do you need the multi-user support in dashboard? Can you describe the scenario you are using this feature?

**Comment by YangKeao** [comment]
BTW, @g1eny0ung It seems that [the document](https://chaos-mesh.org/docs/manage-user-permissions/) needs to be updated

**Comment by g1eny0ung** [comment]
> BTW, @g1eny0ung It seems that [the document](https://chaos-mesh.org/docs/manage-user-permissions/) needs to be updated

Good catch. I will update it soon.

**Comment by lddlww** [comment]
@YangKeao thanks for your reminder，i don't need multi-users，just want use one user to login dashboard in my test environment ；i will try again later

**Comment by YangKeao** [comment]
> @YangKeao thanks for your reminder，i don't need multi-users，just want use one user to login dashboard in my test environment ；i will try again later

BTW. If you are installing Chaos Mesh by `install.sh`, this feature is not enabled too. It would be better to install with `helm`.

**Comment by lddlww** [comment]
ok，thanks

**Comment by YangKeao** [comment]
@g1eny0ung @lddlww 

I have tested. It doesn't work! The first problem is the resource link (`/static/js/main.cce2d46a.chunk.js`, `/static/js/2.396a6d11.chunk.js`...), which is coded with absolute path. I will rewrite them to `/chaos-mesh/...` to see whether there are other problems.
