### ISSUE TITLE
Modify the `supported release` for release 2.1

### ISSUE THREAD

**Issue by YangKeao** [chaos-mesh/chaos-mesh#2719]
Current document about [supported releases](https://chaos-mesh.org/docs/next/supported-releases/) is about the lifecycle of our release. Please add the `release-2.1` to this document.

Do we have anything like a todolist for release a new version? If so, we could add the need to modify this document into it.

In case others will maintain the release, we'd better collaborate to manage this document in a public (or private) repo. I think if we could share the routine to publish new versions, it would be helpful for not only us, but for the whole open source community (just like a good code style guideline 😃 ).

**Comment by STRRL** [comment]
I would update the document "Supported Releases", and draft a guideline for releasing a new version.

**Comment by STRRL** [comment]
closed by  chaos-mesh/website#212
