### ISSUE TITLE
use kubectl get podnetworkchaos command return environment`s pod resource

### ISSUE THREAD

**Issue by Ai-yoo** [chaos-mesh/chaos-mesh#2725]
## Bug Report

**What version of Kubernetes are you using?**
1.16.3

**What version of Chaos Mesh are you using?**
2.0.5

**What did you do?**
I injected the exception of podnetworkchaos into the environment, today use 
```
for i in $(kubectl api-resources | grep chaos-mesh | awk '{print $1}'); do kubectl get $i -A; done
```
get chao-mesh`s resource return k8s`s POD;
After comparison, It`s kubectl get podnetworkchaos returned content

PS: I injected this pod exception

**Comment by g1eny0ung** [comment]
Yep, the `podnetworkchaos` is the same name as the injected `pod`.
