### ISSUE TITLE
I can't find the way to access the dashboard in the documentation

### ISSUE THREAD

**Issue by acechef** [chaos-mesh/chaos-mesh#2737]
I can't find the way to access the dashboard in the documentation at https://chaos-mesh.org/zh/docs/

**Comment by Andrewmatilde** [comment]
Users can access dashboard with NodePort function in kubernetes. 
Example:
```
$kubectl get svc -A
NAMESPACE       NAME                            TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)                                 AGE
chaos-testing   chaos-daemon                    ClusterIP   None           <none>        31767/TCP,31766/TCP                     16h
chaos-testing   chaos-dashboard                 NodePort    10.102.78.79   <none>        2333:30436/TCP                          16h
chaos-testing   chaos-mesh-controller-manager   ClusterIP   10.107.34.26   <none>        443/TCP,10081/TCP,10082/TCP,10080/TCP   16h
```
Users can access dashboard with the NodePort in chaos-dashboard.

**Comment by acechef** [comment]
> Users can access dashboard with NodePort function in kubernetes. Example:
> 
> ```
> $kubectl get svc -A
> NAMESPACE       NAME                            TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)                                 AGE
> chaos-testing   chaos-daemon                    ClusterIP   None           <none>        31767/TCP,31766/TCP                     16h
> chaos-testing   chaos-dashboard                 NodePort    10.102.78.79   <none>        2333:30436/TCP                          16h
> chaos-testing   chaos-mesh-controller-manager   ClusterIP   10.107.34.26   <none>        443/TCP,10081/TCP,10082/TCP,10080/TCP   16h
> ```
> 
> Users can access dashboard with the NodePort in chaos-dashboard.

thanks

**Comment by iguoyr** [comment]
If the former comment doesn't solve your problem. Feel free to reopen this issue.
