### ISSUE TITLE
remove china mainland docker registry mirror in `install.sh`

### ISSUE THREAD

**Issue by STRRL** [chaos-mesh/chaos-mesh#2740]
## Feature Request

Request:

Remove `docker_mirror` feature and related codes in `install.sh`. 

Reason:
- `dockerhub.azk8s.cn`( also `gcr.azk8s.cn` and `quay.azk8s.cn`) could not access with public network anymore, related issue #2294
- After release-2.1, we moved docker images from dockerhub to ghcr.io, there are no other docker registry mirror(s) supporting `ghcr.io` in china mainland right now.

**Comment by rksharma95** [comment]
I am new to this project and would like to work on this issue, I checked `install.sh` we can easily remove it from the FLAGS but at places, it is the part of a conditional statement @STRRL can you help to understand the issue well.

**Comment by STRRL** [comment]
Hi @rksharma95 I think we could just remove all the codes about `docker_mirror` directly. If some conditional statement using it, just remove it.

**Comment by rksharma95** [comment]
> Hi @rksharma95 I think we could just remove all the codes about `docker_mirror` directly. If some conditional statement using it, just remove it.

thanks, I started working on it will submit a PR after I complete it.
