### ISSUE TITLE
improve the error log of JVMChaos

### ISSUE THREAD

**Issue by WangXiangUSTC** [chaos-mesh/chaos-mesh#2746]
## Feature Request

**Is your feature request related to a problem? Please describe:**
Improve the error log of JVMChaos. When install agent or submit rule failed, will return an error like this: 
```log
Failed to apply chaos: rpc error: code = Unknown desc = exit status 1
```

Users can't get the useful information from the error log.

**Comment by STRRL** [comment]
closed by #3004
