### ISSUE TITLE
DNSChaos: not working when kubeproxy running in ipvs mode

### ISSUE THREAD

**Issue by imlonghao** [chaos-mesh/chaos-mesh#2748]
## Bug Report

**What version of Kubernetes are you using?**

```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.10", GitCommit:"8152330a2b6ca3621196e62966ef761b8f5a61bb", GitTreeState:"clean", BuildDate:"2021-08-11T18:06:15Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.3", GitCommit:"01849e73f3c86211f05533c2e807736e776fcf29", GitTreeState:"clean", BuildDate:"2021-02-17T12:35:49Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
```

**What version of Chaos Mesh are you using?**

```
Controller manager Version: version.Info{GitVersion:"v2.1.2", GitCommit:"24a1f565ed000ba8738a4ed568b4e9a0925fe2fb", BuildDate:"2021-12-29T11:43:40Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"linux/amd64"}
```

**What did you do?**

Normally create a DNSChaos experiment on the web dashboard

Let's say the mode is ERROR and the pattern is `google.com`

**What did you expect to see?**

```
# dig @10.173.3.71 google.com

; <<>> DiG 9.10.3-P4-Ubuntu <<>> @10.173.3.71 google.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 59427
;; flags: qr rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;google.com.                    IN      A

;; Query time: 7 msec
;; SERVER: 10.173.3.71#53(10.173.3.71)
;; WHEN: Tue Jan 04 18:45:56 CST 2022
;; MSG SIZE  rcvd: 39
```

`10.173.3.71` is the `chaos-dns-server`'s pod IP

I am expecting to see the chaos DNS server return a SERVFAIL status

**What did you see instead?**

Running `dig google.com` on the target pod, I can get the DNS result with NOERROR.

```
# dig google.com

; <<>> DiG 9.10.3-P4-Ubuntu <<>> google.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 42945
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;google.com.                    IN      A

;; ANSWER SECTION:
google.com.             29      IN      A       46.82.174.69

;; Query time: 0 msec
;; SERVER: 10.254.132.241#53(10.254.132.241)
;; WHEN: Tue Jan 04 18:41:01 CST 2022
;; MSG SIZE  rcvd: 65
```

`10.254.132.241` is the `chaos-dns-server`'s Cluster IP

The following are the log of chaos-dns-server

```
[INFO] plugin/k8s_dns_chaos: receive SetDNSChaos request name:"block-google.com-34ft5" pods:<namespace:"REDACTED" name:"REDACTED" > action:"error" patterns:"google.com" 
[INFO] plugin/k8s_dns_chaos: k8s services, source IP: 10.31.6.83 
```

The IP `10.31.6.83` is the host eth0 IP, somehow SNAT from the pod IP to the host IP.

I believed the problem is the kubeproxy is running in ipvs mode, which will do a SNAT when accessing Cluster IP from pod.

**Output of chaosctl**

Not related to chaosctl

**Comment by WangXiangUSTC** [comment]
Yeah, you are right, `chaos-dns-server` will get the IP of the target Pod, and save it into a map. When `chaos-dns-server` receives a DNS request, it will get the source IP of the request, only when the source IP contained in this map(it's from the target Pod) will return an error or wrong IP address.

**Comment by WangXiangUSTC** [comment]
This scenario is not supported currently, I'll think about it.

**Comment by YangKeao** [comment]
@imlonghao In cluster traffic shouldn't have been SNATed. Maybe you have enabled `masquerade-all=true` for the `kube-proxy`? Turn off the `masquerade-all=true`, then the dns server can see the pod ip.

**Comment by imlonghao** [comment]
Removing the `--masquerade-all=true` from kube-proxy options work for me.
Thanks.
