### ISSUE TITLE
Supported registries

### ISSUE THREAD

**Issue by torbendury** [chaos-mesh/chaos-mesh#2750]
## Question

Hello everyone! First of all, thanks for keeping this great project up!

I wanted to ask which container registries you push your Chaos Mesh images to, since DockerHub has changed its terms since january and we want to keep as far away from it as possible. Maybe quay,GCR,...?

Thank you in advance!

**Comment by WangXiangUSTC** [comment]
We migrate images from docker hub to github docker registry,  you can see this pr https://github.com/chaos-mesh/chaos-mesh/pull/2462

**Comment by STRRL** [comment]
And there are no available docker registry mirrors for `ghcr.io`; related issue: https://github.com/chaos-mesh/chaos-mesh/issues/2740
