### ISSUE TITLE
Keep the POD in non-running state for a period of time

### ISSUE THREAD

**Issue by zhufanqin** [chaos-mesh/chaos-mesh#2776]
## Bug Report
There is a Fault scenario that can keep the POD in non-running state for a period of time, but the fault of POD kill can`t keep the POD in non-running state for a period of time.When try "pod-failure"，the actual failure time is much smaller than the set, which is not ideal。

**What version of Kubernetes are you using?**

**What version of Chaos Mesh are you using?**

**What did you do?**

**What did you expect to see?**

**What did you see instead?**

**Output of chaosctl**

**Comment by Andrewmatilde** [comment]
Hi @zhufanqin , I agree with you but I think it is hard to fix it.

**Comment by cwen0** [comment]
@zhufanqin Can you provide your configuration of `pod-failure` experiment?

**Comment by cwen0** [comment]
`pod-failure` will use a fake image instead of the target pod container images. This action will maybe cause pod restart. But the restart action maybe spend some time. So your duration and interval are too short, which maybe make the phenomenon is not obvious.

**Comment by STRRL** [comment]
As [this comment](https://github.com/chaos-mesh/rfcs/issues/33#issuecomment-1010607109) said, you could setup helm chart values `controllerManager.podChaos.podFailure.pauseImage` to another image as the "fake image", and it might reduce the time.

**Comment by cwen0** [comment]
> As [this comment](https://github.com/chaos-mesh/rfcs/issues/33#issuecomment-1010607109) said, you could setup helm chart values `controllerManager.podChaos.podFailure.pauseImage` to another image as the "fake image", and it might reduce the time. 

Yes. If you use a fake image that can't be pulled, the pod will turn to `Imagepullbackoff` status after starting `pod-failure` action.
