### ISSUE TITLE
preparation for multi-version api

### ISSUE THREAD

**Issue by YangKeao** [chaos-mesh/chaos-mesh#2811]
The Chaos Mesh has stepped too far before adapting the multi-version api. I really regret not doing it earlier 😢 after investigating the roadmap to allow multiple versions api in Chaos Mesh.

On Wednesday and Thursday, I tried to create a new version of some chaos in [YangKeao/chaos-mesh@multi-version-api-attempt](https://github.com/YangKeao/chaos-mesh/tree/multi-version-api-attempt). During this journey, I found we have to finish some preparation tasks before discussing and writing an RFC for it.

## `api/v1alpha` package design

- [ ] `controller-tools` cannot work for multiple sub-modules, so maybe we have to use a single module for a family, but not for a version (see https://github.com/kubernetes-sigs/controller-tools/issues/516) (or use a workaround)

## `chaos-builder`

- [ ] Allow the `chaos-builder` to generate codes in different packages.

## controller

- [ ] Automatically register the scheme and conversion webhook.

**Comment by STRRL** [comment]
I think we'd better also use the "internal - versioned API" pattern for flexible future in-coming changes like mentioned in https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api_changes.md
