### ISSUE TITLE
Use `chaos-mesh` instead of `chaos-testing` in anywhere

### ISSUE THREAD

**Issue by STRRL** [chaos-mesh/chaos-mesh#2818]
## Feature Request

**Is your feature request related to a problem? Please describe:**
No. 

**Describe the feature you'd like:**
We use `chaos-testing` in most scripts and codes as the namespace which assumed/expected that Chaos Mesh installed. It's a  historical problem and using `chaos-testing` does not properly describe what would Chaos Mesh be expected.

So we propose that use `chaos-mesh` to replace `chaos-testing` as the namespace.

**Describe alternatives you've considered:**

It would need lots of changes, it would not be cherry-picked into release-2.1 and release-2.0.

**Teachability, Documentation, Adoption, Migration Strategy:**

No other reference.

**Comment by dmallya** [comment]
Created a PR for this, tried to consciously go over what I replaced but might have mistakenly replaced a few. Would be happy to correct any mistakes.

**Comment by STRRL** [comment]
since #2828 is closed, this issue is available. 

Contribution is welcome. :)

**Comment by xlgao-zju** [comment]
@STRRL my concern is would this be a break change?

**Comment by STRRL** [comment]
> @STRRL my concern is would this be a break change?

I think it would only change the development experience. The user who wants to upgrade with `helm` is still required to use `--namespace` to specify the namespace.
