### ISSUE TITLE
Remove `namespace` in yaml files under `examples`

### ISSUE THREAD

**Issue by STRRL** [chaos-mesh/chaos-mesh#2819]
## Feature Request

**Is your feature request related to a problem? Please describe:**

No.

**Describe the feature you'd like:**

There are many example chaos experiments described in YAML under `/examples`, and many of them were declared with certain `namespace`.

Once `namespace` is introduced in yaml file, we could not use `kubectl -n <namespace>` to "overwrite" it. So I think we'd better remove it in each example file.

**Describe alternatives you've considered:**

There is no necessary to cherry-picked these changes into release-2.1 and release-2.0

No other alternatives.

**Teachability, Documentation, Adoption, Migration Strategy:**

No other references.

**Comment by dmallya** [comment]
Hi,
Sorry I am new to this, do I just delete the ``namespace`` key-value pairs in all the YAML files under ``/examples`` and create a pull request?
Just making sure.

**Comment by STRRL** [comment]
> Hi, Sorry I am new to this, do I just delete the `namespace` key-value pairs in all the YAML files under `/examples` and create a pull request? Just making sure.

Yes. Just make a try! :)

**Comment by dmallya** [comment]
Created a PR and sent it through!
