### ISSUE TITLE
Full automation between OpenAPI and front-end

### ISSUE THREAD

**Issue by g1eny0ung** [chaos-mesh/chaos-mesh#2822]
Starting at #2615, we will fully automate the OpenAPI to UI interface, and **after this issue is closed**, all changes to the API will be automatically applied to the UI without any manual changes.

The process is divided into three steps:

1. OpenAPI to TypeScript API Client and Form Data. #2770
2. Update all API requests with the generated client. #2926
3. Adapt the UI interface with the generated form data. #3185

I will update them one by one in the future.

**Comment by g1eny0ung** [comment]
Since the second step is a separate step, it doesn't affect release `2.2`. So I changed the millstone of this issue to `2.3`.

**Comment by STRRL** [comment]
Hi @g1eny0ung, I noticed that the all of the 3 steps mentioned in this tracking issue had been **completed/merged**.

Could we close this issue as completed?

**Comment by g1eny0ung** [comment]
> Hi @g1eny0ung, I noticed that the all of the 3 steps mentioned in this tracking issue had been **completed/merged**.
> 
> Could we close this issue as completed?

Yep! I will close this issue now.
