### ISSUE TITLE
i18n: zh-cn translation mismatch, "顺序" or "串行" for "Serial"

### ISSUE THREAD

**Issue by STRRL** [chaos-mesh/chaos-mesh#2835]
## Question

Thanks to @en-jin19, for helping us find a translation mismatch between document site and chaos dashboard i18n files.

When we translate the workflow "serial" node, we use "串行" in document site and use "顺序" in chaos dashboard.

![image](https://user-images.githubusercontent.com/20221408/151168500-6b84a689-a98a-40c5-9f79-a77577f9d82d.png)
![image](https://user-images.githubusercontent.com/20221408/151168580-2411d838-64fe-473c-973f-13bf3fbb1aab.png)

We'd better keep consistent between them, which one is better?  How do you think about it? @g1eny0ung @cwen0

**Comment by g1eny0ung** [comment]
For now, I prefer `串行` because the parallel is `并行`.
