### ISSUE TITLE
Proposal: interactive katacoda playground for various chaos experiment examples

### ISSUE THREAD

**Issue by STRRL** [chaos-mesh/chaos-mesh#2842]
## Feature Request

**Is your feature request related to a problem? Please describe:**

No.

**Describe the feature you'd like:**

Thanks to Jonathan Johnson, contributing us an interactive tutorial for Chaos Mesh: https://chaos-mesh.org/interactive-tutorial/ 

I think we could also use katacoda playground to introduce each example in https://github.com/chaos-mesh/chaos-mesh/tree/master/examples in a better way.

One of the most benefits of Chaos Mesh is its powerful various fault injection, but there are lots of configurable flags for a certain type of Chaos, for example, NetworkChaos: https://chaos-mesh.org/docs/simulate-network-chaos-on-kubernetes/#description-for-action-related-fields. It would let users be confused with which one should be set and what's the expected behaviors.

We also provide many examples, but every chaos experiment needs a target application to inject, and the target application needs well-defined observability to make sense that chaos experiment "works". For example, https://github.com/chaos-mesh/web-show is a good example application 

So this proposal wants to build: 

- different katacoda scenarios for various chaos experiment
- build the example application for different Chaos(like https://github.com/chaos-mesh/web-show for NetworkChaos ) as the target application with good observabilities if required.

**Describe alternatives you've considered:**

No other alternatives.

**Teachability, Documentation, Adoption, Migration Strategy:**

It requires you to get familiar with Linux, kubernetes, and basic concepts with Chaos Mesh.

**Comment by STRRL** [comment]
Yeah, that's very interesting when injecting different chaos into different components and the user could "feel" them. 😜

But when providing demonstrations (like katacoda playground) for Chaos Mesh, I still prefer to use metrics (as line chart) to tell the user "something happened, and the side-effect is shown as a line chart with time-series data." 🤔

**Comment by ggold7046** [comment]
Hi, I am new to open source project.  Could anyone guide me how to contribute to this project. I have some knowledge of git, kubernetes,shell

**Comment by STRRL** [comment]
> Hi, I am new to open source project. Could anyone guide me how to contribute to this project. I have some knowledge of git, kubernetes,shell

Hi @ggold7046! Thanks for your attention on Chaos Mesh! 

Currently, this proposal is selected to be one project for LFX Mentorship Q1-2022. You could apply for it at [here](https://mentorship.lfx.linuxfoundation.org/project/09847d84-5d14-4c05-8644-57cdde5b6466). And the deadline for application is Feb, 15th. ❤️

And there are also many other issues with labels "help-wanted" or "good-first-issue", it's a great way to get started with them. :D

**Comment by ggold7046** [comment]
Hi @STRRL,
thanks for replying. I have one curiosity. Do we need to make some contribution to this project beforehand to get selected  for LFX mentorship ? 
Thanks in advance.  :)

**Comment by STRRL** [comment]
I am going to close this issue because the corresponding LFX mentorship has been completed.
