### ISSUE TITLE
Rootless k3s - daemon hangs; mounting "/dev/shm" to rootfs at "/dev/shm" caused: operation not permitted: unknown

### ISSUE THREAD

**Issue by shoffmeister** [chaos-mesh/chaos-mesh#2845]
## Bug Report

**What version of Kubernetes are you using?**

v1.23.3+k3s1 (k3s - in **rootless** mode)

**What version of Chaos Mesh are you using?**

GitVersion:"v2.1.3", GitCommit:"cbe789587678a5ea28e9b38343d222c1d5ea8657"

**What did you do?**

Follow the QuickStart instructions for k3s to install Chaos Mesh

**What did you expect to see?**

Successfully started Chaos Mesh containers.

**What did you see instead?**

The `chaos-daemon` container is stuck on `ContainerCreating`,

```
kubectl get pod --namespace=chaos-testing 

NAME                                        READY   STATUS              RESTARTS   AGE
chaos-daemon-2xfgt                          0/1     ContainerCreating   0          29m
chaos-controller-manager-759fb446bc-hllkf   1/1     Running             0          29m
chaos-controller-manager-759fb446bc-j2smb   1/1     Running             0          29m
chaos-dashboard-7b46dcd786-bv6tg            1/1     Running             0          29m
chaos-controller-manager-759fb446bc-wkkrv   1/1     Running             0          29m
```

The output of `kubectl -n chaos-testing describe pod chaos-daemon-2xfgt` contains, at the end, the following failure information:

```
Events:
  Type     Reason                  Age                     From               Message
  ----     ------                  ----                    ----               -------
  Normal   Scheduled               7m39s                   default-scheduler  Successfully assigned chaos-testing/chaos-daemon-2xfgt to fedora
  Warning  FailedCreatePodSandBox  2m13s (x26 over 7m39s)  kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to create containerd task: failed to create shim: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: rootfs_linux.go:75: mounting "/dev/shm" to rootfs at "/dev/shm" caused: operation not permitted: unknown
```

This is a freshly installed k3s in rootless mode (https://rancher.com/docs/k3s/latest/en/advanced/#running-k3s-with-rootless-mode-experimental) with the systemd user script and IP NAT forwarding configured appropriately.

Host is Fedora 35 on kernel 5.16.18.

**Comment by shoffmeister** [comment]
This is indeed tied to k3s **rootless**; turning off the user k3s-rootless.service, starting the (system) k3s-service, then installing following the instructions provided in the Chaos Mesh Quick Start guide yields `Chaos Mesh chaos-mesh is installed successfully` feedback.

**Comment by STRRL** [comment]
I am not sure about chaos-daemon could work in a rootless container. 🤔 Give us more time to dive into it.

**Comment by shoffmeister** [comment]
Thank you :) I understand where you are coming from with respect to rootless.

I think there might be two steps:
a) not hanging dead but make the daemon bounce - this would then emit more (diagnostic) noise, perhaps making discovery of "oops" easier?
b) assess whether rootless (on k3s) is feasible, perhaps with degraded functionality or degraded performance; for developers rootless might be quite useful to develop / prepare / learn / iterate.
