### ISSUE TITLE
cant run container failure experiment

### ISSUE THREAD

**Issue by 870921** [chaos-mesh/chaos-mesh#2847]
## Bug Report

**What version of Kubernetes are you using?**
1.20.9

**What version of Chaos Mesh are you using?**

v2.1.1
**What did you do?**
I tried the experiment numerous time with different pods and combinations
the container kill experiment requires to provide the container name , however when we provide the container name it
throws the error

Failed to apply chaos: rpc error: code = Unknown desc = expected docker:// but got container

this is the same if we run via the yaml file

I tried creating a simple nginx pod with nginx container name , still i get the same

kind: PodChaos
apiVersion: chaos-mesh.org/v1alpha1
metadata:
  namespace: sdctmtec-ns
  name: nginx
  annotations:
    experiment.chaos-mesh.org/pause: 'true'
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"chaos-mesh.org/v1alpha1","kind":"PodChaos","metadata":{"annotations":{"experiment.chaos-mesh.org/pause":"true"},"name":"nginx","namespace":"sdctmtec-ns"},"spec":{"action":"container-kill","containerNames":["nginx"],"gracePeriod":0,"mode":"one","selector":{"namespaces":["sdctmtec-ns"],"pods":{"sdctmtec-ns":["nginx"]}}}}
spec:
  selector:
    namespaces:
      - sdctmtec-ns
    pods:
      sdctmtec-ns:
        - nginx
  mode: one
  containerNames:
    - nginx
  action: container-kill
  gracePeriod: 0
 
**Output of chaosctl**

**Comment by FingerLeader** [comment]
Could you give us the log of controller manager and chaos daemon?

**Comment by 870921** [comment]
[controller2.txt](https://github.com/chaos-mesh/chaos-mesh/files/8011694/controller2.txt)
[daemon1.txt](https://github.com/chaos-mesh/chaos-mesh/files/8011695/daemon1.txt)
[daemon2.txt](https://github.com/chaos-mesh/chaos-mesh/files/8011696/daemon2.txt)
[controller1.txt](https://github.com/chaos-mesh/chaos-mesh/files/8011697/controller1.txt)

Please find the logs

**Comment by fewdan** [comment]
"Failed to apply chaos: rpc error: code = Unknown desc = expected docker:// but got container"

**Comment by 870921** [comment]
i tried to uninstall and reinstall chaos mesh and the damons are all in the crashed state

Error: failed to create containerd task: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: rootfs_linux.go:76: mounting "/run/containerd/io.containerd.runtime.v1.linux/k8s.io/chaos-daemon/C:/Program Files/Git/run/containerd/containerd.sock" to rootfs at "/run/containerd/containerd.sock" caused: stat /run/containerd/io.containerd.runtime.v1.linux/k8s.io/chaos-daemon/C:/Program Files/Git/run/containerd/containerd.sock: no such file or directory: unknown

![image](https://user-images.githubusercontent.com/74430379/152882044-5044dcee-6628-4284-94f6-5ec33981ce11.png)

**Comment by cwen0** [comment]
@870921 If the node operating system is not Windows. This may be a Helm for Windows issue. You can refer to this issue https://github.com/chaos-mesh/chaos-mesh/issues/2182.
