### ISSUE TITLE
Refine logging in `pkg/chaosdaemon`, move package level variable `log` into struct `DaemonServer` as a field

### ISSUE THREAD

**Issue by STRRL** [chaos-mesh/chaos-mesh#2872]
I found that package level variable `log` also referenced at many places, I prefer to split them into multiple steps:

- [ ] use `log.L()` instead of package variable `log` https://github.com/chaos-mesh/chaos-mesh/pull/2893
- [ ] move the each reference with `log.L()` into corresponding struct
  - [ ] DaemonServer
  - [ ] Graph
  - [ ] tcClient

**Comment by YangKeao** [comment]
@STRRL, I cannot wait to push forward the implementation of tracing in the chaosdaemon. Reading the log of a big replica (e.g. the test-infra in pingcap) is nearly impossible without the help of the separation of resources. I have done a brief attempt in #2902, but I cannot say it's done well. PTAL.

**Comment by STRRL** [comment]
>  Reading the log of a big replica (e.g. the test-infra in pingcap) is nearly impossible without the help of the separation of resources.

What does this mean?

**Comment by STRRL** [comment]
closed by https://github.com/chaos-mesh/chaos-mesh/pull/2902
