### ISSUE TITLE
Refine logging in `pkg/dashboard/apiserver/utils`, use `log.L()` instead of package level variable `Log`

### ISSUE THREAD

**Issue by STRRL** [chaos-mesh/chaos-mesh#2878]
> Please leave comments with your idea if you are interested in this issue. And comment `/assign` to operate self-assign before you work on it.

**Comment by basit9958** [comment]
should i delete `log.go` file in `pkg/dashboard/apiserver/utils`

**Comment by spencercjh** [comment]
I found that this issue was not completely resolved, and I raised a PR.

**Comment by g1eny0ung** [comment]
> I found that this issue was not completely resolved, and I raised a PR as my first contribution 😄 . If you think this issue is out of date, close it.

Not outdated. :) And appreciated your contribution.
