### ISSUE TITLE
Refine logging in `pkg/webhook/config/watcher`, acquired a logger from constructor `New` and use it as the field of `K8sConfigMapWatcher`

### ISSUE THREAD

**Issue by STRRL** [chaos-mesh/chaos-mesh#2890]
> Please leave comments with your idea if you are interested in this issue. And comment `/assign` to operate self-assign before you work on it.

**Comment by STRRL** [comment]
> /assign

Hi @ashwinhs , I am sorry there is already a PR for this issue, and I forgot to self-assign.... 😭 

You could take a look at other issues with good-first-issue, thanks...

**Comment by ashwinhs** [comment]
Sure @STRRL . Thanks!
