### ISSUE TITLE
Refine logging in `pkg/webhook/inject`, refactor these function as methods of a Struct, them move package level variable `log` as a field

### ISSUE THREAD

**Issue by STRRL** [chaos-mesh/chaos-mesh#2891]

**Comment by afzal442** [comment]
@STRRL, I'm interested, could you make little more clear here which `logging` needs to be refactored?
Do you mean like this as below?
e.g.
https://github.com/chaos-mesh/chaos-mesh/blob/a2854f0e1a74130f8cb304b9036fea0d5eb91c4c/pkg/webhook/inject/command.go#L23
```go
type mergeCmd struct {
inject []string
origin []string 
args []string
}
func (mg mergeCmd)MergeCommands() []string {

```

**Comment by STRRL** [comment]
Hi @afzal442! Thanks for your attention on Chaos Mesh! 

Well, the refactor pattern which you used is excelly correct, but this issue only want to refactor about functions which have used `log`, for example, `Inject(res *v1.AdmissionRequest, cli client.Client, cfg *config.Config, controllerCfg *controllerCfg.ChaosControllerConfig, metrics *metrics.ChaosControllerManagerMetricsCollector) *v1.AdmissionResponse ` in file `pkg/webhook/inject/inject.go`.

If you think other files also need refactor (and it does actually need), it's better to make another issue and PR for that. :D

**Comment by afzal442** [comment]
thanks @STRRL, for your suggestion. But I wondered how I can move package level variable `log` as a field.

**Comment by Amshu-k** [comment]
@g1eny0ung - could you please help me with this issue?
I'm looking at the codebase and this directory `pkg/webhook/inject` doesn't exist anymore? Am I missing something here?

**Comment by g1eny0ung** [comment]
@Amshu-k I've found that this issue is outdated because the `inject.go` was removed in https://github.com/chaos-mesh/chaos-mesh/pull/3886, I forgot about this PR, so I reopened this issue again. You don't miss anything. I'll go ahead and close this issue now.
