### ISSUE TITLE
an error will be reported When I use make generate

### ISSUE THREAD

**Issue by zhuazi** [chaos-mesh/chaos-mesh#2920]
version : 2.1.3
Follow the steps of the document. When I use 'make generate', an error will be reported.
doc url : https://chaos-mesh.org/docs/add-new-chaos-experiment-type/

![image](https://user-images.githubusercontent.com/4626297/154877837-73ad585c-b90d-4704-b677-7f97c3b8585a.png)

then

![image](https://user-images.githubusercontent.com/4626297/154877906-24d53783-19fb-4d70-85f6-993985731a67.png)

How to solve?

**Comment by STRRL** [comment]
I think this PR could fix this issue: https://github.com/chaos-mesh/chaos-mesh/pull/2600. But it was not cherry-picked into branch `release-2.1` or `release-2.0`.


I think maybe you are not working on the `master` branch. We recommend using `master` branch when you following the docs "Add New Chaos Experiment".
