### ISSUE TITLE
Dashboard: support TTL for archived schedule and workflow data

### ISSUE THREAD

**Issue by cwen0** [chaos-mesh/chaos-mesh#2922]
## Feature Request

**Is your feature request related to a problem? Please describe:**

At present, Dashboard supports setting TTL for archived events and experiments, but schedule and workflow do not.  We can extend to this [function](https://github.com/chaos-mesh/chaos-mesh/blob/master/pkg/dashboard/ttlcontroller/ttlcontroller.go#L73-L80)  to implement TTL for schedule and workflow data

**Describe the feature you'd like:**

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by rksharma95** [comment]
I would like to work on this issue.

**Comment by rksharma95** [comment]
hey @cwen0 , I was trying to understand the issue well and went through the codebase and found that the case for adding TTL for `schedule` is pretty straightforward. 
In the case of `workflow` as `WorkflowStore` is something different from others. There is no existing functionality of handling the deletion of workflow based on finish time. do we need to implement one for the same?

can you help me to understand the scenario? 
Thanks in advance.

**Comment by cwen0** [comment]
> hey @cwen0 , I was trying to understand the issue well and went through the codebase and found that the case for adding TTL for `schedule` is pretty straightforward. In the case of `workflow` as `WorkflowStore` is something different from others. There is no existing functionality of handling the deletion of workflow based on finish time. do we need to implement one for the same?
> 
> can you help me to understand the scenario? Thanks in advance.

Yes, `DeleteByFinishTime` is needed, you can implement one for `WorkflowStore`.  I will assign this issue to you.

**Comment by rksharma95** [comment]
as we have to delete all the workflows based on finish time. In `DeleteByFinishTime` we are finding all relvent workflows by retrieving the meta-list. 

the `DeleteByFinishTime` defined as:

```
func (it *WorkflowStore) DeleteByFinishTime(ctx context.Context, ttl time.Duration) error {
	workflows, err := it.ListMeta(context.Background(), "", "", true)
	if err != nil {
		return err
	}	
nowTime := time.Now()
	for _, wfl := range workflows {
		if wfl.FinishTime.Add(ttl).Before(nowTime) {
			if err := it.db.Where("uid = ?", wfl.UID).Unscoped().Delete(*it).Error; err != nil {
				return err
			}
		}
	}

	return nil
}
```

should I continue with the above implementation?

**Comment by cwen0** [comment]
> 



> as we have to delete all the workflows based on finish time. In `DeleteByFinishTime` we are finding all relvent workflows by retrieving the meta-list.
> 
> the `DeleteByFinishTime` defined as:
> 
> ```
> func (it *WorkflowStore) DeleteByFinishTime(ctx context.Context, ttl time.Duration) error {
> 	workflows, err := it.ListMeta(context.Background(), "", "", true)
> 	if err != nil {
> 		return err
> 	}	
> nowTime := time.Now()
> 	for _, wfl := range workflows {
> 		if wfl.FinishTime.Add(ttl).Before(nowTime) {
> 			if err := it.db.Where("uid = ?", wfl.UID).Unscoped().Delete(*it).Error; err != nil {
> 				return err
> 			}
> 		}
> 	}
> 
> 	return nil
> }
> ```
> 
> should I continue with the above implementation?

Yes, you can continue. In fact, we should not list the metas first and then delete them. If we can delete them directly, it will be better. But If we want to refactor this logic, we should refactor `experimentstore`, `scheduleStroe` together in another single PR.

**Comment by rksharma95** [comment]
Can you share the logic, how I can handle the deletion directly without listing the meta? how can we get access to the `FinishTime` field without a meta list?

**Comment by cwen0** [comment]
> Can you share the logic, how I can handle the deletion directly without listing the meta? how can we get access to the `FinishTime` field without a meta list?

You can continue to use `meta` to implement `DeleteByFinishTime`. About the `DeleteByFinishTime` improvement, you can create a new issue to discuss it. You don't need to consider it in this pr.

**Comment by rksharma95** [comment]
Thanks for your feedback. I will open an issue for that.
