### ISSUE TITLE
jvm-chaos shoule add -Dorg.jboss.byteman.compile.to.bytecode 

### ISSUE THREAD

**Issue by zhqqqy** [chaos-mesh/chaos-mesh#2923]
## Bug Report

**What version of Kubernetes are you using?**
Kubernetes version is  v1.14.10

**What version of Chaos Mesh are you using?**
Chaos Mesh version is 2.1

**What did you do?**
When I inject a fault through jvm-chaos, I inject a toString method, and a StackOverflow error will appear at this time
```java
public class Complex {
    private double re, im;
    public Complex(double re, double im) {
        this.re = re;
        this.im = im;
    }
    @Override
    public String toString() {
        return this.re + " + " + this.im + "i";
    }
}
```
Main.Java
```java
public class Main {
    public static void main(String[] args) {
        Complex c1 = new Complex(10, 15);
        for(int x = 0; x < 3600; x = x+1) {
            try {
                Thread.sleep(1000);
                 System.out.println(c1);
            } catch (Exception e) {
                System.out.println("Got an exception!" + e);
            }
        }
    }
}
```
rule.btm
```
RULE overriding methods
CLASS ^java.lang.Object
METHOD toString
IF true
DO System.out.println("comming" )
ENDRULE
```
There is a similar issue documented here : https://developer.jboss.org/message/928389#928389

**What did you see instead?**
when I add -Dorg.jboss.byteman.compile.to.bytecode parameter ，it's ok

so ,I think ， bminstall.sh shoule add -Dorg.jboss.byteman.compile.to.bytecode paramete when starting.

**Comment by WangXiangUSTC** [comment]
Is it return StackOverflow error every time?

**Comment by zhqqqy** [comment]
> 



> Is it return StackOverflow error every time?

yes

**Comment by WangXiangUSTC** [comment]
It looks more like an infinite loop, `toString` is a common function in java. The `toString` in `Complex` trigger  the byteman's rule, and `toString` function is executed in byteman somewhere, then it trigger the rule again, endless...

You can update the rule.btm file to:

```bash
RULE overriding methods
CLASS Complex
METHOD toString
IF true
DO System.out.println("comming" )
ENDRULE
```

Only match the `toString` method in `Complex` class.

**Comment by zhqqqy** [comment]
> somewhere

the Complex class just a example，as described in this question  https://developer.jboss.org/message/928389#928389 , it should be the problem caused by reflection. If the `-Dorg.jboss.byteman.compile.to.bytecode` parameter is added at startup, the rules will be compiled without reflection, although this makes the first execution of the rule take longer but  subsequent execution should be a lot faster.

**Comment by zhqqqy** [comment]
> It looks more like an infinite loop, `toString` is a common function in java. The `toString` in `Complex` trigger the byteman's rule, and `toString` function is executed in byteman somewhere, then it trigger the rule again, endless...
> 
> You can update the rule.btm file to:
> 
> ```shell
> RULE overriding methods
> CLASS Complex
> METHOD toString
> IF true
> DO System.out.println("comming" )
> ENDRULE
> ```
> 
> Only match the `toString` method in `Complex` class.

the Complex class just a example，as described in this question https://developer.jboss.org/message/928389#928389 , it should be the problem caused by reflection. If the -Dorg.jboss.byteman.compile.to.bytecode parameter is added at startup, the rules will be compiled without reflection, although this makes the first execution of the rule take longer but subsequent execution should be a lot faster.

**Comment by WangXiangUSTC** [comment]
I tried to add the `-Dorg.jboss.byteman.compile.to.bytecode` parameter but got the same infinite log. Can you provide the whole bminstall.sh command？

**Comment by zhqqqy** [comment]
> I tried to add the `-Dorg.jboss.byteman.compile.to.bytecode` parameter but got the same infinite log. Can you provide the whole bminstall.sh command？

```bash
./bminstall.sh -p 6000 -b -Dorg.jboss.byteman.transform.all -Dorg.jboss.byteman.verbose -Dorg.jboss.byteman.compile.to.bytecode 47186
# submit rule 
./bmsubmit.sh -p 6000 over.btm
```
test.btm
```
RULE overriding methods
CLASS ^java.lang.Object
METHOD toString
IF true
DO System.out.println("Finalizing---------" )
ENDRULE
```

![image](https://user-images.githubusercontent.com/13046318/155288849-df891f77-0e28-4b89-9124-324598ecff49.png)

**Comment by WangXiangUSTC** [comment]
https://downloads.jboss.org/byteman/4.0.18/byteman-programmers-guide.html#environment-settings
There is a environment setting named `org.jboss.byteman.compileToBytecode`, is it same with `org.jboss.byteman.compile.to.bytecode`?

**Comment by zhqqqy** [comment]
> https://downloads.jboss.org/byteman/4.0.18/byteman-programmers-guide.html#environment-settings There is a environment setting named `org.jboss.byteman.compileToBytecode`, is it same with `org.jboss.byteman.compile.to.bytecode`?

yes

**Comment by WangXiangUSTC** [comment]
OK, may you fix this issue? Update this line https://github.com/chaos-mesh/chaos-mesh/blob/bef904904603b8bd81a8bc780bcbf58f3fa1d98c/pkg/chaosdaemon/jvm_server.go#L34

**Comment by zhqqqy** [comment]
pr has been submitted ： https://github.com/chaos-mesh/chaos-mesh/pull/2945
