### ISSUE TITLE
How to select pods by labelSelectors with OR grammar?

### ISSUE THREAD

**Issue by zhuwenxing** [chaos-mesh/chaos-mesh#2925]
## Question

For example, I have to apply the chaos to all pods that belong to a release. But for some reason, we can't find a labelSelectors to get all pods, because labelSelectors works as k1=v1 AND k2=v2 but all pods do not have a common (k,v).

Assume that the pods can be selected with k1=v1 OR k2=v2.

To implement this feature, I have to create a workflow with two parallel child tasks. One is with labelSelectors as k1=v1 and another is with labelSelectors as k2=v2.

But don't you think this implementation is ugly? Why not just make labelSelectors support OR grammar in chaos mesh though labelSelectors OR grammar is not supported in K8S? 

Before asking a question, make sure you have:

- Reviewed relevant Kubernetes information: Google your error messages and look at K8s docs.
- Searched open and closed [GitHub issues](https://github.com/chaos-mesh/chaos-mesh/issues?utf8=%E2%9C%93&q=is%3Aissue)
- Read the documentation:
  - [Chaos Mesh Readme](https://github.com/chaos-mesh/chaos-mesh)
  - [Chaos Mesh Doc](https://chaos-mesh.org/docs)

**Output of chaosctl**

**Comment by STRRL** [comment]
You could set `expressionSelectors` instead of `LabelSelectors`, which supports OR. The usage is mostly like [set-based requirements](https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#resources-that-support-set-based-requirements)

**Comment by zhuwenxing** [comment]
> You could use `expressionSelectors` ( which supports OR) instead of `labelSelectors`.
> 
> [Related documentation](https://chaos-mesh.org/docs/define-chaos-experiment-scope/#expression-selectors) on chaos-mesh.org .

Got it!
It looks like much features are supported in dashboard  UI 😕

**Comment by STRRL** [comment]
I am going to close this issue, feel free to reopen it if you have other questions. :)
