### ISSUE TITLE
io delay experiment causes file system corruption and write error into volumePath of zookeeper statefulset pod

### ISSUE THREAD

**Issue by alelerac** [chaos-mesh/chaos-mesh#2927]
## Bug Report

**What version of Kubernetes are you using?**

Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.1", GitCommit:"c4d752765b3bbac2237bf87cf0b1c2e307844666", GitTreeState:"clean", BuildDate:"2020-12-18T12:09:25Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4", GitCommit:"ec2760d6d916781de466541a6babb4309766c995", GitTreeState:"clean", BuildDate:"2021-02-27T17:18:03Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}

**What version of Chaos Mesh are you using?**

Controller manager Version: version.Info{GitVersion:"v2.1.3", GitCommit:"cbe789587678a5ea28e9b38343d222c1d5ea8657", BuildDate
:"2022-01-27T05:15:02Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/amd64"}

**What did you do?**

1.	run io delay experiment on zookeeper-zk-0 statefulset pod 
2.	in parallel run this three commands 
       a)	kubectl exec -i -t -n robustness zookeeper-zk-0 -- ls -l /var/lib/  
       b)	kubectl exec -i -t -n robustness zookeeper-zk-0 -- ls -l /var/lib/zookeeper/  
       c)	kubectl exec -i -t -n robustness zookeeper-zk-0 -- dd if=/dev/zero of=/var/lib/zookeeper/test1.log bs=1 count=1  
3.	result printout for the ls commands in 2a) and 2b) are different before and after chaos injection. 
4.	Command in 2c) fails with permission denied 

**What did you expect to see?**

read/write delays from specified volumePath.

**What did you see instead?**
1) permission denied when writing into volumePath
2) files  in /var/lib/zookeeper/ are not available after experiment is started

**Filesystem before experiment is started**
sh$ ls -l /var/lib/
total 4
drwxr-xr-x 2 root root    21 Nov  5 13:05 YaST2
drwxr-xr-x 1 root root    71 Nov  5 13:06 alternatives
drwxr-xr-x 1 root root    73 Nov  5 13:06 ca-certificates
drwxr-xr-x 2 root root     6 Mar  3  2021 empty
drwxr-xr-x 2 root root     6 Mar  3  2021 misc
drwx------ 2 root root     6 Nov  2 01:16 private
lrwxrwxrwx 1 root root    26 Oct 12 11:42 rpm -> ../../usr/lib/sysimage/rpm
drwxr-xr-x 4 root root    38 Nov  2 01:17 systemd
drwxrwsr-x 7 root 10000 4096 Feb 22 14:43 zookeeper
drwxr-xr-x 1 root root    52 Nov  5 13:05 zypp
sh$ 
sh$ 
sh$ ls -l /var/lib/zookeeper
total 40
drwxrwsr-x 2 101493 10000  4096 Feb 22 14:56 config-dynamic
-rw-rw-r-- 1 101493 10000     0 Feb 22 14:58 configurePmCert.lock
-rw-rw-r-- 1 101493 10000     0 Feb 22 14:58 configurecert.lock
drwxrwsr-x 3 101493 10000  4096 Feb 19 21:25 data
drwxrwsr-x 3 101493 10000  4096 Feb 19 21:25 log
drwxrws--- 2 root   10000 16384 Feb 19 21:23 lost+found
drwxrwsr-x 4 101493 10000  4096 Feb 22 14:58 secrets
-rw-rw-r-- 1 101493 10000     1 Feb 22 13:16 test.log
-rw-rw-r-- 1 101493 10000     1 Feb 22 15:00 test1.log
sh$ 
sh$ 
sh$ dd if=/dev/zero of=/var/lib/zookeeper/test1.log
1+0 records in
1+0 records out
1 byte copied, 0.000125903 s, 7.9 kB/s
sh$ 
sh$ 

**Filesystem after and during experiment**
sh$ ls -l /var/lib/
total 4
drwxr-xr-x 2 root root    21 Nov  5 13:05 YaST2
drwxrwsr-x 7 root 10000 4096 Feb 22 14:43 __chaosfs__zookeeper__
drwxr-xr-x 1 root root    71 Nov  5 13:06 alternatives
drwxr-xr-x 1 root root    73 Nov  5 13:06 ca-certificates
drwxr-xr-x 2 root root     6 Mar  3  2021 empty
drwxr-xr-x 2 root root     6 Mar  3  2021 misc
drwx------ 2 root root     6 Nov  2 01:16 private
lrwxrwxrwx 1 root root    26 Oct 12 11:42 rpm -> ../../usr/lib/sysimage/rpm
drwxr-xr-x 4 root root    38 Nov  2 01:17 systemd
drwxrwxr-x 1 root root    29 Nov  5 13:06 zookeeper
drwxr-xr-x 1 root root    52 Nov  5 13:05 zypp
sh$ 
sh$ 
sh$ ls -l /var/lib/zookeeper
total 0
drwxrwxr-x 1 101493 root 6 Nov  5 13:06 data
drwxrwxr-x 1 101493 root 6 Nov  5 13:06 log
sh$ 
sh$ 
sh$ dd if=/dev/zero of=/var/lib/zookeeper/test1.log
dd: failed to open '/var/lib/zookeeper/test1.log': Permission denied
command terminated with exit code 1
sh$ 
sh$ 

**Output of chaosctl**

**Attachments**
[describe_iochaos_iodelay.txt](https://github.com/chaos-mesh/chaos-mesh/files/8118087/describe_iochaos_iodelay.txt)
[experiment_file.txt](https://github.com/chaos-mesh/chaos-mesh/files/8118122/experiment_file.txt)

**Comment by STRRL** [comment]
Hi @alelerac , could you provide the log of `chaos-daemon-xx` which is on the same nodes with Pod `zookeeper-zk-0`? ❤️

**Comment by alelerac** [comment]
Hi @STRRL , log file of chaos-daemon is attached. Many thanks for the quick response.
[chaos_daemon_io_delay_zookeeper.log](https://github.com/chaos-mesh/chaos-mesh/files/8122567/chaos_daemon_io_delay_zookeeper.log)

**Comment by STRRL** [comment]
Hi @alelerac , I think I could not exactly reproduce this certain issue. Could you tell us more detail about the way to deployment the zookeeper? like the image of containers or the helm charts you used.

I have taken a try with bitnami zookeeper helm charts, I occurred some issues but it does not look like this issue.

**Comment by alelerac** [comment]
Hi @STRRL ,

I have attached three files:
- zookeeper.yaml (manifest for zookeeper statefulset)
- io_test.sh  (script which prints directory structure)
- io_delay_zk.yaml (io delay manifest)

How to reproduce:
1) deploy zookeeper statefulset (zookeeper.yaml)
2) run io_test.sh to print directory structure and write file into persistent volume
3) start io delay experiment  (io_delay_zk.yaml)
4) compare printouts from io_test.sh before and after experiment 

Thanks for your support.
[io_delay_zk.tar.gz](https://github.com/chaos-mesh/chaos-mesh/files/8168954/io_delay_zk.tar.gz)

**Comment by alelerac** [comment]
Hi @STRRL,
please check provided files and instruction on how to reproduce.
Thanks.

**Comment by STRRL** [comment]
> Hi @STRRL, please check provided files and instruction on how to reproduce. Thanks.

Thanks! I would take a look!

**Comment by STRRL** [comment]
> Hi @STRRL, could you reproduce the issue?

Yes, I could reproduce this issue. Still working on fixing it.

Sorry for the late response and  I did not spend enough time on this issue the last few days.

**Comment by STRRL** [comment]
The reason causes this issue is there are some directories at `/var/lib/zookeeper` in the image `k8s.gcr.io/kubernetes-zookeeper:1.0-3.4.10`. So it seems we should use `-o nonempty` when mounting toda.

**Comment by alelerac** [comment]
Hi @STRRL ,
can you already estimate when a new version with this fix will be released? 
Many thanks

**Comment by STRRL** [comment]
> Hi @STRRL , can you already estimate when a new version with this fix will be released? Many thanks

I think we could release a bugfix/patch version 2.1.x in the next 2 weeks.
