### ISSUE TITLE
use hostNetwork pod cannot  use chaos-mesh network

### ISSUE THREAD

**Issue by liu0208xuan** [chaos-mesh/chaos-mesh#2931]
my k8s env version:
  1.13

In my test resources env , all the pods use hostNetwork， when i apply network-chaos， encounter error:

ERROR   records fail to apply chaos     {"error": "It's dangerous to inject network chaos on a pod(default/ps-standby1-16904-16906-18929) with `hostNetwork`"}

so is there any methods to avoid this error ?

thanks !

**Comment by STRRL** [comment]
You could enable the networkchaos on hostNetwork by configuring helm charts with `--set controllerManager.allowHostNetworkTesting=true`

**Comment by STRRL** [comment]
I am going to close this issue because we have provided the solution for this question.

Please feel free to reopen this issue if it does not work or you have other questions. :)
