### ISSUE TITLE
error when try to compile chaos-mesh with make command

### ISSUE THREAD

**Issue by ycwdaaaa** [chaos-mesh/chaos-mesh#2938]
just like the title,   there is no more useful information.  

kustomize build output/config-v1beta1/default > manifests/crd-v1beta1.yaml
CGO_ENABLED=1 go build -ldflags "-s -w -X 'github.com/chaos-mesh/chaos-mesh/pkg/version.buildDate=2022-02-24T09:01:15Z' -X 'github.com/chaos-mesh/chaos-mesh/pkg/version.gitCommit=bef904904603b8bd81a8bc780bcbf58f3fa1d98c' -X 'github.com/chaos-mesh/chaos-mesh/pkg/version.gitVersion=master-gbef904904603b8'" -tags "" -o images/chaos-daemon/bin/chaos-daemon ./cmd/chaos-daemon/main.go
go: updates to go.mod needed; to update it:
	go mod tidy
make: *** [images/chaos-daemon/bin/chaos-daemon] Error 1

**Comment by STRRL** [comment]
Could you provide which branch and commit are you using for compiling? :heart:

**Comment by ycwdaaaa** [comment]
> 



> Could you provide which branch and commit are you using for compiling? ❤️

Thanks for your reply,  this problem just cannot reproduce,  now I can use make  command to compile chaos-mesh. but when I want to run the dashboard with yarn  start:default command, I got this error:


cainsun@CAINSUN-MB0 ui % yarn start:default
yarn run v1.22.17
error Command "start:default" not found.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by STRRL** [comment]
> > 
> 
> > Could you provide which branch and commit are you using for compiling? heart
> 
> Thanks for your reply, this problem just cannot reproduce, now I can use make command to compile chaos-mesh. but when I want to run the dashboard with yarn start:default command, I got this error:
> 
> cainsun@CAINSUN-MB0 ui % yarn start:default yarn run v1.22.17 error Command "start:default" not found. info Visit [yarnpkg.com/en/docs/cli/run](https://yarnpkg.com/en/docs/cli/run) for documentation about this command.

Please follow the [README](https://github.com/chaos-mesh/chaos-mesh/blob/master/ui/README.md) in `ui` folder,  you should execute `yarn bootstrap` then `yarn workspace @ui/app start:default`.

Please let us know if it works. :heart:

**Comment by g1eny0ung** [comment]
Sorry, the command in the documentation has not been updated. I'll go update it now.

**Comment by g1eny0ung** [comment]
https://github.com/chaos-mesh/website/pull/257
