### ISSUE TITLE
after make command to build image, i got error "Dashboard UI is not built"

### ISSUE THREAD

**Issue by ycwdaaaa** [chaos-mesh/chaos-mesh#2939]
Dashboard UI is not built.
Please run UI=1 make.
Run UI=1 make images/chaos-dashboard/bin/chaos-dashboard if you only want to build dashboard only.
(Note: If you only want to build the binary in local, pass IN_DOCKER=1)

**Comment by STRRL** [comment]
Please try `UI=1 make image`.

**Comment by ycwdaaaa** [comment]
> Please try `UI=1 make clean image`.

I just tried, but got this error, do you know how to deal with it ?

$ cd ..; is-ci || husky install ./ui/.husky
husky - Git hooks installed
Done in 335.96s.
cd ui &&\
	yarn build
yarn run v1.22.17
$ yarn workspace @ui/mui-extends build && yarn workspace @ui/app build
$ tsc
$ react-scripts build
Creating an optimized production build...








The build failed because the process exited too early. This probably means the system ran out of memory or someone called `kill -9` on the process.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed.
Exit code: 1
Command: /usr/bin/node
Arguments: /usr/lib/node_modules/yarn/lib/cli.js build
Directory: /Users/cainsun/tools/go-workspace/src/chaos-mesh/ui/app
Output:

info Visit https://yarnpkg.com/en/docs/cli/workspace for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
make: *** [ui] Error 1

**Comment by STRRL** [comment]
It most probably is oom killing happens on nodejs.

I guess you are using "Docker desktop" on macOS (or windows). Please set up more memory for the docker.

**Comment by ycwdaaaa** [comment]
> It most probably is oom killing happens on nodejs.
> 
> I guess you are using "Docker desktop" on macOS (or windows). Please set up more memory for the docker.

yes, i'm using Docker desktop on macOS.  I will  set up memory to 6G and  retry.  thanks very much

**Comment by STRRL** [comment]
I am going to close this issue, feel free to reopen it if you still have problem on building chaos mesh! :D

**Comment by ycwdaaaa** [comment]
> I am going to close this issue, feel free to reopen it if you still have problem on building chaos mesh! :
just one  more question,  after the command complete,  how can i get the image?  i cannot find the dashbord image built
