### ISSUE TITLE
How to verify time offset taking effect?

### ISSUE THREAD

**Issue by zhuwenxing** [chaos-mesh/chaos-mesh#2979]
## Question

>TimeChaos only affects the PID 1 process in the PID namespace of the container, and child processes of the PID 1. For example, the process started by kubectl exec does not be affected.

as stated above, we can't `kubectl exec` into the container, and use the output of `date` as the time after chaos?

I set time offset as '-10m', but after timestamps of injecting time offset chaos, the following timestamps in the log is still increasing.

Before asking a question, make sure you have:

- Reviewed relevant Kubernetes information: Google your error messages and look at K8s docs.
- Searched open and closed [GitHub issues](https://github.com/chaos-mesh/chaos-mesh/issues?utf8=%E2%9C%93&q=is%3Aissue)
- Read the documentation:
  - [Chaos Mesh Readme](https://github.com/chaos-mesh/chaos-mesh)
  - [Chaos Mesh Doc](https://chaos-mesh.org/docs)

**Output of chaosctl**

**Comment by YangKeao** [comment]
For example, if process 1 (and its child process) printed log, then the log timestamp would change. A clearer example is that:

```go
func main() {
  loop {
    fmt.Println(time.Now())
    time.Sleep(1 * time.Second)
  }
}
```

This program (if it was the injectee) will print the modified time

**Comment by tesstnew** [comment]
same question，View pod log time, time offset takes effect，But enter the pod through kubectl exec, execute date, the time has not changed ，How did you do it??

**Comment by YangKeao** [comment]
@tesstnew In short, Chaos Mesh modified the implementation of `clock_gettime` or other functions related to time in the target processes' memory space (for more detail, see [vdso](https://man7.org/linux/man-pages/man7/vdso.7.html)), so only the target processes (and their subprocesses) are modified. The other processes in the same machine could still get the correct time.

The Chaos Mesh doesn't watch and inject the processes started later (by `kubectl exec`), so the `bash` and `date` executed by `kubectl exec` can still get the correct time.

Linux doesn't provide any native way to isolate the time (the time namespace after Linux 5.6 doesn't meet our requirement either), so we have to cast the magic 🧙‍♂️

**Comment by tesstnew** [comment]
@YangKeao  thanks   it might also explain    
https://chaos-mesh.org/zh/blog/simulating-clock-skew-in-k8s-without-affecting-other-containers-on-node/
