### ISSUE TITLE
Usage of deprecated api for dashboard ingress

### ISSUE THREAD

**Issue by Bonitas** [chaos-mesh/chaos-mesh#2998]
## Bug Report

**What version of Kubernetes are you using?**
1.21.9

**What version of Chaos Mesh are you using?**
2.1.3

**What did you do?**
I deployed chaos mesh via the helm chart. 

**What did you expect to see?**
I expected it to use the current version of ingresses

**What did you see instead?**
It deploys an ingress resource with API version extension/v1beta1 (see also https://github.com/chaos-mesh/chaos-mesh/blob/master/helm/chaos-mesh/templates/ingress.yaml#L16). 

**Why is this a problem**
We are using multiple ingress controllers. This is why we need to specify which controller handles the deployed ingress resource.  In the old version you could use an annotation to specify which ingress-class to use. The later version introduced a new field called 'ingressClassName'. By default ingress-nginx does not understand the old annotations anymore. Also we need to expect that the old version will be removed soon.

**Comment by Bonitas** [comment]
I can open a PR for that if you want. Would you suggest to support both versions for downward compatibility or can we just update as networking v1 was already introduced in k8s 1.19

**Comment by g1eny0ung** [comment]
> I can open a PR for that if you want. Would you suggest to support both versions for downward compatibility or can we just update as networking v1 was already introduced in k8s 1.19

Definitely! If you can open a PR, we would certainly welcome it. ❤️ Refer to [Supported Releases](https://chaos-mesh.org/docs/supported-releases/), the minimum k8s version we wanna support is `1.15`. So we still need to be backward compatible.

**Comment by KimDoubleB** [comment]
Is the PR going on?

`argo-cd` is also written as you suggested. Please refer to it. @Bonitas 
- https://github.com/argoproj/argo-helm/blob/master/charts/argo-cd/templates/_helpers.tpl#L205-L218
- https://github.com/argoproj/argo-helm/blob/master/charts/argo-cd/templates/argocd-server/ingress.yaml#L7

If the PR is not in progress, please let me know. I'll try to fix it 😃
I hope this issue will be resolved soon.

**Comment by Bonitas** [comment]
Sorry totally missed the reply. Unfortunately I’m quite busy at the moment. Would be super happy if you could take over :)

**Comment by KimDoubleB** [comment]
@MarkAndersonTrocme Yeap. 
I'm a little busy on weekdays, so I'm going to work now. 
I'll try it until the weekend :)
