### ISSUE TITLE
PhysicalMachineChaos  dial tcp xx.xx.xx.xx:xxx : connect: connection refused

### ISSUE THREAD

**Issue by tesstnew** [chaos-mesh/chaos-mesh#3001]
kind: PhysicalMachineChaos
apiVersion: chaos-mesh.org/v1alpha1
metadata:
  namespace: default
  name: cpu
  annotations:
    experiment.chaos-mesh.org/pause: 'true'
spec:
  action: stress-cpu
  address:
    - http://xx.xx.xx.xx
  uid: 8a778c6a-e93a-40b9-b43f-fc04ae7372e0
  stress-cpu:
    load: 20
    workers: 20

version 2.1.3

**Comment by tesstnew** [comment]
Failed to apply chaos: : Post "http://xx.xx.xx.xx/api/attack/stress": dial tcp xx.xx.xx.xx:xx: connect: connection refused

**Comment by g1eny0ung** [comment]
The information is a bit scarce, can chaosd's address be accessed directly?

**Comment by tesstnew** [comment]
@g1eny0ung thanks ， Intranet address.，   Inaccessible ，
I refer to this question   https://chaos-mesh.org/docs/faqs/#q-i-have-deployed-chaos-mesh-and-created-podchaos-experiments-successfully-but-i-still-failed-in-creating-networkchaostimechaos-experiment-the-log-is-shown-below

chaos-controller-manager ping chaos-daemon  ok  

maybe  we can Tencent conference  hahahaha
