### ISSUE TITLE
Where is the code that manager the chaos's life cycle?

### ISSUE THREAD

**Issue by zhuazi** [chaos-mesh/chaos-mesh#3005]
## Question
after looking at the source code,I can't find the code  that use the  parameter 'duration' manager the chaos's life cycle，can  somebody help me？

**Comment by zhuazi** [comment]
the entry point for the schedule task that  stops running chaos. is controller? or dashboard?

**Comment by Andrewmatilde** [comment]
PTAL @STRRL .

**Comment by STRRL** [comment]
Hi @zhuazi, we use a series of controllers for the lifecycle of all types of chaos, you could find it in:

https://github.com/chaos-mesh/chaos-mesh/blob/8d8ed48eed82ca60106cf85c84a368bd10f6bc4e/controllers/common/step.go#L26-L28

**Comment by zhuazi** [comment]
hi @STRRL ，i found these functions has changed the status of chaos，but i didn't find a loop function to watch the Duration of the chaos , Can you show me how it work?

**Comment by STRRL** [comment]
Sorry for the late response, the "controller" called `desiredphase` would use the current time, creation timestamp, and field `duration` to determine  "should the chaos experiment effect right now or not"
