### ISSUE TITLE
Need a `Warning` log func

### ISSUE THREAD

**Issue by Andrewmatilde** [chaos-mesh/chaos-mesh#3021]
I approved the rfc : 
```
V(0) - This is the default level, would ALWAYS be visible to users.
CLI argument handling, print args before the program starts
Application configuration
Expected errors as warning message
```

But in real code , I feel wired about the code `logger.V().Info()`.
@STRRL 
related : #3002

**Comment by STRRL** [comment]
We could use `logger.Info()` without `V(0)`. 

Or do you think using Info as Warning is weird?

**Comment by Andrewmatilde** [comment]
Yes, I think Info as Warning is weird.

**Comment by STRRL** [comment]
Using `Error` and `Verbosity-levels Info` is another different pattern from the log level with `Error`, `Warning`, `Info`, `Debug`, `Trace`, which we used before.

Using the `Warning` level is actually ambiguous, and actually, no one would read the warning level.

About eliminating the warning level, I think this blog could introduce better than me: https://dave.cheney.net/2015/11/05/lets-talk-about-logging, chapter "Let’s talk about warnings".

**Comment by Andrewmatilde** [comment]
I think warning is a debug hint. Meybe a msg : "I don't know how to divide a error situation but there may have error" is better.
