### ISSUE TITLE
Host failure experiment delete experiment failed

### ISSUE THREAD

**Issue by zhqqqy** [chaos-mesh/chaos-mesh#3028]
## Bug Report

**What version of Kubernetes are you using?**

Kubernetes 1.14
**What version of Chaos Mesh are you using?**

chaos-mesh v2.1.3
**What did you do?**

When I injected a stress  experiment and set the duration to 20s, the experiment was not deleted when the 20s time expired
**What did you expect to see?**
kill stress-ng process
**What did you see instead?**
chaosd prompt 404 
![image](https://user-images.githubusercontent.com/13046318/158537647-cf38cc75-0b7a-4fab-b25c-3b3c42dc7136.png)
log is
![image](https://user-images.githubusercontent.com/13046318/158539636-53ffa756-d933-4405-9a43-3fa548b62a2d.png)
crd yaml
![image](https://user-images.githubusercontent.com/13046318/158540791-91120137-7c01-473d-b6bd-569163865ea6.png)

**Output of chaosctl**

**Comment by WangXiangUSTC** [comment]
I see that the `DELETE` request miss the `uid` information, and the `uid` is generated by webhook, are there some problems with the webhook?

**Comment by zhqqqy** [comment]
> I see that the `DELETE` request misses the `uid` information, and the `uid` is generated by webhook, are there some problems with the webhook?

uid exists, but in metadata instead of spec. I don't know why

**Comment by zhqqqy** [comment]
> I see that the `DELETE` request misses the `uid` information, and the `uid` is generated by webhook, are there some problems with the webhook?

what is the difference between metadata.uid and spec.uid ?

**Comment by WangXiangUSTC** [comment]
The `spec.uid` is used for `chaosd`'s experiment(only for PhysicalMachineChaos), `chaosd` need to locate an experiment information by a `uid`.  The `metadata.uid` is used for all the experiments in Chaos Mesh, it is used for Chaos Dashboard. 
By the way, I think we can abandon the `sepc.uid` and use `metadata.uid` later.
