### ISSUE TITLE
IOChaos latency injected failed to rootfs directory

### ISSUE THREAD

**Issue by sigezhao** [chaos-mesh/chaos-mesh#3040]
root@disk-chaos-test-955984b4d-knzr6:/app# df -h
Filesystem      Size  Used Avail Use% Mounted on
overlay          50G   14G   34G  30% /    **-- 注入这里面的/home/目录不行**
tmpfs            64M     0   64M   0% /dev
tmpfs            31G     0   31G   0% /sys/fs/cgroup
/dev/vdb        9.8G   24K  9.8G   1% /mnt **-- 注入这里面是可以的**
/dev/vda1        50G   14G   34G  30% /etc/hosts
shm              64M     0   64M   0% /dev/shm
tmpfs            31G   12K   31G   1% /run/secrets/kubernetes.io/serviceaccount
tmpfs            31G     0   31G   0% /proc/acpi
tmpfs            31G     0   31G   0% /proc/scsi
tmpfs            31G     0   31G   0% /sys/firmware

==== 

chaosctl output
./chaosctl debug iochaos -n chaos-testing
failed to execute cmd: 

        internal system error

========

controller log

1.6475705960823858e+09	INFO	records	iterating record	{"record": {"id":"chaos-testing/disk-chaos-test-955984b4d-knzr6/disk-chaos-test","selectorKey":".","phase":"Not Injected/Wait"}, "desiredPhase": "Run"}
1.6475705960823936e+09	INFO	records	apply chaos	{"id": "chaos-testing/disk-chaos-test-955984b4d-knzr6/disk-chaos-test"}
1.6475705960823972e+09	INFO	iochaos	iochaos Apply	{"namespace": "chaos-testing", "name": "disk-chaos-latency-home-v1"}
1.647570596082413e+09	ERROR	records	fail to apply chaos	{"error": "rpc error: code = Unknown desc = toda startup takes too long or an error occurs: source: /home/, target: /__chaosfs__home__"}
github.com/chaos-mesh/chaos-mesh/controllers/common/pipeline.(*Pipeline).Reconcile
	/mnt/controllers/common/pipeline/pipeline.go:73
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile
	/tmp/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:114
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/tmp/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:311
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/tmp/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:266
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	/tmp/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:227
1.6475705960824583e+09	INFO	pipeline	reconcile result	{"result": {"Requeue":true,"RequeueAfter":0}}
1.6475706165627375e+09	INFO	pipeline	reconcile result	{"result": {"Requeue":false,"RequeueAfter":0}}
1.6475706165627875e+09	INFO	desiredphase	modify desiredPhase	{"desiredPhase": "Run"}
1.647570616562795e+09	INFO	pipeline	reconcile result	{"result": {"Requeue":false,"RequeueAfter":0}}
1.647570616562821e+09	INFO	pipeline	reconcile result	{"result": {"Requeue":false,"RequeueAfter":0}}
1.6475706165628362e+09	INFO	records	iterating record	{"record": {"id":"chaos-testing/disk-chaos-test-955984b4d-knzr6/disk-chaos-test","selectorKey":".","phase":"Not Injected/Wait"}, "desiredPhase": "Run"}
1.6475706165628448e+09	INFO	records	apply chaos	{"id": "chaos-testing/disk-chaos-test-955984b4d-knzr6/disk-chaos-test"}
1.6475706165628488e+09	INFO	iochaos	iochaos Apply	{"namespace": "chaos-testing", "name": "disk-chaos-latency-home-v1"}
1.6475706165628662e+09	ERROR	records	fail to apply chaos	{"error": "rpc error: code = Unknown desc = toda startup takes too long or an error occurs: source: /home/, target: /__chaosfs__home__"}
github.com/chaos-mesh/chaos-mesh/controllers/common/pipeline.(*Pipeline).Reconcile
	/mnt/controllers/common/pipeline/pipeline.go:73
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile
	/tmp/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:114
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/tmp/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:311
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/tmp/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:266
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	/tmp/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:227
1.6475706165629084e+09	INFO	pipeline	reconcile result	{"result": {"Requeue":true,"RequeueAfter":0}}

==================
chaos-daemon errosr message，== {"log":"{\"jsonrpc\": == output once per 17 min。

{"log":"note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.\n","stream":"stderr","time":"2022-03-17T09:57:42.180310123Z"}
{"log":"1.6475110641470585e+09\u0009INFO\u0009chaos-daemon-server\u0009Starting toda takes too long or encounter an error\n","stream":"stderr","time":"2022-03-17T09:57:44.147159218Z"}
{"log":"1.6475110641471047e+09\u0009INFO\u0009chaos-daemon-server\u0009killing toda\u0009{\"pid\": 333787}\n","stream":"stderr","time":"2022-03-17T09:57:44.147180257Z"}
{"log":"\u001b[2mMar 17 09:57:44.147\u001b[0m \u001b[32m INFO\u001b[0m toda: start to recover and exit\n","stream":"stderr","time":"2022-03-17T09:57:44.147434765Z"}
{"log":"1.6475110641482434e+09\u0009INFO\u0009background-process-manager\u0009process stopped\u0009{\"pid\": 333787}\n","stream":"stderr","time":"2022-03-17T09:57:44.148297403Z"}
....
{"log":"{\"jsonrpc\":\"2.0\",\"result\":\"source: /home/, target: /__chaosfs__home__\",\"id\":1}\n","stream":"stdout","time":"2022-03-18T01:22:52.038728139Z"}
{"log":"{\"jsonrpc\":\"2.0\",\"result\":\"source: /home/, target: /__chaosfs__home__\",\"id\":1}\n","stream":"stdout","time":"2022-03-18T01:39:34.068195839Z"}
{"log":"{\"jsonrpc\":\"2.0\",\"result\":\"source: /home/, target: /__chaosfs__home__\",\"id\":1}\n","stream":"stdout","time":"2022-03-18T01:56:16.107363417Z"}
{"log":"{\"jsonrpc\":\"2.0\",\"result\":\"source: /home/, target: /__chaosfs__home__\",\"id\":1}\n","stream":"stdout","time":"2022-03-18T02:12:58.13987878Z"}

**Comment by YangKeao** [comment]
Yes. The `volumepath` cannot be the root, because we need to `mount --move` the mountpoint, and it's obvious that we can't move the root mountpoint.

**Comment by YangKeao** [comment]
And the `volume_path` should also be a a mountpoint. It seems that the `/home` is not a mountpoint, which is also not allowed.
