### ISSUE TITLE
STRESS TEST load over 100 will not take effect

### ISSUE THREAD

**Issue by 15767637775** [chaos-mesh/chaos-mesh#3064]
chaos mesh v2.1.3
dashboard -> STRESS TEST -> CPU -> Load

If I fill in the blank with value over 100, the STRESS TEST will not take effect.
the value's validation is needed.
![image](https://user-images.githubusercontent.com/71695537/160222121-2b590c57-149d-49f1-8e99-aa1ab4a67586.png)

**Comment by Andrewmatilde** [comment]
@15767637775 Thanks for your feedback.
/cc @g1eny0ung May I assign this issue to you?
