### ISSUE TITLE
Inode of containerd socket in chaos daemon pod is not equal to the Inode on host, after restart containerd

### ISSUE THREAD

**Issue by xlgao-zju** [chaos-mesh/chaos-mesh#3072]
## Bug Report

**What version of Kubernetes are you using?**

Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.15+k3s1", GitCommit:"60f1e80dcb07a32a42688e149778778ffb00ca9a", GitTreeState:"clean", BuildDate:"2021-01-14T22:50:21Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.15+k3s1", GitCommit:"60f1e80dcb07a32a42688e149778778ffb00ca9a", GitTreeState:"clean", BuildDate:"2021-01-14T22:50:21Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

**What version of Chaos Mesh are you using?**

2.1.1

**What did you do?**

1. on host
```shell  
stat /run/k3s/containerd/containerd.sock

  File: /run/k3s/containerd/containerd.sock
  Size: 0         	Blocks: 0          IO Block: 4096   socket
Device: 17h/23d	Inode: 405450      Links: 1
Access: (0660/srw-rw----)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2022-03-28 18:38:02.580902830 +0800
Modify: 2022-03-28 18:20:12.121940582 +0800
Change: 2022-03-28 18:20:12.121940582 +0800
 Birth: -
```
we can see the Inode is 405450.

2. and the Inode of ` /run/k3s/containerd/containerd.sock` in chaos daemon  pod is also 405450.

3. restart the containerd. and the Inode of ` /run/k3s/containerd/containerd.sock`  changes. 
on the host, we get
```shell
stat /run/k3s/containerd/containerd.sock
  File: /run/k3s/containerd/containerd.sock
  Size: 0         	Blocks: 0          IO Block: 4096   socket
Device: 17h/23d	Inode: 556343      Links: 1
Access: (0660/srw-rw----)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2022-03-28 18:56:06.751757033 +0800
Modify: 2022-03-28 18:56:05.847761260 +0800
Change: 2022-03-28 18:56:05.847761260 +0800
 Birth: -
```

4. the Inode of ` /run/k3s/containerd/containerd.sock` in chaos daemon do not change. the Inode in the pod is still 405450.

**What did you expect to see?**
the Inode of ` /run/k3s/containerd/containerd.sock` in chaos daemon also changes to 556343.

**What did you see instead?**

**Output of chaosctl**

**Comment by xlgao-zju** [comment]
I'd like to file a PR to fix this bug.

/assign

**Comment by xlgao-zju** [comment]
cc @track87

**Comment by FingerLeader** [comment]
That must be very helpful, if you can fix this bug.
