### ISSUE TITLE
HTTPCHAOS "Failed to apply chaos: rpc error: code = DeadlineExceeded desc = context deadline exceeded"

### ISSUE THREAD

**Issue by zhuazi** [chaos-mesh/chaos-mesh#3089]
## Question
hi , when i use the httpchaos  replace , the controller reply "Failed to apply chaos: rpc error: code = DeadlineExceeded desc = context deadline exceeded"
the events
![image](https://user-images.githubusercontent.com/4626297/161184097-3e9c5ae0-1d19-4d57-a2ac-c6a5dfdda051.png)
the controller logs
![image](https://user-images.githubusercontent.com/4626297/161184676-c84cdadf-444f-45a5-9ce6-d264119e5f08.png)
the  chaos yaml
![image](https://user-images.githubusercontent.com/4626297/161184817-1367eb40-39b3-4608-ad56-8ed710ceaf26.png)
sometime ,it will reply "Failed to apply chaos: status(400), apply fail: unknown variant ``, expected `TEXT` or `BASE64` at line 1 column 179"
![image](https://user-images.githubusercontent.com/4626297/161184915-c6119c55-9280-4fa8-920c-4ca6027085ee.png)

**Comment by iguoyr** [comment]
> when i use the httpchaos replace

@zhuazi Hi, can you provide more informations about this operation, do you mean updating a HTTPChaos? And what version of Chaos Mesh are you using?

**Comment by zhuazi** [comment]
> 
hi，I cloned the code from the master，It should be 2.1.3 , and I didn‘t update the HTTPCHAOS.

**Comment by Andrewmatilde** [comment]
> hi @iguoyr ，I cloned the code from the master，It should be 2.1.3 , and I didn‘t update the HTTPCHAOS.

Hi @zhuazi ,  thanks for your feedback. I am sorry that it seems you should use the master brench or wait for the 2.2.X . The HTTP-Chaos was failed to cherry-pick and fix this problem now.

**Comment by iguoyr** [comment]
@zhuazi I close this issue for now, if you have any other problems, feel free to open new issues :)
