### ISSUE TITLE
how to exec command in specific node？

### ISSUE THREAD

**Issue by ycwdaaaa** [chaos-mesh/chaos-mesh#3093]
## Question
Hi， I noticed chao-mesh will deploy choas-daemon on every node， I just want to know if I write a new type like kill kubelet or docker， I need to specific one node to execute this command。 How can I do it that only the  specific node‘s chao-mesh will revice request and execute this command？

**Comment by ycwdaaaa** [comment]
sorry to bother you , I just wish to learn how chaos-mesh does.  I found the svc of chaos-daemon is a headless svc.  but still cannot understand how to send request to the  chaos-daemon on the specific node

**Comment by iguoyr** [comment]
@ycwdaaaa Hi, you could refer to [this function](https://github.com/chaos-mesh/chaos-mesh/blob/master/controllers/utils/chaosdaemon/chaosdaemon.go#L52), it lists `Endpoints`, and find which IP matches the NodeName of the specific node.

**Comment by ycwdaaaa** [comment]
> @ycwdaaaa Hi, you could refer to [this function](https://github.com/chaos-mesh/chaos-mesh/blob/master/controllers/utils/chaosdaemon/chaosdaemon.go#L52), it lists `Endpoints`, and find which IP matches the NodeName of the specific node.

So if I‘m able to get the pod id by endpoints, so why would I need to use headless service?
