### ISSUE TITLE
helm-chart deployment with cert-manager, after 90 days cert is invalid

### ISSUE THREAD

**Issue by Oro** [chaos-mesh/chaos-mesh#3099]
## Bug Report

**What version of Kubernetes are you using?**

```
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.5-eks-bc4871b", GitCommit:"5236faf39f1b7a7dabea8df12726f25608131aa9", GitTreeState:"clean", BuildDate:"2021-10-29T23:32:16Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
```

**What version of Chaos Mesh are you using?**
```
Controller manager Version: version.Info{GitVersion:"v2.1.2", GitCommit:"24a1f565ed000ba8738a4ed568b4e9a0925fe2fb", BuildDate:"2021-12-29T11:43:40Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"linux/amd64"}
```

**What did you do?**

```yaml
dashboard:
  securityMode: false
  service:
    type: ClusterIP
webhook:
  certManager:
    enabled: true
```
(Only the certmanager part is relevant)

**What did you expect to see?**
After 90 days, chaos CRDs should be deployable
**What did you see instead?**
After 90 days, chaos CRDs can no longer be deployed with following error
```
error.api.internal_server_error: Internal error occurred: failed calling webhook "mpodchaos.kb.io": Post "https://chaos-mesh-controller-manager.chaos-mesh.svc:443/mutate-chaos-mesh-org-v1alpha1-podchaos?timeout=5s": x509: certificate has expired or is not yet valid: current time 2022-04-05T08:36:14Z is after 2022-04-03T20:13:29Z
```

My guess is that this is because the CA validity for `chaos-mesh-ca` was reached the certs for the mutating webhook are no longer valid.
While the certs themselves do have a duration of 5 years, the CA does not have an explicit duration set https://github.com/chaos-mesh/chaos-mesh/blob/master/helm/chaos-mesh/templates/secrets-configuration.yaml#L329 and therefore uses the [default duration](https://cert-manager.io/docs/faq/#if-renewbefore-or-duration-is-not-defined-what-will-be-the-default-value) of 90 days.

The easy fix would probably be to set the CA validity to 5 years; However I think the correct fix is to set the validity for the webhook cert much lower (30 days? 90 days?) instead (or make the validities user configurable)

EDIT:
To make that obvious, after a `kubectl cert-manager renew -n chaos-mesh  chaos-mesh-cert` (no pod restart or anything, just this command) chaos CRDs were deployable again.
Also of note: AFAICT cert-manager does not automatically renew leaf certs if the root cert changed, https://github.com/cert-manager/cert-manager/issues/2478

**Comment by iguoyr** [comment]
@Oro Hi, thanks for reporting this issue! It looks like an inevitable problem. Do you have any interest in helping to fix this problem?

**Comment by Oro** [comment]
Sure, should be easy enough. How should it be implemented? User configuration, one for CA duration and one for cert duration, default to 10 years and 5 years? That is probably the most straight-forward backwards-compatible fix.

NB: I have just stumbled across https://github.com/chaos-mesh/chaos-mesh/issues/2767 , meaning that (probably//hopefully if the full chain is checked) the same issue happens for the other certs if created via cert-manager too, I don't know if they are refreshed on-the-fly without a pod restart.

**Comment by iguoyr** [comment]
> Sure, should be easy enough. How should it be implemented? User configuration, one for CA duration and one for cert duration, default to 10 years and 5 years? That is probably the most straight-forward backwards-compatible fix.

@Oro Hi, sorry for the late reply, I think set the default duration of CA and cert at 5 years is a good idea, which is the same strategy as [using helm template to generate certs](https://github.com/chaos-mesh/chaos-mesh/blob/v2.1.4/helm/chaos-mesh/templates/secrets-configuration.yaml#L16) (both 5 years).

> NB: I have just stumbled across #2767 , meaning that (probably//hopefully if the full chain is checked) the same issue happens for the other certs if created via cert-manager too, I don't know if they are refreshed on-the-fly without a pod restart.

It looks like #2767 is irrelevant to this issue, it would like to split the original configuration into separate parts, which improves the ease of use, but does not resolve the cert-manager configuration problem. 🤔
