### ISSUE TITLE
networkchaos delete fail

### ISSUE THREAD

**Issue by zhuazi** [chaos-mesh/chaos-mesh#3122]
version 2.1.3
the networkchaos  Injection failed , then i can't delete the experiment，The guess is that one failed experiment affected all subsequent experiments。
![image](https://user-images.githubusercontent.com/4626297/162904786-fd99442c-fc93-4fc9-821e-b36d5d1cc4ea.png)
![image](https://user-images.githubusercontent.com/4626297/162905731-7d8fed17-6daf-48bc-b006-8b1b99662a73.png)

**Comment by cwen0** [comment]
> @cwen0 is this? ![image](https://user-images.githubusercontent.com/4626297/162911283-c31d27a7-dd77-49a1-af7a-0dddc9a11f19.png)

1. If the experiment can't be deleted, you can use the following command to force delete it: 

```
kubectl annotate networkchaos ${experiment-name} chaos-mesh.chaos-mesh.org/cleanFinalizer=forced
```

For more info refer to https://chaos-mesh.org/docs/run-a-chaos-experiment/

2. Chaos Mesh is not allowed to inject network chaos on `hostNetwork` pods by default. Because `hostNetwork` pod will use the network interface of nodes directly and injecting network chaos on this interface is very dangerous.  You also can use `controllerManager. allowHostNetworkTesting` field to enable it, like: 

```
helm upgrade chaos-mesh chaos-mesh/chaos-mesh -n xxx --set controllerManager.allowHostNetworkTesting=true
```

3. Actually, I'm more curious about this issue:
![image](https://user-images.githubusercontent.com/22956341/162915127-4291414f-82fb-40e3-907f-b5daba7a16ca.png)

Can you provide more context logs related to this issue? You can use `networkcaos90-od` to filter `chaos-controller-manager` log or upload the whole log to me.

**Comment by cwen0** [comment]
> @cwen0 I guess it may be caused by this parameter，and I'm more concerned about why it can't be deleted ![image](https://user-images.githubusercontent.com/4626297/162929458-40402e0a-7447-478a-ad60-8faa66026a04.png) ![image](https://user-images.githubusercontent.com/4626297/162930656-f7d0e95e-ae24-4764-8e3c-c9050c5196f4.png)

This injection action was failed, and chaos mesh didn't know why it failed and not sure if some chaos rules has been injected to the target pod. So chaos mesh requires users to handle this error and recover it manually. If users make sure that the chaos was not working, chaos mesh provides a way to force recover it, like it: 

```
kubectl annotate networkchaos ${experiment-name} chaos-mesh.chaos-mesh.org/cleanFinalizer=forced
```

Or you can just empty the finalizers of the chaos object directly by `kubectl edit ....`. For more info refer to https://chaos-mesh.org/docs/run-a-chaos-experiment/

**Comment by zhuazi** [comment]
hi @cwen0 , where is the code to change the 'networkchaos record Phase' from "Not Injected/Wait" to  "Injected" ? i want to check whether there is a way to avoid this .

**Comment by cwen0** [comment]
> hi @cwen0 , where is the code to change the 'networkchaos record Phase' from "Not Injected/Wait" to "Injected" ? i want to check whether there is a way to avoid this.

`NetworkChaos` will apply chaos configuration to `PodNetworkChaos` and wait for this `PodNetworChaos` to inject the failure into the target pod. You can find the implementation logic here: 
https://github.com/chaos-mesh/chaos-mesh/blob/master/controllers/chaosimpl/networkchaos/trafficcontrol/impl.go#L58-L176 

Here is the `phase` conversion logic: 
https://github.com/chaos-mesh/chaos-mesh/blob/master/controllers/common/records/controller.go#L115-L194

**Comment by zhuazi** [comment]
> > hi @cwen0 , where is the code to change the 'networkchaos record Phase' from "Not Injected/Wait" to "Injected" ? i want to check whether there is a way to avoid this.
> 
> `NetworkChaos` will apply chaos configuration to `PodNetworkChaos` and wait for this `PodNetworChaos` to inject the failure into the target pod. You can find the implementation logic here: https://github.com/chaos-mesh/chaos-mesh/blob/master/controllers/chaosimpl/networkchaos/trafficcontrol/impl.go#L58-L176
> 
> Here is the `phase` conversion logic: https://github.com/chaos-mesh/chaos-mesh/blob/master/controllers/common/records/controller.go#L115-L194

hi @cwen0  Thank you for your patient answer, I still have a few questions
    Who let networkchaos repeatedly add to the informer workqueue? I checked the code and didn't find out who changed the state of networkchaos to enable him to enter the informer workqueue.
    There are too many asynchronous operations in the code of chaomesh, so I can't see a completed process. thx.
..

**Comment by cwen0** [comment]
> > > hi @cwen0 , where is the code to change the 'networkchaos record Phase' from "Not Injected/Wait" to "Injected" ? i want to check whether there is a way to avoid this.
> > 
> > 
> > `NetworkChaos` will apply chaos configuration to `PodNetworkChaos` and wait for this `PodNetworChaos` to inject the failure into the target pod. You can find the implementation logic here: https://github.com/chaos-mesh/chaos-mesh/blob/master/controllers/chaosimpl/networkchaos/trafficcontrol/impl.go#L58-L176
> > Here is the `phase` conversion logic: https://github.com/chaos-mesh/chaos-mesh/blob/master/controllers/common/records/controller.go#L115-L194
> 
> hi @cwen0 Thank you for your patient answer, I still have a few questions Who let networkchaos repeatedly add to the informer workqueue? I checked the code and find out the re-queue logic ,the code indicates that it cannot re-queue immediately, but the controller logs show that it will re-queue immediately. ![image](https://user-images.githubusercontent.com/4626297/163134818-8d82a5a8-88fe-492c-a604-8bee89fa6624.png)
> 
> ```
> There are too many asynchronous operations in the code of chaomesh, so I can't see a completed process. thx.
> ```
> 
> ..

If the object was updated, it will be re-queued and the network `Reconcile` function would be called.
