### ISSUE TITLE
Add new Experiment HelloWorldChaos failed

### ISSUE THREAD

**Issue by ShangfengDing** [chaos-mesh/chaos-mesh#3124]
## Bug Report

**What version of Chaos Mesh are you using?**
release-2.1
commit 2d200a0d2ed2e4e9f689355a86430da5c2743de9

**What did you do?**
I follow the guide https://chaos-mesh.org/zh/docs/add-new-chaos-experiment-type/ add HelloWorldChaos

**What did you expect to see?**
In step one, I new helloworldchaos_types.go in api/v1alpha1 and then run make generate. 
I expect to see all code generate successful.

zz_generated.chaosmesh.go
zz_generated.chaosmesh_test.go
zz_generated.schedule.chaosmesh.go
zz_generated.workflow.chaosmesh.go
zz_generated.workflow.chaosmesh_test.go
generate successful.

zz_generated.deepcopy.go
generate failed. No changes at all.

**What did you see instead?**
go generate ./pkg/ctrlserver/graph
validation failed: packages.Load: /mnt/api/v1alpha1/zz_generated.chaosmesh.go:568:27: cannot use &(HelloWorldChaos literal) (value of type *HelloWorldChaos) as admission.Validator value in variable declaration: missing method DeepCopyObject
/mnt/api/v1alpha1/zz_generated.chaosmesh.go:575:27: cannot use &(HelloWorldChaos literal) (value of type *HelloWorldChaos) as admission.Defaulter value in variable declaration: missing method DeepCopyObject
/mnt/api/v1alpha1/zz_generated.chaosmesh.go:505:9: cannot use in.DeepCopy() (value of type *"k8s.io/apimachinery/pkg/apis/meta/v1".ListMeta) as GenericChaosList value in return statement: missing method DeepCopyList
/mnt/api/v1alpha1/zz_generated.chaosmesh.go:513:27: cannot use &item (value of type *HelloWorldChaos) as GenericChaos value in argument to append: missing method DeepCopyObject
/mnt/api/v1alpha1/zz_generated.chaosmesh.go:554:33: old (variable of type "k8s.io/apimachinery/pkg/runtime".Object) cannot have dynamic type *HelloWorldChaos (missing method DeepCopyObject)
/mnt/api/v1alpha1/zz_generated.chaosmesh.go:1910:25: cannot use &(HelloWorldChaos literal) (value of type *HelloWorldChaos) as "k8s.io/apimachinery/pkg/runtime".Object value in argument to SchemeBuilder.Register: missing method DeepCopyObject
/mnt/api/v1alpha1/zz_generated.chaosmesh.go:1910:45: cannot use &(HelloWorldChaosList literal) (value of type *HelloWorldChaosList) as "k8s.io/apimachinery/pkg/runtime".Object value in argument to SchemeBuilder.Register: missing method DeepCopyObject
/mnt/api/v1alpha1/zz_generated.chaosmesh.go:1912:10: cannot use &(HelloWorldChaos literal) (value of type *HelloWorldChaos) as client.Object value in struct literal: missing method DeepCopyObject
/mnt/api/v1alpha1/zz_generated.chaosmesh.go:1913:10: cannot use &(HelloWorldChaosList literal) (value of type *HelloWorldChaosList) as GenericChaosList value in struct literal: missing method DeepCopyObject
/mnt/api/v1alpha1/zz_generated.chaosmesh.go:1993:10: cannot use &(HelloWorldChaos literal) (value of type *HelloWorldChaos) as client.Object value in struct literal: missing method DeepCopyObject
/mnt/api/v1alpha1/zz_generated.chaosmesh.go:1994:10: cannot use &(HelloWorldChaosList literal) (value of type *HelloWorldChaosList) as GenericChaosList value in struct literal: missing method DeepCopyObject
/mnt/api/v1alpha1/zz_generated.schedule.chaosmesh.go:79:10: cannot use &result (value of type *HelloWorldChaos) as GenericChaos value in return statement: missing method DeepCopyObject
/mnt/api/v1alpha1/zz_generated.workflow.chaosmesh.go:108:10: cannot use &result (value of type *HelloWorldChaos) as GenericChaos value in return statement: missing method DeepCopyObject
/mnt/api/v1alpha1/zz_generated.workflow.chaosmesh.go:211:10: cannot use &result (value of type *HelloWorldChaosList) as GenericChaosList value in return statement: missing method DeepCopyObject
/mnt/api/v1alpha1/zz_generated.workflow.chaosmesh.go:273:27: cannot use &item (value of type *HelloWorldChaos) as GenericChaos value in argument to append: missing method DeepCopyObject
pkg/ctrlserver/graph/resolver.go:18: running "gqlgen": exit status 1
make: *** [Makefile:436: generate-ctrl] Error 1
make: *** [generate] Error 2

**Comment by ShangfengDing** [comment]
zz_generated.deepcopy.go seems to be no change after the make generate command.

**Comment by tonystz** [comment]
there are still an issue for the [hellowworld](https://chaos-mesh.org/docs/add-new-chaos-experiment-type/) example:
```
kustomize build output/config-v1beta1/default > manifests/crd-v1beta1.yaml
CGO_ENABLED=1 go build -ldflags "-s -w -X 'github.com/chaos-mesh/chaos-mesh/pkg/version.buildDate=2022-06-24T06:39:23Z' -X 'github.com/chaos-mesh/chaos-mesh/pkg/version.gitCommit=aef6f9a9c4bb37d2b7b066dc3d2c8963e6de9894' -X 'github.com/chaos-mesh/chaos-mesh/pkg/version.gitVersion=v2.3.0-alpha.2'" -tags "" -o images/chaos-daemon/bin/chaos-daemon ./cmd/chaos-daemon/main.go
# github.com/chaos-mesh/chaos-mesh/api/v1alpha1
api/v1alpha1/zz_generated.chaosmesh.go:776:9: cannot use in.DeepCopy() (value of type *"k8s.io/apimachinery/pkg/apis/meta/v1".ListMeta) as type GenericChaosList in return statement:
        *"k8s.io/apimachinery/pkg/apis/meta/v1".ListMeta does not implement GenericChaosList (missing DeepCopyList method)
api/v1alpha1/zz_generated.chaosmesh.go:784:27: cannot use &item (value of type *HelloWorldChaos) as type GenericChaos in argument to append:
        *HelloWorldChaos does not implement GenericChaos (missing DeepCopyObject method)
api/v1alpha1/zz_generated.chaosmesh.go:825:33: impossible type assertion: old.(*HelloWorldChaos)
        *HelloWorldChaos does not implement runtime.Object (missing DeepCopyObject method)
api/v1alpha1/zz_generated.chaosmesh.go:839:27: cannot use &HelloWorldChaos{} (value of type *HelloWorldChaos) as type admission.Validator in variable declaration:
        *HelloWorldChaos does not implement admission.Validator (missing DeepCopyObject method)
api/v1alpha1/zz_generated.chaosmesh.go:846:27: cannot use &HelloWorldChaos{} (value of type *HelloWorldChaos) as type admission.Defaulter in variable declaration:
        *HelloWorldChaos does not implement admission.Defaulter (missing DeepCopyObject method)
api/v1alpha1/zz_generated.chaosmesh.go:2271:25: cannot use &HelloWorldChaos{} (value of type *HelloWorldChaos) as type runtime.Object in argument to SchemeBuilder.Register:
        *HelloWorldChaos does not implement runtime.Object (missing DeepCopyObject method)
api/v1alpha1/zz_generated.chaosmesh.go:2271:45: cannot use &HelloWorldChaosList{} (value of type *HelloWorldChaosList) as type runtime.Object in argument to SchemeBuilder.Register:
        *HelloWorldChaosList does not implement runtime.Object (missing DeepCopyObject method)
api/v1alpha1/zz_generated.chaosmesh.go:2273:10: cannot use &HelloWorldChaos{} (value of type *HelloWorldChaos) as type client.Object in struct literal:
        *HelloWorldChaos does not implement client.Object (missing DeepCopyObject method)
api/v1alpha1/zz_generated.chaosmesh.go:2274:10: cannot use &HelloWorldChaosList{} (value of type *HelloWorldChaosList) as type GenericChaosList in struct literal:
        *HelloWorldChaosList does not implement GenericChaosList (missing DeepCopyObject method)
api/v1alpha1/zz_generated.chaosmesh.go:2368:10: cannot use &HelloWorldChaos{} (value of type *HelloWorldChaos) as type client.Object in struct literal:
        *HelloWorldChaos does not implement client.Object (missing DeepCopyObject method)
api/v1alpha1/zz_generated.chaosmesh.go:2368:10: too many errors
make: *** [images/chaos-daemon/bin/chaos-daemon] Error 2
```

**Comment by iguoyr** [comment]
Hi @tonystz, which branch did you use?

**Comment by iguoyr** [comment]
Hi @tonystz, from the error message:
```
*HelloWorldChaos does not implement GenericChaos (missing DeepCopyObject method)
```
It seems that the `/api/alpha1v1/zz_generated.deepcopy.go` is not modified.

Did you run `make generate` command in `Step1: Define the schema type`? Maybe you could try `make generate` command, then make images.
