### ISSUE TITLE
Test verdict for the system under test

### ISSUE THREAD

**Issue by BonjourGit** [chaos-mesh/chaos-mesh#3160]
Hi,

Does chaos-mesh provide test verdict for the system under test?

It is understood that the chaos tests provide the "Status" (Paused, Selected, AllInjected, AllRecovered) and "Events" via "kubectl describe" or chaos dashboard.
However, it appears to be an indicator of the status of the chaos test itself, i.e. how the test itself proceeds and the events associated with the test. Is the understanding correct?

In terms of the overall status of the system under chaos test (e.g. the Kubernetes cluster/namespace and the traffic the system is handling), does chaos-mesh also provide similar test verdict, or it is out of the scope of chaos-mesh and requires external observation?
I.e. evaluate the relevant system status before & after a chaos test, and provide a test verdict (success or failure) depending on indicators showing whether the system under test has sustained such chaos test.

Please advise.

Many thanks!

**Comment by Hexilee** [comment]
I'm sorry that Chaos Mesh doesn't provide build-in effects observation currently. However, we are planning to provide it in the future version. Here is a relevant [discussion](https://github.com/chaos-mesh/chaos-mesh/discussions/3012), you are welcome to talk about your requirements and advice!

**Comment by BonjourGit** [comment]
@Hexilee @iguoyr

Thank you for the input. Adding my two cents.
IMO the system observability along with running Chaos Mesh could possibly be considered in two distinctive layers.

1. Kubernetes Layer
At the Kubernetes layer, compare the infrastructure status from Kubernetes point of view before & after chaos mesh testing.
Since it does not depend on specific cloud application under test, Chaos mesh could consider including this as an integral part of StatusCheck natively. E.g. just to name a few:
- Are the instantiated resources/workloads match what are described in helm manifests?
- Are all nodes in Ready state?
- Are all Pods in Running state?
- Are the number of Pod replicas match the requirement?
- Are there any anomaly detected in selected Kubernetes metrics?
- etc.

2. Service Layer
The service layer checks the status of the actual cloud application before & after chaos mesh testing.
This can be more sophisticated due to the broad range of applications under test.
It needs domain knowledge to measure the service level objectives of different applications.
The HTTP request/response model as proposed by StatusCheck possibly fall into this category.
The application under test must be able to expose e.g. RESTful APIs to return its own status.
Observability at this layer would most likely work as application plug-ins/APIs for Chaos Mesh to call and return verification results.

Above are just some coarse thoughts that pops up.
Thanks!
