### ISSUE TITLE
How about avoiding using "SecurityMode", it is kind of ambigous.

### ISSUE THREAD

**Issue by STRRL** [chaos-mesh/chaos-mesh#3167]
## Question

There are soo many words in the configuration introduced as `<something>SecurirtyMode`, and they require different integration for different features, relates to RBAC of Kubernetes and in-application RPC security.

**Comment by YangKeao** [comment]
(Then rename to "hardened mode" :crying_cat_face:  )

**Comment by STRRL** [comment]
> (Then rename to "hardened mode" crying_cat_face )

IMO both "hardened" and "security" would not make people know what it effects.

How about naming it with what actually it controls? 

For example: 
- gcpSecurityMode -> gcpOIDCIntegration
- dashboard.SecurityMode -> dashboard.userRBAC
- controllerManager.chaosdSecurityMode -> controllerManager.chaosd.mtls.enabled
- ....

**Comment by STRRL** [comment]
duplicated with https://github.com/chaos-mesh/chaos-mesh/issues/3015
