### ISSUE TITLE
Release Cycle for Chaos Mesh

### ISSUE THREAD

**Issue by STRRL** [chaos-mesh/chaos-mesh#3172]
## Feature Request

**Is your feature request related to a problem? Please describe:**

YES. The current state of release policy is not satisfactory.

Chaos Mesh is still a fresh opensource project, we have tried to make effort to bring our work to the adopters regularly and stably.

BUT:

- Chaos Mesh 2.1.0 was released on Nov 30, 2021; (the last minor release)

It has been about **5 months** since we release our last minor release with our awesome new features, much longer than we introduced "we create a new release every three months" on [documentation](https://chaos-mesh.org/docs/supported-releases/).

From the last several experiences of releasing new versions, we are still lacking experience in project management and agile development in an open-source way.

**Describe the feature you'd like:**

Make up a Release Cycle guideline and handbooks, basically following the pattern of the Kubernetes community, and make small changes fitted with Chaos Mesh.

**Describe alternatives you've considered:**

Maybe we could follow the release cycle of other awesome projects (other than Kubernetes) if there are other people kindly remind/suggest to us. 

**Teachability, Documentation, Adoption, Migration Strategy:**

https://kubernetes.io/releases/release/
https://kubernetes.io/releases/release-managers/

**Comment by xlgao-zju** [comment]
k8s release cycle is 
```
[Normal Dev (Weeks 1-11)](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-release/release.md#normal-dev-weeks-1-11)
[Code Freeze (Weeks 12-14)](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-release/release.md#code-freeze-weeks-12-14)
[Post-Release (Weeks 14+)](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-release/release.md#post-release-weeks-14+)
```

it's about  4 month. since chaos mesh is a fresh project, so I we can still follow the rule `we create a new release every three months`

**Comment by STRRL** [comment]
Refer: https://github.com/chaos-mesh/chaos-mesh/discussions/3256

Personal opinion, the reason why I prefer 8 weeks instead of 12 weeks is, that I think a shorter duration of a cycle would bring a quicker walkthrough of the release things. I prefer to keep the 8 weeks as the release cycle at least until we make the handbooks for the release cycle.
