### ISSUE TITLE
`make test` would failed when `make failpoint-disable`

### ISSUE THREAD

**Issue by STRRL** [chaos-mesh/chaos-mesh#3215]
We execute `make test` with `RUN_IN_DEV_SHELL`, which introduces running inside of docker container. 

But the last command `make failpoint-disable` also requires docker, which does not existed in the dev-env

**Comment by DaivikDave** [comment]
I can take this issue.

**Comment by STRRL** [comment]
Hi @DaivikDave , do you need some help? )

**Comment by DaivikDave** [comment]
Hey @STRRL, I wasn't able to work on it due to some urgency. I'll try to get it completed.
