### ISSUE TITLE
I want write a book about chaos-mesh

### ISSUE THREAD

**Issue by ycwdaaaa** [chaos-mesh/chaos-mesh#3219]
I'm planing to write a book about how to test product in k8s. so in a section i will introduce how to add new type of chaos exeperiment in chaos-mesh. is that ok for you guys?

**Comment by cwen0** [comment]
@ycwdaaaa Great! This is good news! If you need any help, please free to create an issue or send your question to the slack channel. We will give you feedback asap!

**Comment by ycwdaaaa** [comment]
> 

Thanks a lot ~  I will contact you guys when I need help.
