### ISSUE TITLE
`containerNames` field in `NetworkChaosSpec` is documented but not implemented

### ISSUE THREAD

**Issue by etigerstudio** [chaos-mesh/chaos-mesh#3249]
Hi, I'm seeking to inject a network fault(e.g. delay) to one specific container in a pod(there are more than one containers in this pod).

According to [v2.1.5 doc](https://chaos-mesh.org/docs/simulate-network-chaos-on-kubernetes/), a field named `containerNames` is supposed to act as a container selector for a network fault. However, it turns out that there's no such field in [NetworkChaosSpec](https://pkg.go.dev/github.com/chaos-mesh/chaos-mesh/api/v1alpha1#NetworkChaosSpec) data structure and my yaml configuration fails to take into effect(the error is "unknown field "containerNames" in org.chaos-mesh.v1alpha1.NetworkChaos.spec;").

<img width="819" alt="Screen Shot 2022-05-07 at 8 17 26 PM" src="https://user-images.githubusercontent.com/2973222/167254530-0d453011-69e6-4d3d-a3f7-cb6ce125a061.png">

Here's my fault definition yaml:
```yaml
kind: NetworkChaos
apiVersion: chaos-mesh.org/v1alpha1
metadata:
  namespace: lightning
  name: net-delay
spec:
  containerNames:
    - d
  selector:
    namespaces:
      - lightning
    labelSelectors:
      app.kubernetes.io/managed-by: foo
  mode: all
  action: delay
  duration: 5m
  delay:
    latency: 50ms
    correlation: '0'
    jitter: 20ms
  direction: from
```

So my question is that how to inject network fault into **one container** in a pod with multiple containers? 
Why `containerNames` field is documented but not implemented?
Will `containerNames` field be supported in the future?

Thank you!

**Comment by Andrewmatilde** [comment]
Sorry, this is a doc fault. NetworkChaos cannot inject fault into one container. I guess `containerNames` field will not be implemented because every container inside one pod share the network device & IP & mac. So we can hardly divide two container in network layer.
In future, I plan to add port filter for Network Chaos and you can add a port filter for one container in server side. Port filter is already added in external target by client side.

**Comment by etigerstudio** [comment]
Glad to hear from you!

Now I see it's hard to specify a container to inject faults because containers in a pod share one network device.
I'm interested in the port filter you mentioned. Currently I could only successfully specify external target by passing a domain name(baidu.com) or IP address(127.0.0.1). However I don't know how to use the port filter because I tried "127.0.0.1:8080" but that didn't work(FYI, "127.0.0.1" did work for all ports).

> Port filter is already added in external target by client side.

Could you shed some light on how to use the port filter for external target?

**Comment by Andrewmatilde** [comment]
I don't understand why external target with 127.0.0.1:8080 failed yet. I think it may be related with some ipset problem, but external target works well on port filter with www.baidu.com:80 or www.baidu.com:443 in client side.

**Comment by Andrewmatilde** [comment]
PTAL for external target : 127.0.0.1:8080 @STRRL @YangKeao .

**Comment by etigerstudio** [comment]
I just tested external target "www.baidu.com:80" & "www.baidu.com:443", but both didn't worked. And external target 
 "www.baidu.com" did work(of course both port 80 & 443 are affected).
Could it be that port filters for external target is not supported yet?

**Comment by Andrewmatilde** [comment]
> I just tested external target "www.baidu.com:80" & "www.baidu.com:443", but both didn't worked.

I have checked the iptables & ipset , so then I found that may because the DNS of "www.baidu.com" is not stable . NetworkChaos can only filter part of IPs through DNS. If you try to make HTTP connection more times ,Networks may works.

![image](https://user-images.githubusercontent.com/32479514/167323391-0b37a657-b9e2-4065-a386-d26cead693d3.png)
In this situation, I can only get www.baidu.com from IP:110.242.68.4 & block on IP:220.181.38.149.

**Comment by Andrewmatilde** [comment]
I know why extern target:127.0.0.1:8080 failed now. It is because Network Chaos only apply IPTABLES rules on 'eth0'.I will try to fix it later.

**Comment by etigerstudio** [comment]
> I know why extern target:127.0.0.1:8080 failed now. It is because Network Chaos only apply IPTABLES rules on 'eth0'.I will try to fix it later.

I see. However I want to point out that Network Chaos at this moment *is able to* apply rules on localhost targets by setting "lo" as `device`, and it does work this way as I tested. According to [Network Chaos docment](https://chaos-mesh.org/docs/simulate-network-chaos-on-kubernetes/) the default value of `device` field is "eth0", thus we only need to set device to "lo" if we are injecting localhost targets.

<img width="752" alt="Screen Shot 2022-05-09 at 11 37 52 AM" src="https://user-images.githubusercontent.com/2973222/167336515-1f0d9887-91b6-4f21-8228-56303a99fdaa.png"> 

> > I just tested external target "www.baidu.com:80" & "www.baidu.com:443", but both didn't worked.
> 
> I have checked the iptables & ipset , so then I found that may because the DNS of "www.baidu.com" is not stable . NetworkChaos can only filter part of IPs through DNS. If you try to make HTTP connection more times ,Networks may works.
> 

Yes, I agree with your findings. IP of "www.baidu.com" is not stable.
You mentioned a good point to debug the rules. I will check iptables & ipset later to see if ports are actually appropriately configured.

**Comment by etigerstudio** [comment]
> > > I just tested external target "www.baidu.com:80" & "www.baidu.com:443", but both didn't worked.
> > 
> > 
> > I have checked the iptables & ipset , so then I found that may because the DNS of "www.baidu.com" is not stable . NetworkChaos can only filter part of IPs through DNS. If you try to make HTTP connection more times ,Networks may works.
> 
> Yes, I agree with your findings. IP of "www.baidu.com" is not stable. You mentioned a good point to debug the rules. I will check iptables & ipset later to see if ports are actually appropriately configured.

I tested external target "1.1.1.1:80" and "www.baidu.com:80" and it looks like Network Chaos see the *IP/hostname together with port* as a hostname to lookup resulting in a lookup failure. However, it is supposed to split the hostname and port first, lookup hostname, and add port to tc netem rule. 

So I'm curious that is Network Chaos currently designed to support specifying port in `externalTargets` field?

Following are web UI logs for "1.1.1.1:80", "www.baidu.com:80", "www.baidu.com" respectively:

"1.1.1.1:80", failed
<img width="548" alt="Screen Shot 2022-05-09 at 12 18 24 PM" src="https://user-images.githubusercontent.com/2973222/167340646-0910eaf3-0a06-4507-a2fe-9908adaa6d99.png">

"www.baidu.com:80", failed
<img width="567" alt="Screen Shot 2022-05-09 at 12 18 39 PM" src="https://user-images.githubusercontent.com/2973222/167340652-5a1954c2-97e8-4217-9a89-ce1c3d162c71.png">

""www.baidu.com", succeeded
<img width="560" alt="Screen Shot 2022-05-09 at 12 19 15 PM" src="https://user-images.githubusercontent.com/2973222/167340662-183141d8-7305-4c64-ba0e-d6c183edff39.png">

**Comment by Andrewmatilde** [comment]
@etigerstudio Can you share your yaml? It works forme.
![image](https://user-images.githubusercontent.com/32479514/167346800-c780639e-2253-43a0-9978-756dea89a0f4.png)

**Comment by YangKeao** [comment]
@Andrewmatilde I think external targets with ports only supports after v2.2.0? See https://github.com/chaos-mesh/chaos-mesh/pull/2932

**Comment by etigerstudio** [comment]
> @etigerstudio Can you share your yaml config? It works forme. ![image](https://user-images.githubusercontent.com/32479514/167346800-c780639e-2253-43a0-9978-756dea89a0f4.png)

I'm using v2.1.5.

Here's my yaml config:
<img width="1199" alt="Screen Shot 2022-05-09 at 2 15 46 PM" src="https://user-images.githubusercontent.com/2973222/167351201-195792cd-477a-44f9-989a-920847ebf612.png">

```yaml
kind: NetworkChaos
apiVersion: chaos-mesh.org/v1alpha1
metadata:
  namespace: lightning
  name: net-partition
spec:
  selector:
    namespaces:
      - lightning
    labelSelectors:
      app.kubernetes.io/name: lightning
  mode: all
  action: partition
  duration: 15m
  direction: to
  externalTargets:
    - www.baidu.com:80
```

**Comment by etigerstudio** [comment]
I'll update to v2.2.0 and test whether port filter works for me.

**Comment by etigerstudio** [comment]
> I'll update to v2.2.0 and test whether port filter works for me.

I just updated to v2.2.0 and everything works like a charm!
Thanks for your assistance!
