### ISSUE TITLE
HTTPChaos allowing delays without time unit

### ISSUE THREAD

**Issue by ruancmoral** [chaos-mesh/chaos-mesh#3261]
## Bug Report

**What version of Kubernetes are you using?**
v1.18.2

**What version of Chaos Mesh are you using?**
v2.1.5

**What did you do?**

When creating a HTTPChaos with Response or Request delays. I can insert any delay time without specifying the time unit (s,ms,..). And it looks that some times it gets stuck in 'injecting' because of this. 

**What did you expect to see?**

Expected not to be allowed to insert delays without specifying the time unit just like the "duration" field

**Comment by Andrewmatilde** [comment]
Hi @ruancmoral . I have simply add a validator. It may help chaos-mesh not to get stuck when `injecting`. Thanks for your suggestion!

**Comment by ruancmoral** [comment]
Thanks for your time.
