### ISSUE TITLE
chaos-daemon BACK-off restarting failed container

### ISSUE THREAD

**Issue by S972776051** [chaos-mesh/chaos-mesh#3262]
离线安装后，其他服务都正常启动，chaos-daemon状态为 CrashLoopBackoff，一直重复启动，已经设置标签指定节点安装pod，有人遇到同样的问题吗？求解决下，谢谢各位哥哥们。

**Comment by YangKeao** [comment]
Translate:

> After offline installation, other services start normally, but the state of `chaos-daemon` is always `CrashLoopBackoff`, and restarted again and again. I have set the node of pods. Is there anyone facing the same problem? Please help me to solve it. Thanks.

Please attach the log and describe of chaos-daemon. You can get them through `kubectl logs` and `kubectl describe`. It will help us to investigate the problem.

Translate:

> 可以通过 `kubectl logs` 和 `kubectl describe` 这两个命令查看 chaos-daemon 的日志和状态，来帮助我们了解问题出在哪里 :thinking:

**Comment by S972776051** [comment]
> 翻译：
> 
> > 离线安装后，其他服务正常启动，但状态`chaos-daemon`始终为`CrashLoopBackoff`，反复重启。我已经设置了 pod 的节点。有没有人面临同样的问题？请帮我解决它。谢谢。
> 
> 请附上chaos-daemon的日志和描述。你可以让他们通过`kubectl logs`和`kubectl describe`。它将帮助我们调查问题。
> 
> 翻译：
> 
> > 可以通过 `kubectl logs` 和 `kubectl describe` 这两个命令查看 chaos-daemon 的日志和状态，来帮助我们了解问题出在哪里 🤔

已解决！ 需要修改配置

**Comment by STRRL** [comment]
Since the issue has been resolved, I am going to close this issue :)
