### ISSUE TITLE
Release Alpha Version on Branch `master`

### ISSUE THREAD

**Issue by STRRL** [chaos-mesh/chaos-mesh#3274]
There are several things to be done before we release the first alpha version:

- [x] figure out which version to use for helm charts on branch `master`
- [x] #3292
- [x] #3310
- [x] run CI on branch `master`

**Comment by STRRL** [comment]
There are 2 GitHub Action Workflows related to the git tag:

- .github/workflows/release_helm_chart.yml
- .github/workflows/upload_release_files.yml


The first one would build the helm chart to https://github.com/chaos-mesh/charts.
The second one would upload some artifacts (like install.sh) to the aws s3.

IMO, I prefer to:

- only release helm charts for the alpha/beta releases, not release install script for alpha/beta releases.
- release helm charts and install script(install.sh) for minor/bugfix releases

What do you think about that? @chaos-mesh/maintainers @chaos-mesh/committers 

Also cc release managers @YangKeao @Hexilee

**Comment by YangKeao** [comment]
@STRRL Release both helm charts and install script seems fine (and will keep consistency between different types of release). I don't know why you don't want to release install script for alpha/beta releases?

**Comment by YangKeao** [comment]
> > @STRRL Release both helm charts and install script seems fine (and will keep consistency between different types of release). I don't know why you don't want to release install script for alpha/beta releases?
> 
> Because there is nowhere in the documentation site point to the URL of install.sh.
> 
> Only "nightly" (with tag `latest`) and latest bugfix version( `2.1.5` for now) would be introduced by installing with that script: https://chaos-mesh.org/docs/quick-start/
> 
> If we publish the `install.sh` for the alpha/beta release, the user might depend on it, but without any announcement. thinking

Will the alpha/beta release even have documents? If it doesn't for both, I think we don't need to take care of it specially, as the url of it is also not documented anywhere...

**Comment by STRRL** [comment]
> Will the alpha/beta release even have documents? 

I think they would not have documents.

So I have no idea why a user would use the URL like `https://mirrors.chaos-mesh.org/vX.Y.Z-alpha.W/install.sh` 🙈

**Comment by STRRL** [comment]
we have released v2.3.0-alpha.0.
