### ISSUE TITLE
webhook ca verification error on k8s

### ISSUE THREAD

**Issue by Hexilee** [chaos-mesh/chaos-mesh#3276]
## Bug Report

**What version of Kubernetes are you using?**

minikube(v1.25.2) kvm2 driver

Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.6", GitCommit:"ad3338546da947756e8a88aa6822e9c11e7eac22", GitTreeState:"archive", BuildDate:"2022-04-29T06:39:16Z", GoVersion:"go1.18.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.3", GitCommit:"816c97ab8cff8a1c72eccca1026f7820e93e0d25", GitTreeState:"clean", BuildDate:"2022-01-25T21:19:12Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"linux/amd64"}

**What version of Chaos Mesh are you using?**

master branch 4cdb546df844eae706986b8e18d02bb9dc0dd911

**What did you do?**

```bash
> cat httpchaos.yaml
kind: HTTPChaos
apiVersion: chaos-mesh.org/v1alpha1
metadata:
  name: http-fault
  namespace: default
spec:
  selector:
    namespaces:
      - default
    labelSelectors:
      app: nginx
  mode: all
  target: Response
  port: 80
  method: GET
  path: /s
  delay: 1s
  replace:
    code: 500
> kubectl apply -f httpchaos.yaml
```

**What did you expect to see?**

```log
httpchaos.chaos-mesh.org/http-fault created
```

**What did you see instead?**

```log
Error from server (InternalError): error when creating "httpchaos.yaml": Internal error occurred: failed calling webhook "vauth.kb.io": failed to call webhook: Post "https://chaos-mesh-controller-manager.chaos-testing.svc:443/validate-auth?timeout=5s": x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "chaos-mesh-ca")
```

**Output of chaosctl**

**Comment by YangKeao** [comment]
```
❯ kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.3", GitCommit:"c92036820499fedefec0f847e2054d824aea6cd1", GitTreeState:"archive", BuildDate:"1980-01-01T00:00:00Z", GoVersion:"go1.16.13", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.5", GitCommit:"c285e781331a3785a7f436042c65c5641ce8a9e9", GitTreeState:"clean", BuildDate:"2022-03-16T15:52:18Z", GoVersion:"go1.17.8", Compiler:"gc", Platform:"linux/amd64"}
```

Failed to reproduce on my local cluster.

**Comment by YangKeao** [comment]
As communicated with @Hexilee, and this issue cannot be produced anymore, I would close this issue.

**Comment by Hexilee** [comment]
> ```
> ❯ kubectl version
> Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.3", GitCommit:"c92036820499fedefec0f847e2054d824aea6cd1", GitTreeState:"archive", BuildDate:"1980-01-01T00:00:00Z", GoVersion:"go1.16.13", Compiler:"gc", Platform:"linux/amd64"}
> Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.5", GitCommit:"c285e781331a3785a7f436042c65c5641ce8a9e9", GitTreeState:"clean", BuildDate:"2022-03-16T15:52:18Z", GoVersion:"go1.17.8", Compiler:"gc", Platform:"linux/amd64"}
> ```
> 
> Failed to reproduce on my local cluster.

I cannot reproduce it, too. I'm going to close this issue.
