### ISSUE TITLE
Some Enhancements for Network Chaos

### ISSUE THREAD

**Issue by Andrewmatilde** [chaos-mesh/chaos-mesh#3278]
## Feature Request

**Is your feature request related to a problem? Please describe:**

#2295 Expand NetworkChaos to support src/dst ports. This is not a BUG ,but the problem is we can not simply complete this simple feature
#3204 Bug: Network Partition with both target & external target will block from target to external target

**Describe the feature you'd like:**

Complete the feature #2295 . Fix #3204.

**Teachability, Documentation, Adoption, Migration Strategy:**

First I need to share about how Network Chaos(Partition) works now. If there are some problem please point out it.
```
1. Apply Network Chaos k8s API & run webhook.
2. for selected PODs:
        if direction is TO || BOTH:
            Apply PodNetworkChaos with pb.Chain_OUTPUT for Target pod & external target
        if direction is FROM || BOTH:
            Apply PodNetworkChaos with pb.Chain_INPUT for Target pod & external target
    for Target PODs:
        if direction is TO || BOTH:
            Apply PodNetworkChaos with pb.Chain_INPUT for Selected pod & external target
        if direction is FROM || BOTH:
            Apply PodNetworkChaos with pb.Chain_OUTPUT for Selected pod & external target
3. What PodNetworkChaos do: 
    Set ipset for Target pods & external target in Selected pods
    Set ipset for Selected pods & external target in Target pods
    for PodNetworkChaos  with pb.Chain_INPUT:
        DROP network package with source and destination inside ipset in INPUT chain
    for PodNetworkChaos  with pb.Chain_OUTPUT:
        DROP network package with destination inside ipset in OUPUT chain
```

I don't understand why we need to block web stream twice , it seems that was added for use network partition without setting target in #1978.
But for add src ports supports I can modify code for direction:FROM. I will add ipset with selected POD itself : port and this will block web stream with src port.
And if it doesn't apply PodNetworkChaos with external target #3204 will be fixed.

**Comment by YangKeao** [comment]
> I don't understand why we need to block web stream twice , it seems that was added for use network partition without setting target in https://github.com/chaos-mesh/chaos-mesh/pull/1978.

No. AIK, at the very first day when the `NetworkChaos` exists, we applied it twice. At that time (nearly three years ago) I didn't understand the network structure of kubernetes, but was asked to create such a thing. Then I found if I applied it twice, the traffic through `ClusterIP` service will also be blocked, which sounds really good :smiley: .

Now, I know the `ClusterIP` service doesn't SNAT, so if we are filtering through the source ip on the target pod, the packet targeting a service will also be dropped. It's somehow expected :crying_cat_face:, and I thought maybe there are someone depending on this behavior (as little user will connect to a cluster ip directly).

**Comment by Andrewmatilde** [comment]
> No. AIK, at the very first day when the `NetworkChaos` exists, we applied it twice. At that time (nearly three years ago) I didn't understand the network structure of kubernetes, but was asked to create such a thing. Then I found if I applied it twice, the traffic through `ClusterIP` service will also be blocked, which sounds really good 😃 .
> 
> Now, I know the `ClusterIP` service doesn't SNAT, so if we are filtering through the source ip on the target pod, the packet targeting a service will also be dropped. It's somehow expected 😿, and I thought maybe there are someone depending on this behavior (as little user will connect to a cluster ip directly).

I know the problem we possibly should divide Network inside the K8S and common Network From Domin to Domin (External Target).
