### ISSUE TITLE
Issues when deployed in VMWare Tanzu

### ISSUE THREAD

**Issue by DanielH56** [chaos-mesh/chaos-mesh#3279]
I may have missed a step, but having successfully installed chaos-mesh and applied an experiment without issues, I am not observing any impacts on the target application itself.  Here are the details:

For installation: 

root@server:~# helm install chaos-mesh chaos-mesh/chaos-mesh -n=chaos-testing --set dashboard.securityMode=false --set chaosDaemon.runtime=containerd --set chaosDaemon.socketPath=/run/containerd/containerd.sock --version 2.2.0
NAME: chaos-mesh
LAST DEPLOYED: Thu May 19 23:46:18 2022
NAMESPACE: chaos-testing
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
1. Make sure chaos-mesh components are running
   kubectl get pods --namespace chaos-testing -l app.kubernetes.io/instance=chaos-mesh
root@sl697tanzucli:~# kubectl get pods -n chaos-testing
NAME                                        READY   STATUS    RESTARTS   AGE
chaos-controller-manager-55cdd5c9f6-4l4rs   1/1     Running   0          11s
chaos-controller-manager-55cdd5c9f6-bxg92   1/1     Running   0          11s
chaos-controller-manager-55cdd5c9f6-zlvvj   1/1     Running   0          11s
chaos-daemon-qq5cg                          1/1     Running   0          11s
chaos-daemon-vrch6                          1/1     Running   0          11s
chaos-daemon-zvvp6                          1/1     Running   0          11s
chaos-dashboard-99fdb4bdd-pxsxx             1/1     Running   0          11s

On the experiment itself:

root@server:~/locust/chaos-mesh# kubectl apply -f network-loss.yaml
networkchaos.chaos-mesh.org/network-loss created
root@server:~/locust/chaos-mesh# cat network-loss.yaml
apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: network-loss
spec:
  action: loss # the specific chaos action to inject
  mode: one # the mode to run chaos action; supported modes are one/all/fixed/fixed-percent/random-max-percent
  selector: # pods where to inject chaos actions
    namespaces:
      - default
    labelSelectors:
      'app': 'nginx-demo' # the label of the pod for chaos injection
  loss:
    loss: '75'
    correlation: '25'
    #duration: '10s'
root@server:~/locust/chaos-mesh# kubectl describe networkchaos network-loss
apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: network-loss
spec:
  action: loss # the specific chaos action to inject
  mode: one # the mode to run chaos action; supported modes are one/all/fixed/fixed-percent/random-max-percent
  selector: # pods where to inject chaos actions
    namespaces:
      - default
    labelSelectors:
      'app': 'nginx-demo' # the label of the pod for chaos injection
  loss:
    loss: '75'
    correlation: '25'
    #duration: '10s'
root@sl697tanzucli:~/locust/chaos-mesh# kubectl describe networkchaos network-loss
Name:         network-loss
Namespace:    default
Labels:       <none>
Annotations:  <none>
API Version:  chaos-mesh.org/v1alpha1
Kind:         NetworkChaos

( .... )

Events:
  Type    Reason           Age   From          Message
  ----    ------           ----  ----          -------
  Normal  FinalizerInited  22s   finalizers    Finalizer has been inited
  Normal  Updated          22s   finalizers    Successfully update finalizer of resource
  Normal  Started          22s   desiredphase  Experiment has started
  Normal  Updated          22s   desiredphase  Successfully update desiredPhase of resource
  Normal  Updated          22s   records       Successfully update records of resource
  Normal  Applied          22s   records       Successfully apply chaos for default/net-deployment-7587998bf4-r9tvm
  Normal  Updated          22s   records       Successfully update records of resource

Any suggestions / advise?

Thanks!

**Comment by g1eny0ung** [comment]
It looks like there is nothing wrong with the configuration. What about trying to make the `duration` longer first? Let the experiment run for a more extended period to see the problem.
