### ISSUE TITLE
admission webhook "vpodchaos.kb.io" denied the request: Cannot update chaos spec

### ISSUE THREAD

**Issue by mikiihuang** [chaos-mesh/chaos-mesh#3281]
## Bug Report

**What version of Kubernetes are you using?**
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.20", GitCommit:"1f3e19b7beb1cc0110255668c4238ed63dadb7ad", GitTreeState:"clean", BuildDate:"2021-06-16T12:58:51Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.20", GitCommit:"1f3e19b7beb1cc0110255668c4238ed63dadb7ad", GitTreeState:"clean", BuildDate:"2021-06-16T12:51:17Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

**What version of Chaos Mesh are you using?**
v2.0.5

**What did you do?**
create pod failure 

**What did you expect to see?**
created successfully

**What did you see instead?**
fail to create
**Output of chaosctl**
Error from server (Cannot update chaos spec): error when applying patch:
{"metadata":{"annotations":{"kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"chaos-mesh.org/v1alpha1\",\"kind\":\"PodChaos\",\"metadata\":{\"annotations\":{},\"name\":\"indexer-pod-failure\",\"namespace\":\"onest-checker\"},\"spec\":{\"action\":\"pod-failure\",\"duration\":\"60s\",\"mode\":\"one\",\"selector\":{\"namespaces\":[\"onest-indexer\"],\"nodes\":[\"dc02-indexer-01\"]}}}\n"}},"spec":{"duration":"60s"}}
to:
Resource: "chaos-mesh.org/v1alpha1, Resource=podchaos", GroupVersionKind: "chaos-mesh.org/v1alpha1, Kind=PodChaos"
Name: "indexer-pod-failure", Namespace: "onest-checker"
for: "indexer-pod-failure.yaml": admission webhook "vpodchaos.kb.io" denied the request: Cannot update chaos spec

**Comment by g1eny0ung** [comment]
Ref #2227. Until now Chaos Mesh didn't support updating a chaos. You can choose to create a new chaos with a different name instead.
