### ISSUE TITLE
这个是怎么回事，我可以提供我的服务器地址，求解决

### ISSUE THREAD

**Issue by S972776051** [chaos-mesh/chaos-mesh#3284]
![image](https://user-images.githubusercontent.com/65998909/169752788-5062a8fa-7cad-467a-b6bb-3c856c4feb52.png)

**Comment by YangKeao** [comment]
Duplicated of https://github.com/chaos-mesh/chaos-mesh/issues/3263

I will respond in the https://github.com/chaos-mesh/chaos-mesh/issues/3263, please don't create new issues for a single problem.
