### ISSUE TITLE
front bug： when define PhysicalMachineChaos , input : chaosd server address ,always throw exception

### ISSUE THREAD

**Issue by minyiwang6** [chaos-mesh/chaos-mesh#3286]
## Bug Report

**What version of Kubernetes are you using?**

v1.19.6

**What version of Chaos Mesh are you using?**

Controller manager Version: version.Info{GitVersion:"master-gd80563f9436515", GitCommit:"d80563f943651519a75254f4148d2a72a341f35a", BuildDate:"2022-05-18T18:04:48Z", GoVersion:"go1.18", Compiler:"gc", Platform:"linux/amd64"}

**What did you do?**

install : helm 

**What did you expect to see?**

**What did you see instead?**

**Output of chaosctl**

define PhysicalMachineChaos through front ,  when input the address , I try any format but always throw exception as below :

![image](https://user-images.githubusercontent.com/105764503/169777787-392cc6e9-b647-4484-8d4a-b591393977c6.png)

![image](https://user-images.githubusercontent.com/105764503/169777275-ddd6de99-860d-4311-8fb3-548689d5f8f2.png)

**Comment by cwen0** [comment]
@WangXiangUSTC PTAL

**Comment by cwen0** [comment]
@minyiwang6 Can you make sure that chaosd was installed and add the chaosd server address to chaos-mesh? You can refer to this docs https://chaos-mesh.org/docs/simulate-physical-machine-chaos/

**Comment by minyiwang6** [comment]
@cwen0 
As the picture  ,my  PhysicalMachineChaos have run success  by using kubectl .  I think the chaosd have installed correctly .But ， this experiment can not be "load  from " for creating another new one .  

What do you mean that  add the address to chaos-mesh ? Can you provide some commands?

![image](https://user-images.githubusercontent.com/105764503/169960980-53885424-c1c7-427a-b048-43b547cebaf2.png)

**Comment by WangXiangUSTC** [comment]
> 

could you please provide the error message when using `load from`?

**Comment by WangXiangUSTC** [comment]
![image](https://user-images.githubusercontent.com/5793595/169966140-7d5ca943-1ba1-4869-9b72-f8152e617040.png)
After you type the address, you need to press `shift` + `enter`, and then the address is set success. Seems that the tip `Type and end with a space to add one or more chaosd addresses` is wrong, @g1eny0ung PTAL

**Comment by minyiwang6** [comment]
@WangXiangUSTC  Well done ,it's ok now! Thanks much !

**Comment by g1eny0ung** [comment]
This problem has already been solved. Thanks all.
