### ISSUE TITLE
chaos-daemon keeps CrashLoopBackOff with error: flag provided but not defined: -runtime-socket-path

### ISSUE THREAD

**Issue by nototain** [chaos-mesh/chaos-mesh#3287]
## Question
I deployed chaos mesh in k8s environment with version v2.1.5, after deployed both control-manager and dashboard pods are running, but chaos-daemon pods keep  CrashLoopBackOff with error: flag provided but not defined: -runtime-socket-path, does anyone know what is wrong with the config?  thanks!

> kubectl logs -f chaos-daemon-n8t7m -n chaos-testing
**> flag provided but not defined: -runtime-socket-path**
> Usage of /usr/local/bin/chaos-daemon:
>   -ca string
>         ca certificate of grpc server
>   -cert string
>         certificate of grpc server
>   -grpc-port int
>         the port which grpc server listens on (default 31767)
>   -http-port int
>         the port which http server listens on (default 31766)
>   -key string
>         key of grpc server
>   -kubeconfig string
>         Paths to a kubeconfig. Only required if out-of-cluster.
>   -pprof
>         enable pprof
>   -runtime string
>         current container runtime (default "docker")
>   -version
>         print version information and exit

![image](https://user-images.githubusercontent.com/89573078/169843144-52b11085-6fc4-4afc-840e-8d20a2452cf1.png)

 

Before asking a question, make sure you have:

- Reviewed relevant Kubernetes information: Google your error messages and look at K8s docs.
- Searched open and closed [GitHub issues](https://github.com/chaos-mesh/chaos-mesh/issues?utf8=%E2%9C%93&q=is%3Aissue)
- Read the documentation:
  - [Chaos Mesh Readme](https://github.com/chaos-mesh/chaos-mesh)
  - [Chaos Mesh Doc](https://chaos-mesh.org/docs)

**Output of chaosctl**

**Comment by S972776051** [comment]
同问？ 谢谢

**Comment by nototain** [comment]
Chaos Mesh v2.1.5 was deployed by following offline installation guide:
https://chaos-mesh.org/zh/docs/offline-installation/

**Comment by WangXiangUSTC** [comment]
https://chaos-mesh.org/zh/docs/offline-installation/#%E4%B8%8B%E8%BD%BD-chaos-mesh-%E4%BB%93%E5%BA%93%E5%8E%8B%E7%BC%A9%E5%8C%85

Seems that the description is wrong, the download URL is the master branch' URL, please change to `https://github.com/chaos-mesh/chaos-mesh/archive/refs/tags/v2.1.5.zip` and try again

**Comment by S972776051** [comment]
已解决
