### ISSUE TITLE
Why not separate the HELM directory to a repository

### ISSUE THREAD

**Issue by nioshield** [chaos-mesh/chaos-mesh#3289]
## Question

Why not separate the HELM directory to a repository?
Install Chaos Mesh offline just download helm file

**Comment by WangXiangUSTC** [comment]
There is no special reason, just make it easier to manage

**Comment by nioshield** [comment]
Thanks your replay,  have any plans to move in the future ?

**Comment by WangXiangUSTC** [comment]
Unfortunately, we don't have plan now 🙈
