### ISSUE TITLE
version unrelated manifests in the repo

### ISSUE THREAD

**Issue by STRRL** [chaos-mesh/chaos-mesh#3292]
We should update our build system, and make the manifest version unrelated. 

After that, the version would only relate to the tag on the commit

**Comment by S972776051** [comment]
> 将仅与提交上的标签有关

请问有2.2.0版本的镜像吗？

**Comment by STRRL** [comment]
> > 将仅与提交上的标签有关
> 
> 请问有2.2.0版本的镜像吗？

It seems your question is not related to this issue.

 Please feel free to open a new issue. :D

**Comment by S972776051** [comment]
> > > 将仅与提交上的标签有关
> > 
> > 
> > 请问有2.2.0版本的镜像吗？
> 
> It seems your question is not related to this issue.
> 
> Please feel free to open a new issue. :D

已经找到

**Comment by S972776051** [comment]
> > > > 将仅与提交上的标签有关
> > > 
> > > 
> > > 请问有2.2.0版本的镜像吗？
> > 
> > 
> > It seems your question is not related to this issue.
> > Please feel free to open a new issue. :D
> 
> We also have a wechat group and a slack channel for community. :)
> 
> Slack Channel: https://cloud-native.slack.com/archives/C0193VAV272 WeChat Group: You could add my wechat contact: strrlthedev, I would invite you into that group

I have added you up
