### ISSUE TITLE
离线安装无法使用（之前的问题没有解决）

### ISSUE THREAD

**Issue by S972776051** [chaos-mesh/chaos-mesh#3299]
![e0d367758e90b84327a5958d937755b](https://user-images.githubusercontent.com/65998909/170191752-042b9f79-3d99-443e-863c-e86fbc864a1f.jpg
![286398bc5b1b66655df8e1101057d12](https://user-images.githubusercontent.com/65998909/170191772-90396eae-76df-4d65-8504-c2cd0aeef769.jpg)
)
昨天大佬给的意见是
Use the latest image, download ghcr.io/chaos-mesh/...:v2.2.0 instead of v2.1.5
Use the older helm chart, helm install ..... --version 2.1.5
我检查了版本都是2.1.5，和离线安装文档一致。
我换了台服务器再次测试还是无法离线安装2.1.5版本，
2.2.0版没有镜像，请问应该如何解决

**Comment by YangKeao** [comment]
You are using the v2.2.0 helm chart... If you already have v2.1.5 image, please try to execute the following commands:

```
helm uninstall -n chaos-testing chaos-mesh
helm install -n chaos-testing chaos-mesh --version 2.1.5
```

If you are using the correct 2.1.5 chart, run `kubectl describe pods -n chaos-testing chaos-daemon-xxxxx`, and notice the `Command`, it will be:

```
    Command:
      /usr/local/bin/chaos-daemon
      --runtime
      docker
      --http-port
      31766
      --grpc-port
      31767
      --pprof
      --ca
      /etc/chaos-daemon/cert/ca.crt
      --cert
      /etc/chaos-daemon/cert/tls.crt
      --key
      /etc/chaos-daemon/cert/tls.key
```

There will be no `runtime-socket-path` flag in the command.

**Comment by STRRL** [comment]
Hi @S972776051, I think this comment would works: https://github.com/chaos-mesh/chaos-mesh/issues/3287#issuecomment-1136640444 

Thanks for your feedback!

I would update the doc later: https://github.com/chaos-mesh/website/issues/301

**Comment by S972776051** [comment]
> 您正在使用 v2.2.0 的 helm 图表...如果您已有 v2.1.5 镜像，请尝试执行以下命令：
> 
> ```
> helm uninstall -n chaos-testing chaos-mesh
> helm install -n chaos-testing chaos-mesh --version 2.1.5
> ```
> 
> 如果您使用的是正确的 2.1.5 图表，请运行 ，并注意 ，它将是：`kubectl describe pods -n chaos-testing chaos-daemon-xxxxx``Command`
> 
> ```
>     Command:
>       /usr/local/bin/chaos-daemon
>       --runtime
>       docker
>       --http-port
>       31766
>       --grpc-port
>       31767
>       --pprof
>       --ca
>       /etc/chaos-daemon/cert/ca.crt
>       --cert
>       /etc/chaos-daemon/cert/tls.crt
>       --key
>       /etc/chaos-daemon/cert/tls.key
> ```
> 
> 命令中没有标志。`runtime-socket-path`

你说的很对，是版本问题，我觉得是官方的离线文档中下载的yaml有问题，刚刚证实是这样，这个问题已经解决！感谢
