### ISSUE TITLE
Can not apply chaos to the pod in the namespace which was not `chaos-testing`

### ISSUE THREAD

**Issue by zhuwenxing** [chaos-mesh/chaos-mesh#3315]
## Bug Report

**What version of Kubernetes are you using?**

**What version of Chaos Mesh are you using?**

v2.0.3
**What did you do?**

apply chaos to the pod in `qa-milvus` namespace when chaos mesh was installed in `chaos-testing` namespace

**What did you expect to see?**
the pod was killed
**What did you see instead?**
no pod was killed
**Output of chaosctl**

The log of chaos-controller-manage
[chaos-mesh.log](https://github.com/chaos-mesh/chaos-mesh/files/8797839/chaos-mesh.log)

**Comment by zhuwenxing** [comment]
> the yaml file is
> 
> ```
> kind: Schedule
> apiVersion: chaos-mesh.org/v1alpha1
> metadata:
>   name: test-querynode-pod-kill
>   namespace: qa-milvus
> spec:
>   schedule: '*/5 * * * * *'
>   startingDeadlineSeconds: 60
>   concurrencyPolicy: Forbid
>   historyLimit: 1
>   type: PodChaos
>   podChaos:
>     selector:
>       namespaces:
>         - qa-milvus
>       labelSelectors:
>         app.kubernetes.io/instance: milvus-multi-querynode
>         app.kubernetes.io/name: milvus
>         component: querynode
>     mode: fixed
>     value: "1"
>     action: pod-kill
>     gracePeriod: 0
> ```

The describe of the target pod. I can confirm that the selector is correct.
![image](https://user-images.githubusercontent.com/12268675/170980839-c9704860-30c3-4ee7-b27e-0659622f1b79.png)

**Comment by Andrewmatilde** [comment]
> user have the privileges on namespace, auth validate passed	{"user": "system:serviceaccount:chaos-testing:chaos-controller-manager", "groups": ["system:serviceaccounts", "system:serviceaccounts:chaos-testing", "system:authenticated"], "namespace": {"qa-milvus":{}}} 
> namespace is not enabled for chaos-mesh
It seems this is a auth problem.

**Comment by Andrewmatilde** [comment]
PTAL @cwen0 , can you give some advice?

**Comment by zhuwenxing** [comment]
Yes, my first guess to the possible cause is a permissions issue. chaos mesh is installed by the cluster administrator, but we only have access to a single namespace.

**Comment by zhuwenxing** [comment]
https://chaos-mesh.org/zh/docs/configure-enabled-namespace/
Will this be helpful?

**Comment by zhuwenxing** [comment]
> https://chaos-mesh.org/zh/docs/configure-enabled-namespace/ Will this be helpful?

It works after config following this doc
