### ISSUE TITLE
Multi-Cluster Support Tracking Issue

### ISSUE THREAD

**Issue by YangKeao** [chaos-mesh/chaos-mesh#3341]
After submitting https://github.com/chaos-mesh/rfcs/pull/44, the developer teams have agreed on some of the designs, but at the same time, we doesn't have a good solution for the authentication/authorization. Luckily, it doesn't stop us from moving towards the target: injecting chaos into multiple clusters.

We can split the implementation into several parts:

1. Add a framework to allow developers to run reconcilers of different clusters inside a single process @YangKeao  https://github.com/chaos-mesh/chaos-mesh/pull/3342
2. Allow different reconcilers (remote cluster or manage cluster) to get and use the client of any clusters @YangKeao https://github.com/chaos-mesh/chaos-mesh/pull/3342
3. Implement the installation, uninstallation and updates @STRRL 
4. Implement the chaos injection and status synchronization @FingerLeader 

The following two steps can be split further, feel free to comment or edit this issue directly.

**Comment by STRRL** [comment]
> Implement the installation, uninstallation and updates @zhouqiang-cl

It should assign to me. 🤣
