### ISSUE TITLE
10 minute guide failed

### ISSUE THREAD

**Issue by Cas-pian** [chaos-mesh/chaos-mesh#3344]
## Bug Report

**What version of Kubernetes are you using?**

v1.23.3

**What version of Chaos Mesh are you using?**

v2.1.5

**What did you do?**

Follow the [10 minute guide](https://chaos-mesh.org/docs/the-guide-to-chaos-mesh-v21/)
Which versioin of chaos-mesh should we use in this guide?  v2.1.x or v2.2.0 ? There might be something wrong with this page.

**What did you expect to see?**
httpchaos run succeed

**What did you see instead?**
```
  Failed to apply chaos: status(400), apply fail: unknown variant ``, expected `JSON` at line 1 column 121`
```

**Comment by iguoyr** [comment]
Hi @Cas-pian, this issue is duplicate with #3089, v2.2.0 is released now, you could upgrade to v2.2.0 and try this document again :)

**Comment by Cas-pian** [comment]
@iguoyr Thanks, I'll have a try, and the document title should be updated.

**Comment by iguoyr** [comment]
@Cas-pian Yes! Will fix that document soon. Thanks for your feedback.
