### ISSUE TITLE
provide values.schema.json for helm chart

### ISSUE THREAD

**Issue by STRRL** [chaos-mesh/chaos-mesh#3358]
## Feature Request

**Is your feature request related to a problem? Please describe:**

Schemaless helm values.yaml.

**Describe the feature you'd like:**

provide `values.schema.json`

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by losisin** [comment]
@STRRL I can pick up this one. It will include validations for `dashboard.env.DATABASE_DRIVER` and `chaosDaemon.runtime`. Let me know if thee are other validations needed
