### ISSUE TITLE
Unable to install on k8s v1.22.0

### ISSUE THREAD

**Issue by gopimandala** [chaos-mesh/chaos-mesh#3375]
K8s v1.22.0

I am following the tutorial at https://chaos-mesh.org/docs/1.1.4/user_guides/installation/#install-by-helm
In the Step 2: Create custom resource type, the following error msg appears.
`$curl -sSL https://mirrors.chaos-mesh.org/v1.1.4/crd.yaml | kubectl apply -f -`
_unable to recognize "STDIN": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1beta1"_

Chaos-mesh repo v2.2.0
```
root@new:~# helm search repo chaos-mesh
NAME                    CHART VERSION   APP VERSION     DESCRIPTION                                       
chaos-mesh/chaos-mesh   2.2.0           2.2.0           Chaos Mesh is a cloud-native Chaos Engineering ...

```
I see a somewhat related issue (https://github.com/kubeflow/manifests/issues/2028) wherein the solution given is to downgrade k8s, which I don't think will be acceptable on most installations - as there will be tons of other dependencies with everything else on the cluster.

Is there any solution for getting this done without having to mess with k8s versions of cluster?

**Comment by xlgao-zju** [comment]
looks like you followed an old version install guide(1.14), and the apiversion ` apiextensions.k8s.io/v1beta1`(which used in chaos mesh 1.1.4) is remove in k8s v1.22.0.

I think you can try 2.2.0: https://chaos-mesh.org/docs/production-installation-using-helm/
