### ISSUE TITLE
chaos-daemon create failed using helm install

### ISSUE THREAD

**Issue by chamilzr** [chaos-mesh/chaos-mesh#3379]
environment: 
os: linux 
kubectl version 1.14.1
chaos-mesh version: 2.3.0-alpha.0  and 2.2.0
install command:
helm install  --name chaos-mesh helm/chaos-mesh  --namespace=chaos-testing --set chaosDaemon.env.DOCKER_API_VERSION=1.39
 After installed, there is no chaos-daemon, and find blew error in the daemonset.
kubectl -n chaos-testing describe daemonset chaos-daemon
 Warning  FailedCreate  <invalid> (x13 over <invalid>)  daemonset-controller  Error creating: pods "chaos-daemon-" is forbidden: unable to validate against any pod security policy: [spec.securityContext.hostPID: Invalid value: true: Host PID is not allowed to be used spec.containers[0].securityContext.privileged: Invalid value: true: Privileged containers are not allowed spec.containers[0].securityContext.capabilities.add: Invalid value: "SYS_PTRACE": capability may not be added]
Is there any workaround for this issue?

**Comment by cwen0** [comment]
@chamilzr Are you using an OpenShift cluster? It looks like OpenShift clusters have different permissions by default (more restrictive). I found the same issue, which maybe is helpful for you. https://github.com/Azure/aks-periscope/issues/78#issuecomment-874492249.

**Comment by chamilzr** [comment]
Thank you, resolved it.

**Comment by cwen0** [comment]
@chamilzr I will close this issue. If you have more problems, free to reopen it or create a new issue.
