### ISSUE TITLE
what's difference between chaosd attack host shutdown and shutdown ?

### ISSUE THREAD

**Issue by hillbun** [chaos-mesh/chaos-mesh#3380]
what's difference between chaosd attack host shutdown and system command shutdown ?

**Comment by STRRL** [comment]
I think there should be no differences.

You could see that chaosd would actually execute `shutdown`:

https://github.com/chaos-mesh/chaosd/blob/e4cabb4419a73eb84f9ddbc97ce6d4603cdad138/pkg/server/chaosd/host_unix.go#L35

cc @WangXiangUSTC @Andrewmatilde @FingerLeader

**Comment by STRRL** [comment]
I am going to close this issue. If you have other questions, feel free to reopen it. ❤️❤️❤️
