### ISSUE TITLE
Network Attack not working in DigitalOcean Kubernetes Cluster

### ISSUE THREAD

**Issue by QAInsights** [chaos-mesh/chaos-mesh#3382]
## Bug Report

**What version of Kubernetes are you using?**
v1.22.8

**What version of Chaos Mesh are you using?**
2.2.0

**What did you do?**

1. Deployed ChaosMesh on Digital Ocean Kubernetes Cluster. 
2. Deployed sample nginx deployment.
3. Created a network attack type of `delay` with 10s on nginx.

**What did you expect to see?**
- The response time of nginx deployment should be 10s for the whole duration.
- Pod kill experiment is working fine.

**What did you see instead?**
No chaos has been injected.

**Output of chaosctl**
`make chaosctl` is failing, so couldn't grab the log using chaosctl.

**Comment by QAInsights** [comment]
Sure @cwen0 I will raise a separate issue for `chaosctl`. Here are the logs. 
[chaos-controller-manager-7dc5b5c6f8-6f4vc.log](https://github.com/chaos-mesh/chaos-mesh/files/8945379/chaos-controller-manager-7dc5b5c6f8-6f4vc.log)
[chaos-daemon-kmbq5.log](https://github.com/chaos-mesh/chaos-mesh/files/8945380/chaos-daemon-kmbq5.log)
[chaos-daemon-79dw9.log](https://github.com/chaos-mesh/chaos-mesh/files/8945381/chaos-daemon-79dw9.log)
[chaos-controller-manager-7dc5b5c6f8-s8jm4.log](https://github.com/chaos-mesh/chaos-mesh/files/8945382/chaos-controller-manager-7dc5b5c6f8-s8jm4.log)
[chaos-controller-manager-7dc5b5c6f8-c5bzh.log](https://github.com/chaos-mesh/chaos-mesh/files/8945383/chaos-controller-manager-7dc5b5c6f8-c5bzh.log)

**Comment by cwen0** [comment]
> Sure @cwen0 I will raise a separate issue for `chaosctl`. Here are the logs. [chaos-controller-manager-7dc5b5c6f8-6f4vc.log](https://github.com/chaos-mesh/chaos-mesh/files/8945379/chaos-controller-manager-7dc5b5c6f8-6f4vc.log) [chaos-daemon-kmbq5.log](https://github.com/chaos-mesh/chaos-mesh/files/8945380/chaos-daemon-kmbq5.log) [chaos-daemon-79dw9.log](https://github.com/chaos-mesh/chaos-mesh/files/8945381/chaos-daemon-79dw9.log) [chaos-controller-manager-7dc5b5c6f8-s8jm4.log](https://github.com/chaos-mesh/chaos-mesh/files/8945382/chaos-controller-manager-7dc5b5c6f8-s8jm4.log) [chaos-controller-manager-7dc5b5c6f8-c5bzh.log](https://github.com/chaos-mesh/chaos-mesh/files/8945383/chaos-controller-manager-7dc5b5c6f8-c5bzh.log)

@QAInsights I found this error log  

```
2022-06-21T02:20:33.387Z	ERROR	records	records/controller.go:85	fail to select	{"error": "no pod is selected", "errorVerbose": "no pod is selected\ngithub.com/chaos-mesh/chaos-mesh/pkg/selector/pod.init\n\t/home/runner/work/chaos-mesh/chaos-mesh/pkg/selector/pod/selector.go:40\nruntime.doInit\n\t/usr/local/go/src/runtime/proc.go:6222\nruntime.doInit\n\t/usr/local/go/src/runtime/proc.go:6199\nruntime.doInit\n\t/usr/local/go/src/runtime/proc.go:6199\nruntime.doInit\n\t/usr/local/go/src/runtime/proc.go:6199\nruntime.doInit\n\t/usr/local/go/src/runtime/proc.go:6199\nruntime.doInit\n\t/usr/local/go/src/runtime/proc.go:6199\nruntime.doInit\n\t/usr/local/go/src/runtime/proc.go:6199\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:233\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1571"}
github.com/chaos-mesh/chaos-mesh/controllers/common/records.(*Reconciler).Reconcile
	/home/runner/work/chaos-mesh/chaos-mesh/controllers/common/records/controller.go:85
github.com/chaos-mesh/chaos-mesh/controllers/common/pipeline.(*Pipeline).Reconcile
	/home/runner/work/chaos-mesh/chaos-mesh/controllers/common/pipeline/pipeline.go:73
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile
	/tmp/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:114
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/tmp/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:311
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/tmp/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:266
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	/tmp/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:227
``` 

Did you get any error information when you apply your experiment? Can you check the status and event of the target experiment object by `kubectl describe or kubectl get event xx"?

**Comment by QAInsights** [comment]
@cwen0 i fixed this by selecting the right pod and executed it. Still no attack.

**Comment by QAInsights** [comment]
@cwen0 Here is the `chaosctl` log.
[chaosctl.log](https://github.com/chaos-mesh/chaos-mesh/files/8963304/chaosctl.log)

**Comment by Lttstbj** [comment]
我也遇到同样的问题：
2023-04-24T03:50:20.284Z	ERROR	records	fail to select	{"error": "no pod is selected"}
github.com/go-logr/zapr.(*zapLogger).Error
	/tmp/go/pkg/mod/github.com/go-logr/zapr@v0.1.0/zapr.go:128
github.com/chaos-mesh/chaos-mesh/controllers/records.(*Reconciler).Reconcile
	/mnt/controllers/records/controller.go:99
github.com/chaos-mesh/chaos-mesh/controllers/pipeline.(*Pipeline).Reconcile
	/mnt/controllers/pipeline/controller.go:70
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/tmp/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.0/pkg/internal/controller/controller.go:256
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/tmp/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.0/pkg/internal/controller/controller.go:232
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker
	/tmp/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.0/pkg/internal/controller/controller.go:211
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1
	/tmp/go/pkg/mod/k8s.io/apimachinery@v0.17.0/pkg/util/wait/wait.go:152
k8s.io/apimachinery/pkg/util/wait.JitterUntil
	/tmp/go/pkg/mod/k8s.io/apimachinery@v0.17.0/pkg/util/wait/wait.go:153
k8s.io/apimachinery/pkg/util/wait.Until
	/tmp/go/pkg/mod/k8s.io/apimachinery@v0.17.0/pkg/util/wait/wait.go:88
2023-04-24T03:50:20.284Z	INFO	pipeline	reconcile result	{"result": {"Requeue":false,"RequeueAfter":0}}
2023-04-24T03:50:20.284Z	DEBUG	controller-runtime.controller	Successfully Reconciled	{"controller": "jvmchaos-pipeline", "request": "hello/jvm-return-example"}
2023-04-24T03:50:20.285Z	INFO	pipeline	reconcile result	{"result": {"Requeue":false,"RequeueAfter":0}}
2023-04-24T03:50:20.285Z	INFO	desiredphase	modify desiredPhase	{"desiredPhase": "Run"}
2023-04-24T03:50:20.285Z	INFO	pipeline	reconcile result	{"result": {"Requeue":false,"RequeueAfter":0}}
2023-04-24T03:50:20.285Z	INFO	pipeline	reconcile result	{"result": {"Requeue":false,"RequeueAfter":0}}
2023-04-24T03:50:20.285Z	ERROR	records	fail
