### ISSUE TITLE
Whether chaos-mesh events can be collected by Prometheus

### ISSUE THREAD

**Issue by nioshield** [chaos-mesh/chaos-mesh#3383]
## Question

In my scenario, associating application metrics with Experiment using Grafana Annotations is a good idea, thanks to the Data Source Plugin.

But tester redeploy the application frequently, and Grafana is part of the application, so reinstalling the plug-in each time is not an easy task.

Experiment can define labels to associate with the application. Can we add labels to the event? Grafana can filter metrics by labels

So, is it possible to collect these metrics through Prometheus? Only Prometheus Rules need to be configured each time, and labels can be flexibly defined in metrics

**Comment by cwen0** [comment]
> So, is it possible to collect these metrics through Prometheus? Only Prometheus Rules need to be configured each time, and labels can be flexibly defined in metrics

@nioshield At present, Chaos Mesh exports events by Kubernetes events.  To achieve your goal, we may need to find a good way to export Kubernetes events to prometheus. I am not familiar with this, do you have some suggestion?

**Comment by nioshield** [comment]
@cwen0 Thanks for your reply. I learned that the Chaos Dashboard watch event data and saves it to SQllite. Is it possible to collect event metrics at the same time here? This is just an idea that may not be correct. Do you have better suggestions?

**Comment by cwen0** [comment]
> @cwen0 Thanks for your reply. I learned that the Chaos Dashboard watches event data and saves it to SQLite. Is it possible to collect event metrics at the same time here? This is just an idea that may not be correct. Do you have better suggestions?

Yes, Chaos Dashboard watches event data and saves it to SQLite.  Prometheus is more suitable to collect time-series data,  but I didn't find a suitable way to store event data in Prometheus.

**Comment by STRRL** [comment]
Maybe https://github.com/chaos-mesh/chaos-mesh/pull/3170 could help you, we have embedded some event in XXChaos Status field.

You could try it in our latest alpha version :D

**Comment by xlgao-zju** [comment]
as what @STRRL said, we can find the event about injection and recovery in the status filed. and if you more events, any suggestion and  request  is welcomed.

**Comment by xlgao-zju** [comment]
I'm going to close this issue, feel free to reopen it.
