### ISSUE TITLE
fail to inject jvm chaos on Openshift Container Platform

### ISSUE THREAD

**Issue by realzhuangxinyu** [chaos-mesh/chaos-mesh#3408]
## Question

What version of Kubernetes  are you using?
Kubernetes version：
  Client Version: v0.21.0-beta.1
  Server Version: v1.21.1+051ac4f
OCP version：
  Client Version: 4.8.2
  Server Version: 4.8.2

What version of Chaos Mesh are you using?
2.2.0

What did you do?
Injected multiple kvm chaos, like latency, exception, etc.

What did you see ?
(1)firstly, error occured:
`Failed to apply chaos: rpc error: code = Unknown desc = com.sun.tools.attach.AttachNotSupportedException: Unable to open socket file /proc/1991978/root/tmp/.java_pid1: target process 1991978 doesn't respond within 10500ms or HotSpot VM not loaded at jdk.attach/sun.tools.attach.VirtualMachineImpl.<init>(VirtualMachineImpl.java:100) at jdk.attach/sun.tools.attach.AttachProviderImpl.attachVirtualMachine(AttachProviderImpl.java:58) at jdk.attach/com.sun.tools.attach.VirtualMachine.attach(VirtualMachine.java:207) at org.chaos_mesh.agent_installer.Install.attach(Install.java:203) at org.chaos_mesh.agent_installer.Install.main(Install.java:47) : exit status 1`

I thought maybe the reason was that the uid of the container was a unique id 185 while  that of  chaos deamon was 0(root).
(2)Then, I made the contener's uid 0. Another error arose:
`Failed to apply chaos: rpc error: code = Unknown desc = com.sun.tools.attach.AgentLoadException: 102 com.sun.tools.attach.AgentLoadException: 100 at jdk.attach/sun.tools.attach.HotSpotVirtualMachine.loadAgentLibrary(HotSpotVirtualMachine.java:108) at jdk.attach/sun.tools.attach.HotSpotVirtualMachine.loadAgentLibrary(HotSpotVirtualMachine.java:119) at jdk.attach/sun.tools.attach.HotSpotVirtualMachine.loadAgent(HotSpotVirtualMachine.java:147) at jdk.attach/com.sun.tools.attach.VirtualMachine.loadAgent(VirtualMachine.java:538) at org.chaos_mesh.agent_installer.Install.injectAgent(Install.java:255) at org.chaos_mesh.agent_installer.Install.main(Install.java:48) : exit status 1`

At the same time, container printed error log which mentioned :
`Exception in thread "Attach Listener" java.lang.reflect.InvocationTargetException
	at sun.reflect.GeneratedMethodAccessor49.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)
	at sun.instrument.InstrumentationImpl.loadClassAndCallAgentmain(InstrumentationImpl.java:411)
Caused by: java.lang.Exception: Main : attempting to load Byteman agent more than once
	at org.jboss.byteman.agent.Main.premain(Main.java:57)
	at org.jboss.byteman.agent.Main.agentmain(Main.java:309)
	... 5 more
Agent failed to start!
Error opening zip file or JAR manifest missing: /usr/local/byteman/lib/chaos-agent.jar`

And I found there were only byteman-helper.jar and byteman.jar in /usr/local/byteman/lib/.

Any kind favor will be appraciated.

**Comment by YangKeao** [comment]
@WangXiangUSTC @Andrewmatilde @Hexilee PTAL

**Comment by WangXiangUSTC** [comment]
1. For the first error, it is similar to https://github.com/chaos-mesh/chaos-mesh/issues/2588, could you please check the Linux kernel's version of the K8s's node? It requires v4.2 at least.

2. For the second error, it's similar to https://github.com/chaos-mesh/chaos-mesh/issues/3330#issuecomment-1150944701, and this error can be ignored, I will update the code.

3. `And I found there were only byteman-helper.jar and byteman.jar in /usr/local/byteman/lib/.

Do you check the files in chaos-daemon Pod, or in your application's Pod?

**Comment by realzhuangxinyu** [comment]
> 1. For the first error, it is similar to [JVMChaos: target process doesn't respond within 10500ms or hotspot vm not loaded #2588](https://github.com/chaos-mesh/chaos-mesh/issues/2588), could you please check the Linux kernel's version of the K8s's node? It requires v4.1 at least.
> 2. For the second error, it's similar to [AttachNotSupportedException! JVM Chaos Injection failed. #3330 (comment)](https://github.com/chaos-mesh/chaos-mesh/issues/3330#issuecomment-1150944701), and this error can be ignored, I will update the code.
> 3. `And I found there were only byteman-helper.jar and byteman.jar in /usr/local/byteman/lib/.
> 
> Do you check the files in chaos-daemon Pod, or in your application's Pod?

Hello, thanks.
Reply:
1.  Linux kernel's version of the K8s's node is 4.18.
2. As my Jvm chaos experiments are alwanys failing, I assume this error can't be igonred.
3. I checked my application's pod, because it was my aplliction pod that printed the error "Error opening zip file or JAR manifest missing: /usr/local/byteman/lib/chaos-agent.jar".

**Comment by WangXiangUSTC** [comment]
2. I mean the error can be ignored in Chaos Mesh's code, although it reports an error, the agent is installed success. I have already fix it in https://github.com/chaos-mesh/chaos-mesh/pull/3415
3. I will check it

**Comment by realzhuangxinyu** [comment]
> 2. I mean the error can be ignored in Chaos Mesh's code, although it reports an error, the agent is installed success. I have already fix it in [JVMChaos: update the error message that can be ignored #3415](https://github.com/chaos-mesh/chaos-mesh/pull/3415)
> 3. I will check it
Do you mean I can't use jvm chaos until I reinstall my chaos mesh?

**Comment by realzhuangxinyu** [comment]
> > > 2. 我的意思是在 Chaos Mesh 的代码中可以忽略错误，虽然报错，但是代理安装成功。我已经在[J​​VMChaos 中修复了：更新可以忽略的错误信息 #3415](https://github.com/chaos-mesh/chaos-mesh/pull/3415)
> > > 3. 我会检查它
> > >    你的意思是在我重新安装我的混乱网格之前我不能使用 jvm chaos 吗？
> 
> 是的，您需要将混沌网格升级到包含[#3415中的更改的更新版本](https://github.com/chaos-mesh/chaos-mesh/pull/3415)

**Comment by realzhuangxinyu** [comment]
Thanks, I will try.
