### ISSUE TITLE
Cannot apply physiclamachine disk-write

### ISSUE THREAD

**Issue by parkjeongryul** [chaos-mesh/chaos-mesh#3410]
## Bug Report

**What version of Kubernetes are you using?**

1.23

**What version of Chaos Mesh are you using?**

2.2.0
**What did you do?**

create

```
chaosv1alpha1.PhysicalMachineChaos{
		ObjectMeta: metav1.ObjectMeta{
			Name:      chaosName,
			Namespace: ns,
		},
		Spec: chaosv1alpha1.PhysicalMachineChaosSpec{
			PhysicalMachineSelector: chaosv1alpha1.PhysicalMachineSelector{
				Mode: chaosv1alpha1.FixedPercentMode,
				Selector: chaosv1alpha1.PhysicalMachineSelectorSpec{
					GenericSelectorSpec: chaosv1alpha1.GenericSelectorSpec{
						Namespaces: []string{ns},
						LabelSelectors: map[string]string{
							"node-role.kubernetes.io/worker": "true"},
					},
				},
				Value: strconv.FormatInt(int64(chaosPercent), 10),
			},
			Action: chaosv1alpha1.PMDiskReadPayloadAction,
			ExpInfo: chaosv1alpha1.ExpInfo{
				DiskWritePayload: &chaosv1alpha1.DiskPayloadSpec{
					DiskFileSpec: chaosv1alpha1.DiskFileSpec{
						Size: diskSize,
						Path: "",
					},
					PayloadProcessNum: 1,
				},
			},
		},
	}
```

**What did you expect to see?**
apply chaos
**What did you see instead?**
disk-write-fill

***
Failed to apply chaos: {"error":true,"message":"error.api.internal_server_error: exit status 1","code":"error.api.internal_server_error","full_text":"error.api.internal_server_error: exit status 1\n at github.com/chaos-mesh/chaosd/pkg/server/httpserver.handleError()\n\t/__w/chaosd/chaosd/pkg/server/httpserver/server.go:335\n at github.com/chaos-mesh/chaosd/pkg/server/httpserver.(*httpServer).createDiskAttack()\n\t/__w/chaosd/chaosd/pkg/server/httpserver/server.go:237\n at github.com/gin-gonic/gin.(*Context).Next()\n\t/github/home/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161\n at github.com/chaos-mesh/chaosd/pkg/server/utils.MWHandleErrors.func1()\n\t/__w/chaosd/chaosd/pkg/server/utils/error.go:47\n at github.com/gin-gonic/gin.(*Context).Next()\n\t/github/home/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161\n at github.com/gin-gonic/gin.RecoveryWithWriter.func1()\n\t/github/home/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/recovery.go:83\n at github.com/gin-gonic/gin.(*Context).Next()\n\t/github/home/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161\n at github.com/gin-gonic/gin.LoggerWithConfig.func1()\n\t/github/home/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/logger.go:241\n at github.com/gin-gonic/gin.(*Context).Next()\n\t/github/home/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161\n at github.com/gin-gonic/gin.(*Engine).handleHTTPRequest()\n\t/github/home/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/gin.go:409\n at github.com/gin-gonic/gin.(*Engine).ServeHTTP()\n\t/github/home/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/gin.go:367\n at net/http.serverHandler.ServeHTTP()\n\t/__t/go/1.16.2/x64/src/net/http/server.go:2887\n at net/http.(*conn).serve()\n\t/__t/go/1.16.2/x64/src/net/http/server.go:1952\n at runtime.goexit()\n\t/__t/go/1.16.2/x64/src/runtime/asm_amd64.s:1371"}: HTTP status is not OK
***

**Output of chaosctl**

**Comment by parkjeongryul** [comment]
`Action: chaosv1alpha1.PMDiskReadPayloadAction,`
-> `Action: chaosv1alpha1.PMDiskWritePayloadAction,`

maybe this... sorry😢

**Comment by heifengli2021** [comment]
Hello, I also reported the same error here. How did you solve it?

**Comment by parkjeongryul** [comment]
action and expInfo was not synced.

first one was set to read and second was set to write.
