### ISSUE TITLE
Running stress chaos on container having no shell

### ISSUE THREAD

**Issue by ashishgoyal111** [chaos-mesh/chaos-mesh#3411]
Hi Chaos-mesh community,

I want to check if stress chaos experiments require sh on the container to run the experiment. We are trying to apply chaos on container which are derived From scratch and getting errors like following-

> Exec lifecycle hook ([sh -c sleep 70]) for Container 'scout' in Pod 'stormcloud--scout-stage-scout-scout-838f40c5c14577d359a0bfgqqlk_ns-ethos-139fa23a0929052344860a8c6-stage(1bd801fa-db8d-4ec0-9bc5-f119019dca85)' failed - error: command 'sh -c sleep 70' exited with 126: , message: 'OCI runtime exec failed: exec failed: unable to start container process: exec: \\'sh
': executable file not found in $PATH: unknown\\r
n'

Could you confirm if the container must have sh so that chaos can be applied on them?

**Comment by YangKeao** [comment]
> Exec lifecycle hook ([sh -c sleep 70]) for Container 'scout' in Pod 'stormcloud--scout-stage-scout-scout-838f40c5c14577d359a0bfgqqlk_ns-ethos-139fa23a0929052344860a8c6-stage(1bd801fa-db8d-4ec0-9bc5-f119019dca85)' failed - error: command 'sh -c sleep 70' exited with 126: , message: 'OCI runtime exec failed: exec failed: unable to start container process: exec: \'sh
': executable file not found in $PATH: unknown\r
n'

Is this log coming from chaos mesh? I don't think chaos mesh will execute something like `sh -c sleep 70` :thinking:  . The stresschaos doesn't depend on any other software (, we have done a lot to avoid extra dependencies). Also, it will not modify the pod definitions.

**Comment by ashishgoyal111** [comment]
@YangKeao Thank you for your response! I am closing this issue.
