### ISSUE TITLE
Unable to create experiments using 'byYaml' or 'load from' options. Brower goes blank.

### ISSUE THREAD

**Issue by gopimandala** [chaos-mesh/chaos-mesh#3416]
## Bug Report

**What version of Kubernetes are you using?**
1.22.8 node
1.22.0 client

**What version of Chaos Mesh are you using?**
chart-2.2.1

**What did you do?**
Tried to create experiment using 'load from' option as well as 'by Yaml' option. 

**What did you expect to see?**
The experiment should have been loaded.

**What did you see instead?**
The UI goes fully and absolutely blank. No menu seen. If i refresh the browser it comes back to experiments menu with only the previously completed experiments shown. (Basically what it was before i select the load from or by yaml options).

Note: I had resinstalled chaos mesh using `helm install chaos-mesh chaos-mesh/chaos-mesh -n=chaos-testing --set chaosDaemon.runtime=containerd --set chaosDaemon.socketPath=/run/containerd/containerd.sock`. If i create experiments using 'New experiment' menu they are working fine, even network chaos, but am unable to add experiments using yaml or reusing existing experiments.

**Comment by gopimandala** [comment]
I spun up a new cluster and installed everything afresh and it worked fine there (both from yaml and from past experiments). Not sure what went wrong in the above case.

**Comment by Hexilee** [comment]
Is the issue still exists on the old cluster? I also cannot reproduce this issue on Chaos Mesh v2.2.1. Frontend issues may be caused by complicated reason, like the cache or uncompleted loading of javascript resources.

**Comment by PungYoung** [comment]
I also encountered this problem.

**Comment by gopimandala** [comment]
When i created new cluster it worked initially but then again ran into this issue of dashboard going blank when using byYaml or loadFrom options.

**Comment by STRRL** [comment]
I could produce this issue on 2.2.2:
<img width="337" alt="image" src="https://user-images.githubusercontent.com/20221408/180968720-905770d3-f8b5-47aa-9ea0-7125ea95c9d1.png">

**Comment by STRRL** [comment]
also on 2.1.7
