### ISSUE TITLE
can't generator clientset

### ISSUE THREAD

**Issue by TaoTi888** [chaos-mesh/chaos-mesh#3421]
Hello, I have a problem: 
When I want to generate the clientset code through code-generator, I find that the groupname is chaos-mesh.org, and then an error occurs, which is not allowed to appear '-' this symbol. Is there any solution? ? Looking forward to your reply

**Comment by TaoTi888** [comment]
chaos-mesh version: v2.2.0
code-generator version: v0.24.2

**Comment by Andrewmatilde** [comment]
I find that some example in code-generator have group name with symbol '-'.https://github.com/kubernetes/code-generator/blob/5bc604e30f37bdbf711df0d92d74e9becb904959/examples/apiserver/apis/example/v1/doc.go#L21

**Comment by Andrewmatilde** [comment]
I forgot how to use code-generator to generate client, so I can only give an example for iochaos.https://github.com/Andrewmatilde/chaos-test-tidb/blob/main/chaosmesh/iochaos.go

**Comment by Andrewmatilde** [comment]
And code-generator will generate XXXchaos as XXXchaoses ,which cannot be direct use.

**Comment by STRRL** [comment]
Another way is using the client provided by controller-runtime, it might be useful to operate the CRD without provided clientset.

**Comment by TaoTi888** [comment]
> I find that some example in code-generator have group name with symbol '-'.https://github.com/kubernetes/code-generator/blob/5bc604e30f37bdbf711df0d92d74e9becb904959/examples/apiserver/apis/example/v1/doc.go#L21

well，code-generator will use first word, ex chaos-mesh.org will use chaos-mesh,

example.vi.chaos-mesh.org will use example ,

there is no symbol  '-'.

**Comment by TaoTi888** [comment]
> And code-generator will generate XXXchaos as XXXchaoses ,which cannot be direct use.



> And code-generator will generate XXXchaos as XXXchaoses ,which cannot be direct use.

yeah，I also encountered this problem，do you have a solution？

**Comment by Andrewmatilde** [comment]
> yeah，I also encountered this problem，do you have a solution？

I fixed it with manually delete `es`. :(

**Comment by TaoTi888** [comment]
> > yeah，I also encountered this problem，do you have a solution？
> 
> I fixed it with manually delete `es`. :(

thanks
