### ISSUE TITLE
Not able to see any impact of specifying different number of workers for memory stress

### ISSUE THREAD

**Issue by anuragpaliwal80** [chaos-mesh/chaos-mesh#3427]
## Bug Report

**What version of Kubernetes are you using?**

**What version of Chaos Mesh are you using?**

**What did you do?**

**What did you expect to see?**
I am using 2.2.0 so it's using memStress under the hood.

```
stressors:
    memory:
      workers: 1
      size: '256MB'
```
If I change workers to 4 as well, I am not seeing any impact in memory usage.

Without stress:
```
anurags-mbp-3:chaos-mesh anuragpaliwal$ ko2 top po
NAME                                                              CPU(cores)   MEMORY(bytes)   
doautomation--py1-2022-stage2-py12022-py12022-57ad92997220vw4qn   1m           89Mi
```
With stress, having workers as 1:
```
anurags-mbp-3:chaos-mesh anuragpaliwal$ ko2 top po
NAME                                                              CPU(cores)   MEMORY(bytes)   
doautomation--py1-2022-stage2-py12022-py12022-57ad92997220vw4qn   1m           339Mi
```
With stress, having workers as 4:
```
anurags-mbp-3:chaos-mesh anuragpaliwal$ ko2 top po
NAME                                                              CPU(cores)   MEMORY(bytes)   
doautomation--py1-2022-stage2-py12022-py12022-57ad92997220vw4qn   3m           346Mi
```
**What did you see instead?**

**Output of chaosctl**

**Comment by Hexilee** [comment]
The total size of memory occupation is not affected by the number of works, I am sorry the docs are outdated.

**Comment by FingerLeader** [comment]
The doc will be updated in PR [#322](https://github.com/chaos-mesh/website/pull/322)

**Comment by anuragpaliwal80** [comment]
So the role of `workers` in memory stress: Number of thread consuming this much memory or anything else ?

**Comment by FingerLeader** [comment]
Yes, this number of threads will occupy memory of `size`. `workers` has the same meaning of it does in stress-ng.
