### ISSUE TITLE
make check error: "flag provided but not defined: -pd"

### ISSUE THREAD

**Issue by ConnieHan2019** [chaos-mesh/chaos-mesh#3448]
## Bug Report

**What version of Kubernetes are you using?**

Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:18:45Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-20+cbbba6c5def2f8", GitCommit:"cbbba6c5def2f864fdfca30c56f490a9984f9119", GitTreeState:"clean", BuildDate:"2021-03-10T14:41:33Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
WARNING: versi

**What version of Chaos Mesh are you using?**

based on master branch 
latest commit: commit 26288bdf7850b9f39

**What did you do?**

run "make check" command.

**What did you see instead?**
I'm having problem with "make check" command. An error "flag provided but not defined: -pd" occurs during "make generate-ctrl". I'm not sure whether the problem is relavant with swagger version or go version. So far I have tried go1.13,go1.15 and go1.18, but the problem never changed. 
Maybe a "required.txt" should be added to the project so that contributors can easily figure out what version of goland/swagger do they need ?
<img width="1105" alt="make_check" src="https://user-images.githubusercontent.com/48054157/178733630-86a3e194-b38c-4d87-815a-55d62620c899.png">

**Output of chaosctl**

**Comment by xlgao-zju** [comment]
@g1eny0ung any idea about this issue?

**Comment by g1eny0ung** [comment]
Yes, there is a recent change that upgraded swag. Try `go mod tidy` to upgrade local dependencies.

**Comment by xlgao-zju** [comment]
> Yes, there is a recent change that upgraded swag. Try go mod tidy to upgrade local dependencies.

@g1eny0ung I thought we run `make check` in a container... lol

**Comment by g1eny0ung** [comment]
Oh...Sorry, I didn't look carefully. You should check whether the `dev-env` image is a recent version. Try pull the latest image and then `make check`.

**Comment by STRRL** [comment]
It could be fixed by https://github.com/chaos-mesh/chaos-mesh/pull/3444

**Comment by xlgao-zju** [comment]
talked with @ConnieHan2019 offline, after run `make clean` this issue have been fixed..

**Comment by ConnieHan2019** [comment]
yes，thanks @xlgao-zju  a lot ;-)
