### ISSUE TITLE
Return only annotated namespaces when filter is enabled

### ISSUE THREAD

**Issue by brnck** [chaos-mesh/chaos-mesh#3452]
## Feature Request

**Is your feature request related to a problem? Please describe:**

I’ve enabled filter namespace in the controller:

```
# If enabled, only pods in the namespace annotated with `"chaos-mesh.org/inject": "enabled"` could be injected
enableFilterNamespace: true
```

When logged in to the UI I can see all available namespaces in the cluster. For the record - only one namespace has this annotation (demo-bookapp)

![image](https://user-images.githubusercontent.com/14329469/178921195-da2f993e-ce4e-42e9-962d-fcc40d89998c.png)

But as you can see full list of namespaces is visible in the UI

**Describe the feature you'd like:**

Ideally, I'd like Chaosmesh to return only those namespace that has the annotation `"chaos-mesh.org/inject": "enabled"`.

Even though we can't run chaos tests against the namespaces that do not have this annotation, reducing information noise would improve the UX. It would, also, simplify things because when a cluster has >100 namespaces, but only, let's say, 5 namespaces have this annotation, there is no point in returning rest of the namespaces

Return only namespaces that have the annotation will remove information noise in a couple of places:

<img width="1294" alt="image" src="https://user-images.githubusercontent.com/14329469/178922510-77f88d8d-116f-4e8e-90af-3a7ff527f4c8.png">

**Describe alternatives you've considered:**

N/A

**Teachability, Documentation, Adoption, Migration Strategy:**

N/A

**Comment by nioshield** [comment]
@STRRL the feature have any plan ?

**Comment by brnck** [comment]
@nioshield I'm planning to contribute and resolve this by myself. If everything is okay, I'll start working on this tomorrow or Thursday
