### ISSUE TITLE
macos can not build chaos-mesh daemon

### ISSUE THREAD

**Issue by yiyanwannian** [chaos-mesh/chaos-mesh#3499]
## Bug Report

**What version of Chaos Mesh are you using?**
release-2.3

**What did you do?**

**What did you expect to see?**
chaos-mesh daemon run
**What did you see instead?**

package github.com/chaos-mesh/chaos-mesh/cmd/chaos-daemon
	imports github.com/chaos-mesh/chaos-mesh/pkg/chaosdaemon
	imports github.com/chaos-mesh/chaos-mesh/pkg/time
	imports github.com/chaos-mesh/chaos-mesh/pkg/ptrace: build constraints exclude all Go files in /Users/zhouhoufa/Code/src/github.com/chaos-mesh/chaos-mesh/pkg/ptrace
<img width="1352" alt="截屏2022-07-28 10 47 23" src="https://user-images.githubusercontent.com/8225547/181409280-32931f31-5512-47cf-81ea-1cd146e8b458.png">

**Comment by FingerLeader** [comment]
Hi @yiyanwannian , if you can run k8s on your macos, then you can deloy chaos daemon it's no materr with your OS. How do you install chaos mesh?

**Comment by yiyanwannian** [comment]
I can launch k8s by docker-desktop.
my steps:
1. git clone github.com/chaos-mesh/chaos-mesh 
2. cd choas-mesh && go mod tidy
3. start debug with goland and then show it issue

**Comment by STRRL** [comment]
chaos-daemon is NOT designed to run on macOS/Darwin, so we did not implement some features like `ptrace` on the platform darwin.

The `make` recipes would **always** build components inside of docker, which means inside of a linux environment, so please use commands like `make image-chaos-daemon` to build them.

At last, if you want to debug Chaos Mesh, you could take a look on: https://chaos-mesh.org/docs/next/configure-development-environment/#debug-chaos-mesh-in-local-environment
