### ISSUE TITLE
Inject JVMChaos:  install com.sun.tools.attach.AgentLoadException

### ISSUE THREAD

**Issue by QuchengRep1** [chaos-mesh/chaos-mesh#3530]
## Question
**I use the  chaos-mesh official docker image below:**
Version: chaos-mesh v2.2.2
ghcr.io/chaos-mesh/chaos-daemon: v2.2.2 
ghcr.io/chaos-mesh/chaos-mesh: v2.2.2 
ghcr.io/chaos-mesh/chaos-dashboard: v2.2.2 

**when i use dashboard to inject a JVMChaos ,chaos dashbord returns :"Failed to apply chaos: rpc error: code = Unknown desc = exit status 1". So I checked the chaos-daemo logs, and it says:"install com.sun.tools.attach.AgentLoadException: 102" when execute "sh -c bminstall.sh -b -Dorg.jboss.byteman.transform.all -Dorg.jboss.byteman.verbose -p 9277 115009"**

**Then I manually executed the bminstall.sh operation using Byteman installed in the container by myself, and it worked.
I want to know how can I get the JVMChaos task to run properly?**

**Below is the command  I manually executed command in dockerimage of Java application, I install byteman:v4.0.4 in this image**
[root@node-100 Byteman]# jps -l
116801 /data/Byteman/byteman-0.0.1-SNAPSHOT.jar

[root@node-100 Byteman]# ps -ef | grep java
root     116801 116781  0 17:06 ?        00:00:05 java -jar /data/Byteman/byteman-0.0.1-SNAPSHOT.jar

**[root@node-100 Byteman]# bminstall.sh -b -Dorg.jboss.byteman.transform.all -Dorg.jboss.byteman.verbose -p 9091 116801
[root@node-100 Byteman]# bmsubmit.sh -l  byteman.btm**

kubectl logs display it works OK:

Rule.execute called for trace byteman entry_0
trace byteman entry execute
byteman entering...
Rule.execute called for trace byteman exit_1
trace byteman exit execute
byteman exiting...
Time echo: Fri Aug 05 09:39:38 UTC 2022
Rule.execute called for trace byteman entry_0

**below is byteman btm  scritp, and com.qucheng.demo.byteman.BytemanDemo1 is a  Java package that prints the current time for each minute** 
#byteman.btm
RULE trace byteman entry
CLASS com.qucheng.demo.byteman.BytemanDemo1
METHOD printDate
AT ENTRY
IF true
DO traceln("byteman entering...")
ENDRULE

RULE trace byteman exit
CLASS com.qucheng.demo.byteman.BytemanDemo1
METHOD printDate
AT EXIT
IF true
DO traceln("byteman exiting...")
ENDRULE

_**below is chaos-daemon error log:**_

2022-08-05T07:14:43.106Z	INFO	chaos-daemon-server	InstallJVMRules	{"request": "container_id:\"docker://b065cdf5efb8a5beccca692c39b226bef27e284c4ab27897287cc7f413205f31\"  rule:\"\\nRULE --gc-1659683653\\nCLASS org.chaos_mesh.chaos_agent.TriggerThread\\nMETHOD triggerFunc\\nHELPER org.chaos_mesh.byteman.helper.GCHelper\\nAT ENTRY\\nBIND flag:boolean=true;\\nIF true\\nDO\\n\\tgc();\\nENDRULE\\n\"  port:9277  enterNS:true"}
2022-08-05T07:14:43.109Z	INFO	background-process-manager	build command	{"command": "/usr/local/bin/nsexec -m /proc/115009/ns/mnt -- sh -c mkdir -p /usr/local/byteman/lib/"}
2022-08-05T07:14:43.124Z	INFO	background-process-manager	build command	{"command": "/usr/local/bin/nsexec -m /proc/115009/ns/mnt -- sh -c cat > /usr/local/byteman/lib/byteman.jar"}
2022-08-05T07:14:43.141Z	INFO	background-process-manager	build command	{"command": "sh -c bminstall.sh -b -Dorg.jboss.byteman.transform.all -Dorg.jboss.byteman.verbose -p 9277 115009"}
**2022-08-05T07:14:44.355Z	**ERROR**	chaos-daemon-server	-b -Dorg.jboss.byteman.transform.all -Dorg.jboss.byteman.verbose -p 9277 115009**

/usr/local/byteman/lib/byteman-install.jar
java  -classpath /usr/local/byteman/lib/byteman-install.jar org.jboss.byteman.agent.install.Install -b -Dorg.jboss.byteman.transform.all -Dorg.jboss.byteman.verbose -p 9277 115009
install com.sun.tools.attach.AgentLoadException: 102
com.sun.tools.attach.AgentLoadException: 102
	at jdk.attach/sun.tools.attach.HotSpotVirtualMachine.loadAgentLibrary(HotSpotVirtualMachine.java:108)
	at jdk.attach/sun.tools.attach.HotSpotVirtualMachine.loadAgentLibrary(HotSpotVirtualMachine.java:119)
	at jdk.attach/sun.tools.attach.HotSpotVirtualMachine.loadAgent(HotSpotVirtualMachine.java:147)
	at org.jboss.byteman.agent.install.Install.injectAgent(Install.java:525)
	at org.jboss.byteman.agent.install.Install.main(Install.java:61)
	{"error": "exit status 1"}
github.com/chaos-mesh/chaos-mesh/pkg/chaosdaemon.(*DaemonServer).InstallJVMRules
	/mnt/pkg/chaosdaemon/jvm_server.go:95
github.com/chaos-mesh/chaos-mesh/pkg/chaosdaemon/pb._ChaosDaemon_InstallJVMRules_Handler.func1
	/mnt/pkg/chaosdaemon/pb/chaosdaemon.pb.go:3655
github.com/grpc-ecosystem/go-grpc-prometheus.(*ServerMetrics).UnaryServerInterceptor.func1
	/tmp/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-prometheus@v1.2.0/server_metrics.go:107
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1
	/tmp/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.2.0/chain.go:25
github.com/chaos-mesh/chaos-mesh/pkg/grpc.TimeoutServerInterceptor
	/mnt/pkg/grpc/utils.go:188
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1
	/tmp/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.2.0/chain.go:25
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1
	/tmp/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.2.0/chain.go:34
github.com/chaos-mesh/chaos-mesh/pkg/chaosdaemon/pb._ChaosDaemon_InstallJVMRules_Handler
	/mnt/pkg/chaosdaemon/pb/chaosdaemon.pb.go:3657
google.golang.org/grpc.(*Server).processUnaryRPC
	/tmp/go/pkg/mod/google.golang.org/grpc@v1.33.2/server.go:1210
google.golang.org/grpc.(*Server).handleStream
	/tmp/go/pkg/mod/google.golang.org/grpc@v1.33.2/server.go:1533
google.golang.org/grpc.(*Server).serveStreams.func1.2
	/tmp/go/pkg/mod/google.golang.org/grpc@v1.33.2/server.go:871

Before asking a question, make sure you have:

- Reviewed relevant Kubernetes information: Google your error messages and look at K8s docs.
- Searched open and closed [GitHub issues](https://github.com/chaos-mesh/chaos-mesh/issues?utf8=%E2%9C%93&q=is%3Aissue)
- Read the documentation:
  - [Chaos Mesh Readme](https://github.com/chaos-mesh/chaos-mesh)
  - [Chaos Mesh Doc](https://chaos-mesh.org/docs)

**Output of chaosctl**

**Comment by WangXiangUSTC** [comment]
https://github.com/chaos-mesh/chaos-mesh/blob/b81f57835b4d12b9fd9d5e21f8b6ec9bac2757ba/pkg/chaosdaemon/jvm_server.go#L118

This error can be ignored and is ignored here, it doesn't matter. Please check the experiment's status.

**Comment by QuchengRep1** [comment]
> https://github.com/chaos-mesh/chaos-mesh/blob/b81f57835b4d12b9fd9d5e21f8b6ec9bac2757ba/pkg/chaosdaemon/jvm_server.go#L118
> 
> This error can be ignored and is ignored here, it doesn't matter. Please check the experiment's status.

Thans, 
and when we use JDK11 based image+chaosMesh2.3, the previous jvmChaos exception does not occur again.
