### ISSUE TITLE
What is "safe mode" that's referred to in the installation documentation?

### ISSUE THREAD

**Issue by pcgeek86** [chaos-mesh/chaos-mesh#3541]
## Question

What is this "safe mode" that is referred to in the Chaos Mesh installation documentation?

The documentation states how to disable this "safe mode," but gives no indication what it is, or why I would want to disable it, or if I *should* disable it. 

- What is safe mode? 
- What are the risks of disabling it? 
- Why does this option exist at all?

![image](https://user-images.githubusercontent.com/466713/183786715-1244be52-06ed-4db9-b851-024552fc8016.png)

**Comment by Andrewmatilde** [comment]
Hi @pcgeek86 ! Thanks for your feedback. Disable `safe mode` will stop [user permission check]("https://chaos-mesh.org/docs/manage-user-permissions/") in chaos-mesh.  It is quite dangerous that everyone can access the dashboard can apply any chaoses on your kubernetes cluster. We just use it in testing & debugging situation in safe inner network.

**Comment by pcgeek86** [comment]
Thanks for your response!
