### ISSUE TITLE
e2e case run failed 

### ISSUE THREAD

**Issue by zhengbingxian** [chaos-mesh/chaos-mesh#3560]
## Bug Report

**What version of Chaos Mesh are you using?**

2.3.0

**What did you do?**

1、use helm chart deploy the chaos-mesh  as follows:
```shell
helm install chaos-mesh chaos-mesh/chaos-mesh -n=chaos-testing \
--set controllerManager.podChaos.podFailure.pauseImage=<My image registry>/gcr_io_google-containers_pause \
--set chaosDaemon.env.DOCKER_API_VERSION=1.40 \
--version v2.3.0 \
--create-namespace \
```
As the cluster can't visit gcr.io registry，so I changed it 。  

2、run e2e test
```shell
make e2e
```

**What did you expect to see?**
some error found in the report。
[Fail] [Basic] [PodChaos] [PodFailure] [It] [Schedule]
...

**What did you see instead?**
All e2e test can pass .

**My troubleshoot**
- Run test pod。
- When pod is running, podchaos will be created，to  replace test pod image "e2e-helper" to "pause" image。
- Then we list pods, and verify the image if it is equal to e2econst.PauseImage。  e2econst.PauseImage is hardcode with ”gcr.io/google-containers/pause:latest“， so all the case involve with these code will failed。 

```shell
# c.Image will be "<My image registry>/gcr_io_google-containers_pause"
# e2econst.PauseImage  will be gcr.io/google-containers/pause:latest

if c.Image == e2econst.PauseImage {
        return true, nil
			}
```

Chaos-mesh can set the pause image arg，If  the e2e program also add the arg with pause image  instead of hardcode，error will dispear and e2e test seems match the chaosmesh much better。

In original scripts, add ”--e2e-PauseImage xxxxxx“

```shell
./e2e-test/image/e2e/bin/ginkgo   ./e2e-test/image/e2e/bin/e2e.test    --  \
--e2e-image ghcr.io/pingcap/e2e-helper:latest  \
--e2e-PauseImage xxxxxx    # add
```

**Comment by Andrewmatilde** [comment]
Hi @zhengbingxian , thanks for your detailed feedback. We will fix it later. And I suggest you can just change it in hard code & run before we fix it in master. Or it will be appreciate to us that you can make a pull request for it.

**Comment by zhengbingxian** [comment]
@Andrewmatilde  
I have fixed it already.  Please help me review the code if you have time. THX.
