### ISSUE TITLE
e2e test of “sidecar config” run failed in some scenario

### ISSUE THREAD

**Issue by zhengbingxian** [chaos-mesh/chaos-mesh#3563]
## Bug Report

**What version of Chaos Mesh are you using?**

2.3.0

**What did you do?**

run e2e test cases.

**What did you expect to see?**

All cases success.

**What did you see instead?**

[Fail] [Basic] [Sidecar Config] [Template Config] [It] [InValid ConfigMap key] 
/opt/chaosmesh/chaos-mesh/e2e-test/e2e/chaos/sidecar/template_config.go:47

[Fail] [Basic] [Sidecar Config] [Template Config] [It] [InValid Configuration] 
/opt/chaosmesh/chaos-mesh/e2e-test/e2e/chaos/sidecar/template_config.go:90

[Panic!] [Basic] [Sidecar Config] [Injection Config] [It] [No Template Args]

[Panic!] [Basic] [Sidecar Config] [Injection Config] [It] [No Template] 
/tmp/go/pkg/mod/k8s.io/apimachinery@v0.23.1/pkg/util/runtime/runtime.go:55

**Comment by zhengbingxian** [comment]
After debug, the root of the problem is that there is no judgment set

**Comment by Andrewmatilde** [comment]
I close this issue because it seem already fixed. 
Thanks for your contribution!!
