### ISSUE TITLE
Cert could not be generate because  namespace of secret was not been denfined

### ISSUE THREAD

**Issue by fbi007130** [chaos-mesh/chaos-mesh#3574]
## Bug Report

**What version of Kubernetes are you using?**

**What version of Chaos Mesh are you using?**
2.3.0

**What did you do?**
Follow the step in https://chaos-mesh.org/docs/next/chaosctl-tool/#generate-tls-certificates-for-chaosd  and try to add parameter -N to generate the cert.

**What did you expect to see?**
`aa@bb:~> ./chaosctl  --manager-namespace chaos-testing   pm init node2 --ip=192.168.7.58
failed to execute cmd:

        could not found secret `chaos-mesh-chaosd-client-certs` in namespace chaos-mesh: secrets "chaos-mesh-chaosd-client-certs" not found

aa@bb:~> ./chaosctl     pm init node2 --ip=192.168.7.58   --manager-namespace chaos-testing
failed to execute cmd:

        could not found secret `chaos-mesh-chaosd-client-certs` in namespace chaos-mesh: secrets "chaos-mesh-chaosd-client-certs" not found

aa@bb:~> ./chaosctl     pm init node2 --ip=192.168.7.58   -N chaos-testing
failed to execute cmd:

        could not found secret `chaos-mesh-chaosd-client-certs` in namespace chaos-mesh: secrets "chaos-mesh-chaosd-client-certs" not found

aa@bb:~> ./chaosctl     pm init node2 --ip=192.168.7.58   -N chaos-testing
`

**What did you see instead?**
Generate cert valid.
**Output of chaosctl**

**Comment by Andrewmatilde** [comment]
PTAL @Hexilee

**Comment by Hexilee** [comment]
@fbi007130 Could you try `./chaosctl pm init node2 --ip=192.168.7.58 --chaos-mesh-namespace=chaos-testing`?

**Comment by fbi007130** [comment]
thx
