### ISSUE TITLE
User "system:serviceaccount:chaos-testing:chaos-controller-manager" cannot get resource "leases" in API group "coordination.k8s.io" in the namespace "chaos-testing"

### ISSUE THREAD

**Issue by memorais** [chaos-mesh/chaos-mesh#3668]
## Bug Report

**What version of Kubernetes are you using?**
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.20", GitCommit:"1f3e19b7beb1cc0110255668c4238ed63dadb7ad", GitTreeState:"clean", BuildDate:"2021-06-16T12:58:51Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.20", GitCommit:"1f3e19b7beb1cc0110255668c4238ed63dadb7ad", GitTreeState:"clean", BuildDate:"2021-06-16T12:51:17Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

**What version of Chaos Mesh are you using?**
Controller manager Version: version.Info{GitVersion:"master-ga6620f7d6c5297", GitCommit:"a6620f7d6c5297d90f958e2e4054743daa7a6a92", BuildDate:"2022-09-21T18:05:14Z", GoVersion:"go1.18", Compiler:"gc", Platform:"linux/amd64"}

**What did you do? / Minimal Reproducible Example**
Install version 2.3.2 using helm and check controllers logs on `chaos-testing` namespace.

**What did you expect to see?**
No RBAC permission errors.

**What did you see instead?**
```
E0922 20:04:01.318578       1 leaderelection.go:330] error retrieving resource lock chaos-testing/chaos-mesh: leases.coordination.k8s.io "chaos-mesh" is forbidden: User "system:serviceaccount:chaos-testing:chaos-controller-manager" cannot get resource "leases" in API group "coordination.k8s.io" in the namespace "chaos-testing"
```

**Output of chaosctl**
N/A

If we add `leases` resource on `coordination.k8s.io` API Group, the error don't happen.

Workaround:
Add the following lines on chaos-mesh-chaos-controller-manager-cluster-level:

```
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - get
  - list
  - update
```

**Comment by STRRL** [comment]
it should use `configmaps` not `configmapsleases` within 2.3.2, let me take a look.

**Comment by STRRL** [comment]
Hi @memorais, I could only reproduce this issue with `helm install xxxx --set image.tag=latest`, which is not expected.

Please make sure that the image of `chaos-controller-image` is `ghcr.io/chaos-mesh/chaos-mesh:v2.3.2`, not the `latest` image.

**Comment by STRRL** [comment]
I will close this issue as the mismatch configuration for release and docker image tag version. 

Feel free to reopen it if you still face this issue.
