### ISSUE TITLE
io-delay experiment causes restart of cassandra container

### ISSUE THREAD

**Issue by eedjama** [chaos-mesh/chaos-mesh#3680]
**What version of Kubernetes are you using?**
_Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.1", GitCommit:"c4d752765b3bbac2237bf87cf0b1c2e307844666", GitTreeState:"clean", BuildDate:"2020-12-18T12:09:25Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4", GitCommit:"ec2760d6d916781de466541a6babb4309766c995", GitTreeState:"clean", BuildDate:"2021-02-27T17:18:03Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}_

**What version of Chaos Mesh are you using?**
_v2.3.1_

**What did you do?**
_Run  IOChaos, type=delay=10ms  for cassandra_ 

Content of io-delay.yaml file:
              apiVersion: chaos-mesh.org/v1alpha1
              kind: IOChaos
              metadata:
                name: io-delay-cassandra
                namespace: footprint
              spec:
                action: latency
                mode: one
                selector:
                  labelSelectors:
                    "statefulset.kubernetes.io/pod-name": cassandra-0
                volumePath: /var/lib/cassandra/ 
                delay: "10ms"
                percent: 10
                duration: "10s"

**What did you expect to see?**
_I expect to see read/write delays of 10ms from specified volumePath._

**What did you see instead?**
_Restart of cassandra container and_ 

See chaos-daemon log
[chaosMeshDaemonCassandraLog.zip](https://github.com/chaos-mesh/chaos-mesh/files/9674666/chaosMeshDaemonCassandraLog.zip)

Last lines of cassandra container log:
[cassandra_IOchaosMesh.zip](https://github.com/chaos-mesh/chaos-mesh/files/9674980/cassandra_IOchaosMesh.zip)

**Comment by eedjama** [comment]
Hi,
any updates on this issue?
Did you manage to reproduce the fault?
Please find attached more instructions about the issue and how to trigger it.
Thanks and br
Janine
[CassandraFaultReproducer.zip](https://github.com/chaos-mesh/chaos-mesh/files/10382883/CassandraFaultReproducer.zip)

**Comment by PerSundstr8m** [comment]
Easy fix @STRRL ?

**Comment by PerSundstr8m** [comment]
Is anybody looking at these issues ??
The fix is easy and obvious.
  /Per

**Comment by MichaelMorrisEst** [comment]
I've submitted a PR to fix this in chaos-mesh/toda: https://github.com/chaos-mesh/toda/pull/42

FYI @PerSundstr8m

**Comment by eedjama** [comment]
The fix in the PR has been successfully tested.
