### ISSUE TITLE
Bring CLOMonitor Score to 100%

### ISSUE THREAD

**Issue by eddie-knight** [chaos-mesh/chaos-mesh#3696]
Chaos Mesh is signed up as part of the KubeCon [Security Slam](https://events.linuxfoundation.org/kubecon-cloudnativecon-north-america/attend/experiences/#security-slam), so I grabbed the checklist for this repo from the official [CLOMonitor page for Chaos Mesh](https://clomonitor.io/projects/cncf/chaos-mesh). It refreshes every hour, so this should be up-to-date.

### Summary

**Repository**: chaos-mesh
**URL**: https://github.com/chaos-mesh/chaos-mesh
**Checks sets**:  `COMMUNITY` + `CODE`
**Score**: 95

### Checks passed per category

| Category  |  Score  |
| :----------------- | --------: |
|  Documentation  |  100%  |
|  License  |  100%  |
|  Best Practices  |  100%  |
|  Security  |  75%  |
|  Legal  |  100%  |

### Documentation [100%]

  - [x] [Adopters](https://github.com/chaos-mesh/chaos-mesh/blob/master/ADOPTERS.md) ([_docs_](https://clomonitor.io/docs/topics/checks/#adopters))
  - [x] [Changelog](https://github.com/chaos-mesh/chaos-mesh/blob/master/CHANGELOG.md) ([_docs_](https://clomonitor.io/docs/topics/checks/#changelog))
  - [x] [Code of conduct](https://github.com/chaos-mesh/chaos-mesh/blob/master/CODE_OF_CONDUCT.md) ([_docs_](https://clomonitor.io/docs/topics/checks/#code_of_conduct))
  - [x] [Contributing](https://github.com/chaos-mesh/chaos-mesh/blob/master/CONTRIBUTING.md) ([_docs_](https://clomonitor.io/docs/topics/checks/#contributing))
  - [x] [Governance](https://github.com/chaos-mesh/chaos-mesh/blob/master/GOVERNANCE.md) ([_docs_](https://clomonitor.io/docs/topics/checks/#governance))
  - [x] [Maintainers](https://github.com/chaos-mesh/chaos-mesh/blob/master/MAINTAINERS.md) ([_docs_](https://clomonitor.io/docs/topics/checks/#maintainers))
  - [x] [Readme](https://github.com/chaos-mesh/chaos-mesh/blob/master/README.md) ([_docs_](https://clomonitor.io/docs/topics/checks/#readme))
  - [x] [Roadmap](https://github.com/chaos-mesh/chaos-mesh/blob/master/ROADMAP.md) ([_docs_](https://clomonitor.io/docs/topics/checks/#roadmap))
  - [x] [Website](https://chaos-mesh.org) ([_docs_](https://clomonitor.io/docs/topics/checks/#website))
  
### License [100%]

  - [x] Apache-2.0 ([_docs_](https://clomonitor.io/docs/topics/checks/#license_spdx_id))
  - [x] Approved license ([_docs_](https://clomonitor.io/docs/topics/checks/#license_approved))
  - [x] [License scanning](https://app.fossa.com/projects/git%2Bgithub.com%2Fchaos-mesh%2Fchaos-mesh?ref=badge_shield) ([_docs_](https://clomonitor.io/docs/topics/checks/#license_scanning))
  
### Best Practices [100%]

  - [x] Analytics ([_docs_](https://clomonitor.io/docs/topics/checks/#analytics))
  - [x] [Artifact Hub badge](https://artifacthub.io/packages/helm/chaos-mesh/chaos-mesh) ([_docs_](https://clomonitor.io/docs/topics/checks/#artifacthub_badge))
  - [x] Contributor License Agreement ([_docs_](https://clomonitor.io/docs/topics/checks/#cla)) `EXEMPT`
  - [x] Community meeting ([_docs_](https://clomonitor.io/docs/topics/checks/#community_meeting))
  - [x] Developer Certificate of Origin ([_docs_](https://clomonitor.io/docs/topics/checks/#dco))
  - [x] [Github discussions](https://github.com/chaos-mesh/chaos-mesh/discussions/3695) ([_docs_](https://clomonitor.io/docs/topics/checks/#github_discussions))
  - [x] [OpenSSF badge](https://bestpractices.coreinfrastructure.org/projects/3680) ([_docs_](https://clomonitor.io/docs/topics/checks/#openssf_badge))
  - [x] [Recent release](https://github.com/chaos-mesh/chaos-mesh/releases/tag/v2.1.7) ([_docs_](https://clomonitor.io/docs/topics/checks/#recent_release))
  - [x] Slack precense ([_docs_](https://clomonitor.io/docs/topics/checks/#slack_presence))
  
### Security [75%]

  - [x] Binary artifacts ([_docs_](https://clomonitor.io/docs/topics/checks/#binary_artifacts))
  - [x] Code review ([_docs_](https://clomonitor.io/docs/topics/checks/#code_review))
  - [x] Dangerous workflow ([_docs_](https://clomonitor.io/docs/topics/checks/#dangerous_workflow))
  - [x] Dependency update tool ([_docs_](https://clomonitor.io/docs/topics/checks/#dependency_update_tool))
  - [x] Maintained ([_docs_](https://clomonitor.io/docs/topics/checks/#maintained))
  - [x] Software bill of materials (SBOM) ([_docs_](https://clomonitor.io/docs/topics/checks/#sbom))
  - [x] [Security policy](https://github.com/chaos-mesh/chaos-mesh/blob/master/SECURITY.md) ([_docs_](https://clomonitor.io/docs/topics/checks/#security_policy))
  - [x] Signed releases ([_docs_](https://clomonitor.io/docs/topics/checks/#signed_releases))
  - [x] #3699
  
### Legal [100%]

  - [x] Trademark disclaimer ([_docs_](https://clomonitor.io/docs/topics/checks/#trademark_disclaimer))
  
For more information about the checks sets available and how each of the checks work, please see the [CLOMonitor's documentation](https://clomonitor.io/docs/topics/checks/).

**Comment by g1eny0ung** [comment]
Hi @eddie-knight, thanks for the follow-up. We have almost finished the rest of the tasks, but there is a problem with **signed releases**. In the past time, we haven't uploaded our components or binaries to the release, all of them were distributed as images (published to ghcr).

In the future, we may upload our CLI tool (chaosctl) to the release. The reason why we didn't upload it in the past is that it is still in the experimental stage.

I also contact our other maintainers and we feel that this task is currently out of reach for the time being. So we should only do the SBOM and Token permissions first. 😃

**Comment by g1eny0ung** [comment]
The SBOM of the last release: https://github.com/chaos-mesh/chaos-mesh/releases/tag/v2.4.1.

**Comment by g1eny0ung** [comment]
> The SBOM of the last release: https://github.com/chaos-mesh/chaos-mesh/releases/tag/v2.4.1.

Also with all signatures.

**Comment by g1eny0ung** [comment]
@eddie-knight I test in my local with the `scorecard` build from the main branch. The token checks have been passed! Thanks for improving. 🐝

![image](https://user-images.githubusercontent.com/15034155/197101733-be42bc06-3bd5-4a14-9ec3-4493318fde2d.png)

**Comment by eddie-knight** [comment]
Great work @g1eny0ung & @STRRL 👏 👏 👏

**Comment by g1eny0ung** [comment]
@eddie-knight Seems there has some network error, the CLOMonitor does not update as expected. 🤔

<img width="862" alt="image" src="https://user-images.githubusercontent.com/15034155/197190965-4d59edf7-05f4-4c23-a659-ba641bda7119.png">

**Comment by g1eny0ung** [comment]
> @eddie-knight Seems there has some network error, the CLOMonitor does not update as expected. 🤔
> 
> <img alt="image" width="862" src="https://user-images.githubusercontent.com/15034155/197190965-4d59edf7-05f4-4c23-a659-ba641bda7119.png">

It works!

<img width="524" alt="image" src="https://user-images.githubusercontent.com/15034155/197192303-f2e0b9ce-b9cb-4326-a1f7-9e05466bd143.png">

**Comment by eddie-knight** [comment]
Looks like this was a temporary blip during a site upgrade! Per discussion on the #clomonitor slack channel, it seems @g1eny0ung you managed to catch this during the deployment window. Good eye! 😅
