### ISSUE TITLE
Append SBOM section in README.md

### ISSUE THREAD

**Issue by STRRL** [chaos-mesh/chaos-mesh#3697]
## Feature Request

**Is your feature request related to a problem? Please describe:**

Yes, we want to reach 100% on CLOMonitor.

**Describe the feature you'd like:**

- ~provide SBOM section in README.md~
- automatic attach `.sbom` file to GitHub release, thanks to @g1eny0ung , introduce https://github.com/kubernetes-sigs/bom

**Describe alternatives you've considered:**

- ~automatic attach `.sbom` file to GitHub release, it might be harder because we would also push docker images and helm charts. It's better to use documentation to explain it.~
- provide SBOM section in README

**Teachability, Documentation, Adoption, Migration Strategy:**

ref:

- https://github.com/chaos-mesh/chaos-mesh/issues/3696
- https://clomonitor.io/docs/topics/checks/#sbom
- example projects reached SBOM check: https://clomonitor.io/search?rating=a&passing_check=sbom&page=1

**Comment by g1eny0ung** [comment]
I agree to use documentation to explain it. It's easier and more transparency for users.

**Comment by g1eny0ung** [comment]
Found a tool that can help us to generate sbom! https://github.com/kubernetes-sigs/bom

**Comment by g1eny0ung** [comment]
I've already uploaded the sbom of the last release to https://github.com/chaos-mesh/chaos-mesh/releases/tag/v2.4.1.
