### ISSUE TITLE
Issue with choas-mesh experiments 

### ISSUE THREAD

**Issue by pinkygangula** [chaos-mesh/chaos-mesh#3784]
I'm trying to do New experiment Pod Failure getting below error : 

error.api.internal_server_error: Internal error occurred: failed calling webhook "mpodchaos.kb.io": failed to call webhook: Post "https://chaos-mesh-controller-manager.chaos-mesh.svc:443/mutate-chaos-mesh-org-v1alpha1-podchaos?timeout=5s": x509: certificate signed by unknown authority (possibly because of "x509: cannot verify signature: insecure algorithm SHA1-RSA (temporarily override with GODEBUG=x509sha1=1)" while trying to verify candidate authority certificate "chaos-mesh-controller-manager.chaos-mesh.svc")

in both ways of trying yaml file and dashboard .

using mini kube version:1.28.0
Chaos-mesh version: 2.4.2

**Comment by g1eny0ung** [comment]
Close due to resolved.
