### ISSUE TITLE
Installing with `--set controllerManager.leaderElection.enabled=false` results in three ControllerManager pods

### ISSUE THREAD

**Issue by pxsalehi** [chaos-mesh/chaos-mesh#3829]
## Bug Report

**What version of Kubernetes are you using?**
1.23.12

**What version of Chaos Mesh are you using?**
2.5.0

**What did you do? / Minimal Reproducible Example**
```
helm install chaos-mesh chaos-mesh/chaos-mesh -n=chaos-mesh --set chaosDaemon.runtime=containerd --set chaosDaemon.socketPath=/run/containerd/containerd.sock --set controllerManager.leaderElection.enabled=false --version 2.5.0
```

**What did you expect to see?**
Based on https://chaos-mesh.org/docs/production-installation-using-helm I should see only one `chaos-controller-manager-xxx`.

**What did you see instead?**
```
NAME                                       READY   STATUS    RESTARTS   AGE
chaos-controller-manager-ff5f9674b-cp996   1/1     Running   0          3m51s
chaos-controller-manager-ff5f9674b-gxctp   1/1     Running   0          3m51s
chaos-controller-manager-ff5f9674b-xbxg7   1/1     Running   0          3m51s
chaos-daemon-cgt2n                         1/1     Running   0          3m52s
chaos-daemon-cmzbx                         1/1     Running   0          3m52s
chaos-daemon-fxl6t                         1/1     Running   0          3m52s
chaos-daemon-gb7ss                         1/1     Running   0          3m52s
chaos-daemon-s8gj4                         1/1     Running   0          3m52s
chaos-dashboard-85b45d85db-4xcpl           1/1     Running   0          3m51s
```

**Output of chaosctl**
I don't use it.

**Comment by cwen0** [comment]
@pxsalehi You also need to set the `controllerManager.replicaCount=1` https://github.com/chaos-mesh/chaos-mesh/blob/master/helm/chaos-mesh/values.yaml#L70

**Comment by pxsalehi** [comment]
Thanks @cwen0. The documentation linked above seems to be missing this info, although it clearly says:

> If leader-election feature is turned off manually, chaos-controller-manager should only have 1 replication.

**Comment by cwen0** [comment]
> Thanks @cwen0. The documentation linked above seems to be missing this info, although it clearly says:
> 
> > If leader-election feature is turned off manually, chaos-controller-manager should only have 1 replication.

OK, I will update it.

**Comment by cwen0** [comment]
> > Thanks @cwen0. The documentation linked above seems to be missing this info, although it clearly says:
> > > If leader-election feature is turned off manually, chaos-controller-manager should only have 1 replication.
> 
> OK, I will update it.

Fixed https://github.com/chaos-mesh/website/pull/369
