### ISSUE TITLE
api package not compatible with latest version of sigs.k8s.io/controller-runtime

### ISSUE THREAD

**Issue by fasmat** [chaos-mesh/chaos-mesh#3875]
## Bug Report

**What version of Kubernetes are you using?**
n/a

**What version of Chaos Mesh are you using?**
github.com/chaos-mesh/chaos-mesh/api v0.0.0-20221215071653-5b5c537d2ff6

**What did you do? / Minimal Reproducible Example**
`go mod tidy`

**What did you expect to see?**
go successfully fetching the dependencies for my application

**What did you see instead?**
```
go: finding module for package sigs.k8s.io/controller-runtime/pkg/envtest/printer
github.com/spacemeshos/go-spacemesh/systest/chaos imports
        github.com/chaos-mesh/chaos-mesh/api/v1alpha1 tested by
        github.com/chaos-mesh/chaos-mesh/api/v1alpha1.test imports
        sigs.k8s.io/controller-runtime/pkg/envtest/printer: module sigs.k8s.io/controller-runtime@latest found (v0.14.1), but does not contain package sigs.k8s.io/controller-runtime/pkg/envtest/printer
```

**Output of chaosctl**
n/a

**Comment by xiaomudk** [comment]
Any roadmap on fixing this issue?

**Comment by jiayouxujin** [comment]
Hi @cwen0 ,
This issue still exists, are there any plans to fix it?

**Comment by fasmat** [comment]
@jiayouxujin this should have been fixed with https://github.com/chaos-mesh/chaos-mesh/pull/3902 which updated `sigs.k8s.io/controller-runtime` to v0.14.2

Additionally https://github.com/chaos-mesh/chaos-mesh/pull/4154 will further update `sigs.k8s.io/controller-runtime` to v0.15.2
