### ISSUE TITLE
Dashboard not rolling-restarting

### ISSUE THREAD

**Issue by torbendury** [chaos-mesh/chaos-mesh#3876]
## Bug Report

**What version of Kubernetes are you using?**

```
Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.0", GitCommit:"b46a3f887ca979b1a5d14fd39cb1af43e7e5d12d", GitTreeState:"clean", BuildDate:"2022-12-08T19:58:30Z", GoVersion:"go1.19.4", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.4-gke.2100", GitCommit:"0e55ef943b612cf213ba4abfd1e6e915b9832969", GitTreeState:"clean", BuildDate:"2022-12-07T09:33:35Z", GoVersion:"go1.19.3 X:boringcrypto", Compiler:"gc", Platform:"linux/amd64"}
```

**What version of Chaos Mesh are you using?**

```
v2.5.0
```

**What did you do? / Minimal Reproducible Example**

I deployed the Chaos Mesh Helm chart with a PersistentVolumeClaim (RWO) for the dashboard. I tried to do a `kubectl rollout restart deployment chaos-dashboard` to restart the dashboard.

**What did you expect to see?**
I expected to see a restart of the deployment.

**What did you see instead?**
The rollout is stuck because the PersistentVolumeClaim can only be bound to one Pod at the same time (RWO).

```bash
chaos-dashboard-5477447df-2kfcm             1/1     Running    0          11m   172.22.193.254   gke-XXXXXXXXXXXXXXXXXXXxx-e33a33db-vfx7   <none>           <none>
chaos-dashboard-568594946f-kvq6t            0/1     Init:0/1   0          13m   <none>           gke-XXXXXXXXXXXXXXXXXXXxx-e33a33db-9lhx   <none>           <none>

```

kubectl describe pod <the pod that is stuck>:

```bash
  Warning  FailedAttachVolume  14m                  attachdetach-controller  Multi-Attach error for volume "pvc-e0b0e23c-1a6b-4762-b2b8-70d65a4643da" Volume is already used by pod(s) chaos-dashboard-5477447df-rpt49
  Warning  FailedMount         7m56s                kubelet                  Unable to attach or mount volumes: unmounted volumes=[storage-volume], unattached volumes=[XXXXXXXXXXXXXXXXXXXXXXXXXXXX]: timed out waiting for the condition

```

**Output of chaosctl**

Not needed I guess.

**Hint from me: Since the dashboard is a single Pod and the PVC is RWO, the `restartPolicy` of the Deployment might need to be changed so the Pod is replaced by Kubernetes instead of a rolling restart.**

**Comment by torbendury** [comment]
Hi! Anything happening here? :)

**Comment by g1eny0ung** [comment]
Thank you @torbendury! We missed this problem for a long time. I will review your PR now and appreciate your contributions.
