### ISSUE TITLE
Update base image for chaos-mesh/chaos-mesh

### ISSUE THREAD

**Issue by q7r** [chaos-mesh/chaos-mesh#3891]
## Feature Request

**Is your feature request related to a problem? Please describe:**
The base image Alpine 3.12.12 https://github.com/chaos-mesh/chaos-mesh/blob/master/images/chaos-mesh/Dockerfile#L1 has reached end of support since 01 May 2022 and does not get security patches. 

**Describe the feature you'd like:**
Please update the base image to a newer version https://alpinelinux.org/releases/
Thanks!

**Comment by STRRL** [comment]
Hi @q7r , could you help us update it? Thanks :heart:
