### ISSUE TITLE
create networkchaos error use wiki doc

### ISSUE THREAD

**Issue by zhanghuidinah** [chaos-mesh/chaos-mesh#391]
## Bug Report
```
Warning  ChaosRecoverFailed  2m41s (x25 over 166m)  networkchaos-controller  rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 10.200.0.72:31767: connect: connection refused"
```
**What version of Kubernetes are you using?**

`v1.13`

**What did you do?**

- when I create networkchaos refer to  [Network Chaos](https://github.com/pingcap/chaos-mesh/wiki/Network-Chaos)

**Reason**
- Need to remove metadata/namespaces field，cause  the partition here is globally default
![image](https://user-images.githubusercontent.com/31201589/77911733-e5558e00-72c3-11ea-8aad-561206a06043.png)

**Comment by zhouqiang-cl** [comment]
@cwen0 PTAL

**Comment by cwen0** [comment]
@zhanghuidinah I am confused about this issue. Form the error log, the `controllers` have no access to `chaos-daemon`, Can you check the status of the `chaos-daemon`?  And make sure that the chaos-daemon pod with IP `10.200.0.72 ` is running. 
```
kubectl get pod -n chaos-testing -o wide 
``` 

If we remove metadata/namespaces field, the NetworkChaos object was created under the `default` namespace. I don't know why it is work for this issue. Can you provide more information about this reason?

**Comment by zhanghuidinah** [comment]
```
root@qa-3:/home/zhangh# kubectl get pod -n chaos-testing -o wide
NAME                                         READY   STATUS    RESTARTS   AGE     IP               NODE           NOMINATED NODE   READINESS GATES
chaos-collector-database-d699dd54b-9fr2v     0/1     Pending   0          4d      <none>           <none>         <none>           <none>
chaos-controller-manager-7ddc56fb74-95xlf    1/1     Running   12         4d      192.168.15.97    ai-1080ti-15   <none>           <none>
chaos-daemon-2s4kc                           1/1     Running   0          4d      192.168.14.63    dl-47     <none>           <none>
chaos-daemon-5td8l                           1/1     Running   1          4d      192.168.20.168   ai-1080ti-62   <none>           <none>
chaos-daemon-8qqp7                           1/1     Running   0          4d      192.168.5.81     dl-42     <none>           <none>
chaos-daemon-bjhkg                           1/1     Running   0          4d      192.168.13.210   dl-46     <none>           <none>
chaos-daemon-bpzz2                           1/1     Running   2          4d      192.168.24.213   qa-12g    <none>           <none>
chaos-daemon-bz8rz                           1/1     Running   0          4d      192.168.17.188   ai-1080ti-57   <none>           <none>
chaos-daemon-hk2cs                           1/1     Running   0          3d23h   192.168.2.86     qa-14     <none>           <none>
chaos-daemon-jzqcn                           1/1     Running   0          4d      192.168.3.39     qa-15     <none>           <none>
chaos-daemon-n2f64                           1/1     Running   0          4d      192.168.19.48    dl-48     <none>           <none>
chaos-daemon-nwrbf                           1/1     Running   0          4d      192.168.15.95    ai-1080ti-15   <none>           <none>
chaos-daemon-nxv67                           1/1     Running   0          4d      192.168.10.198   qa-4      <none>           <none>
chaos-daemon-qwv48                           1/1     Running   1          4d      192.168.4.109    qa-16     <none>           <none>
chaos-daemon-w6vgs                           1/1     Running   0          4d      192.168.22.106   qa-10g    <none>           <none>
chaos-daemon-xgw8h                           1/1     Running   0          3d23h   192.168.12.20    qa-5      <none>           <none>
chaos-daemon-zz9gz                           1/1     Running   2          4d      192.168.11.20    qa-8g     <none>           <none>
chaos-dashboard-5886b58d8d-gcnr8             1/1     Running   0          4d      192.168.20.164   ai-1080ti-62   <none>           <none>
istio-system-chaos-grafana-8d84f7964-mdhqw   1/1     Running   0          23h     192.168.2.206    qa-14     <none>           <none>
```


- Sorry, I found the root cause that one node's firewall is not turned on. This issue is solved

![image](https://user-images.githubusercontent.com/31201589/78004147-4d5faf00-736c-11ea-9e23-c3e2c176ce9b.png)

**Comment by hoang-tranviet** [comment]
@zhanghuidinah I have got the same problem. Would you mind to explain what your environment is (e.g. in kind) and how do you solve the firewall issue in details?
Thank you!

**Comment by qhh0205** [comment]
@hoang-tranviet @zhanghuidinah @zhouqiang-cl 
The same issue to me, does no 31767 port on the node, i don't konw why access node_ip:31767, what's the port used for?
```bash
Warning  ChaosInjectFailed  92s (x17 over 6m59s)  networkchaos-controller  rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 10.21.0.13:31767: connect: connection refused"
```

**Comment by zhouqiang-cl** [comment]
@YangKeao PTAL

**Comment by YangKeao** [comment]
@qhh0205 That's because we have set `hostPort` for the DaemonSet.

But it seems that `hostPort` cannot work well in many situations (for example, the firewall on the node may block this connection), maybe we should consider a better & more stable way to communicate with chaos-daemon. @cwen0

**Comment by qhh0205** [comment]
@YangKeao I have check the hostPort on the node, no 31767 port listend but the Pod is running. In addition, not the pod_ip:31767 can be accessed:
```bash
# Port 31767 not listen on the node
netstat -ntlp | grep 31767
<no result, not listen 31767>

# The pod ip and port can be accessed
nc -zv 192.168.103.105 31767
Connection to 192.168.103.105 31767 port [tcp/*] succeeded!

# chaos conponent is running
NAME                                      READY   STATUS    RESTARTS   AGE
chaos-controller-manager-545b497b-5xw8j   1/1     Running   0          6d20h
chaos-daemon-28dc4                        1/1     Running   0          14d
chaos-daemon-j8qxw                        1/1     Running   0          14d
chaos-daemon-rp6st                        1/1     Running   0          14d
chaos-daemon-w277s                        1/1     Running   0          14d
chaos-daemon-zrt25                        1/1     Running   0          14d
chaos-dashboard-69f86c6789-bgv6k          1/1     Running   0          6d20h
```

**Comment by qhh0205** [comment]
Maybe NodePort is more stable.

**Comment by YangKeao** [comment]
@qhh0205 Yes. `chaos-mesh` only sets `hostPort` in DaemonSet configuration file and expects kubernetes to listen to the port for it. However, `hostPort` feature fails to work in some situations (for example, some extra configuration is needed to enable hostPort on some CNI, as discussed [here](https://github.com/kubernetes/kubernetes/issues/23920)).

A simple and brute-force workaround is to install chaos-mesh with `hostNetwork`

```
helm install chaos-mesh helm/chaos-mesh --namespace=chaos-testing --set chaosDaemon.hostNetwork=true ...
```

Or you can edit the `chaos-daemon` DaemonSet manually to add `hostNetwork: true` in its spec.

> Maybe NodePort is more stable.

With `NodePort` we cannot connect with the daemon on a specific node. In the Kubernetes website, there are four ways to communicate with DaemonSet:

*    Push: Pods in the DaemonSet are configured to send updates to another service, such as a stats database. They do not have clients.
*    NodeIP and Known Port: Pods in the DaemonSet can use a hostPort, so that the pods are reachable via the node IPs. Clients know the list of node IPs somehow, and know the port by convention.
*    DNS: Create a headless service with the same pod selector, and then discover DaemonSets using the endpoints resource or retrieve multiple A records from DNS.
*    Service: Create a service with the same Pod selector, and use the service to reach a daemon on a random node. (No way to reach specific node.)

Except `hostPort` and `service`, it seems that DNS is the only choice left :sweat_smile:

**Comment by cwen0** [comment]
> @qhh0205 Yes. `chaos-mesh` only sets `hostPort` in DaemonSet configuration file and expects kubernetes to listen to the port for it. However, `hostPort` feature fails to work in some situations (for example, some extra configuration is needed to enable hostPort on some CNI, as discussed [here](https://github.com/kubernetes/kubernetes/issues/23920)).
> 
> A simple and brute-force workaround is to install chaos-mesh with `hostNetwork`
> 
> ```
> helm install chaos-mesh helm/chaos-mesh --namespace=chaos-testing --set chaosDaemon.hostNetwork=true ...
> ```
> 
> Or you can edit the `chaos-daemon` DaemonSet manually to add `hostNetwork: true` in its spec.
> 
> > Maybe NodePort is more stable.
> 
> With `NodePort` we cannot connect with the daemon on a specific node. In the Kubernetes website, there are four ways to communicate with DaemonSet:
> 
> * Push: Pods in the DaemonSet are configured to send updates to another service, such as a stats database. They do not have clients.
> * NodeIP and Known Port: Pods in the DaemonSet can use a hostPort, so that the pods are reachable via the node IPs. Clients know the list of node IPs somehow, and know the port by convention.
> * DNS: Create a headless service with the same pod selector, and then discover DaemonSets using the endpoints resource or retrieve multiple A records from DNS.
> * Service: Create a service with the same Pod selector, and use the service to reach a daemon on a random node. (No way to reach specific node.)
> 
> Except `hostPort` and `service`, it seems that DNS is the only choice left 😅

We can try `DNS` for `chaos-daemon` 😏

**Comment by qhh0205** [comment]
> Or you can edit the `chaos-daemon` DaemonSet manually to add `hostNetwork: true` in its spec.
> 
> >

I have set the `hostNetwork: true`, and the port can be accessed, but new error report -_-!, event as following:
```bash
Events:
  Type     Reason             Age                   From                     Message
  ----     ------             ----                  ----                     -------
  Warning  ChaosInjectFailed  4m35s (x17 over 10m)  networkchaos-controller  rpc error: code = Unimplemented desc = unknown service chaosdaemon.ChaosDaemon
```
@YangKeao

**Comment by qhh0205** [comment]
The following is the NetworkChaos i created:
```yaml
apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: web-show-network-delay
spec:
  action: delay # the specific chaos action to inject
  mode: one # the mode to run chaos action; supported modes are one/all/fixed/fixed-percent/random-max-percent
  selector: # pods where to inject chaos actions
    namespaces:
      - default
    labelSelectors:
      "app": "web-show"  # the label of the pod for chaos injection
  delay:
    latency: "10ms"
  duration: "30s" # duration for the injected chaos experiment
  scheduler: # scheduler rules for the running time of the chaos experiments about pods.
    cron: "@every 60s"
```

**Comment by YangKeao** [comment]
@qhh0205 It seems that `chaos-mesh`'s GRPC service renames from `chaosdaemon.ChaosDaemon` to `pb.ChaosDaemon`. And the docker image version of your `controller-manager` may mismatch with your `chaos-daemon`'s if you only restart(delete) chaos-daemon pods.

A simple solution is to delete/update `controller-manager`. @cwen0  Do we need any mechanism to detect the mismatch between the versions of the images?

**Comment by qhh0205** [comment]
@YangKeao Thank you very much, you are right, i have change the controller-manager deployment's imagePullPolicy from `imagePullPolicy: IfNotPresent` to `imagePullPolicy: always`, then that worked. I have found that by default, the controller-manager imagePullPolicy is `IfNotPresent` and the chaos-daemon's imagePullPolicy is `Always`. So this will lead the mismatch between controller-manager and chaos-daemon.

**Comment by YangKeao** [comment]
>  I have found that by default, the controller-manager imagePullPolicy is IfNotPresent and the chaos-daemon's imagePullPolicy is Always

`git blame` showes me that the `imagePullPolicy` has been `Always` by default since 5 monthes ago (#289) 😅

**Comment by YangKeao** [comment]
@qhh0205 How is your experience with  `chaos-mesh` ? If this issue has been solved, please close it 😸
