### ISSUE TITLE
Support for LB in dashboard svc

### ISSUE THREAD

**Issue by vyshnavii-synopsys** [chaos-mesh/chaos-mesh#3920]
## Feature Request

**Describe the feature you'd like:**
For dashboard k8s service we don't have support to add loadbalancer source IPs.

`{{- if and .Values.dashboard.service.type (eq .Values.dashboard.service.type "LoadBalancer") }}
  {{- with .Values.dashboard.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
  {{- toYaml . | nindent 4 }}
 {{- end }}
{{- end }}`

**Comment by prakrit55** [comment]
haey @STRRL, may I put a pr here to solve it

**Comment by g1eny0ung** [comment]
Hi @prakrit55, I noticed that there is already a PR (#4172) but we've ignored it for so long. I may take a look at it at first, and if you have some suggestions, please let us know, like do you feel that this PR doesn't address the issue or something like that.

**Comment by prakrit55** [comment]
I think this pr is all okay but it has some conflict in the branch, and the person hasnt resolved it yet.

**Comment by jamshidi799** [comment]
I will resolve the conflicts very soon

**Comment by g1eny0ung** [comment]
Thank you all @prakrit55 @jamshidi799. I'll review it right now.
