### ISSUE TITLE
Provide a way to build binaries locally in `Makefile`

### ISSUE THREAD

**Issue by g1eny0ung** [chaos-mesh/chaos-mesh#3989]
Ref: https://github.com/chaos-mesh/chaos-mesh/pull/3986#discussion_r1152731381

**Comment by STRRL** [comment]
Great! 

Actually, I noticed another similar way to make contributor's local setup more easier: https://github.com/apache/incubator-opendal/pull/1687/files

But our situation is, we have used too many environment variables to configure the building process, which is not easy to passthrough into the docker.

**Comment by STRRL** [comment]
Any other idea about avoiding using too many environment variables as "feature flags" in Makefile?

also cc @yangkeao @cwen0

**Comment by g1eny0ung** [comment]
> Any other idea about avoiding using too many environment variables as "feature flags" in Makefile?
> 
> also cc @YangKeao @cwen0

@STRRL In #4004, I tried to alleviate this problem with a temporary solution. PTAL.

**Comment by g1eny0ung** [comment]
This issue has a milestone and is already available. So I will close it for now.
