### ISSUE TITLE
Integration Test on AMD64 Keeps Failing 

### ISSUE THREAD

**Issue by STRRL** [chaos-mesh/chaos-mesh#3998]
## Bug Report

**What version of Kubernetes are you using?**

N/A 

**What version of Chaos Mesh are you using?**

N/A

**What did you do? / Minimal Reproducible Example**

I noticed that Integration Tests faced continues failing recent days:

<img width="1337" alt="image" src="https://user-images.githubusercontent.com/20221408/229829283-022946cf-91bc-4775-87e0-9f8df4fd8da6.png">

**What did you expect to see?**

**What did you see instead?**

**Output of chaosctl**

**Comment by g1eny0ung** [comment]
> error: timed out waiting for the condition on pods/localstack-5bf996bf57-jxktr

Most failures are due to timeouts (60s) when bootstrapping the local stack. A straightforward way to fix this is to increase the timeout duration.

But since I remember that the previous integration tests were also often wrong (unstable), we should consider overhauling the integration tests to make them as practical as possible.

**Comment by STRRL** [comment]
I am going to close this issue because it was recovered. Maybe there is something like networking or computing platform changed behind GitHub Action, and then it recovered.


> Most failures are due to timeouts (60s) when bootstrapping the LocalStack. A straightforward way to fix this is to increase the timeout duration.

Yeah, I noticed that. But It seems the Integration Tests have been recovered without any code changes.

> But since I remember that the previous integration tests were also often wrong (unstable), we should consider overhauling the integration tests to make them as practical as possible.

Definitely yes, maybe later in next month, I would have more time on it.

**Comment by g1eny0ung** [comment]
> Definitely yes, maybe later in next month, I would have more time on it.

That would be great! 🙌🏼
