### ISSUE TITLE
添加新的混沌实验类型HelloWorldChaos 报错

### ISSUE THREAD

**Issue by Lttstbj** [chaos-mesh/chaos-mesh#4025]
kubectl apply -f /path/to/chaos.yaml
提示错误：

Error from server: error when creating "chaos.yaml": admission webhook "vauth.kb.io" denied the request: kind HelloWorldChaos is not support: invalid value

**Comment by g1eny0ung** [comment]
I will try to implement it and then see what it is

**Comment by 892195580** [comment]
I run make generate failed.

**Comment by g1eny0ung** [comment]
Hi guys, I've revisited the old development guides and refactored more in https://github.com/chaos-mesh/website/pull/393. Please try again. You can see the latest content via PR's site preview.

**Comment by g1eny0ung** [comment]
> Hi guys, I've revisited the old development guides and refactored more in [chaos-mesh/website#393](https://github.com/chaos-mesh/website/pull/393). Please try again. You can see the latest content via PR's site preview.

This PR has been merged. I'll close this issue for now. If you still find some problems related to this development guide. Please submit to https://github.com/chaos-mesh/website/issues.
