### ISSUE TITLE
The chaos-dashboard UI doesn't follow the CRDs configurations

### ISSUE THREAD

**Issue by jouini-mohamed** [chaos-mesh/chaos-mesh#4031]
## Bug Report

**What version of Kubernetes are you using?**
`kubectl version`: v1.23

**What version of Chaos Mesh are you using?**
`chaos-controller-manager -version`: chart-2.5.2

**What did you do? / Minimal Reproducible Example**

I installed chaos-mesh `v2.5.2` using the helm chat; I'm only interested in some experiments, let's say: only `PodChaos` , so I removed all not need CRDs manifest files from `crds` folder and also from `webhook.CRDS` to avoid installing unnecessary admission webhooks.

I verified that only needed CRDs are present in my deployment using `kubectl get crd`

**What did you expect to see?**

Based on my deployment, I expect that the chaos-dashboard UI will only display available experiments.  

**What did you see instead?**

It seems to be hardcoded, and all experiments are available in UI even if they do not exist and are not configured (no CRD, no admission webhook) 

I got those error messages, BTW , AWSChaos and GCPChaos are not installed 
```
error.api.internal_server_error: no matches for kind "AWSChaos" in version "chaos-mesh.org/v1alpha1"
error.api.internal_server_error: no matches for kind "GCPChaos" in version "chaos-mesh.org/v1alpha1"
....
```

After a while, I got this error from the chaos-dashboard pod, and the pod is passed to `CrashLoopBackOff` status 

```
ERROR	collector	collector/server.go:155	could not start collector	{"error": "failed to wait for gcpchaos caches to sync: timed out waiting for cache to be synced"}
```

Fixed after redeploying all CRDs, looks like can't select what we need, and we have to install all experiments 

Can we only display experiments if they are included in deployment?

Thank you

**Comment by STRRL** [comment]
The enable/disable of certain controllers could be configured by this helm value:

- `controllerManager.enabledControllers` 

The default value is `["*"]`, which means enable all the controllers.

For only enabling PodChaos, you could change it to

- `["podchaos-condition", "podchaos-desirephase", "podchaos-initFinalizers", "podchaos-cleanFinalizers", "podchaos-records"]`


The name of the controller is the combination of "resource name" and "controller type", and that relates to the implementation detail of Chaos Mesh. So it is kind of a confusing configuration flag.

**Comment by jouini-mohamed** [comment]
@STRRL, Thanks a lot,
