### ISSUE TITLE
High CPU with a lot of info log generated by process-builder

### ISSUE THREAD

**Issue by chris-ng-scmp** [chaos-mesh/chaos-mesh#4058]
## Bug Report

**What version of Kubernetes are you using?**
1.24

**What version of Chaos Mesh are you using?**
2.5.2

**What did you do? / Minimal Reproducible Example**
I have Chaos Mesh installed and running only 2 schedules those are pod-kill every 30mins

But chaos-daemon keep high CPU with the following logs, the number of log is massive, this is just part of the log within 1s

```
chaos-daemon-9rp64 chaos-daemon 2023-05-23T16:03:02.590+0800	INFO	chaos-daemon.daemon-server.background-process-manager.process-builder	utils/ipset.go:28	build command	{"command": "/usr/local/bin/nsexec -n /proc/113147/ns/net -- ipset save -o xml"}
chaos-daemon-9rp64 chaos-daemon 2023-05-23T16:03:02.593+0800	INFO	chaos-daemon.daemon-server.background-process-manager.process-builder	utils/tc.go:27	build command	{"command": "/usr/local/bin/nsexec -n /proc/113147/ns/net -- tc qdisc"}
chaos-daemon-6rhf4 chaos-daemon 2023-05-23T16:03:02.595+0800	INFO	chaos-daemon.daemon-server.background-process-manager.process-builder	utils/ipset.go:28	build command	{"command": "/usr/local/bin/nsexec -n /proc/3921999/ns/net -- ipset save -o xml"}
chaos-daemon-46l5p chaos-daemon 2023-05-23T16:03:02.598+0800	INFO	chaos-daemon.daemon-server.background-process-manager.process-builder	utils/iptables.go:28	build command	{"command": "/usr/local/bin/nsexec -n /proc/2507958/ns/net -- iptables-save -c"}
chaos-daemon-9rp64 chaos-daemon 2023-05-23T16:03:02.599+0800	INFO	chaos-daemon.daemon-server.background-process-manager.process-builder	utils/iptables.go:28	build command	{"command": "/usr/local/bin/nsexec -n /proc/67704/ns/net -- iptables-save -c"}
chaos-daemon-6rhf4 chaos-daemon 2023-05-23T16:03:02.600+0800	INFO	chaos-daemon.daemon-server.background-process-manager.process-builder	utils/tc.go:27	build command	{"command": "/usr/local/bin/nsexec -n /proc/3921999/ns/net -- tc qdisc"}
chaos-daemon-46l5p chaos-daemon 2023-05-23T16:03:02.601+0800	INFO	chaos-daemon.daemon-server.background-process-manager.process-builder	utils/ipset.go:28	build command	{"command": "/usr/local/bin/nsexec -n /proc/2507958/ns/net -- ipset save -o xml"}
chaos-daemon-46l5p chaos-daemon 2023-05-23T16:03:02.604+0800	INFO	chaos-daemon.daemon-server.background-process-manager.process-builder	utils/tc.go:27	build command	{"command": "/usr/local/bin/nsexec -n /proc/2507958/ns/net -- tc qdisc"}
chaos-daemon-6rhf4 chaos-daemon 2023-05-23T16:03:02.613+0800	INFO	chaos-daemon.daemon-server.background-process-manager.process-builder	utils/iptables.go:28	build command	{"command": "/usr/local/bin/nsexec -n /proc/855352/ns/net -- iptables-save -c"}
chaos-daemon-dzg4b chaos-daemon 2023-05-23T16:03:02.614+0800	INFO	chaos-daemon.daemon-server.background-process-manager.process-builder	utils/iptables.go:28	build command	{"command": "/usr/local/bin/nsexec -n /proc/1563577/ns/net -- iptables-save -c"}

```

**What did you expect to see?**
Chaos mesh should only have loading when experiment is running, with only 2 pod-kill schedules should not generate should logs and keep high CPU

![image](https://github.com/chaos-mesh/chaos-mesh/assets/2509212/6dd9eb3d-58db-4e8d-a51d-aad153a33c60)
![image](https://github.com/chaos-mesh/chaos-mesh/assets/2509212/7c7de4f5-7814-4699-81ab-b1f468296636)

**Comment by STRRL** [comment]
It seems it's the overhead of the metrics system of Chaos Mesh.

We append some annotations on our services like 

```yaml
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "{{ .Values.chaosDaemon.httpPort }}"
```

Maybe trying to disable the scraping would work.

**Comment by scmp-techsys** [comment]
@STRRL

 I can confirm such logs are not appear if the scraping is disabled, the CPU usage also becomes normal as well

I think those metrics scraping is important for the system to keep track of those records, would be great if the metric endpoint behave normally.

**Comment by scmp-techsys** [comment]
The HELM template has no way to disable the scaping btw...

https://github.com/chaos-mesh/chaos-mesh/blob/master/helm/chaos-mesh/templates/chaos-daemon-service.yaml#L21

**Comment by chris-ng-scmp** [comment]
@STRRL

I can confirm such logs are not appear if the scraping is disabled, the CPU usage also becomes normal as well

I think those metrics scraping is important for the system to keep track of those records, would be great if the metric endpoint behave normally.

The HELM template has no way to disable the scaping btw...

https://github.com/chaos-mesh/chaos-mesh/blob/master/helm/chaos-mesh/templates/chaos-daemon-service.yaml#L21
