### ISSUE TITLE
Couldn't delete HttpChaos because request too large

### ISSUE THREAD

**Issue by dearboll23** [chaos-mesh/chaos-mesh#4076]
## Bug Report

**What version of Kubernetes are you using?**

Client Version: v1.24.2
Server Version: v1.24.11-gke.1000

**What version of Chaos Mesh are you using?**

ghcr.io/chaos-mesh/chaos-mesh:v2.5.1

**What did you do? / Minimal Reproducible Example**

I want to delete a HttpChaos CR, but the deletion is hanging over, and the chaos-controller's log shows the target HttpFault resource is very large, with an error message `request too large`, seems like an error message from etcd log. So I guess the issue is the size of HttpChaos is too large to delete it in etcd server. When I show the HttpChaos as yaml format, the `status` field is really very long recording all the history of itself.

**What did you expect to see?**

**What did you see instead?**

**Output of chaosctl**

**Comment by dearboll23** [comment]
Update. I repaired the large HttpChaos resource and delete it by the following commands.
``` shell 
kubectl delete validatingwebhookconfigurations.admissionregistration.k8s.io chaos-mesh-validation-auth
kubectl patch --type=merge  httpchaos delaytest2 -p '{"status":null}’
```
But I think there should be a limitation for the event recorder to avoid the resource being too large.

**Comment by spencercjh** [comment]
I try to reproduce and create the httpchaos locally and failed to delete. It is hung over and there isn't any log about `delete` in the controller-manager.

**Comment by spencercjh** [comment]
I think the author of the issue has a good point in saying that the event in status cannot grow indefinitely. I can't even apply the yaml provided by `kubectl apply -f` with error `metadata.annotations: Too long: must have at most 262144 characters`.
