### ISSUE TITLE
RemoteCluster: Sync Chaos Experiements Status back to the Management Cluster

### ISSUE THREAD

**Issue by STRRL** [chaos-mesh/chaos-mesh#4108]
## Feature Request

**Is your feature request related to a problem? Please describe:**

**Describe the feature you'd like:**

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by nioshield** [comment]
@STRRL Is there any new progress?

**Comment by nioshield** [comment]
I want to implement this feature in the remotechaosmonitor controller. The steps are as follows:
1. Obtain the remote status and compare the local status
2. If they are different, the update operation is required
3. Update the local status information

Possible problems:
1. The RemoteObject interface only provides the GetStatus () method, but does not provide a method to write to the ChaosStatus to local object

Is there any potential problem with this implementation? 
 @STRRL @g1eny0ung

**Comment by g1eny0ung** [comment]
> Is there any potential problem with this implementation?

Not sure. 🤔 I need to take a complete look at the code for this piece.
