### ISSUE TITLE
Grafana query for chaos mesh gives error.api.bad_request: token is empty

### ISSUE THREAD

**Issue by sangugwad1993** [chaos-mesh/chaos-mesh#4115]
Performed below steps:

Have installed Docker, and Kubernetes and deployed Chaos-mesh pods using helm
On the physical system added chaosd services
On Grafana added Chaos-mesh plugin
Followed the procedure from the chaos mesh document and still getting the below error on grafan:
![image](https://github.com/chaos-mesh/chaos-mesh/assets/137896048/29d401a2-5a77-4fb3-9a7f-eef4b3cdc275)

**Comment by g1eny0ung** [comment]
Close because it was a duplicate of #4111.
