### ISSUE TITLE
support for Cilium/DPv2 - enable NetworkChaos with the use of eBPF

### ISSUE THREAD

**Issue by hoozgomk** [chaos-mesh/chaos-mesh#4124]
## Feature Request

**Is your feature request related to a problem? Please describe:**
I'm working on emulating various types of incidents on services running on Kubernetes.
I'm using the Chaos Mesh as it provides me the multiple possibilities to inject issues into the pods and it works great with Netem.

I see that the eBPF standard is becoming very popular nowadays and I'm seeing the lack of support for eBPF while emulating Network Issues as a noticeable flaw.

**Describe the feature you'd like:**
Provide support for emulating NetworkChaos on the k8s clusters with eBPF.

**Comment by STRRL** [comment]
Thanks @hoozgomk! We would consider that.


Chaos Mesh NetworkChaos builds the features based on Kubernetes Pod Networking Standard, it means no matter which CNI is used in the Kubernetes cluster, Chaos Mesh could always make the effect.

eBPF is a powerful way to leverage the user space modification for the linux kernel, but I do not realize what thing or which kind of certain experiment could be done by eBPF. Would you give us some examples? :heart:
