### ISSUE TITLE
Error while trying to create GCP chaos

### ISSUE THREAD

**Issue by rohit131989** [chaos-mesh/chaos-mesh#4158]
## Bug Report

**What version of Kubernetes are you using?**
1.25

**What version of Chaos Mesh are you using?**
Git Version: chart-2.5.2 (Got from UI)

**What did you do? / Minimal Reproducible Example**
Created GCP Chaos type Stop Node experiment. 
{
"namespace": "chaos-mesh-experiments",
"name": "exp-gcpchaos-nodestop2",
"kind": "GCPChaos",
"uid": "db97ad15-830c-47d5-a5ae-ed8dc9105c7e",
"created_at": "2023-08-14T11:49:30Z",
"status": "finished",
"kube_object": {
"kind": "GCPChaos",
"apiVersion": "chaos-mesh.org/v1alpha1",
"metadata": {
"namespace": "chaos-mesh-experiments",
"name": "exp-gcpchaos-nodestop2"
},
"spec": {
"action": "node-stop",
"duration": "2m",
"secretName": "sa-secret",
"project": "proj-1",
"zone": "asia-southeast1-a",
"instance": "instance-id-1"
}
}
}

Note: I also noticed that from UI, if I try to click on the experiment to see the detailed experiment info, the page does not load the experiment and returns a blank page. This happens for GCP Node chaos only. I can view pods chaos just fine

**What did you expect to see?**
Chaos should have been injected
**What did you see instead?**
The following error appears for each chaos type under GCP chaos: (Node Stop / Node Reset)

Normal FinalizerInited 10s initFinalizers Finalizer has been inited
Normal Updated 10s initFinalizers Successfully update finalizer of resource
Normal Updated 10s desiredphase Successfully update desiredPhase of resource
Warning Failed 10s records Failed to apply chaos: invalid character '÷' looking for beginning of value

The logs of the chaos controller show the error (fail to get the compute service) to be in the below method
"/chaos-mesh/controllers/chaosimpl/gcpchaos/nodestop/impl.go"

I could not make out why the '÷' symbol is messing up since there is NO value in input parameters apart from alpha-numeric values with hyphen(-).

**Comment by cwen0** [comment]
@rohit131989 Can you check your secret and make sure it is right?

**Comment by rohit131989** [comment]
Below is the definition of secret I used:
Note: After running kubectl apply, the key auto converts to base64.

apiVersion: v1
kind: Secret
metadata:
  name: sa-secret
  namespace: chaos-mesh
type: Opaque
stringData:
  service_account: 123examplekey

**Comment by rohit131989** [comment]
This is resolved. The secret expects whole json file but I was providing the key only.
Thanks
