### ISSUE TITLE
GCP OAuth Authentication - Logout - Cannot read properties of undefined (reading 'token')

### ISSUE THREAD

**Issue by smarcu92** [chaos-mesh/chaos-mesh#4197]
## Bug Report

**What version of Kubernetes are you using?**
version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.15-gke.1700"}

**What version of Chaos Mesh are you using?**
Controller manager Version: version.Info{GitVersion:"chart-2.6.2", GitCommit:"f1dacea430068701a6dd48fdde7ad7ed97b49f0e", BuildDate:"2023-08-23T06:44:17Z", GoVersion:"go1.19.7", Compiler:"gc", Platform:"linux/amd64"}

**What did you do? / Minimal Reproducible Example**
Installed via helm chart. (2.6.2)
Ingress via Istio. (1.16.1)
Istio sidecar enabled (all workloads).
GCP OAuth Authentication setup based on official docs.
Using PostgreSQL (15.2). 

Login works fine. 
Logout results in the following error
![Screenshot 2023-09-14 at 16 45 53](https://github.com/chaos-mesh/chaos-mesh/assets/69853637/39390b11-8cf3-4f84-bbee-0f55c492cdf2)

**Comment by jamshidi799** [comment]
I think this [PR](https://github.com/chaos-mesh/chaos-mesh/pull/4193) will fix this issue

**Comment by jamshidi799** [comment]
@g1eny0ung can we close this issue now?

**Comment by g1eny0ung** [comment]
@jamshidi799 Sure. Closed.
