### ISSUE TITLE
GCP OAuth - Add gcp client ID and secret from existing secret

### ISSUE THREAD

**Issue by losisin** [chaos-mesh/chaos-mesh#4206]
## Feature Request

**Is your feature request related to a problem? Please describe:**

In our organization all values files for every chart and all CI/CD workflows/pipelines are transparent to all developers for viewing. That said, we don't want to use `gcpClientSecret` in plain text in version control or use overrides in CI/CD. Example use case would be:
1.  create credentials with Terraform 
2. Store the output in Google Secrets Manager
3. In Kubernetes create secret with some tool like external-secrets

If this is of any interest I would be happy to create PR

**Describe the feature you'd like:**

It would be nice to have gcp oauth read from existing secret used with `envFrom`. The secret must hold both `GCP_CLIENT_ID` and `GCP_CLIENT_SECRET`. In `values.yaml` we can reference the secret with `gcpexistingSecret`
**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by STRRL** [comment]
Hi @losisin , do you have interests in helping us improve that?

**Comment by losisin** [comment]
@STRRL I'd be happy to!
