### ISSUE TITLE
JVMChaos not working with JDK21

### ISSUE THREAD

**Issue by M-Whitaker** [chaos-mesh/chaos-mesh#4290]
## Bug Report

**What version of Kubernetes are you using?**
v1.27.7+k3s1

**What version of Chaos Mesh are you using?**
v2.6.2

**What did you do? / Minimal Reproducible Example**

Chaos mesh installed using helm chart.

JVM exception injected to JDK17 service, exception thrown

JVM exception injected to JDK21 service, exception not thrown

**What did you expect to see?**

Same results as JDK17

**What did you see instead?**

Both log and load the java agent. Just the JDK21 service isn't affected.

From my very limited research I have found maybe the byteman version used by chaos mesh might need updating? http://bytemanblog.blogspot.com/2023/04/

**Comment by STRRL** [comment]
Hi @M-Whitaker , would you like to help us to bump the version of byteman to the latest version? Thanks!

**Comment by M-Whitaker** [comment]
I was having a quick browse around your repositories and saw some of the potential places you bring in the upstream however would need some clarification on how it's packaged. But happy to help where I can.

**Comment by STRRL** [comment]
if you have docker installed on your computer, you could execute `make image` to build all the container images needed by Chaos Mesh locally.

ref:
https://github.com/chaos-mesh/chaos-mesh/blob/f82f35331903a92b19d09108f67caaec0cf5f748/Makefile#L182

**Comment by M-Whitaker** [comment]
Ok, thanks & my idea was to straight copy this for the byteman bump: https://github.com/chaos-mesh/byteman-helper/commit/734aa8e99b2543d1e334c443f065f160fb9cb6ad

**Comment by STRRL** [comment]
yeah, byteman-helper is required to be updated.

and besides of that, some codes in this repo also need be updates, you could take a look about https://github.com/chaos-mesh/chaos-mesh/pull/3863 as a reference.

**Comment by M-Whitaker** [comment]
Just raised those two PRs. Hopefully, that does it. If there's anything more needed I'm happy to look into it.
