### ISSUE TITLE
Enrich e2e cases

### ISSUE THREAD

**Issue by Yisaer** [chaos-mesh/chaos-mesh#433]
## Feature Request

**Is your feature request related to a problem? Please describe:**

I'm glad to say that for now chaos-mesh could run e2e-test for every PR. This would be a powerful way to guarantee the functional ability for chaos-mesh. Now we are going to enrich the e2e cases to cover all existed kinds chaos.

Currently, we have Pod / Network / IO / Container / Time chaos. For each kind of chaos, we would like to test its `duration / scheduler / pause ` situation.

PodFailuire
- [x]  Duration PodFailure chaos
- [ ]   Schedule PodFailure chaos
- [x] Pause schedule PodFailure chaos
 
PodKill
- [x]  Duration PodKill chaos
- [ ]   Schedule PodKill chaos
- [x] Pause schedule PodKill chaos

Container Kill
- [x] Duration Container Kill chaos
- [ ] Schedule Container Kill chaos
- [x] Pause schedule Container Kill chaos

Network Delay
- [ ] Duration Network Delay chaos
- [ ] Schedule Network Delay chaos
- [ ] Pause schedule Network Delay chaos

Network Partition
- [ ] Duration Network Partition chaos
- [ ] Schedule Network Partition chaos
- [ ] Pause schedule Network Partition chaos

Time skew
- [ ] Duration Time skew cahso
- [x] Schedule Time skew chaos
- [x] Pause schedule Time skew chaos

IO Delay
- [ ] Duration IO Delay chaos
- [x] Schedule IO Delay chaos
- [x] Pause schedule IO Delay chaos

IO Errno
- [ ] Duration IO Errno chaos
- [x] Schedule IO Errno chaos
- [x] Pause schedule IO Errno chaos

**Comment by yeya24** [comment]
I can take the container kill part first

**Comment by Yisaer** [comment]
I also notice that the Network chaos also have many kinds of case that we could test in e2e-test. 
After https://github.com/pingcap/chaos-mesh/pull/403 is merged , we could test the pod-to-pod nework chaos.

**Comment by yeya24** [comment]
Is there a good way to test io-delay?

**Comment by Yisaer** [comment]
How about deploying a single etcd and run etcdctl in the e2e binary and parse the result? @yeya24

**Comment by yeya24** [comment]
Note that since stress chaos is merged, we want to have e2e cases for CPU stress and memory stress as well

**Comment by yeya24** [comment]
Maybe we can combine `Duration` case and `Scheduler` case together. The test cases are very similar. TBH, I think it is okay to have just `Scheduler` case. WDYT @Yisaer

**Comment by Yisaer** [comment]
It's ok for me to combine the `Schedule`/ `Duration` / `Pause` into one ginkgo item to reduce the duplicated preparing work. @yeya24

**Comment by yeya24** [comment]
Still valid. Any ideas on how to move this forward? It is not very straightforward to test other chaos.

**Comment by zhouqiang-cl** [comment]
Still valid
