### ISSUE TITLE
Security improvement: Get database connection username and password from secret instead

### ISSUE THREAD

**Issue by iluwatar** [chaos-mesh/chaos-mesh#4358]
## Feature Request

**Is your feature request related to a problem? Please describe:**

Security improvement

**Describe the feature you'd like:**

This is a feature request to improve Chaos Mesh Helm installation security. At the moment the database connection is configured using `dashboard.env.DATABASE_DATASOURCE` Helm property. The connection string can contain also username and password.

Helm values are not the best option to store confidential information since they are typically stored in repositories. Instead, it would be much better if we could specify the secret name and secret key where to read the information from. This is how it's typically implemented in Helm charts.

**Describe alternatives you've considered:**

I'm not aware of any alternative way to configure Chaos Mesh persistence

**Teachability, Documentation, Adoption, Migration Strategy:**

-

**Comment by STRRL** [comment]
Thanks!

**Comment by iluwatar** [comment]
Ok @STRRL, here we go: https://github.com/chaos-mesh/chaos-mesh/pull/4363
