### ISSUE TITLE
Chaos Mesh experiment failing with "admission webhook 'vstresschaos.kb.io' denied the request: Spec: Invalid value: xxx. missing stressors"

### ISSUE THREAD

**Issue by RenzoPrettoMS** [chaos-mesh/chaos-mesh#4393]
## Bug Report

**What version of Kubernetes are you using?**
1.27.7

**What version of Chaos Mesh are you using?**
GitVersion:"chart-2.6.3"

**What did you do? / Minimal Reproducible Example**
1. az aks get-credentials -g $RESOURCE_GROUP -n $CLUSTER_NAME
2. helm repo add chaos-mesh https://charts.chaos-mesh.org
3. helm repo update
4. kubectl create ns chaos-testing
5. helm install chaos-mesh chaos-mesh/chaos-mesh --namespace=chaos-testing --set chaosDaemon.runtime=containerd --set chaosDaemon.socketPath=/run/containerd/containerd.sock
6. Verified all necessary pods are there with: kubectl get po -n chaos-testing

**What did you expect to see?**
Expected to be able to run the chaos mesh experiment successfully.

**What did you see instead?**
failed with below error. 

admission webhook 'vstresschaos.kb.io' denied the request: Spec: Invalid value: v1alpha1.StressChaosSpec{ContainerSelector:v1alpha1.ContainerSelector{PodSelector:v1alpha1.PodSelector{Selector:v1alpha1.PodSelectorSpec{GenericSelectorSpec:v1alpha1.GenericSelectorSpec{Namespaces:[]string{'demo'}, FieldSelectors:map[string]string(nil), LabelSelectors:map[string]string(nil), ExpressionSelectors:v1alpha1.LabelSelectorRequirements(nil), AnnotationSelectors:map[string]string(nil)}, Nodes:[]string(nil), Pods:map[string][]string(nil), NodeSelectors:map[string]string(nil), PodPhaseSelectors:[]string(nil)}, Mode:'all', Value:''}, ContainerNames:[]string(nil)}, Stressors:(*v1alpha1.Stressors)(nil), StressngStressors:'', Duration:(*string)(0xc000d8a0a0), RemoteCluster:''}: missing stressors

**Output of chaosctl**
[chaos pod logs.txt](https://github.com/chaos-mesh/chaos-mesh/files/14936081/chaos.pod.logs.txt)

**Comment by STRRL** [comment]
please check your stresschaos spec/definition, the error message indicate that the chaos is not valid

**Comment by ashokyedluri** [comment]
Hii @STRRL , below is the default config we are using. I Added the target ( my aks cluster in azure is enabled ) . As a 
Service-direct capabilities. With this  we can able to do stress chaos, IO chaos and few more tests. But Not able to do it. Post that i created a Chaos Experiment and used default branch and step . Below is the default json i used. I used the same to test AKS Chaos Mesh Stress chaos. Apart from that i don't , do any changes. Please let me know, your suitable time to have a call to discuss in detail.

{"action":"pod-failure","mode":"all","duration":"600s","selector":{"namespaces":["default"]}}


<img width="839" alt="Screenshot 2024-04-22 at 10 56 47" src="https://github.com/chaos-mesh/chaos-mesh/assets/60726553/f9aa2e95-df0b-45af-9a51-50c4ddd5d172">

<img width="1479" alt="Screenshot 2024-04-22 at 10 54 29" src="https://github.com/chaos-mesh/chaos-mesh/assets/60726553/795cc6fa-09f1-4589-be09-bd2bab0454af">

**Comment by ashokyedluri** [comment]
<img width="1722" alt="Screenshot 2024-04-22 at 11 03 10" src="https://github.com/chaos-mesh/chaos-mesh/assets/60726553/4ae0b673-2cd4-4b3e-8941-3518213b0fc7">

**Comment by RenzoPrettoMS** [comment]
@ashokyedluri Can you please verify you are using the correct definition for the scenario? The definition you are showing seems to be for the "PodChaos" scenario not the "StressChaos" scenario. Please let me know if this fixes the experiment.
