### ISSUE TITLE
Unable to view saved information in the archive, program log reports' Error # 01: error. api.badunrequest: the archive schedule is not found '

### ISSUE THREAD

**Issue by Lynxhide** [chaos-mesh/chaos-mesh#4493]
chaos mesh version: v2.6.3

kubernetes version: v1.23.16

Error message：[GIN] 2024/09/11 - 17:33:51 | 500 |    3.155843ms |      10.244.0.1 | GET      "/api/archives/schedules/4f6c7698-2378-4cfd-84d6-d8dce37e839a"
Error #01: error.api.bad_request: the archive schedule is not found

browser：
![image](https://github.com/user-attachments/assets/ec8f5127-ba82-456c-a77d-a041eeaea67a)

**Comment by g1eny0ung** [comment]
Would you please provide more logs? I can not find the reason about the failed 500 request just from a screenshot.

**Comment by Lynxhide** [comment]
log message：
[GIN] 2024/09/18 - 12:10:08 | 200 |    3.427742ms |      10.244.0.1 | GET      "/api/archives"
[GIN] 2024/09/18 - 12:10:09 | 200 |   25.826581ms |      10.244.0.1 | GET      "/api/events"
[GIN] 2024/09/18 - 12:10:10 | 200 |    3.533821ms |      10.244.0.1 | GET      "/api/archives"
[GIN] 2024/09/18 - 12:10:11 | 500 |    1.511517ms |      10.244.0.1 | GET      "/api/archives/workflows/4f6c7698-2378-4cfd-84d6-d8dce37e839a"
Error #01: error.api.bad_request: the archive schedule is not found
[GIN] 2024/09/18 - 12:10:11 | 500 |    1.662159ms |      10.244.0.1 | GET      "/api/archives/schedules/4f6c7698-2378-4cfd-84d6-d8dce37e839a"
Error #01: error.api.bad_request: the archive schedule is not found
[GIN] 2024/09/18 - 12:10:11 | 200 |    2.301614ms |      10.244.0.1 | GET      "/api/events?object_id=4f6c7698-2378-4cfd-84d6-d8dce37e839a&limit=999"
[GIN] 2024/09/18 - 12:10:25 | 200 |     3.52971ms |      10.244.0.1 | GET      "/api/events?object_id=4f6c7698-2378-4cfd-84d6-d8dce37e839a&limit=999"
[GIN] 2024/09/18 - 12:10:25 | 500 |    1.503952ms |      10.244.0.1 | GET      "/api/archives/workflows/4f6c7698-2378-4cfd-84d6-d8dce37e839a"
Error #01: error.api.bad_request: the archive schedule is not found
[GIN] 2024/09/18 - 12:10:25 | 500 |     1.45178ms |      10.244.0.1 | GET      "/api/archives/schedules/4f6c7698-2378-4cfd-84d6-d8dce37e839a"
Error #01: error.api.bad_request: the archive schedule is not found
[GIN] 2024/09/18 - 12:10:27 | 200 |    4.361905ms |      10.244.0.1 | GET      "/api/events?object_id=4f6c7698-2378-4cfd-84d6-d8dce37e839a&limit=999"
[GIN] 2024/09/18 - 12:10:27 | 500 |    5.043655ms |      10.244.0.1 | GET      "/api/archives/schedules/4f6c7698-2378-4cfd-84d6-d8dce37e839a"
Error #01: error.api.bad_request: the archive schedule is not found
[GIN] 2024/09/18 - 12:10:27 | 500 |    7.631669ms |      10.244.0.1 | GET      "/api/archives/workflows/4f6c7698-2378-4cfd-84d6-d8dce37e839a"
Error #01: error.api.bad_request: the archive schedule is not found

**Comment by Lynxhide** [comment]
archive info:
![image](https://github.com/user-attachments/assets/e5e98b1b-68a5-4458-8e27-e3f67f0247e3)

**Comment by jingkl** [comment]
I encountered the same issue. Please take a look.

**Comment by jingkl** [comment]
Can I ask about the progress on this? @g1eny0ung @STRRL

**Comment by g1eny0ung** [comment]
@Lynxhide @jingkl Thanks for providing the info. I found the reason for this error and I'll solve it now.
