### ISSUE TITLE
[Bug]: get x509 error when run host experiment

### ISSUE THREAD

**Issue by Rosyya** [chaos-mesh/chaos-mesh#4549]
### Chaos Mesh Version

V2.6.0

### Kubernetes Version

V1.28.0

### Describe the bug

install chaos-mesh with helm chart v2.6.0, when add a host experiment, address was chaos daemon pod ip, port was 31767 which is grpc port, but get error `Failed to apply chaos: : Post "https://ip:31767/api/attack/stress": x509: certificate is valid for localhost, chaos-daemon.chaos-mesh.org, not chaosd.chaos-mesh.org, but the domain was created by official template and there is no value to change to chaosd.chaos-mesh.org, not sure why use this domain, anybody can help please?

**Comment by STRRL** [comment]
please follow this doc: [chaos-mesh.org/docs/chaosctl-tool#generate-tls-certificates-for-chaosd](https://chaos-mesh.org/docs/chaosctl-tool/#generate-tls-certificates-for-chaosd) to get the correct certificate

**Comment by g1eny0ung** [comment]
I'll close this issue since there have been no responses for two weeks. If you still encounter any problems, feel free to re-open it.
