### ISSUE TITLE
[Bug]: Garbled Chinese text

### ISSUE THREAD

**Issue by wanghygh** [chaos-mesh/chaos-mesh#4568]
### Chaos Mesh Version

v2.6.5

### Kubernetes Version

v1.22.15

### Describe the bug

I am going to Dashboard and trying to create an experiment: simulate JVM application faults with modify return values of a method.
![5E550C04-2748-4876-B7F6-B92F23FA9432](https://github.com/user-attachments/assets/cfada13b-3294-467d-b802-fc73374ccb1b)

Value contains Chinese characters but appears as garbled text in the application logs.
![4B48A963-FF3D-4BFD-8AB7-4987DEF0A0D6](https://github.com/user-attachments/assets/2e40634b-076a-4963-91fb-e938f58439fe)

Application server character set UTF-8.
![4A63CAE1-6BCD-4571-AE6B-60D4597E85FC](https://github.com/user-attachments/assets/26c0b1da-a1c6-4bd3-9dc0-3df4bebfe9ac)

**Comment by wanghygh** [comment]
Configure container(dashboard\controller-manager\daemon) environment variables during Helm installation.
for example: --set controllerManager.env.LANG={app.server.charsets},controllerManager.env.LC_ALL={app.server.charsets}

**Comment by STRRL** [comment]
Hi @wanghygh , sorry for the late response, do you think there is some improvement could be done with our helm? Thanks ❤️
