### ISSUE TITLE
Support power-off chaos

### ISSUE THREAD

**Issue by 5kbpers** [chaos-mesh/chaos-mesh#458]
## Feature Request

**Is your feature request related to a problem? Please describe:**

For now, chaos mesh supports `random-kill`, but sometimes we need something like `random-power-off`, to simulate the situations like the network connections don't be closed properly.

**Describe the feature you'd like:**

Chaos which can power-off nodes.

**Teachability, Documentation, Adoption, Migration Strategy:**

I guess actions like destroying and re-creating a container would address this requirement.

**Comment by Yisaer** [comment]
Power-off chaos is rather interesting while it is hard to guarantee the recovery when we removed the chaos if we really approach to simulate the node power-of.

Maybe we could fail all the pods on the target node and make the target node un-schedule-able?

**Comment by 5kbpers** [comment]
I guess all the persistent states (data in the disk) could be saved in a shared volume and then we could re-mount the shared volume to recover those states.

And shutdown a node may also make sense to me if we can ensure there is only one pod on the target node (because we may only want to power-off a pod).

**Comment by 5kbpers** [comment]
I don't know if it is possible to destroy and re-create a container without destroying the pod. 🤣

**Comment by Yisaer** [comment]
We already have Container kill chaos, but I dont' understand the relation between container chaos and power-of chaos.

**Comment by 5kbpers** [comment]
Some resources like page cache, TCP connections, etc. would not be reclaimed when a node was power off accidentally.

I think it could cover more abnormal situations.
