### ISSUE TITLE
Make chaos-mesh helm repository

### ISSUE THREAD

**Issue by HillebrandtOldenberg** [chaos-mesh/chaos-mesh#462]
## Feature Request

**Is your feature request related to a problem? Please describe:**

I don't want to `git clone https://github.com/pingcap/chaos-mesh.git` in order to make Chaos Mesh work. I want to be able to do it over the internet.

**Describe the feature you'd like:**

Make https://github.com/pingcap/chaos-mesh/tree/master/helm/chaos-mesh a [chart repo](https://helm.sh/docs/topics/chart_repository/).

P.S.: Add the option to install the CRDs using the raw YAML `kubectl apply -f https://raw.githubusercontent.com/pingcap/chaos-mesh/master/manifests/crd.yaml` as well to the wiki, to make the Chaos Mesh installation fully portable (i.e. over the internet).

**Comment by fewdan** [comment]
@HillebrandtOldenberg 
Thanks for your suggestion, we will add this in the future.

**Comment by zhouqiang-cl** [comment]
It done here  https://github.com/chaos-mesh/charts
