### ISSUE TITLE
Support namespace scoped rbac chaos-mesh

### ISSUE THREAD

**Issue by Yisaer** [chaos-mesh/chaos-mesh#487]
## Description

Currently Chaos-mesh required ClusterScope rbac to run in Kubernetes. However, in some strict environments, we need chaos-mesh run as a namespace-scoped rbac. We want to support namespace scoped rbac chaos-mesh 

Close #477 

## Score

* 300

## Mentor(s)

* [@yisaer](https://github.com/Yisaer)

Contact the mentors: **#tidb-challenge-program** channel in [TiDB-Operator Community](https://join.slack.com/t/tidbcommunity/shared_invite/enQtNzc0MzI4ODExMDc4LWYwYmIzMjZkYzJiNDUxMmZlN2FiMGJkZjAyMzQ5NGU0NGY0NzI3NTYwMjAyNGQ1N2I2ZjAxNzc1OGUwYWM0NzE)  Slack Workspace
As the logic is not simple and the detail is still needed to be discussed, we are welcome for every challenger to contact the mentor if you have any questions.

## Recommended Skills
* Golang
* Kubernetes

**Comment by yeya24** [comment]
@Yisaer Is this issue conflict with https://github.com/pingcap/chaos-mesh/issues/355?

**Comment by Yisaer** [comment]
> @Yisaer Is this issue conflict with #355?

I don't think so. If the chaos-mesh only have the namespaced scope rbac, it should watch the configmaps in the certain namespace with certain labels.

**Comment by yeya24** [comment]
> > @Yisaer Is this issue conflict with #355?
> 
> I don't think so. If the chaos-mesh only have the namespaced scope rbac, it should watch the configmaps in the certain namespace with certain labels while it do need some work to do.

Thanks for the clarification. Make sense. So we need something like a `--mode` flag to specify whether chaos mesh is clusterscoped?

**Comment by Yisaer** [comment]
@yeya24  Exactly.

**Comment by STRRL** [comment]
I am trying to work on this issue.

Here is my idea:
- Make new fields `ClusterScoped` and `Namespace` in struct `ChaosControllerConfig`; `ClusterScoped`(bool) represent that running in cluster mode or not. `Namespace` represent the namespace could injected chaos into.
- Make same above configurations in helm's yaml file
- New validation about configurations: `ClusterScoped`, `Namespace`, `AllowedNamespaces`, `IgnoredNamespaces`   
- While  `ClusterScoped` is `false`, and `Namespace` is specified, running controller manager with certain NS.

I will make a PR soon. : )
