### ISSUE TITLE
Support setting only duration field and not setting cron

### ISSUE THREAD

**Issue by cwen0** [chaos-mesh/chaos-mesh#501]
## Feature Request

**Is your feature request related to a problem? Please describe:**

At present, we both require to set `cron` and `duration` fields when to define chaos experiment, but sometimes, we also just want to set `duration` and not setting `cron`. For example, we just want to inject chaos action once and last a specific time.

**Comment by yeya24** [comment]
Help wanted!

**Comment by qhh0205** [comment]
+1

**Comment by STRRL** [comment]
Hi @cwen0 , I realize that `cron` and `at` can cover most of scenario, less is more.
So in my new design, there is no any complex things, only adding support for `at`. It will add a new field for `SchedulerSpec` like `At`, and modify two-phase controller for supporting only-one-shot.

Any problem about this design? 
I will make a PR in next days.

**Comment by qhh0205** [comment]
any update? @STRRL @cwen0

**Comment by STRRL** [comment]
@qhh0205 

Just a few days ago, I have a more clearly solution, could avoid making changes on two-phase controller.

I will implement `at` feature via the common Reconciler.

I need more time, please keeping your expectance. :)

**Comment by STRRL** [comment]
I think we'd better implement this by the workflow. So I will close it now.

**Comment by YangKeao** [comment]
Now (after release-2.0). Every `*Chaos` has only duration without cron 😺
