### ISSUE TITLE
Support pause chaos for a certain duration

### ISSUE THREAD

**Issue by yeya24** [chaos-mesh/chaos-mesh#544]
## Feature Request

**Is your feature request related to a problem? Please describe:**

Now Chaos Mesh supports pausing chaos by annotation. However, the pause state is continued forever unless the user removes that annotation.

**Describe the feature you'd like:**

It would be good to support pausing a certain time duration. After that duration, the chaos resumes. The command should be like:

```shell
kubectl annotate networkchaos web-show-network-delay experiment.chaos-mesh.org/pauseTime=1h
```

**Teachability, Documentation, Adoption, Migration Strategy:**

Can refer to the implement of [experiment.chaos-mesh.org/pause](https://github.com/chaos-mesh/chaos-mesh/blob/5d409d77ae86c3896b15e2809c6b977999368479/api/v1alpha1/common_types.go#L26)

**Comment by zhouqiang-cl** [comment]
Not staale

**Comment by dsam82** [comment]
I would like to take this issue if anyone else is not working. I've gone through the source code and may need some initial guidance.

**Comment by yeya24** [comment]
@dsam82 Sure please go ahead. If you have any questions, feel free to ask here or on our slack channel.

**Comment by dsam82** [comment]
So, got to learn a lot about chaos-mesh from this issue.
Regarding the issue, I still have some doubts regarding the implementation. If we pause the experiment for the duration, then how should we resume it after the duration completes?
Can we set next-recover to `current time + Pause duration` in the [twophase controller](https://github.com/chaos-mesh/chaos-mesh/blob/master/controllers/twophase/types.go#L100)? And how should we do this the [common controller](https://github.com/chaos-mesh/chaos-mesh/blob/master/controllers/common/types.go#L160)?
