### ISSUE TITLE
Archive deleted experiments multiple times

### ISSUE THREAD

**Issue by yeya24** [chaos-mesh/chaos-mesh#557]
## Bug Report

```
select name,start_time,finish_time from archive_experiments where namespace='tipocket-cdc-kafka';
```

Seems the same experiment is stored in the DB several times.

![image](https://user-images.githubusercontent.com/25150124/82839967-1060f600-9e9f-11ea-94aa-ec7a3bd69f63.png)

The cause is that the cleanup of chaos is blocked by the finalized. But since the chaos daemon network problem, the recovery is always failing. But we stored the archive several times.

```
apiVersion: pingcap.com/v1alpha1
kind: TimeChaos
metadata:
  creationTimestamp: "2020-05-14T22:56:43Z"
  deletionGracePeriodSeconds: 0
  deletionTimestamp: "2020-05-14T22:58:57Z"
  finalizers:
  - tipocket-cdc-kafka/tipocket-cdc-kafka-upstream-tikv-1
  generation: 24
  name: tipocket-cdc-kafka-tipocket-cdc-kafka-upstream-tikv-1-time-chaos
  namespace: tipocket-cdc-kafka
  resourceVersion: "76364895"
  selfLink: /apis/pingcap.com/v1alpha1/namespaces/tipocket-cdc-kafka/timechaos/tipocket-cdc-kafka-tipocket-cdc-kafka-upstream-tikv-1-time-chaos
  uid: d3a19fc8-db45-4d43-b4a1-2c39ad826e68
spec:
  clockIds:
  - CLOCK_REALTIME
  mode: one
  paused: false
  selector:
    namespaces:
    - tipocket-cdc-kafka
    pods:
      tipocket-cdc-kafka:
      - tipocket-cdc-kafka-upstream-tikv-1
  timeOffset: -159ms
  value: ""
status:
  experiment:
    phase: Failed
  phase: ""
```

**Comment by cwen0** [comment]
@yeya24 Can we determine whether the experiment is actually deleted?

**Comment by yeya24** [comment]
> @yeya24 Can we determine whether the experiment is actually deleted?

I am not sure. Maybe @Yisaer knows better.

But IMO we should deal with the finalized problem indeed. If the injected pods are deleted, we should cleanup the chaos.

You can see there are no pods, but all the time chaos is left.

![image](https://user-images.githubusercontent.com/25150124/82855996-e5949300-9eda-11ea-8aff-e0bf4f058d33.png)

**Comment by yeya24** [comment]
Do you have a solution for this now? @cwen0 @fewdan

**Comment by zhouqiang-cl** [comment]
I think we can close this issue now.
If there are anything still not works well, please reopen it
