### ISSUE TITLE
How fix it :unable to decode "manifests/crd.yaml": no kind "CustomResourceDefinition" is registered for version "apiextensions.k8s.io/v1beta1"

### ISSUE THREAD

**Issue by sydnever** [chaos-mesh/chaos-mesh#635]
How can i fix it?

![image](https://user-images.githubusercontent.com/2542184/84888617-1fb41780-b0ca-11ea-84ff-8b5d94b49eb4.png)

I am installing chaos-mesh on Centos 7 using minikube and helm

![image](https://user-images.githubusercontent.com/2542184/84888788-6c97ee00-b0ca-11ea-9fb2-e477fd61691c.png)

**Comment by yeya24** [comment]
What Kubernetes version are you using? Could you please try 
```
kubectl version
```
