### ISSUE TITLE
Support injecting fault into Java appliations and JVM 

### ISSUE THREAD

**Issue by cwen0** [chaos-mesh/chaos-mesh#650]
## Feature Request

**Is your feature request related to a problem? Please describe:**

In many scenarios, users need to inject some faults into the Java applications or the JVM itself. However, Chaos Mesh currently does not support injection for specific java applications or jvm granularity.

**Describe alternatives you've considered:**

* Create a new chaos named `JVMChaos`
* We can use [jvm-sandbox](https://github.com/alibaba/jvm-sandbox) as a sidecar container and help us to hack our JAVA application and JVM

**Comment by siddontang** [comment]
do we have any guide about how to ingest a sidecar?

**Comment by zhouqiang-cl** [comment]
> do we have any guide about how to ingest a sidecar?

Not now, we need add it to https://chaos-mesh.org/docs/development_guides/develop_a_new_chaos#make-the-docker-image /cc @cwen0

**Comment by Gallardot** [comment]
I'm still working on this issue. Some JVM permissions are bothering me.

**Comment by STRRL** [comment]
@Gallardot Could you share your idea with us?😁
