### ISSUE TITLE
Support injecting an HTTP delay fault or an HTTP abort fault on the special application

### ISSUE THREAD

**Issue by cwen0** [chaos-mesh/chaos-mesh#651]
## Feature Request

**Is your feature request related to a problem? Please describe:**
 

In many scenarios, users need to inject an HTTP delay fault or an HTTP abort fault on the special application. For example, we just want to inject a delay fault on getting `/api/xxx` router. 

**Describe alternatives you've considered:**

* Create a new chaos named `HTTPChaos`  
* Use [envoy](https://www.envoyproxy.io/) or others as a sidecar and help us to hijack http connections

**Comment by yeya24** [comment]
Any design or ideas currently? I guess this chaos is not compatible with Istio or other service mesh systems?

**Comment by Yisaer** [comment]
> Any design or ideas currently? I guess this chaos is not compatible with Istio or other service mesh systems?

You are right, I think we can tolerate it for now if we try this way.

**Comment by zhouqiang-cl** [comment]
reopen
