### ISSUE TITLE
Kind config in kind-cluster-build.sh can't run when the local docker registry is running

### ISSUE THREAD

**Issue by namco1992** [chaos-mesh/chaos-mesh#666]
## Bug Report

**What version of Kubernetes are you using?**

1.15.6 which is the default version specified in the script.

**What did you do?**

```bash
hack/kind-cluster-build.sh
```

**What did you expect to see?**
A new kind cluster should be started.

**What did you see instead?**
```bash
Creating cluster "kind" ...
 ✓ Ensuring node image (kindest/node:v1.15.6) 🖼 
 ✗ Preparing nodes 📦 📦 📦 📦  
ERROR: failed to create cluster: docker run error: command "docker run --hostname kind-control-plane --name kind-control-plane --label io.x-k8s.kind.role=control-plane --privileged --security-opt seccomp=unconfined --security-opt apparmor=unconfined --tmpfs /tmp --tmpfs /run --volume /var --volume /lib/modules:/lib/modules:ro --detach --tty --label io.x-k8s.kind.cluster=kind --net kind --restart=on-failure:1 --publish=127.0.0.1:5000:5000/TCP --publish=127.0.0.1:57565:6443/TCP kindest/node:v1.15.6" failed with error: exit status 125
Command Output: e1e494ee25ecade2a3c919223ccd96305a3db28cef9e8554f0bdeeaf4cccd76f
docker: Error response from daemon: driver failed programming external connectivity on endpoint kind-control-plane (239ac0c526190f879dd8fd564f69335b39ae6f29b1e1120c5b4356d86ddc748a): Error starting userland proxy: listen tcp 127.0.0.1:5000: bind: address already in use.
```

In short, the port 5000 specified in the `extraPortMappings` is conflicted with the local docker registry, it's the same in `install.sh` `install_kubernetes_by_kind` func. However, the [development guide](https://chaos-mesh.org/docs/development_guides/develop_a_new_chaos) assumes that we run a local docker registry.

I would like to suggest fixing it by the approach that kind recommended: https://kind.sigs.k8s.io/docs/user/local-registry/ I referred to this doc and set up the local env successfully. I can create a PR if it's acceptable.

**Comment by cwen0** [comment]
@namco1992 This a good improvement. Looking forward to your PR!

**Comment by namco1992** [comment]
@cwen0 Thanks! I will work on this.

**Comment by zhouqiang-cl** [comment]
666

**Comment by namco1992** [comment]
Not stale, will work on it soon, sorry.
