### ISSUE TITLE
Makefile default DOCKER_REGISTRY value is empty, breaks the docker build and push locally

### ISSUE THREAD

**Issue by namco1992** [chaos-mesh/chaos-mesh#667]
## Bug Report

**What did you do?**

```bash
make
make docker-push
```

**What did you see instead?**
Unable to push to docker registry.

**What's the reason?**
According to the [development guide](https://chaos-mesh.org/docs/development_guides/develop_a_new_chaos#make-the-docker-image), the default docker registry should be the local docker registry at localhost:5000, however, the makefile is expecting `DOCKER_REGISTRY` variable but didn't set a default value. It will work when it's called by other scripts which set the `DOCKER_REGISTRY`, but it won't work with local docker registry when calling `make` and `make docker-push`.

I can create a PR to add the default value `localhost:5000` back if it's expected.

**Comment by cwen0** [comment]
@namco1992 A good catch!

**Comment by namco1992** [comment]
@cwen0 Thanks! I will work on this.

**Comment by namco1992** [comment]
Not stale, will work on it soon, sorry.

**Comment by zhouqiang-cl** [comment]
Not stale
