### ISSUE TITLE
can't inject some chaos on k3s

### ISSUE THREAD

**Issue by fredleger** [chaos-mesh/chaos-mesh#727]
## Bug Report

**What version of Kubernetes are you using?**
Client Version: v1.15.12
Server Version: v1.17.4+k3s1

**What did you do?**
- installed through helm3 : `helm install chaos-mesh helm/chaos-mesh --namespace=chaos-testing --upgrade --set dashboard.create=true --set chaosDaemon.runtime=containerd --set chaosDaemon.socketPath=/run/containerd/containerd.sock`
- create a StressChaos (also true for time and others):

```yaml
apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: burn-cpu
  namespace: chaos-testing
spec:
  mode: one
  selector:
    labelSelectors:
      app: sf4-animals-demo
  stressors:
    cpu:
      workers: 1
      load: 100
      options: ["--cpu 2", "--timeout 600", "--hdd 1"]
  duration: "30s"
  scheduler:
    cron: "@every 2m"
```

**What did you expect to see?**
No error and effects on pods

**What did you see instead?**

`kubectl describe stresschaos.chaos-mesh.org burn-cpu`

```
Events:
  Type     Reason             Age                  From                    Message
  ----     ------             ----                 ----                    -------
  Warning  ChaosInjectFailed  18m (x7 over 18m)    stresschaos-controller  rpc error: code = Unknown desc = container "d96cb72cf21754b0e5a7affd08df81a4ba38dab7ef613350b30d0ac87bb28e64" in namespace "k8s.io": not found
  Warning  ChaosInjectFailed  13m (x7 over 18m)    stresschaos-controller  rpc error: code = Unknown desc = container "892f4356b7fe3bab92a9f79c45a2d25ae89daffa78dd8a054c030d723746af4b" in namespace "k8s.io": not found
  Warning  ChaosInjectFailed  7m59s (x4 over 18m)  stresschaos-controller  rpc error: code = Unknown desc = container "8f1ba62442a9f909a8f722c9e6da8ba9324b5af7b2a0cd1db9f2c00ace1c4c0f" in namespace "k8s.io": not found
```

**Comment by yeya24** [comment]
@fredleger Hello, I used k3s to inject chaos before. Here you need to set socket path `chaosDaemon.socketPath` to the socket path for your k3s.

I started k3s using k3d, and the containerd socket path is in `/run/k3s/containerd/containerd.sock`. Would you mind taking a look?

**Comment by yeya24** [comment]
Btw thanks for the issue! I believe it is good to document how to use k3s with Chaos Mesh, since it already has many users.

**Comment by fredleger** [comment]
@yeya24 perfect ! It seems to work a lot better except kernelChaos but i guess this is expected since in ran k3s on ubuntu bionic vm with stock kernel

Thanxs for the support
