### ISSUE TITLE
Create networkchaos failed with the reason `i/o timeout`

### ISSUE THREAD

**Issue by del-zhenwu** [chaos-mesh/chaos-mesh#743]
## Bug Report

**What version of Kubernetes are you using?**

**What did you do?**

podchaos can run successfully, but it failed when running networkchaos tests, here is the logs displayed on controller pods:
```
2020-07-27T09:22:51.826Z	INFO	util	Creating client to chaos-daemon	{"node": "test-worker9"}
2020-07-27T09:23:11.811Z	ERROR	controllers.NetworkChaos	flush pod ipset error	{"reconciler": "networkchaos", "action": "partition", "error": "rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial tcp 192.168.1.116:31767: i/o timeout\""}
github.com/go-logr/zapr.(*zapLogger).Error
	/go/pkg/mod/github.com/go-logr/zapr@v0.1.0/zapr.go:128
github.com/chaos-mesh/chaos-mesh/controllers/networkchaos/partition.(*Reconciler).Apply
	/src/controllers/networkchaos/partition/types.go:143
github.com/chaos-mesh/chaos-mesh/controllers/twophase.applyAction
	/src/controllers/twophase/types.go:197
github.com/chaos-mesh/chaos-mesh/controllers/twophase.(*Reconciler).Reconcile
	/src/controllers/twophase/types.go:158
github.com/chaos-mesh/chaos-mesh/controllers/networkchaos.(*Reconciler).scheduleNetworkChaos
	/src/controllers/networkchaos/types.go:91
github.com/chaos-mesh/chaos-mesh/controllers/networkchaos.(*Reconciler).Reconcile
	/src/controllers/networkchaos/types.go:51
github.com/chaos-mesh/chaos-mesh/controllers.(*NetworkChaosReconciler).Reconcile
	/src/controllers/networkchaos_controller.go:56
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:256
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:232
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:211
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1
	/go/pkg/mod/k8s.io/apimachinery@v0.17.1-beta.0/pkg/util/wait/wait.go:152
k8s.io/apimachinery/pkg/util/wait.JitterUntil
	/go/pkg/mod/k8s.io/apimachinery@v0.17.1-beta.0/pkg/util/wait/wait.go:153
k8s.io/apimachinery/pkg/util/wait.Until
	/go/pkg/mod/k8s.io/apimachinery@v0.17.1-beta.0/pkg/util/wait/wait.go:88
2020-07-27T09:23:11.812Z	ERROR	controllers.NetworkChaos	failed to apply chaos action	{"reconciler": "networkchaos", "action": "partition", "error": "rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial tcp 192.168.1.116:31767: i/o timeout\""}
github.com/go-logr/zapr.(*zapLogger).Error
	/go/pkg/mod/github.com/go-logr/zapr@v0.1.0/zapr.go:128
github.com/chaos-mesh/chaos-mesh/controllers/twophase.applyAction
	/src/controllers/twophase/types.go:198
github.com/chaos-mesh/chaos-mesh/controllers/twophase.(*Reconciler).Reconcile
	/src/controllers/twophase/types.go:158
github.com/chaos-mesh/chaos-mesh/controllers/networkchaos.(*Reconciler).scheduleNetworkChaos
	/src/controllers/networkchaos/types.go:91
github.com/chaos-mesh/chaos-mesh/controllers/networkchaos.(*Reconciler).Reconcile
	/src/controllers/networkchaos/types.go:51
github.com/chaos-mesh/chaos-mesh/controllers.(*NetworkChaosReconciler).Reconcile
	/src/controllers/networkchaos_controller.go:56
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:256
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:232
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:211
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1
	/go/pkg/mod/k8s.io/apimachinery@v0.17.1-beta.0/pkg/util/wait/wait.go:152
k8s.io/apimachinery/pkg/util/wait.JitterUntil
	/go/pkg/mod/k8s.io/apimachinery@v0.17.1-beta.0/pkg/util/wait/wait.go:153
k8s.io/apimachinery/pkg/util/wait.Until
	/go/pkg/mod/k8s.io/apimachinery@v0.17.1-beta.0/pkg/util/wait/wait.go:88
2020-07-27T09:23:11.877Z	ERROR	controllers.NetworkChaos	unable to update chaos finalizers	{"reconciler": "networkchaos", "action": "partition", "error": "Operation cannot be fulfilled on networkchaos.chaos-mesh.org \"a-mysql-partition\": StorageError: invalid object, Code: 4, Key: /registry/chaos-mesh.org/networkchaos/chaos-testing/a-mysql-partition, ResourceVersion: 0, AdditionalErrorMsg: Precondition failed: UID in precondition: bec3f2e1-cfea-11ea-bd39-1c1b0d568bc0, UID in object meta: "}
github.com/go-logr/zapr.(*zapLogger).Error
	/go/pkg/mod/github.com/go-logr/zapr@v0.1.0/zapr.go:128
github.com/chaos-mesh/chaos-mesh/controllers/twophase.applyAction
	/src/controllers/twophase/types.go:206
github.com/chaos-mesh/chaos-mesh/controllers/twophase.(*Reconciler).Reconcile
	/src/controllers/twophase/types.go:158
github.com/chaos-mesh/chaos-mesh/controllers/networkchaos.(*Reconciler).scheduleNetworkChaos
	/src/controllers/networkchaos/types.go:91
github.com/chaos-mesh/chaos-mesh/controllers/networkchaos.(*Reconciler).Reconcile
	/src/controllers/networkchaos/types.go:51
github.com/chaos-mesh/chaos-mesh/controllers.(*NetworkChaosReconciler).Reconcile
	/src/controllers/networkchaos_controller.go:56
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:256
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:232
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:211
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1
	/go/pkg/mod/k8s.io/apimachinery@v0.17.1-beta.0/pkg/util/wait/wait.go:152
k8s.io/apimachinery/pkg/util/wait.JitterUntil
	/go/pkg/mod/k8s.io/apimachinery@v0.17.1-beta.0/pkg/util/wait/wait.go:153
k8s.io/apimachinery/pkg/util/wait.Until
	/go/pkg/mod/k8s.io/apimachinery@v0.17.1-beta.0/pkg/util/wait/wait.go:88

```
yaml file:
```
apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: network-partition-example
spec:
  action: partition
  mode: one
  selector:
    namespaces:
      - a
    labelSelectors:
      "app.kubernetes.io/instance": "a"
  direction: to
  target:
    selector:
      namespaces:
        - a
      labelSelectors:
        "app": "a-mysql"
    mode: one
  duration: "10s"
  scheduler:
    cron: "@every 15s"

```
**What did you expect to see?**

**What did you see instead?**

**Comment by YangKeao** [comment]
As I thought there could be two reasons for this error:

1. Some `chaos-daemon` fail to start. You could use `kubectl get pods -n chaos-testing` to check whether every chaos-daemon is running. If someone fails to start, please post the logs and we will try to figure out the reason.

2. The connection between `chaos-daemon` and `controller` is blocked. Do you have any security settings which may block the connection (such as istio config or firewalls on the cluster)?

**Comment by del-zhenwu** [comment]
> As I thought there could be two reasons for this error:
> 
>     1. Some `chaos-daemon` fail to start. You could use `kubectl get pods -n chaos-testing` to check whether every chaos-daemon is running. If someone fails to start, please post the logs and we will try to figure out the reason.
> 
>     2. The connection between `chaos-daemon` and `controller` is blocked. Do you have any security settings which may block the connection (such as istio config or firewalls on the cluster)?

Thanks for your reply.
I have checked the status of the chaos pods, it's all running.
And I can run the same network chaos test at another host successfully.

**Comment by YangKeao** [comment]
`192.168.1.116:31767` is the default grpc port of chaos-daemon which we set in `hostPort` in chaos-daemon's DeamonSet definition. 

The node IP can be verified through `kubectl get nodes -o wide`.

And, you can use `kubectl exec -n chaos-testing -it chaos-controller-manager-POD-NAME -- ping 192.168.99.105` to test whether it is able to send ICMP from controller-manager to this chaos-daemon.

Though the chaos-daemon isn't equipped with enough tools to find network issues, you can install the tools you need with `apk add` or modify the Pod definition to start an ephemeral container (with your favorite docker image). 

There are a lot of issues about `HostPort` not working on kubernetes' repo :sob: . The solution may depend on the CNI plugin, the host firewall, and other kubernetes' configuration, but I don't think it's a bug of `chaos-mesh`.

**Comment by del-zhenwu** [comment]
Thanks, and my issue happened only once, I will follow your advice when it reproduced again

**Comment by del-zhenwu** [comment]
It reproduced when using burn-cpu, chaos-controller-manager can ping successfully, but telnet the ip port failed.
And I start my app using LoadBalancer service type.

**Comment by zhouqiang-cl** [comment]
@YangKeao PTAL

**Comment by zhouqiang-cl** [comment]
Are you using kind to start the cluster? @del-zhenwu 
In my environment, If I the laptop have high load average, It will have `i/o timeout` even if there is no chaos

**Comment by del-zhenwu** [comment]
> Are you using kind to start the cluster? @del-zhenwu
> In my environment, If I the laptop have high load average, It will have `i/o timeout` even if there is no chaos

The cluster started and installed on several servers, not the kind mode

**Comment by zhouqiang-cl** [comment]
> > Are you using kind to start the cluster? @del-zhenwu
> > In my environment, If I the laptop have high load average, It will have `i/o timeout` even if there is no chaos
> 
> The cluster started and installed on several servers, not the `kind` mode

If you do not apply chaos, did it have `i/o timeout` too? You can just try kubectl commands such as `kubectl get xxx`

**Comment by YangKeao** [comment]
> > > Are you using kind to start the cluster? @del-zhenwu
> > > In my environment, If I the laptop have high load average, It will have `i/o timeout` even if there is no chaos
> > 
> > 
> > The cluster started and installed on several servers, not the `kind` mode
> 
> Did you have high load average in this cluster? If you do not apply chaos, did it have `i/o timeout` too? You can just try kubectl commands such as `kubectl get xxx`

Do you mean the high cpu load will affect the network condition? I don't know whether there is a connection between the high cpu load and network failing :sweat_smile: .
