### ISSUE TITLE
Add helm installation on docs

### ISSUE THREAD

**Issue by zhouqiang-cl** [chaos-mesh/chaos-mesh#745]
## Feature Request

**Is your feature request related to a problem? Please describe:**

Add helm installation on docs, there is only install on kind or minikube

**Describe the feature you'd like:**

As title
**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by cwen0** [comment]
https://chaos-mesh.org/docs/installation/installation#install-by-helm

**Comment by cwen0** [comment]
We can close it.
