### ISSUE TITLE
Add Chaos Mesh helm file to https://github.com/helm/hub

### ISSUE THREAD

**Issue by zhouqiang-cl** [chaos-mesh/chaos-mesh#748]
## Feature Request

**Is your feature request related to a problem? Please describe:**

When installing Chaos Mesh, need to [add chaos mesh repository to helm repos](https://chaos-mesh.org/docs/installation/installation#step-1-add-chaos-mesh-repository-to-helm-repos).

**Describe the feature you'd like:**

We can add Chaos Mesh helm file to https://github.com/helm/hub.

**Teachability, Documentation, Adoption, Migration Strategy:**

We need to make sure to update it when we update the local helm file.

**Comment by wuxiaohui94** [comment]
[https://github.com/helm/hub/pull/475](url)
The Helm Hub is going to be deprecated soon,so I add  a repository of Chaos Mesh on https://artifacthub.io/.

**Comment by zhouqiang-cl** [comment]
@wuxiaohui94 thank you
