### ISSUE TITLE
Add experiment name or Id to experiment list item in the dashboard

### ISSUE THREAD

**Issue by werne2j** [chaos-mesh/chaos-mesh#749]
## Feature Request

**Is your feature request related to a problem? Please describe:** No

**Describe the feature you'd like:**

It would be nice if the name or id of the experiment would be displayed on the experiment details list item in the dashboard
<img width="1680" alt="Screen Shot 2020-07-28 at 9 10 04 AM" src="https://user-images.githubusercontent.com/5973248/88669802-5b230800-d0b2-11ea-8731-86ace0ad94e6.png">

**Comment by g1eny0ung** [comment]
Seems that this problem is related to our API changes. Recently we refactored the API fields to lowercase. But the dashboard has not fully adapted to these changes. I will resolve this problem these two days. Thx for reminding!

**Comment by g1eny0ung** [comment]
Fixed in #752.
