### ISSUE TITLE
Support install by brew

### ISSUE THREAD

**Issue by zhouqiang-cl** [chaos-mesh/chaos-mesh#761]
## Feature Request

Chaos Mesh can be installed by brew, such as
```
brew install chaos-mesh
```

**Comment by yeya24** [comment]
Umm, I don't know what is this issue for. Since brew is mostly used on mac, do you want to directly run chaos-mesh on mac?

**Comment by zhouqiang-cl** [comment]
> Umm, I don't know what is this issue for. Since brew is mostly used on mac, do you want to directly run chaos-mesh on mac?

You are right. This issue is not think well, I will think about it later(Now I need to close it)
