### ISSUE TITLE
Add github link and website link in dashboard

### ISSUE THREAD

**Issue by zhouqiang-cl** [chaos-mesh/chaos-mesh#772]
## Feature Request

**Is your feature request related to a problem? Please describe:**

We can add github link and website link in the dashboard(after Archives)

<img width="1742" alt="截屏2020-08-01 下午10 23 35" src="https://user-images.githubusercontent.com/23521459/89103621-ad16b580-d445-11ea-882b-0e00d7173c60.png">

**Comment by g1eny0ung** [comment]
Already resolved.
