### ISSUE TITLE
timeline seems wrong in dashboard

### ISSUE THREAD

**Issue by IamonFireee** [chaos-mesh/chaos-mesh#789]
## Bug Report

**What version of Kubernetes are you using?**

`
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:58:53Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:51:04Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
`
**What did you do?**

created some chaos in chaos-mesh
**What did you expect to see?**
正常工作的时间轴，提供准确的时间信息
**What did you see instead?**
错误的时间轴，横坐标全为相同时间戳，看不到具体的时间信息
![image](https://user-images.githubusercontent.com/20121081/89404383-7514b880-d74c-11ea-8fe8-287605f39fe0.png)

**Comment by g1eny0ung** [comment]
感谢反馈👌🏽，这个页面是 experiment detail 页面的 timeline 吗？

如果是的话，还有一点，进入这个页面是否是通过 events 页面的 table，点击 event detail按钮进入的呢？如果是的话，可能是因为实验已经被归档，导致查询不出来，这个问题的修复工作已经在 PR 了。

**Comment by IamonFireee** [comment]
yes,I can see the detail page and can enter events detail page, it seems this problem has been fixed and i wiil try this again using the new image, thanks for your reply :)
