### ISSUE TITLE
Meaningless retry in reconciler

### ISSUE THREAD

**Issue by YangKeao** [chaos-mesh/chaos-mesh#791]
https://github.com/chaos-mesh/chaos-mesh/blob/8251326fddbf1cc60580da6b0b4d392f4c45f734/controllers/common/types.go#L126-L128

Find this problem while exploring the code. A meaningful conflict retry should be:

1. Fetch the resource

2. Modify the resource

3. Update the resource

If my understanding is correct, only try to update the resource will always be conflict (if it was a conflict for the first time).

**Comment by cwen0** [comment]
@YangKeao Yes, I agree with you.

**Comment by cwen0** [comment]
We can remove the `retry.RetryOnConflict` directly.
