### ISSUE TITLE
how to get experiment execution history?

### ISSUE THREAD

**Issue by qhh0205** [chaos-mesh/chaos-mesh#801]
## Question

Hi, folks, i have created the podchaos experiment by client-go, and the experiment execute periodically. But i don't know how to get the history each execution and then  store each execution info to db? Are there any idea?

**Comment by cwen0** [comment]
@qhh0205 You can get the latest execution info from the status of chaos object. In addition, you also can get this information from the API of Chaos Dashboard. https://github.com/chaos-mesh/chaos-mesh/blob/master/pkg/apiserver/event/event.go#L78

**Comment by qhh0205** [comment]
@cwen0 Thx, I have read the code, if not use the dashboard api, i need to record the event by an independent controller to store the event to db(mysql or sqlite)?

**Comment by fewdan** [comment]
@qhh0205 
If you have installed "dashboard", you can enter the pod corresponding to "chaos-dashboard". In the container, you will see a "core.sqlite" file, which can be accessed through sqlite. Through this db, you can read out the events records.
It should be noted that db sets an expiration time.

**Comment by qhh0205** [comment]
@fewdan I want to store it in MySQL db, if i don't install dashboard, need to external controller list/watch and store to db?

**Comment by fewdan** [comment]
@qhh0205 Sorry, this is temporarily unsupported. Now you can only access events information through the dashboard.

**Comment by qhh0205** [comment]
Ok, i'll write another controller like collector controller to store events into mysql.
