### ISSUE TITLE
How to execute experiment immediately and execute only once, not cron execute?

### ISSUE THREAD

**Issue by qhh0205** [chaos-mesh/chaos-mesh#804]
## Question

How to execute experiment immediately and execute only once, not cron execute?

Now it seems that chao-mesh experiment can only be executed by time scheduler(cron), how to execute experiment immediately, i want to manually execute when I need it.

**Comment by yeya24** [comment]
@qhh0205  If you don't set the `scheduler` and `duration` field, then the chaos should be a one-off job. Can you please try it? 

If that helps then we can close this issue.

**Comment by qhh0205** [comment]
@yeya24 Thanks, you are right! But i think duration filed is needed, because i can controller each experiment execution time duration, after the duration the experiment can be recoverd automatically, now the scheduler and duration field must be ignored simultaneously.

**Comment by yeya24** [comment]
> @yeya24 Thanks, you are right! But i think duration filed is needed, because i can controller each experiment execution time duration, after the duration the experiment can be recoverd automatically, now the scheduler and duration field must be ignored simultaneously.

Yep, I agree with you. Actually I guess https://github.com/chaos-mesh/chaos-mesh/issues/501 is what you want right? If so, we can talk there. :)

**Comment by yeya24** [comment]
Close this issue now.
