### ISSUE TITLE
Label selector does not working

### ISSUE THREAD

**Issue by sbaier1** [chaos-mesh/chaos-mesh#816]
## Bug Report

**What version of Kubernetes are you using?**
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-16T00:04:31Z", GoVersion:"go1.14.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:51:04Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

**What did you do?**
Installed chaos mesh using the command from the website:
`curl -sSL https://raw.githubusercontent.com/chaos-mesh/chaos-mesh/master/install.sh | bash`

**What did you expect to see?**
In the dashboard, i tried starting an experiment. In the Scope view (and in the Target -> Network -> Partition scenario view), i tried entering a label selector, but while the text field works in the first view (Basic), it does not work in the other views. Entering a label selector as specified (`key:value` then pressing space) does not create a label selector but instead does nothing, clicking outside the field again will clear it, making it impossible to create a label selector.

**What did you see instead?**
Label selector creation works the same way on every view.

**Comment by g1eny0ung** [comment]
The `label selectors` in the scope step won't be created from yourself. The scope means you will apply the experiment into **this scope**.

For example, we can create a test deployment with:

`kubectl create deployment echoserver --image=registry.cn-hangzhou.aliyuncs.com/google_containers/echoserver:1.10`

Then you can select the `label selector` like this image shows:

![image](https://user-images.githubusercontent.com/15034155/90231288-89903980-de4d-11ea-9f62-ba0fde96a7bb.png)

After you selected, the experiment will know it will affect the pods with this `label selector`.

**Comment by sbaier1** [comment]
thanks for the explanation. For some reason, the autocompletion didn't work initially and didn't show any labels / pods. Does work now.
