### ISSUE TITLE
Documents could be more friendly for users in mainland China.

### ISSUE THREAD

**Issue by ClSlaid** [chaos-mesh/chaos-mesh#823]
As a zero-knowledged beginner it's nice to know such an awesome project. However while closely following your documents, I still have come up with some annoying problems. I think by inserting contents in your documents as below, would surely make your documents more friendly.
# Add Proxy/Mirror Recommendations
*GitHub* is getting less and less accessible in mainland China now. Adding such recommendations do decrease time wasted on toying with networks.
`K8s` and its relatives are victims of national fire walls. looking for mirrors do stressed out my patience and confidence.
# Chinese Documents
No matter traditional or simplified, though your docs are short, clear and really not difficult to understand, I think it is still necessary to support other languages.

**Comment by zhouqiang-cl** [comment]
@ClSlaid Thank you for your advice, I think it is very necessary. And we will refine the document's structure and try to l10n the document. And then, we will try to make it more smooth  in mainland China(a few days ago, we start to push docker image in aliyun)

**Comment by g1eny0ung** [comment]
🚀 The website was moved to https://github.com/chaos-mesh/website!  Please submit subsequent changes at the new repo.

I will close this issue for now and if there have any questions, feel free to reopen it.
