### ISSUE TITLE
Inconsistent from doc and chart yaml

### ISSUE THREAD

**Issue by Colstuwjx** [chaos-mesh/chaos-mesh#849]
## Bug Report

**What version of Kubernetes are you using?**

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-16T00:04:31Z", GoVersion:"go1.14.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.7", GitCommit:"be3d344ed06bff7a4fc60656200a93c74f31f9a4", GitTreeState:"clean", BuildDate:"2020-02-11T19:24:46Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
```

**What did you do?**
Install chaos mesh with helm by manually.

**What did you expect to see?**
Just as the doc said, I want to install dashboard as well.

**What did you see instead?**
But I found it only installed daemon and controller-manager:

```
➜  ~ kubectl get pods --namespace chaos-testing
NAME                                       READY   STATUS    RESTARTS   AGE
chaos-controller-manager-bb67cb68f-p9rjf   1/1     Running   0          14m
chaos-daemon-vjsv7                         1/1     Running   0          14m
```

And I checked the repo code, it seems that we set the dashboard create option [default to false](https://github.com/chaos-mesh/chaos-mesh/blob/master/helm/chaos-mesh/values.yaml#L100), we may need to update our doc page as well!

**Comment by yeya24** [comment]
I don't find any inconsistency in the document, can you please point me to the doc you mentioned?

I believe it is already clearly mentioned in the installation doc https://chaos-mesh.org/docs/installation/installation#step-3-install-chaos-mesh.

![Screenshot from 2020-08-25 23-30-36](https://user-images.githubusercontent.com/25150124/91252170-03b49e00-e72b-11ea-9120-b9e9b4443631.png)

But I agree it is time to make dashboard installation default to true in our chart, as it is enabled in the script currently.

**Comment by Colstuwjx** [comment]
From the doc page, it told me that expected output would be:

![image](https://user-images.githubusercontent.com/3972545/91252511-507e9000-e790-11ea-9b06-6355aeed71bc.png)

And as you said, there is a note that told us the dashboard is default to false, so I think that the word `Expected output:` and the output result should be updated as well. This is the inconsistency point.

> But I agree it is time to make dashboard installation default to true in our chart, as it is enabled in the script currently.

Yes, this is another issue, and I will be happy to do this.

**Comment by yeya24** [comment]
If you think this part is kind of misleading, again feel free to open a pr to update it. I think moving this note to the beginning of step 3 is good enough and clear.
