### ISSUE TITLE
The chaosfs-sidecar.yaml is wrong when I use it to do IOChaos experiment

### ISSUE THREAD

**Issue by 1964405262** [chaos-mesh/chaos-mesh#859]
## Bug Report

I use kubectl with client version v1.18.6 and server version v1.15.0. The branch of chaos-mesh is master.  When I do IOChaos experiment followed by[ this instruction ](https://chaos-mesh.org/docs/user_guides/iochaos_experiment#available-methods) , I found error msg in kube-controller-manager like this: 

   E0826 23:04:18.192321       1 replica_set.go:450] Sync "chaos-testing/ioapp-7556c69f46" failed with Pod "ioapp-7556c69f46-8r4rd" is invalid: [spec.containers[0].volumeMounts[4].name: Not found: "ioapp", 

   After checking , I found there's lack of  volume config in  chaos-mesh/manifests/chaosfs-sidecar.yaml 
  volumes:
    - name: scripts
      emptyDir: {}
    - name: fuse
      emptyDir: {}
    **- name: {{.VolumeName}}
      emptyDir: {}**

After adding  the last two lines config , I have resolved this problem .

**Comment by yeya24** [comment]
Hello @1964405262, thanks for the issue!

First of all, can you please provide more information about your setup and the yaml you are using? I need to double check the `ioapp` volume.

IIUC, is the `ioapp` volume the datadir volume of your app? If it is this case, then this volume should be added to your application's yaml (deployment/statefulset), and it is not necessary to add it to the template yaml file.

You can find an example for etcd. https://github.com/chaos-mesh/chaos-mesh/blob/release-0.9/examples/etcd/etcd.yaml https://github.com/chaos-mesh/chaos-mesh/blob/release-0.9/examples/etcd/etcd-configmap.yaml

**Comment by 1964405262** [comment]
@yeya24   I checked by deployment yaml file and found that there is no volumeMounts in it . 

apiVersion: apps/v1                                                                                                                                                                                                            
kind: Deployment
metadata:
  name: ioapp
  namespace: chaos-testing
  labels:
    app: ioapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ioapp
  template:
    metadata:
      labels:
        app: ioapp
      annotations: 
        "admission-webhook.chaos-mesh.org/request": "chaosfs-ioapp"
    spec:
      containers:
        - name: ioapp
          imagePullPolicy: Always         
          image: 172.18.194.251:5000/ioapp:v1 
          command: ["/usr/local/bin/ioapp"]
      volumes: 
        - emptyDir: {}
          name: datadir

I will follow your etcd example and check again . Thank you so much.
