### ISSUE TITLE
Specifying fieldSelectors in PodChaos causes an error

### ISSUE THREAD

**Issue by masayag** [chaos-mesh/chaos-mesh#878]
## Bug Report

**What version of Kubernetes are you using?**
Client Version: 4.4.11
Server Version: 4.6.0-0.nightly-2020-08-31-220837
Kubernetes Version: v1.19.0-rc.2+f71a7ab-dirty

**What did you do?**
I used the 'fieldSelectors' in selector element of the PodChaos resource in order to select a pod.

The following request was applied:
```
apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: control-plance-pod-failure
  namespace: chaos-testing
spec:
  action: pod-failure
  mode: one
  value: ""
  duration: "30s"
  selector:
    namespaces:
      - "openshift-kube-apiserver"
    labelSelectors:
      "app": "openshift-kube-apiserver"
      "apiserver": "true"
    fieldSelectors:
      "metadata.name": "kube-apiserver-test-infra-cluster-master-1"
  scheduler:
    cron: "@every 2m"
```
When using kubectl with 'fieldSelectors', the response is valid:
```
oc get pods -n openshift-kube-apiserver --field-selector  metadata.name=kube-apiserver-test-infra-cluster-master-1
NAME                                         READY   STATUS    RESTARTS   AGE
kube-apiserver-test-infra-cluster-master-1   5/5     Running   0          11m
```

**What did you expect to see?**
I'd expect a pod named 'kube-apiserver-test-infra-cluster-master-1' to be the target of the failure.

**What did you see instead?**
The podchaos resource was created, but produced an error:
```
oc describe podchaos -n chaos-testing control-plance-pod-failure
...
Spec:
  Action:          pod-failure
  Container Name:  
  Duration:        30s
  Grace Period:    0
  Mode:            one
  Scheduler:
    Cron:  @every 2m
  Selector:
    Field Selectors:
      metadata.name:  kube-apiserver-test-infra-cluster-master-1
    Label Selectors:
      Apiserver:  true
      App:        openshift-kube-apiserver
    Namespaces:
      openshift-kube-apiserver
  Value:  
Status:
  Experiment:
    Phase:  Failed
  Phase:    
  Scheduler:
Events:
  Type     Reason             Age                From                 Message
  ----     ------             ----               ----                 -------
  Warning  ChaosInjectFailed  1s (x14 over 42s)  podchaos-controller  Index with name field:metadata.name does not exist
```
And the following exception was logged in the chaos controller:
```
2020-09-07T22:54:13.356Z        ERROR   controllers.PodChaos    failed to select and filter pods        {"reconciler": "podchaos", "action": "pod-failure", "error": "Index with name field:metadata.name does not exist"}
github.com/go-logr/zapr.(*zapLogger).Error
        /go/pkg/mod/github.com/go-logr/zapr@v0.1.0/zapr.go:128
github.com/chaos-mesh/chaos-mesh/controllers/podchaos/podfailure.(*Reconciler).Apply
        /src/controllers/podchaos/podfailure/types.go:89
github.com/chaos-mesh/chaos-mesh/controllers/twophase.applyAction
        /src/controllers/twophase/types.go:197
github.com/chaos-mesh/chaos-mesh/controllers/twophase.(*Reconciler).Reconcile
        /src/controllers/twophase/types.go:158
github.com/chaos-mesh/chaos-mesh/controllers/podchaos.(*Reconciler).schedulePodChaos
        /src/controllers/podchaos/types.go:90
github.com/chaos-mesh/chaos-mesh/controllers/podchaos.(*Reconciler).Reconcile
        /src/controllers/podchaos/types.go:51
github.com/chaos-mesh/chaos-mesh/controllers.(*PodChaosReconciler).Reconcile
        /src/controllers/podchaos_controller.go:56
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:256
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:232
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:211
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1
        /go/pkg/mod/k8s.io/apimachinery@v0.17.1-beta.0/pkg/util/wait/wait.go:152
k8s.io/apimachinery/pkg/util/wait.JitterUntil
        /go/pkg/mod/k8s.io/apimachinery@v0.17.1-beta.0/pkg/util/wait/wait.go:153
k8s.io/apimachinery/pkg/util/wait.Until
        /go/pkg/mod/k8s.io/apimachinery@v0.17.1-beta.0/pkg/util/wait/wait.go:88
2020-09-07T22:54:13.356Z        ERROR   controllers.PodChaos    failed to apply chaos action    {"reconciler": "podchaos", "action": "pod-failure", "error": "Index with name field:metadata.name does not exist"}
github.com/go-logr/zapr.(*zapLogger).Error
        /go/pkg/mod/github.com/go-logr/zapr@v0.1.0/zapr.go:128
github.com/chaos-mesh/chaos-mesh/controllers/twophase.applyAction
        /src/controllers/twophase/types.go:198
github.com/chaos-mesh/chaos-mesh/controllers/twophase.(*Reconciler).Reconcile
        /src/controllers/twophase/types.go:158
github.com/chaos-mesh/chaos-mesh/controllers/podchaos.(*Reconciler).schedulePodChaos
        /src/controllers/podchaos/types.go:90
github.com/chaos-mesh/chaos-mesh/controllers/podchaos.(*Reconciler).Reconcile
        /src/controllers/podchaos/types.go:51
github.com/chaos-mesh/chaos-mesh/controllers.(*PodChaosReconciler).Reconcile
        /src/controllers/podchaos_controller.go:56
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:256
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:232
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:211
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1
        /go/pkg/mod/k8s.io/apimachinery@v0.17.1-beta.0/pkg/util/wait/wait.go:152
k8s.io/apimachinery/pkg/util/wait.JitterUntil
        /go/pkg/mod/k8s.io/apimachinery@v0.17.1-beta.0/pkg/util/wait/wait.go:153
k8s.io/apimachinery/pkg/util/wait.Until
        /go/pkg/mod/k8s.io/apimachinery@v0.17.1-beta.0/pkg/util/wait/wait.go:88
```

**Comment by fewdan** [comment]
Please wait a while, I will pay attention to this issue.

**Comment by yeya24** [comment]
As I commented on Slack, since `controller-runtime` uses a cached client, we need to create index fields manually when initializing controller.

TBH this approach is not flexible and not scalable, since we cannot create indexes for all the pod fields. We might have two options here:
1. Remove fieldSelector. It is not necessary to have it as we already have some other powerful selectors.
2. Create indexes for some common fields that might be used by users. The key point here is that it is hard to define what fields do we want to index, and I think most useful fields are already queryable by other selectors.

My idea is to go to the first option, what do you think? @fewdan @cwen0

**Comment by yeya24** [comment]
@masayag Using `metadata.name` here to select pods is not the best option here because pod name changes after restarting. Also you could use `pods` field to specify the pods you want to inject chaos.

**Comment by fewdan** [comment]
@yeya24 
![image](https://user-images.githubusercontent.com/16437100/92487915-7ab85f00-f220-11ea-9a07-f19cb56877c1.png)

I think it is possible to manually initialize the fields in the above figure and add the index into the cache.

**Comment by fewdan** [comment]
Like this :
```
cache := mgr.GetCache()
	indexFunc := func(obj runtime.Object) []string {
		return []string{obj.(*v1.Pod).Name}
	}

	if err := cache.IndexField(&v1.Pod{}, "metadata.name", indexFunc); err != nil {
		panic(err)
	}
```

**Comment by yeya24** [comment]
> **Create indexes for some common fields that might be used by users. The key point here is that it is hard to define what fields do we want to index, and I think most useful fields are already queryable by other selectors.**

Yes, it is doable and I already mentioned it in my previous comment. What I was saying is that this is not really necessary to do and it is hard to find common indexes we want to have.

We already have node filters, namespace filter, phase filters, podsFilter, I believe these filters already cover most cases when selecting pods. For the fields we haven't supported yet, I don't think we want to select pods filtering by `restartPolicy`, `schedulerName` or `serviceAccountName`, etc. The usecase is rare. Considering this, might be not useful to support fieldSelector.

**Comment by yeya24** [comment]
Another option might be to create these indexes. For the filters we have currently like namespaces, pods, phase, we convert them all to fieldSelector in the ListOptions when querying and remove the old logic, which requires manually filtering. This approach might make more sense, but need some more refactoring and I am not sure it is 100% compatible with the current code.

**Comment by fewdan** [comment]
@yeya24 
I understand what you mean. My idea is that there is a bug now, so we should make this fieldSelector usable first, and then discuss refactoring.

**Comment by yeya24** [comment]
I am not saying to not fix this:) Just some ideas about this config.

Anyways, feel free to open a pr to fix this. Thanks!👍

**Comment by yeya24** [comment]
I am not saying to not fix this:) Just some ideas about this config.

Anyways, feel free to open a pr to fix this. Thanks!👍

**Comment by fewdan** [comment]
Oh, understand.

**Comment by yeya24** [comment]
Great work @fewdan. This should be fixed already and I will close this issue.
