### ISSUE TITLE
How to integrate thirdparty service into chaos mesh

### ISSUE THREAD

**Issue by Colstuwjx** [chaos-mesh/chaos-mesh#884]
Hi team,

Chaos mesh is a great platform for doing chaos testing, however, it's limited in k8s ecosystem. Just think the following case:

1. we need to do experiment on our services, to confirm multi-idc ha is ready or not;
2. chaos mesh could do pod-kill with web apps on one datacenter ( a.k.a a k8s cluster );
3. we want to make database or redis down for testing the database failover, but **chaos-mesh did NOT support such operation**

The question is how to make step 3 also integrate with chaos-mesh, we may did have db paas such devops tool, so shall we add a feature for chaos-mesh that we could did HTTP call in an experiment, to make db down also happens?

Thanks.

**Comment by Colstuwjx** [comment]
Related issue: #879 , to be honest, for this issue, I don't want to deploy chaos daemon on my db paas hosts, since we already setup a process for vms ( e.g. using ansible to archive this ).

**Comment by zhouqiang-cl** [comment]
Hi, @Colstuwjx could you add my WeChat, I want to discuss it with you. My WeChat id is flicket

**Comment by YangKeao** [comment]
still valid

I believe plugin or any integration mechanism is really important for Chaos Mesh to build a chaos ecosystem.
