### ISSUE TITLE
admission webhook "mpodchaos.kb.io" denied the request

### ISSUE THREAD

**Issue by IamonFireee** [chaos-mesh/chaos-mesh#889]
## Bug Report

**What version of Kubernetes are you using?**

Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:12:48Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:04:18Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

**What did you do?**

try to create a pod failure with yaml:

apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: pod-failure-example
  namespace: chaos-testing
spec:
  action: pod-failure
  mode: one
  value: ""
  duration: "30s"
  selector: 
    labelSelectors:
      namespaces:
      - "default" 
      "app": "proxy" 
  scheduler:
    cron: "@every 2m"

**What did you expect to see?**
chaospod created successfully
**What did you see instead?**

Error from server: error when creating "pod_failure.yaml": admission webhook "mpodchaos.kb.io" denied the request: v1alpha1.PodChaos.Spec: v1alpha1.PodChaosSpec.Selector: v1alpha1.SelectorSpec.LabelSelectors: ReadString: expects " or n, but found [, error found in #10 byte of ...|espaces":["default"]|..., bigger context ...|r":{"labelSelectors":{"app":"proxy","namespaces":["default"]}},"value":""}}|...

it seems like something goes wrong when server try to parse the request but i have no idea about what happened when i apply the experiment

by the way, when i trying to create experiment on the dashboard:
![image](https://user-images.githubusercontent.com/20121081/92568092-3aed8800-f2b1-11ea-834b-9a3266efc9fc.png)
it happened when i chose the scope of this experiment

![image](https://user-images.githubusercontent.com/20121081/92568399-b18a8580-f2b1-11ea-90e4-80a31690efd0.png)
it happened when i set the cron like "0 0 * * * *", and the experiment cant be created 

im new of k8s, so maybe something wrong in my k8s cluster? but everything seems running normally.....

**Comment by g1eny0ung** [comment]
The error of `annotation_selectors` should be resolved in https://github.com/chaos-mesh/chaos-mesh/pull/881 at yesterday.

And the error of `cron` I guess because we used cron library is https://pkg.go.dev/mod/github.com/robfig/cron/v3, which doesn't support the year field. You can correct with `0 0 * * *`.
