### ISSUE TITLE
Mode naming made me confused

### ISSUE THREAD

**Issue by Colstuwjx** [chaos-mesh/chaos-mesh#893]
## Feature Request

**Is your feature request related to a problem? Please describe:**

For example, for NetworkChaos, there is [network partition example](https://chaos-mesh.org/docs/user_guides/networkchaos_experiment#network-partition-action) in our doc, and we proposed mode and value for controlling the pod target. But I sadly found that we describe the mode with a line word `mode defines the mode to run chaos action.`, TBH, I didn't know what's the meaning of this.

BTW, it seems that we did have two `mode` inside `NetworkChaos`, are they same thing or not?

```
apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
...
spec:
  action: partition
  mode: one
  ...
  target:
    ...
    mode: one
    ...
```

**Describe the feature you'd like:**

Update the docs, just like [PodChaos](https://chaos-mesh.org/docs/user_guides/podchaos_experiment#pod-failure-configuration-file) did.

**Describe alternatives you've considered:**

Or we could change the wording, make it more clear, `mode` and `value` is too ambiguous...

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by YangKeao** [comment]
@cwen0 `mode`, `value` and `selectors` are all selector related fields. I think they should be placed in one field (but not 3). This will make the document better to understand and simplify our validator.

Modifying resource definition is not a good idea at this timing (before releasing 1.0), but we should consider it in the later version.

At least, we can refine the document. :smile_cat:

**Comment by cwen0** [comment]
> @cwen0 `mode`, `value` and `selectors` are all selector related fields. I think they should be placed in one field (but not 3). This will make the document better to understand and simplify our validator.
> 
> Modifying resource definition is not a good idea at this timing (before releasing 1.0), but we should consider it in the later version.
> 
> At least, we can refine the document. 😸

@YangKeao I agree with you. @WangXiangUSTC Can you help tp update the document and make it more clear?
