### ISSUE TITLE
No Daemon Created

### ISSUE THREAD

**Issue by NarzeusNabartey** [chaos-mesh/chaos-mesh#899]
I have successfully installed Chaos-mesh in my local environment

<img width="559" alt="Screen Shot 2020-09-14 at 1 09 03 PM" src="https://user-images.githubusercontent.com/53075732/93046405-49121e80-f68c-11ea-88bd-3bc825a9a43d.png">

However in my private cluster in cloud chaos-daemon pod didn't spawned.
<img width="542" alt="Screen Shot 2020-09-14 at 1 12 09 PM"
 src="https://user-images.githubusercontent.com/53075732/93046477-78c12680-f68c-11ea-86d4-dcc2043ac655.png">

What am i missing here. 

Thank you so much for your reply.

**Comment by cwen0** [comment]
@NarzeusNabartey Can you check the `Taint` on your Kubernetes nodes?  You can refer to https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/. In addition, Can you make sure your Kubernetes nodes allow Daemonset pod to run on them?

**Comment by NarzeusNabartey** [comment]
Hi cwen0. Thank you for your prompt reply. I looked into the daemonset that is supposed to be created in the chaos-testing namespace and i saw this:

<img width="633" alt="Screen Shot 2020-09-14 at 4 10 35 PM" src="https://user-images.githubusercontent.com/53075732/93060554-d724df80-f661-11ea-894e-865f7482eaff.png">

I described it and it has this error:

<img width="1665" alt="Screen Shot 2020-09-14 at 4 04 33 PM" src="https://user-images.githubusercontent.com/53075732/93060235-5e258800-f661-11ea-8046-4bc023b0c7ed.png">

What do you think is the problem here. Thank you.

**Comment by NarzeusNabartey** [comment]
Solved It. I need to privileged scc to default. 

```
oc adm policy add-scc-to-user privileged -n chaos-testing -z default
``` 

Thank you so much.

**Comment by Gallardot** [comment]
> Solved It. I need to add privileged scc to default.
> 
> ```
> oc adm policy add-scc-to-user privileged -n chaos-testing -z default
> ```
> 
> Thank you so much.

Thank you @NarzeusNabartey . We can update this solution to the FAQ for OpenShift users. 😁
