### ISSUE TITLE
Illegal Limit Error Message

### ISSUE THREAD

**Issue by NarzeusNabartey** [chaos-mesh/chaos-mesh#900]
## Bug Report

**What version of Kubernetes are you using?**

Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:13:54Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:51:04Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

**What did you do?**

Successfully installed chaos-mesh using this documentation https://chaos-mesh.org/docs/installation/installation.
I also successfully created Experiments: PodChaos, NetworkChaos. However ,in NetworkChaos, only delay and bandwidth is working. I am getting errors in loss, duplicated and corrupt

This is my sample yaml file:

<img width="271" alt="Screen Shot 2020-09-14 at 1 39 51 PM" src="https://user-images.githubusercontent.com/53075732/93047769-cbe8a880-f68f-11ea-8a3a-46e082a431fe.png">

**What did you expect to see?**
Expected to see a Success error like my other experiments
<img width="1534" alt="Screen Shot 2020-09-14 at 1 41 51 PM" src="https://user-images.githubusercontent.com/53075732/93047901-26820480-f690-11ea-94c8-e4aea6370060.png">

**What did you see instead?**
I am getting these kind of error
<img width="1679" alt="Screen Shot 2020-09-14 at 1 44 02 PM" src="https://user-images.githubusercontent.com/53075732/93047994-677a1900-f690-11ea-9d04-a63016c40b4c.png">

**Comment by YangKeao** [comment]
Can you tell me the version of chaos-mesh? You can get it through:

```
kubectl exec -n chaos-testing chaos-controller-manager-XXXXXXX -- /usr/local/bin/chaos-controller-manager -version
```

**Comment by NarzeusNabartey** [comment]
Hi YangKeao. Thank you so much for the prompt reply. I upgraded the version to 0.9.1 and is now working. Many thanks.

**Comment by YangKeao** [comment]
Great! I will close this issue as it has been solved. If you have more question, feel free to reopen it :smile_cat:

**Comment by NarzeusNabartey** [comment]
Hi YangKeao. The upgrade works in my local environment. However, when i applied it to out devtest environment in cloud, i am getting this error:
<img width="1307" alt="Screen Shot 2020-09-14 at 8 19 08 PM" src="https://user-images.githubusercontent.com/53075732/93085147-b3948000-f6c7-11ea-8b48-36c454218bbf.png">

Thank you for your reply.

**Comment by YangKeao** [comment]
@NarzeusNabartey Can you give me a longer screenshot (which should contain the backtrace below)?

And the version information of the chaos-mesh installed on this environment could also help a lot. You can get it through:

```
kubectl exec -n chaos-testing chaos-controller-manager-XXXXXXX -- /usr/local/bin/chaos-controller-manager -version
```

Just like what you have done on your local environment.

A possible workaround of this issue could be adding a direction field in the yaml.

```
spec:
    direction: to
    ....
```

We have set up a webhook to give the direction a default value ("to"), but it seems that this webhook didn't work well in your devtest environment :man_facepalming:

**Comment by YangKeao** [comment]
```
kubectl get MutatingWebhookConfiguration
```

This command will show all the mutating webhook installed on the cluster. You can use it to verify whether the webhook of chaos-mesh has been installed on your cluster.

**Comment by NarzeusNabartey** [comment]
Hi YangKeao. This is in our devtest env.

chaos-mesh version:
```
Controller manager Version: version.Info{GitVersion:"v0.9.1", GitCommit:"0251df1b1bc3ce72b66a4fd86372471f3f7e8cf8", BuildDate:"2020-09-03T03:46:39Z", GoVersion:"go1.14.4", Compiler:"gc", Platform:"linux/amd64"}
```
Traceback:
<img width="1673" alt="Screen Shot 2020-09-16 at 3 57 32 PM" src="https://user-images.githubusercontent.com/53075732/93309384-0e4bea00-f836-11ea-8f04-e25b3229d225.png">

network-delay.yaml
<img width="473" alt="Screen Shot 2020-09-16 at 3 57 47 PM" src="https://user-images.githubusercontent.com/53075732/93309522-32a7c680-f836-11ea-9606-0c17162071ad.png">

MutatingWebhook
<img width="380" alt="Screen Shot 2020-09-16 at 3 55 37 PM" src="https://user-images.githubusercontent.com/53075732/93309581-46ebc380-f836-11ea-82f6-8b7aec5b5e58.png">

We are very excited to test this out in our devtest and UAT environments. Hope to get this working.

Many thanks and more power.

**Comment by YangKeao** [comment]
@NarzeusNabartey Have you tried deleting and reapplying this networkchaos? It could happen if you have applied this chaos before starting up current version of chaos-mesh.

> `kubectl edit` this chaos and add `direction: to` in specification 

Does this solution work?

**Comment by NarzeusNabartey** [comment]
Hi YangKeao. Thank you for your answer. Adding direction: to in my yaml file makes it work.

<img width="315" alt="Screen Shot 2020-09-17 at 11 01 52 AM" src="https://user-images.githubusercontent.com/53075732/93415067-3b9ba500-f8d5-11ea-9533-652e4733664a.png">

Closing this issue. Will keep you guys posted on the progresses that we made. Great Job.
