### ISSUE TITLE
The config watcher in pkg/webhook is hard to understand

### ISSUE THREAD

**Issue by Andrewmatilde** [chaos-mesh/chaos-mesh#905]
I think the watcher of sidecar was too heavy to understand. It had written for things far more than watching the config, mainly because the config was rendered from template.

I think render the config in watcher was not a good idea, the render may be moved out  as a single utile , then the chaos or controller may use it.This idea may from istio , but istio has a lot of render functions ,and there have a lot of arguements in sidecar to be rendered.

And if there are any methods to instead the request method of polling every 3 second in watcher??

**Comment by cwen0** [comment]
@Andrewmatilde We will delete the sidecar in this pr #826

**Comment by Andrewmatilde** [comment]
@cwen0 Thanks for reply. I am a little confused about how the new iochaos implement works. I am working on HttpChaos it will used sidecar(image of envoy) to transfer the HTTP package. If I could use the same way to instead the sidecar or I could written my own injector implement??

**Comment by YangKeao** [comment]
@Andrewmatilde We can switch network namespace manually to replace the sidecar. The only difference between running binary in `chaos-daemon` directly and running binary in the sidecar is that the namespace of them differ.

For a go program, switching namespace internally (through `setns` system call) is a little difficult, so we can use `nsenter`. You can use `bpm` pkg in #826 ([example](https://github.com/YangKeao/chaos-mesh/blob/bffb445992f74f40cc39c9f9504bec48ac65c9c0/pkg/chaosdaemon/iptables_server.go#L208)), or use the process builder in master ([example](https://github.com/YangKeao/chaos-mesh/blob/bffb445992f74f40cc39c9f9504bec48ac65c9c0/pkg/chaosdaemon/iptables_server.go#L208)).

The biggest problem for entering namespace but not using sidecar is that there is no way to control our privilege. The Kubernetes can restrict `chaos-mesh`'s sidecar through RBAC, but the only switch of `setns` is the `privileged` field for `chaos-daemon`. It will turn from a more detailed privilege control into a binary rough privilege control.

**Comment by Andrewmatilde** [comment]
@YangKeao Thanks for your rely!! I think that's a great work , I will try it.
