### ISSUE TITLE
question about kubeconfig

### ISSUE THREAD

**Issue by nkguoym** [chaos-mesh/chaos-mesh#907]
## Question
hi, chaos-mesh team. I am very excited when I find this project. I am very interested in chaos engineering.
But I am confused whether chaos-mesh has been run on production env?  because I think if run it on production env, we need to get the kubeconfig of production k8s cluster(If I understand wrong, correct me).

**Comment by zhouqiang-cl** [comment]
Hi @nkguoym 
In some community users (TOP 5 internet company in China) using Chaos Mesh in production env. But most of our community users use it in testing env. 

But even in testing env, they also need kubeconfig file(not in kind and minikube env)
