### ISSUE TITLE
Error:Post https://chaos-mesh-controller-manager.chaos-testing.svc:443/mutate-chaos-mesh-org-v1alpha1-podchaos?timeout=30s: x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "chaos-mesh-controller-manager.chaos-testing.svc")

### ISSUE THREAD

**Issue by sbhaita** [chaos-mesh/chaos-mesh#918]
## Bug Report

**What version of Kubernetes are you using?**
Kubernes 16.4

**What did you do?**
Installed chaos-mesh with standard installation script
# curl -sSL https://raw.githubusercontent.com/chaos-mesh/chaos-mesh/master/install.sh | bash

Install Chaos Mesh chaos-mesh
customresourcedefinition.apiextensions.k8s.io/httpchaos.chaos-mesh.org configured
customresourcedefinition.apiextensions.k8s.io/iochaos.chaos-mesh.org configured
customresourcedefinition.apiextensions.k8s.io/kernelchaos.chaos-mesh.org configured
customresourcedefinition.apiextensions.k8s.io/networkchaos.chaos-mesh.org configured
customresourcedefinition.apiextensions.k8s.io/podchaos.chaos-mesh.org configured
customresourcedefinition.apiextensions.k8s.io/podnetworkchaos.chaos-mesh.org configured
customresourcedefinition.apiextensions.k8s.io/stresschaos.chaos-mesh.org configured
customresourcedefinition.apiextensions.k8s.io/timechaos.chaos-mesh.org configured
namespace/chaos-testing unchanged
serviceaccount/chaos-controller-manager unchanged
secret/chaos-mesh-webhook-certs configured
clusterrole.rbac.authorization.k8s.io/chaos-mesh:chaos-controller-manager configured
clusterrolebinding.rbac.authorization.k8s.io/chaos-mesh:chaos-controller-manager unchanged
service/chaos-dashboard created
service/chaos-mesh-controller-manager created
daemonset.apps/chaos-daemon created
deployment.apps/chaos-dashboard created
deployment.apps/chaos-controller-manager created
mutatingwebhookconfiguration.admissionregistration.k8s.io/chaos-mesh-mutation configured
validatingwebhookconfiguration.admissionregistration.k8s.io/chaos-mesh-validation configured
configmap/chaosfs-sidecar created

**What did you expect to see?**
Tried to run a simple KillPod Choas test..Getting the following error. The same choas-test works with an older version of choas-mesh

Error from server (InternalError): error when creating "kill-alertmanager.yaml": Internal error occurred: failed calling webhook "mpodchaos.kb.io": Post https://chaos-mesh-controller-manager.chaos-testing.svc:443/mutate-chaos-mesh-org-v1alpha1-podchaos?timeout=30s: x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "chaos-mesh-controller-manager.chaos-testing.svc")

**What did you see instead?**

This chaos-test should work

**Comment by zhouqiang-cl** [comment]
@cwen0 @YangKeao PTAL

**Comment by cwen0** [comment]
@sbhaita I guess that this issue is caused by the old configure of Chaos Mesh. You did not clean up the old version of the configuration. You can run the following commands to reinstall: 

```
curl -sSL https://mirrors.chaos-mesh.org/latest/install.sh | bash -s -- --template | kubectl delete -f - 

## delete the old configuration, because we have rename them in latest version.
kubectl get mutatingwebhookconfiguration | grep chaos | awk {'print $1'} | xargs -I {} kubectl detele mutatingwebhookconfiguration {} 
kubectl get validatingwebhookconfiguration | grep chaos | awk {'print $1' | xargs -I {} kubectl detele validatingwebhookconfiguration {} 
curl -sSL https://mirrors.chaos-mesh.org/latest/install.sh | bash
```

**Comment by sbhaita** [comment]
Thank you for your feedback...I will give this a try and will get back to you

**Comment by cwen0** [comment]
@sbhaita Is this issue fixed?

**Comment by blencoff** [comment]
@sbhaita 
I've faced with the same issue
```
kc apply -f network-loss.yaml
Error from server (InternalError): error when creating "network-loss.yaml": Internal error occurred: failed calling webhook "mnetworkchaos.kb.io": Post https://chaos-mesh-controller-manager.chaos-testing.svc:443/mutate-chaos-mesh-org-v1alpha1-networkchaos?timeout=30s: x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate 
authority certificate "chaos-mesh-controller-manager.chaos-testing.svc")

kc apply -f pod-kill.yaml
Error from server (InternalError): error when creating "pod-kill.yaml": Internal error occurred: failed calling webhook "mpodchaos.kb.io": Post https://chaos-mesh-controller-manager.chaos-testing.svc:443/mutate-chaos-mesh-org-v1alpha1-podchaos?timeout=30s: x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "chaos-mesh-controller-manager.chaos-testing.svc")
```
Solution with clean up has solved the problem, there was an old `mutatingwebhookconfiguration` that had prevents to create any experiment.
