### ISSUE TITLE
CI Error: License compliance not happy

### ISSUE THREAD

**Issue by Colstuwjx** [chaos-mesh/chaos-mesh#919]
## Bug Report

**What did you expect to see?**
Every PR should pass License compliance check.

**What did you see instead?**
There is license compliance error inside PR, for example, [this one](https://app.fossa.com/projects/git%2Bgithub.com%2Fchaos-mesh%2Fchaos-mesh/refs/branch/master/5e5280e0fbcc9234e3eeda7c66b64980b5f59137), and [this one](https://app.fossa.com/projects/git%2Bgithub.com%2Fchaos-mesh%2Fchaos-mesh/refs/branch/master/8ce400a4eb83ece39dbd28d4f5a013850bbf9f84).

I've noticed that this issue comes starting from PR #904 : 

![image](https://user-images.githubusercontent.com/3972545/93411330-7f8aac00-f8cd-11ea-99a1-6d1dc5268637.png)

BTW, I don't think PR #904 content has any relative problem for introducing this issue, we may need to dive into the CI error and find out the root cause.

**Comment by YangKeao** [comment]
I have removed this CI check. The license check is really stupid :angry: : only the maintainer can see the detail of it.
