### ISSUE TITLE
Experiment event finish_time NULL not update bug when dashboard stop for a while then start

### ISSUE THREAD

**Issue by qhh0205** [chaos-mesh/chaos-mesh#923]
## Bug Report

**What version of Kubernetes are you using?**
`Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3"`

**What did you do?**
Hello, i have found a bug about event finish_time update, there's a problem in this scenario:
If there are some experiment are running, and the event are stored in database, and the event's finish_time filed are NULL, Now the dashboard(event collector) is suddenly broken, stopped for a while. After a while the dashboard(event collector) start, and the previous stored event finish_time will stay NULL, and will not be changed, only the now event are normal. The following is releated code:
https://github.com/chaos-mesh/chaos-mesh/blob/d8b4b11745e6dbbd357340ca127bdfd8265c51f8/pkg/collector/collector.go#L59

That only update the incomplete event when the obj is not found and deleted, not handle the scenario that i descried above.

So, how to handle the such exception scenario? On second thought, maybe the ttl controller should clean the such event, but it seems that it is not easy to do that. Are there any good idea? thanks!
https://github.com/chaos-mesh/chaos-mesh/blob/d8b4b11745e6dbbd357340ca127bdfd8265c51f8/pkg/ttlcontroller/ttlcontroller.go#L73

https://github.com/chaos-mesh/chaos-mesh/blob/d8b4b11745e6dbbd357340ca127bdfd8265c51f8/pkg/store/event/event.go#L405

**Comment by qhh0205** [comment]
@fewdan

**Comment by fewdan** [comment]
OK, let me see

**Comment by fewdan** [comment]
https://github.com/chaos-mesh/chaos-mesh/blob/d8b4b11745e6dbbd357340ca127bdfd8265c51f8/pkg/store/event/event.go#L41
@qhh0205 
I think it is possible to delete the incomplete (and not running) exp records after starting the dashboard and connecting to the db, as in events.

**Comment by qhh0205** [comment]
@fewdan Yes, you are right! Now no problem. Good!
