### ISSUE TITLE
I can't see  latency after I apply network-delay.yaml

### ISSUE THREAD

**Issue by XGameCloud** [chaos-mesh/chaos-mesh#925]
## Question
Env:
  OFF-LINE cluster
  docker: 18.06
  k8s: 1.15.1
  chaos-mesh: v0.9.1
Description:
  I follow the Doc(v0.9.1). At User Guide -> Run Chaos Experiment -> Step 3. I can't see 10ms latency after I use 'kubectl apply -f network-delay.yaml'.
  Here are some info about the whole system.
-------------------------------------------------------------
$ kubectl get nodes
NAME       STATUS   ROLES    AGE   VERSION
xcloud37   Ready    <none>   13h   v1.15.1
xcloud47   Ready    master   23h   v1.15.1
xcloud48   Ready    <none>   23h   v1.15.1
xcloud49   Ready    <none>   20h   v1.15.1
xcloud50   Ready    <none>   20h   v1.15.1
------------------------------------------------------------
$ kubectl get pods -n chaos-testing -o wide
NAME                                        READY   STATUS    RESTARTS   AGE   IP            NODE       NOMINATED NODE   READINESS GATES
chaos-controller-manager-65cd5bfb8b-vh59l   1/1     Running   0          18h   10.244.1.12   xcloud48   <none>           <none>
chaos-daemon-cxbtg                          1/1     Running   0          18h   10.244.1.11   xcloud48   <none>           <none>
chaos-daemon-kh7qz                          1/1     Running   0          13h   10.244.4.2    xcloud37   <none>           <none>
chaos-daemon-knpk8                          1/1     Running   10         18h   10.244.2.10   xcloud49   <none>           <none>
chaos-daemon-tcmc8                          1/1     Running   0          18h   10.244.3.7    xcloud50   <none>           <none>
chaos-dashboard-59bcc758fc-spqg8            1/1     Running   0          14h   10.244.3.8    xcloud50   <none>           <none>
----------------------------------------------------------
$ kubectl get pods -o wide --show-labels
NAME                       READY   STATUS    RESTARTS   AGE   IP            NODE       NOMINATED NODE   READINESS GATES   LABELS
web-show-b4cf67576-qljnw   1/1     Running   0          42m   10.244.2.13   xcloud49   <none>           <none>            app=web-show,pod-template-h
----------------------------------------------------------
$ kubectl get NetworkChaos
NAME                     AGE
web-show-network-delay   17m
--------------------------------------------------------
$ kubectl describe NetworkChaos web-show-network-delay
Name:         web-show-network-delay
Namespace:    default
Labels:       <none>
Annotations:  kubectl.kubernetes.io/last-applied-configuration:
                {"apiVersion":"chaos-mesh.org/v1alpha1","kind":"NetworkChaos","metadata":{"annotations":{},"name":"web-show-network-delay","namespace":"de...
API Version:  chaos-mesh.org/v1alpha1
Kind:         NetworkChaos
Metadata:
  Creation Timestamp:  2020-09-18T02:28:07Z
  Finalizers:
    default/web-show-b4cf67576-qljnw
  Generation:        2
  Resource Version:  136609
  Self Link:         /apis/chaos-mesh.org/v1alpha1/namespaces/default/networkchaos/web-show-network-delay
  UID:               3540af89-c4ab-4b34-8fcb-effb2fcfb232
Spec:
  Action:  delay
  Delay:
    Correlation:  0
    Jitter:       0ms
    Latency:      10ms
  Direction:      to
  Duration:       30s
  Mode:           one
  Scheduler:
    Cron:  @every 60s
  Selector:
    Label Selectors:
      App:  web-show
    Namespaces:
      default
  Value:  
Status:
  Experiment:
    Phase:  Failed
  Phase:    
  Scheduler:
Events:
  Type     Reason             Age                   From                     Message
  ----     ------             ----                  ----                     -------
  Warning  ChaosInjectFailed  4m40s (x18 over 16m)  networkchaos-controller  admission webhook "vpodnetworkchaos.kb.io" denied the request: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 172.16.44.49:31767: connect: no route to host"
-----------------------------------------------------------------------------------------------------
Why would it have to connct 172.16.44.49:31767?
I try 'curl 172.16.44.49:31767', and it also report 'no route to host'. Becase there is no process using port '31767' at 172.16.44.49 at all.
But why?
I am a  newcommer with Docker and k8s (and English ).Please give me some help, THANKS!

**Comment by cwen0** [comment]
@XGameCloud Can you check if there is a chaos-daemon pod run on the node with IP `172.16.44.49` ? I guess that your target pod is on the master node and `172.16.44.49` IP belongs to the master node. Your master node doesn't allow to deploy chaos-daemon pod on it during to `Taints` and you can refer this doc https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/ to check your master node.

**Comment by XGameCloud** [comment]
The hostname of 172.16.44.49 is xcloud49. and Yes, there is a chaos-daemon pod run on 172.16.44.49.
-----------------------------------------------------------------------------
Here is some log.There are so many errors. 
2020-09-18T03:03:54.931Z        ERROR   inject-webhook  channel has closed, should restart watcher
2020-09-18T03:03:54.931Z        ERROR   setup   watcher got error, try to restart watcher       {"error": "watcher channel has closed"}
2020-09-18T03:07:18.229Z        ERROR   controllers.NetworkChaos        error while creating podnetworkchaos    {"reconciler": "networkchaos", "action": "netem", "error": "admission webhook \"vpodnetworkchaos.kb.io\" denied the request: rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial tcp 172.16.44.49:31767: connect: no route to host\""}
2020-09-18T03:07:18.229Z        ERROR   controllers.NetworkChaos        error while updating    {"reconciler": "networkchaos", "action": "netem", "error": "admission webhook \"vpodnetworkchaos.kb.io\" denied the request: rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial tcp 172.16.44.49:31767: connect: no route to host\""}
2020-09-18T03:07:18.229Z        ERROR   controllers.NetworkChaos        fail to commit  {"reconciler": "networkchaos", "action": "netem", "error": "admission webhook \"vpodnetworkchaos.kb.io\" denied the request: rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial tcp 172.16.44.49:31767: connect: no route to host\""}
2020-09-18T03:07:18.229Z        ERROR   controllers.NetworkChaos        failed to apply chaos action    {"reconciler": "networkchaos", "action": "netem", "error": "admission webhook \"vpodnetworkchaos.kb.io\" denied the request: rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial tcp 172.16.44.49:31767: connect: no route to host\""}
------------------------------------------------------------------------
What is 'watcher' and how do I restart it?

**Comment by cwen0** [comment]
This watcher will be restarted automatedly and we have used `info` level log instead of `Error` level in latest version. About this issue, maybe this [FAQ](https://chaos-mesh.org/docs/faqs#q-i-have-deployed-chaos-mesh-and-created-podchaos-experiments-successfully-but-i-still-failed-in-creating-networkchaostimechaos-experiment-the-log-is-shown-below) can help you. You can open `hostNetwork` and then upgrade Chaos Mesh.

**Comment by XGameCloud** [comment]
Thanks a lot. I give it a try. 👍

**Comment by Colstuwjx** [comment]
@cwen0 I've never seen the relative log:

```
2020-09-18T03:07:18.229Z ERROR controllers.NetworkChaos error while creating podnetworkchaos {"reconciler": "networkchaos", "action": "netem", "error": "admission webhook "vpodnetworkchaos.kb.io" denied the request: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 172.16.44.49:31767: connect: no route to host""}
```

Are you sure that it's relative to #910 and fixed?

**Comment by XGameCloud** [comment]
I am at path: helm/chaos-mesh.
I try to modify the file values.yaml. I modify all the 'hostNetwork=true' and then use 'helm install chaos-mesh chaos-mesh/chaos-mesh --namespace=chaos-testing -f values.yaml'.
Everythings goes well. But, I came out the same error.

**Comment by XGameCloud** [comment]
I have found a another strange thing.I try to use dashboard and I found I can not use browser to open it. But I can use 'curl' at local to access it.Am I network something wrong?By the way, I can use browser to open the web-show.

**Comment by cwen0** [comment]
@XGameCloud Can you check the status of the chaos-dashbaord pod?

**Comment by cwen0** [comment]
> @cwen0 I've never seen the relative log:
> 
> ```
> 2020-09-18T03:07:18.229Z ERROR controllers.NetworkChaos error while creating podnetworkchaos {"reconciler": "networkchaos", "action": "netem", "error": "admission webhook "vpodnetworkchaos.kb.io" denied the request: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 172.16.44.49:31767: connect: no route to host""}
> ```
> 
> Are you sure that it's relative to #910 and fixed?

I don't sure about it. Form the log he provided, I guess that some nodes may be not accessible to the node running controller-manager . @XGameCloud Can you check the network between the nodes and the status of the proxy pods?

**Comment by NarzeusNabartey** [comment]
Hi Guys. I am also experiencing the same issue "no route to host" in one of our namespace.

2020-09-30T03:26:43.240Z	ERROR	controllers.NetworkChaos	error while creating podnetworkchaos	{"reconciler": "networkchaos", "action": "netem", "error": "admission webhook \"vpodnetworkchaos.kb.io\" denied the request: rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial tcp 12.15.62.245:31767: connect: no route to host\""}
github.com/go-logr/zapr.(*zapLogger).Error
	/go/pkg/mod/github.com/go-logr/zapr@v0.1.0/zapr.go:128
github.com/chaos-mesh/chaos-mesh/controllers/networkchaos/podnetworkmanager.(*PodNetworkManager).Commit.func1.1
	/src/controllers/networkchaos/podnetworkmanager/podnetworkmanager.go:100
k8s.io/client-go/util/retry.OnError.func1
	/go/pkg/mod/k8s.io/client-go@v0.17.0/util/retry/util.go:51
k8s.io/apimachinery/pkg/util/wait.ExponentialBackoff
	/go/pkg/mod/k8s.io/apimachinery@v0.17.1-beta.0/pkg/util/wait/wait.go:292
k8s.io/client-go/util/retry.OnError
	/go/pkg/mod/k8s.io/client-go@v0.17.0/util/retry/util.go:50
k8s.io/client-go/util/retry.RetryOnConflict
	/go/pkg/mod/k8s.io/client-go@v0.17.0/util/retry/util.go:104
github.com/chaos-mesh/chaos-mesh/controllers/networkchaos/podnetworkmanager.(*PodNetworkManager).Commit.func1
	/src/controllers/networkchaos/podnetworkmanager/podnetworkmanager.go:71
golang.org/x/sync/errgroup.(*Group).Go.func1
	/go/pkg/mod/golang.org/x/sync@v0.0.0-20190911185100-cd5d95a43a6e/errgroup/errgroup.go:57
2020-09-30T03:26:43.240Z	ERROR	controllers.NetworkChaos	error while updating	{"reconciler": "networkchaos", "action": "netem", "error": "admission webhook \"vpodnetworkchaos.kb.io\" denied the request: rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial tcp 12.15.62.245:31767: connect: no route to host\""}

But in other namespace it works well. Really need your help to fix this. Thanks.

**Comment by zhouqiang-cl** [comment]
> Hi Guys. I am also experiencing the same issue "no route to host" in one of our namespace.
> 
> 2020-09-30T03:26:43.240Z ERROR controllers.NetworkChaos error while creating podnetworkchaos {"reconciler": "networkchaos", "action": "netem", "error": "admission webhook "vpodnetworkchaos.kb.io" denied the request: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 12.15.62.245:31767: connect: no route to host""}
> github.com/go-logr/zapr.(*zapLogger).Error
> /go/pkg/mod/github.com/go-logr/zapr@v0.1.0/zapr.go:128
> github.com/chaos-mesh/chaos-mesh/controllers/networkchaos/podnetworkmanager.(*PodNetworkManager).Commit.func1.1
> /src/controllers/networkchaos/podnetworkmanager/podnetworkmanager.go:100
> k8s.io/client-go/util/retry.OnError.func1
> /go/pkg/mod/k8s.io/client-go@v0.17.0/util/retry/util.go:51
> k8s.io/apimachinery/pkg/util/wait.ExponentialBackoff
> /go/pkg/mod/k8s.io/apimachinery@v0.17.1-beta.0/pkg/util/wait/wait.go:292
> k8s.io/client-go/util/retry.OnError
> /go/pkg/mod/k8s.io/client-go@v0.17.0/util/retry/util.go:50
> k8s.io/client-go/util/retry.RetryOnConflict
> /go/pkg/mod/k8s.io/client-go@v0.17.0/util/retry/util.go:104
> github.com/chaos-mesh/chaos-mesh/controllers/networkchaos/podnetworkmanager.(*PodNetworkManager).Commit.func1
> /src/controllers/networkchaos/podnetworkmanager/podnetworkmanager.go:71
> golang.org/x/sync/errgroup.(*Group).Go.func1
> /go/pkg/mod/golang.org/x/sync@v0.0.0-20190911185100-cd5d95a43a6e/errgroup/errgroup.go:57
> 2020-09-30T03:26:43.240Z ERROR controllers.NetworkChaos error while updating {"reconciler": "networkchaos", "action": "netem", "error": "admission webhook "vpodnetworkchaos.kb.io" denied the request: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 12.15.62.245:31767: connect: no route to host""}
> 
> Already applied the hostNetwork=true and still having the same issue.
> 
> ```
> helm upgrade chaos-mesh chaos-mesh/chaos-mesh --namespace=chaos-testing --set hostNetwork=true
> ```
> 
> But in other namespace it works well. Really need your help to fix this. Thanks.

@cwen0 @YangKeao PTAL

**Comment by cwen0** [comment]
> Hi Guys. I am also experiencing the same issue "no route to host" in one of our namespace.
> 
> 2020-09-30T03:26:43.240Z ERROR controllers.NetworkChaos error while creating podnetworkchaos {"reconciler": "networkchaos", "action": "netem", "error": "admission webhook "vpodnetworkchaos.kb.io" denied the request: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 12.15.62.245:31767: connect: no route to host""}
> github.com/go-logr/zapr.(*zapLogger).Error
> /go/pkg/mod/github.com/go-logr/zapr@v0.1.0/zapr.go:128
> github.com/chaos-mesh/chaos-mesh/controllers/networkchaos/podnetworkmanager.(*PodNetworkManager).Commit.func1.1
> /src/controllers/networkchaos/podnetworkmanager/podnetworkmanager.go:100
> k8s.io/client-go/util/retry.OnError.func1
> /go/pkg/mod/k8s.io/client-go@v0.17.0/util/retry/util.go:51
> k8s.io/apimachinery/pkg/util/wait.ExponentialBackoff
> /go/pkg/mod/k8s.io/apimachinery@v0.17.1-beta.0/pkg/util/wait/wait.go:292
> k8s.io/client-go/util/retry.OnError
> /go/pkg/mod/k8s.io/client-go@v0.17.0/util/retry/util.go:50
> k8s.io/client-go/util/retry.RetryOnConflict
> /go/pkg/mod/k8s.io/client-go@v0.17.0/util/retry/util.go:104
> github.com/chaos-mesh/chaos-mesh/controllers/networkchaos/podnetworkmanager.(*PodNetworkManager).Commit.func1
> /src/controllers/networkchaos/podnetworkmanager/podnetworkmanager.go:71
> golang.org/x/sync/errgroup.(*Group).Go.func1
> /go/pkg/mod/golang.org/x/sync@v0.0.0-20190911185100-cd5d95a43a6e/errgroup/errgroup.go:57
> 2020-09-30T03:26:43.240Z ERROR controllers.NetworkChaos error while updating {"reconciler": "networkchaos", "action": "netem", "error": "admission webhook "vpodnetworkchaos.kb.io" denied the request: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 12.15.62.245:31767: connect: no route to host""}
> 
> Already applied the hostNetwork=true and still having the same issue.
> 
> ```
> helm upgrade chaos-mesh chaos-mesh/chaos-mesh --namespace=chaos-testing --set hostNetwork=true
> ```
> 
> But in other namespace it works well. Really need your help to fix this. Thanks.

@NarzeusNabartey Hi, Can you make sure if the node with `controller-manager` pod can access to the node with IP`12.15.62.245`?

**Comment by NarzeusNabartey** [comment]
Hi Guys. I am very sorry for the late reply. After so many troubleshooting and testing, it seems that at some point communication between namespaces are not automatic by default. I am able to solve this issue using the code below in Openshift 3.11

```
oc adm pod-network join-projects --to=chaos-testing <target-namespace>
```

This issue is close on my end. Many thanks.

Zeus
