### ISSUE TITLE
PR magic words documentation request

### ISSUE THREAD

**Issue by Colstuwjx** [chaos-mesh/chaos-mesh#952]
## Question

Kubernetes prow bot offered a [page](https://prow.k8s.io/command-help) for commands, it's very convenient for contributors, I hope we could also have such thing in our doc, maybe CONTRIBUTING.md?

BTW, do we support `/hold` for holding the approved PR? For example, PR #946 is still in-complete, but it has been marked as `can merge`, so the bot merged it soon. If we support `/hold`, we could avoid such thing happens.

Thanks.

**Comment by zhouqiang-cl** [comment]
Yes. I think we need.
