### ISSUE TITLE
Document: add a chaos demo in Get Started

### ISSUE THREAD

**Issue by WangXiangUSTC** [chaos-mesh/chaos-mesh#953]
## Problem

Now we only tell users how to install Chaos Mesh in [Get Started](https://chaos-mesh.org/docs/installation/installation), but users may not know how to use it.

## Description

It's better to show a demo about how chaos works in `Get Started`. 

## Implementation

[run_chaos_experiment](https://chaos-mesh.org/docs/user_guides/run_chaos_experiment) This document shows how to inject network chaos, can move it to `Get Started` as a demo.

**Comment by zhouqiang-cl** [comment]
@wuxiaohui94 thank you ❤️

**Comment by g1eny0ung** [comment]
🚀 The website was moved to https://github.com/chaos-mesh/website!  Please submit subsequent changes at the new repo.

I will close this issue for now and if there have any questions, feel free to reopen it.
