### ISSUE TITLE
Multiple unexpected events generated after update a experiment

### ISSUE THREAD

**Issue by g1eny0ung** [chaos-mesh/chaos-mesh#959]
## Bug Report

**What version of Kubernetes are you using?**

Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T21:51:49Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T13:32:58Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}

**What did you do?**

> Only reproduced in the development environment (go run cmd/chaos-dashboard/main.go). 

Due to I forgot to create a pod or a deployment in my test environment, the experiment I created is failed, this is reasonable.

But after I create an nginx deployment and update the experiment's label selectors, it will generate multiple events accidentally. Like the image below:

![image](https://user-images.githubusercontent.com/15034155/94113443-74a9bb80-fe79-11ea-9eeb-b404405c0a52.png)

I test both `PodChaos` and `NetworkChaos`, they all have this situation.

**What did you expect to see?**

Seems there should only one event.

**What did you see instead?**

**Comment by fewdan** [comment]
Okay, let me take a look.
