### ISSUE TITLE
Encapsulate multi-pod chaos

### ISSUE THREAD

**Issue by YangKeao** [chaos-mesh/chaos-mesh#961]
Many kinds of chaos are sharing the same `Recover` logic. A typical `Recover` function is like below:

```
func (r *Reconciler) Recover(ctx context.Context, req ctrl.Request, obj v1alpha1.InnerObject) error {

	podchaos, ok := obj.(*v1alpha1.PodChaos)
	if !ok {
		err := errors.New("chaos is not PodChaos")
		r.Log.Error(err, "chaos is not PodChaos", "chaos", obj)
		return err
	}

	if err := r.cleanFinalizersAndRecover(ctx, podchaos); err != nil {
		return err
	}

	r.Event(podchaos, v1.EventTypeNormal, utils.EventChaosRecovered, "")
	return nil
}

func (r *Reconciler) cleanFinalizersAndRecover(ctx context.Context, podchaos *v1alpha1.PodChaos) error {
	var result error

	for _, key := range podchaos.Finalizers {
		ns, name, err := cache.SplitMetaNamespaceKey(key)
		if err != nil {
			result = multierror.Append(result, err)
			continue
		}

		var pod v1.Pod
		err = r.Client.Get(ctx, types.NamespacedName{
			Namespace: ns,
			Name:      name,
		}, &pod)

		if err != nil {
			if !k8serror.IsNotFound(err) {
				result = multierror.Append(result, err)
				continue
			}

			r.Log.Info("Pod not found", "namespace", ns, "name", name)
			podchaos.Finalizers = utils.RemoveFromFinalizer(podchaos.Finalizers, key)
			continue
		}

		err = r.recoverPod(ctx, &pod, podchaos)
		if err != nil {
			result = multierror.Append(result, err)
			continue
		}

		podchaos.Finalizers = utils.RemoveFromFinalizer(podchaos.Finalizers, key)
	}

	if podchaos.Annotations[common.AnnotationCleanFinalizer] == common.AnnotationCleanFinalizerForced {
		r.Log.Info("Force cleanup all finalizers", "chaos", podchaos)
		podchaos.Finalizers = podchaos.Finalizers[:0]
		return nil
	}

	return result
}
```

The `Recover` and `cleanFinalizersAndRecover` functions for other reconcilers (such as StressChaos and TimeChaos) even have the same AST :crying_cat_face: . We should encapsulate them into a base struct to avoid the code clone.

Copy & Paste is a shame for a project and programmer :facepalm: . Let's remedy the embarrassing situation.

**Comment by Yiyiyimu** [comment]
Although it seems not working but still

/assign @Yiyiyimu

**Comment by Yiyiyimu** [comment]
The problem is a bit complicated than I thought, could you give me some guidance or reference @YangKeao ?

Currently I'm trying to passing the dynamic argument (which type of chaos) with an empty interface. But the type assertion
https://github.com/chaos-mesh/chaos-mesh/blob/d94435fdf5e6e4ffe623d43c81eaecb907c668ad/controllers/stresschaos/types.go#L122
could not be implemented dynamically, since `reflect.Type is not a Type` so I could not use `reflect.Type` for type assertion.

The same problem happens to `cleanFinalizersAndRecover`, that I could not use `reflect.Type` to define the type of interface.
```
func (r *Reconciler) cleanFinalizersAndRecover(ctx context.Context, chaos Interface{}) error {
	var result error
	for _, key := range chaos.(TypeOfChaos).Finalizers {
```

**Comment by YangKeao** [comment]
@Yiyiyimu Maybe we could create an interface to replace `interface{}`, and the interface should contain all the necessary methods to run `Recover` and `cleanFinalizersAndRecover` such as `Finalizers()`...

I am working on a code generator for `chaos-mesh`. It seems that we need a lot of getters and setters. However, I haven't found a suitable pkg to do it directly, which quite amazed me.

**Comment by Yiyiyimu** [comment]
@YangKeao Sorry I'm a bit occupied these days and failed to reply on time.

Thank you for your suggestions! Learn something new for go! 
It just there is some other problem. `Finalizer` and `Annotations` would work well for this situation. But in `recoverPod` used by `cleanFinalizersAndRecover`, there would be variables like `Status` and `Spec` which are chaos(type)-specific, that could not been put into the interface, like in KernelChaos, StressChaos and TimeChaos.

Also I found a getter-setter generator for java in [vscode extension](https://github.com/afmicc/getter-setter-generator). It seems not so complicated. I think I could work on it if you provide some examples.

**Comment by Yiyiyimu** [comment]
I just notice your PR #940 . I'll try to read it tomorrow and it must be a great reference for this issue.

**Comment by Yiyiyimu** [comment]
comment to remove stale
