### ISSUE TITLE
Restrict Chaos Injection to the Pods of the same namespace where chaos-experiment is created

### ISSUE THREAD

**Issue by abhisheknsit** [chaos-mesh/chaos-mesh#964]
## Feature Request

**Is your feature request related to a problem? Please describe:**
In a multi-tenant cluster, we can't stop tenants from injecting chaos into other tenants namespace.
Creating a chaos-experiment in namespace A, can inject chaos in PODS in namespace B even though the user is not having permission over namespaceB.

**Describe the feature you'd like:**
Limit the pod or k8s object selector to the same namespace where the chaos experiment is created.

**Describe alternatives you've considered:**
I had a look at this issue: #487 . Although this restricts the pod selector to the controllers namespace, but if the tenant is having exec permissions on the controllers pod, he can still invoke havoc on other tenants namespace.

Ideal, solution would be to have the controller in a secure namespace and limit the chaosexperiments selector to the experiments namespace.

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by cwen0** [comment]
@abhisheknsit Do you mean that the chaos object only has control over to its own namespace? I think this is just one of the usage scenarios. Sometimes, our target pods may be included in multiple namespaces, such as network partition. We can add a flag to control it, such as we can add a default field `scope: ns` in chaos object.

**Comment by cwen0** [comment]
@STRRL @Yisaer What is your opinion?

**Comment by abhisheknsit** [comment]
> @abhisheknsit Do you mean that the chaos object only has control over to its own namespace? I think this is just one of the usage scenarios. Sometimes, our target pods may be included in multiple namespaces, such as network partition. We can add a flag to control it, such as we can add a default field `scope: ns` in chaos object.

@cwen0 Yes, the chaos object being able to induce chaos in its own namespace.
We have a multi-tenant cluster, where in we don't trust any other tenant. The tenancy boundary for the tenants are namespaces and we are restricting access to resources via RBAC. We don't want tenant in one namespace be able to induce chaos in some other namespace.

I think a global flag to control should work.
