### ISSUE TITLE
website: interactive tutorial typo in step 6

### ISSUE THREAD

**Issue by Yiyiyimu** [chaos-mesh/chaos-mesh#981]
## Bug Report
In step 6:
1. Define Experiment: the third paragraph repeat the description of NetworkChaos in step 5, while it should be about PodChaos
2. Apply Experiment: the second code block should check PodChaos but not NetworkChaos

**Comment by zhouqiang-cl** [comment]
@cwen0 PTAL

**Comment by cwen0** [comment]
@Yiyiyimu Can you help us fix it?

**Comment by Yiyiyimu** [comment]
@cwen0 Sure. It just I couldn't find the code of katacoda scenarios, could you give me some guide?

**Comment by YangKeao** [comment]
@Yiyiyimu Thanks :beers: ! You can find the file in https://github.com/javajon/katacoda-courses/tree/master/kubernetes-chaos/chaos-mesh

**Comment by Yiyiyimu** [comment]
Close due to issue fixed.
