### ISSUE TITLE
website: change needed in `Develop a New Chaos`

### ISSUE THREAD

**Issue by Yiyiyimu** [chaos-mesh/chaos-mesh#985]
## Bug Report

**What version of Kubernetes are you using?**
v1.18.0

There are two places need to change:
1. In [Add the chaos object in controller](https://chaos-mesh.org/docs/development_guides/develop_a_new_chaos/#add-the-chaos-object-in-controller), no need to change controller-manager-rbac.yaml anymore, since in #872 
> chaos-mesh controller could work without permission of cluster scope
2. In [Make the Docker image](https://chaos-mesh.org/docs/development_guides/develop_a_new_chaos/#make-the-docker-image), we need to do `make generate` before `make`, since otherwise the error would shows like 
```
#18 1.579 api/v1alpha1/helloworldchaos_types.go:38:25: cannot use &HelloWorldChaos literal (type *HelloWorldChaos) as type runtime.Object in argument to SchemeBuilder.Register:
#18 1.579 *HelloWorldChaos does not implement runtime.Object (missing DeepCopyObject method)
```

**Comment by Yiyiyimu** [comment]
3. In [Run Chaos](https://chaos-mesh.org/docs/development_guides/develop_a_new_chaos/#run-chaos), in helm v3 the command should change from
```
helm install helm/chaos-mesh --name=chaos-mesh --namespace=chaos-testing
```
to
```
helm install chaos-mesh helm/chaos-mesh --namespace=chaos-testing
```

**Comment by Yiyiyimu** [comment]
**HELP NEEDED**: helm install keeps failing since k8s could not connect to local registry. docker pull from local registry works.
error log:
```
Normal Scheduled 20m default-scheduler Successfully assigned chaos-testing/chaos-controller-manager-686dd65b5-b6t4r to kind-control-plane
Normal BackOff 23s (x4 over 2m55s) kubelet, kind-control-plane Back-off pulling image "localhost:5000/pingcap/chaos-mesh:latest"
Warning Failed 23s (x4 over 2m55s) kubelet, kind-control-plane Error: ImagePullBackOff
Normal Pulling 9s (x4 over 20m) kubelet, kind-control-plane Pulling image "localhost:5000/pingcap/chaos-mesh:latest"
Warning Failed 9s (x4 over 2m56s) kubelet, kind-control-plane Failed to pull image "localhost:5000/pingcap/chaos-mesh:latest": rpc error: code = Unknown desc = failed to pull and unpack image "localhost:5000/pingcap/chaos-mesh:latest": failed to resolve reference "localhost:5000/pingcap/chaos-mesh:latest": failed to do request: Head https://localhost:5000/v2/pingcap/chaos-mesh/manifests/latest: dial tcp [::1]:5000: connect: connection refused
Warning Failed 9s (x4 over 2m56s) kubelet, kind-control-plane Error: ErrImagePull
```

**Comment by Yiyiyimu** [comment]
OK, I finished the new chaos development guidance, and those are all the problems I met. If someone else met the same problem, plz leave comments here to make sure they could be reproduced, so we could fix the error on the website.

**Comment by dsam82** [comment]
Thanks @Yiyiyimu, I also encountered same problems more or less but it got resolved in the end.
