### ISSUE TITLE
Ingress of Helm-Chart is referring to wrong service

### ISSUE THREAD

**Issue by ChristopherLenz** [chaos-mesh/chaos-mesh#992]
## Bug Report

**What version of Kubernetes are you using?**
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.1", GitCommit:"7879fc12a63337efff607952a323df90cdc7a335", GitTreeState:"clean", BuildDate:"2020-04-08T17:38:50Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.10", GitCommit:"1bea6c00a7055edef03f1d4bb58b773fa8917f11", GitTreeState:"clean", BuildDate:"2020-02-11T20:05:26Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}

**What did you do?**
```
    helm upgrade --install chaos-mesh chaos-mesh/chaos-mesh \
      --namespace=$CHAOS_NAMESPACE \
      --set dashboard.create=true --set dashboard.ingress.enabled=true \
      --set dashboard.ingress.hosts[0].name=$CHAOSMESH_URL
      --set rbac.create=false
```

**What did you expect to see?**
The Chaos Mesh Dashboard via the ingress

**What did you see instead?**
503 service temporarily unavailable

The ingress is referring to a not existing service. See: https://github.com/chaos-mesh/chaos-mesh/blob/08d0a5cbc07561bc986c0ffbb2cb38a0921e27d2/helm/chaos-mesh/templates/ingress.yaml#L34

But the name of the service is generated different. See: https://github.com/chaos-mesh/chaos-mesh/blob/08d0a5cbc07561bc986c0ffbb2cb38a0921e27d2/helm/chaos-mesh/templates/chaos-dashboard-deployment.yaml#L83

This means with a fresh install it looks something like that:

**service**
```
NAME                                    TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)                       AGE   SELECTOR
service/chaos-dashboard                 NodePort    10.105.202.177   <none>        2333:32007/TCP                37m   app.kubernetes.io/component=chaos-dashboard,app.kubernetes.io/instance=chaos-mesh,app.kubernetes.io/name=chaos-mesh
```

**ingress**
```
kubectl describe ingress/chaos-dashboard --namespace chaos-testing        
Name:             chaos-dashboard
Namespace:        chaos-testing
Address:          172.17.0.2
Default backend:  default-http-backend:80 (<error: endpoints "default-http-backend" not found>)
Rules:
  Host               Path  Backends
  ----               ----  --------
  chaosmesh.dms.com  
                     /   chaos-mesh-chaos-dashboard:http (<error: endpoints "chaos-mesh-chaos-dashboard" not found>)
Annotations:         meta.helm.sh/release-name: chaos-mesh
                     meta.helm.sh/release-namespace: chaos-testing
Events:
  Type    Reason  Age   From                      Message
  ----    ------  ----  ----                      -------
  Normal  CREATE  15m   nginx-ingress-controller  Ingress chaos-testing/chaos-dashboard
  Normal  UPDATE  15m   nginx-ingress-controller  Ingress chaos-testing/chaos-dashboard
```

If a correct the ref it works (workaround):
```
CHAOS_SERVICENAME=$(kubectl get service --namespace $CHAOS_NAMESPACE -l app.kubernetes.io/component=chaos-dashboard -o jsonpath="{.items[0].metadata.name}" ; echo)
kubectl patch ingress/chaos-dashboard --namespace $CHAOS_NAMESPACE --type=json -p="[{\"op\": \"replace\", \"path\": \"/spec/rules/0/http/paths/0/backend/serviceName\", \"value\":\"$CHAOS_SERVICENAME\"}]"
```

P.S. let us choose the service-type of the dashboard. Currently NodePort is hardcoded

**Comment by Gallardot** [comment]
@ChristopherLenz  Thanks for your report. Can you help us fix it?
