### ISSUE TITLE
There are many deadlink

### ISSUE THREAD

**Issue by zhouqiang-cl** [chaos-mesh/chaos-mesh#998]
## Bug Report
Thank you for @Yiyiyimu 's Markdown check CI
There are many deadlink show in 

https://github.com/chaos-mesh/chaos-mesh/runs/1181929929

Some of it like this
```
ERROR: 7 dead links found!
[✖] https://codecov.io/gh/pingcap/chaos-mesh → Status: 404
[✖] https://github.com/chaos-mesh/chaos-mesh/blob/master/LICENSE → Status: 429
[✖] https://github.com/datastax/fallout → Status: 429
[✖] https://www.crunchbase.com/organization/netease-fuxi-lab → Status: 403
[✖] /CONTRIBUTING.md → Status: 400
[✖] /ROADMAP.md → Status: 400
[✖] /LICENSE → Status: 400

FILE: ./CODE_OF_CONDUCT.md
[✖] https://github.com/cncf/foundation/blob/master/code-of-conduct.md

1 links checked.

ERROR: 1 dead links found!
[✖] https://github.com/cncf/foundation/blob/master/code-of-conduct.md → Status: 429
```
**What did you expect to see?**

**What did you see instead?**

**Comment by Yiyiyimu** [comment]
Hi @zhouqiang-cl , I'm trying to fix them now :)

Also, we could find there are still many `429 - too many request error` as we talked [before](https://github.com/chaos-mesh/chaos-mesh/pull/987#issuecomment-699647505). Luckily it just [got fixed](https://github.com/tcort/markdown-link-check/pull/106). We'll see if it could work.

**Comment by zhouqiang-cl** [comment]
> Hi @zhouqiang-cl , I'm trying to fix them now :)
> 
> Also, we could find there are still many `429 - too many request error` as we talked [before](https://github.com/chaos-mesh/chaos-mesh/pull/987#issuecomment-699647505). Luckily it just [got fixed](https://github.com/tcort/markdown-link-check/pull/106). We'll see if it could work.

Great, thank you , Wu

**Comment by yeya24** [comment]
Yep this linter seems also very flaky. Let's see how things go.

**Comment by zhouqiang-cl** [comment]
Seems still have some flaky link

**Comment by Yiyiyimu** [comment]
@zhouqiang-cl yes it seems both new filters failed.

I'm thinking to use this to filter out what we don't need:
```
{
  "ignorePatterns": [
		{
			"pattern": ["^/img/"]
    },
    {
			"pattern": ["^http://localhost"]
    },
    {
			"pattern": ["^https://github.com"]
		}
  ]
}
```
The first two are acceptable, but with the third one we'll definitely over-filter some broken links of github. The good news is most of github links work well under my experiment, but still I don't know if that would be acceptable.
